### ISSUE TITLE
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused

### ISSUE THREAD

**Issue by 21ki** [easzlab/kubeasz#1000]
apiserver探测controller-manager 和 scheduler写死直接连的本机
我问过群友也有这个问题

**Comment by 21ki** [comment]
![image](https://user-images.githubusercontent.com/24515576/113671889-8baf4d00-96e9-11eb-8872-1e4c8779568d.png)
使用3.0.1安装我看这个是写得本机ip.然后kubectl get cs 有问题

**Comment by 21ki** [comment]
安装之后默认是服务器本机ip应该修改成127.0.0.1吧

**Comment by 21ki** [comment]
![image](https://user-images.githubusercontent.com/24515576/113713327-c7faa180-9719-11eb-99c5-daa44a4a024f.png)
我以为是我装的问题。不同环境装了两遍都是这个报错

**Comment by 21ki** [comment]
我修改了配置文件不知道是否正确
![image](https://user-images.githubusercontent.com/24515576/113799262-55280f80-9787-11eb-8bed-4014a72e0683.png)

**Comment by gjmzj** [comment]
这样也可以，主要kubectl get cs 这个命令已经官宣废弃了，所以之前不太考虑；如果继续想用这个命令，那就修改下这个配置；我稍后提交一个commit吧

**Comment by xgh2016** [comment]
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused   
controller-manager   Healthy     ok                                                                                            
etcd-2               Healthy     {"health":"true"}                                                                             
etcd-0               Healthy     {"health":"true"}                                                                             
etcd-1               Healthy     {"health":"true"}                                                                             
[root@localhost kubeasz]#

**Comment by xgh2016** [comment]
也是一样的问题

**Comment by gjmzj** [comment]
https://github.com/easzlab/kubeasz/commit/421dd0b3b35ef2ec5ce80b0f564051d3dc708689
虽然这个错误不影响使用，还是不要报错看着舒服
