### ISSUE TITLE
怎么修改ssh的端口？

### ISSUE THREAD

**Issue by planb137** [easzlab/kubeasz#1005]
你好，由于机器原因，ssh端口不能是22，导致在安装的时候报错
TASK [Gathering Facts] **********************************************************************************************************
fatal: [10.202.38.51]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"xxxx\". Make sure this host can be reached over ssh: ssh: connect to host xxxx port 22: Operation timed out\r\n", "unreachable": true}

PLAY RECAP **********************************************************************************************************************
10.202.38.51               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
请问怎么解决呢？

**Comment by gjmzj** [comment]
如果初始化安装，请按如下格式：
```
# 'etcd' cluster should have odd member(s) (1,3,5,...)
[etcd]
192.168.31.244

# master node(s)
[kube_master]
192.168.31.244

# work node(s)
[kube_node]
192.168.31.248 ansible_ssh_port=443
192.168.31.244

...
```

如果是添加节点，参考：
https://github.com/easzlab/kubeasz/blob/master/docs/op/op-node.md

**Comment by planb137** [comment]
> 如果初始化安装，请按如下格
> [kube_node]
> 192.168.31.248 ansible_ssh_port=10022
> 192.168.31.244

不好意思，我没明白你的意思：
[kube_node]
192.168.31.248 ansible_ssh_port=10022 ，**这行是加在哪一个文件里？（我是初始安装，all in阶段报这样的错误❎）**

**Comment by planb137** [comment]
已解决：修改ansible.cfg里面的ssh端口即可

**Comment by kaydxh** [comment]
> 已解决：修改ansible.cfg里面的ssh端口即可

添加的key的名字是啥？默认注释的没看到port字段
<img width="779" alt="image" src="https://user-images.githubusercontent.com/16474709/185954165-bcb3fd23-92cf-4e53-bd47-926f17d5336d.png"> @planb137

**Comment by ahdong2007** [comment]
具体修复方式，/etc/kubeasz/ansible.cfg，ssh_args 去掉注释，并添加 -p <具体端口>
```bash
# cat /etc/kubeasz/ansible.cfg | grep -i ssh | grep ^ssh
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s -p <具体端口>
```
