### ISSUE TITLE
文件roles/kube-master/defaults/main.yml 找不到

### ISSUE THREAD

**Issue by wyw64962771** [easzlab/kubeasz#1007]
1. 按照kubeasz/docs/op/ch_apiserver_cert.md 去加公网ip，但是roles/kube-master/defaults/main.yml 文件找不到
![image](https://user-images.githubusercontent.com/17894513/115686641-fe782380-a38b-11eb-8801-07ddfce20893.png)

**Comment by gjmzj** [comment]
配置都集中在 /etc/kubeasz/clusters/${集群名}/config.yaml 里面了；按需修改后执行：
ezctl setup ${集群名} kube-master
