### ISSUE TITLE
ARM架构的支持，现在很多ARM的服务

### ISSUE THREAD

**Issue by wxh512** [easzlab/kubeasz#1008]
现在很多Arm服务器，特别是政策导致很多企业需要使用国内的操作系统，咱们是不是考虑一下对国产操作系统的支持

**Comment by gjmzj** [comment]
手头上没有arm服务器，没有环境测试安装

**Comment by wxh512** [comment]
是呀arm服务还贼贵

**Comment by a33151** [comment]
之前使用过kubeasz安装arm的服务器，只需要替换K8S docker 依赖组件的二进制包为ARM的二进制包即可

**Comment by a33151** [comment]
还有docker的相关镜像也是需要的

**Comment by xgh2016** [comment]
已经测试过了 没有问题 换arm 二进制文件和镜像

**Comment by wxh512** [comment]
用的是aarch64位操作系统各种问题cfssl问题今天重新编译了，但etcd又起不来哎各种问题，今天还编译harbor那个慢呀还没编译完成，

**Comment by wxh512** [comment]
不知道是cfssl版本太高了还是其它原因，etcd就是起不来

**Comment by wxh512** [comment]
k8s用的1.19.10

**Comment by wxh512** [comment]
-- Subject: A start job for unit etcd.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit etcd.service has finished with a failure.
-- 
-- The job identifier is 62347 and the job result is failed.
May 14 11:05:38 adbc-one audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=etcd comm="systemd>
May 14 11:05:39 adbc-one sshd[110773]: Starting session: command for root from 192.168.8.10 port 51704 id 0
May 14 11:05:39 adbc-one audit[110768]: USER_LOGIN pid=110768 uid=0 auid=0 ses=9 msg='op=login id=0 exe="/usr/sbin/sshd">
May 14 11:05:39 adbc-one audit[110768]: USER_START pid=110768 uid=0 auid=0 ses=9 msg='op=login id=0 exe="/usr/sbin/sshd">
May 14 11:05:39 adbc-one audit[110768]: CRYPTO_KEY_USER pid=110768 uid=0 auid=0 ses=9 msg='op=destroy kind=server fp=SHA>
May 14 11:05:40 adbc-one ansible-command[120610]: Invoked with creates=None executable=None _uses_shell=True strip_empty>
May 14 11:05:40 adbc-one sshd[110773]: Close session: user root from 192.168.8.10 port 51704 id 0
May 14 11:05:40 adbc-one audit[110768]: USER_END pid=110768 uid=0 auid=0 ses=9 msg='op=login id=0 exe="/usr/sbin/sshd" h>
May 14 11:05:40 adbc-one audit[110768]: USER_LOGOUT pid=110768 uid=0 auid=0 ses=9 msg='op=login id=0 exe="/usr/sbin/sshd>

**Comment by wxh512** [comment]
各种版本的ETCD，都出错了

**Comment by wxh512** [comment]
现在已经解决证书生成模块arm64的问题，解决ETCD的问题，继续向前走

**Comment by gjmzj** [comment]
已经正式支持arm64架构了
