### ISSUE TITLE
node-local-dns CrashLoopBackOff

### ISSUE THREAD

**Issue by chowxiaojun** [easzlab/kubeasz#1010]
搜索了一下之前的 Issues 列表，没有找到 node-local-dns 出现 CrashLoopBackOff 的 Issue，因此发一个 Issue 出来，请各位大神帮忙一起分析一下原因，同时也分享出来供大家参考：

1. 首先说明一下版本信息和环境情况：
    - kubeasz 版本为 3.0.1，其他 k8s 相关组件的版本都为默认值
    - 安装环境：RedHat 7.5，离线安装环境
    - 安装 CoreDNS 的配置信息如下：
    ```
    # coredns 自动安装
    dns_install: "yes"
    corednsVer: "1.7.1"
    ENABLE_LOCAL_DNS_CACHE: true
    dnsNodeCacheVer: "1.16.0"
    # 设置 local dns cache 地址
    LOCAL_DNS_CACHE: "169.254.20.10"
    ```
2. 复现步骤与项目 README 中多 master  集群部署 01-07 一致，07 步骤执行完后，发现 node-local-dns 一直出 CrashLoopBackOff 状态，通过 kubectl logs 查看日志发现最后一行日志如下：
    ```
    plugins/forward: no nameservers found
    ```

3. 问题初步分析：
    3.1 可能原因一：根据异常分析，node-local-dns 可能会使用节点的 /etc/resolv.conf，所以查看节点的 /etc/resolv.conf，发现其内容为空，所以日志才会提示 no nameservers found
    3.2 可能原因二：通过查阅 [node-local-dns 原理](https://bbs.huaweicloud.com/blogs/192337)可知，node-local-dns 的 DaemonSet 会利用节点的网络，比如会监控 8080，53等等，怀疑安装环境限制某些端口的使用

4. 初步解决方案：
    4.1 方案一：将 CoreDNS 配置项 ENABLE_LOCAL_DNS_CACHE 设置为 false，然后重新执行 07 步骤
    4.2 方案二：删除集群的 node，然后重新添加到集群中，并执行方案一
    4.3 方案三：重装 master、node 机器的系统，重新执行所有步骤，并设置 ENABLE_LOCAL_DNS_CACHE 为 false

因为安装环境为私有环境，今天没有也没有更多的时间进行进一步的验证与分析，以上是目前的分析和猜测，麻烦 @gjmzj 大神帮忙分析一下，感谢。

**Comment by gjmzj** [comment]
禁用步骤：
1.先删除daemonset
```
kubectl delete -f /etc/kubeasz/clusters/${集群名}/yml/nodelocaldns.yaml
```
2.然后/etc/kubeasz/clusters/${集群名}/config.yml里面设置ENABLE_LOCAL_DNS_CACHE false
3.然后重新执行07步骤即可 ezctl setup ${集群名} 07

**Comment by gjmzj** [comment]
问题原因应该是node主机上/etc/resolv.conf 文件内容为空

**Comment by chowxiaojun** [comment]
> 问题原因应该是node主机上/etc/resolv.conf 文件内容为空

这个是否会影响CoreDNS的功能？

**Comment by chowxiaojun** [comment]
> 禁用步骤：
> 1.先删除daemonset
> 
> ```
> kubectl delete -f /etc/kubeasz/clusters/${集群名}/yml/nodelocaldns.yaml
> ```
> 
> 2.然后/etc/kubeasz/clusters/${集群名}/config.yml里面设置ENABLE_LOCAL_DNS_CACHE false
> 3.重新执行03步骤即可 ezctl setup ${集群名} 03
> 4.重新执行03步骤即可 ezctl setup ${集群名} 04

只要重新执行03和04吗？不需要重新安装 node？执行步骤05？

**Comment by gjmzj** [comment]
> > 问题原因应该是node主机上/etc/resolv.conf 文件内容为空
> 
> 这个是否会影响CoreDNS的功能？


肯定会影响，默认coredns也把/etc/resolv.conf中配置当成上游dns解析

**Comment by chowxiaojun** [comment]
> 说错了，应该是04/05，不是03/04

那重新执行一遍03，应该也没有问题吧？

**Comment by chowxiaojun** [comment]
> > > 问题原因应该是node主机上/etc/resolv.conf 文件内容为空
> > 
> > 
> > 这个是否会影响CoreDNS的功能？
> 
> 肯定会影响，默认coredns也把/etc/resolv.conf中配置当成上游dns解析

我们内部环境不需要外部的域名解析？这个不会影响内部Service的域名解析吧？

**Comment by chowxiaojun** [comment]
总结一下：
    因为节点 /etc/resolv.conf 为空，导致 node-local-dns 启动异常，因此部署时，注意把 ENABLE_LOCAL_DNS_CACHE 修改为 false。最后感谢 @gjmzj 的帮助

**Comment by duudo** [comment]
KUBEASZ_VER=3.1.0,有几个问题：
1. nodelocaldns-ipvs/iptables.yaml.j2中的images版本号是写死为1.16.0版本，而不是通过获取配置的 nodelocaldns版本号，导致yaml中镜像版本号和实际的配置文件中指定的不一致，进而启动时找不到镜像。
2. nodelocaldns-ipvs/iptables.yaml.j2中使用的是DaemonSet，但是cluster-addon的脚本中host只是node节点，这样会导致master节点没有导入相关的镜像，进而pod启动失败。
3. nodelocaldns没有镜像分发的相关实现。

**Comment by tanmx** [comment]
> KUBEASZ_VER=3.1.0,有几个问题：
> 
> 1. nodelocaldns-ipvs/iptables.yaml.j2中的images版本号是写死为1.16.0版本，而不是通过获取配置的 nodelocaldns版本号，导致yaml中镜像版本号和实际的配置文件中指定的不一致，进而启动时找不到镜像。
> 2. nodelocaldns-ipvs/iptables.yaml.j2中使用的是DaemonSet，但是cluster-addon的脚本中host只是node节点，这样会导致master节点没有导入相关的镜像，进而pod启动失败。
> 3. nodelocaldns没有镜像分发的相关实现。

遇到这个问题了，先禁用nodelocaldns 安装
