### ISSUE TITLE
通过ezctl命令重复添加删除相同节点，hosts文件中的节点IP会重复

### ISSUE THREAD

**Issue by jikunbupt** [easzlab/kubeasz#1016]
如题。例如对10.1.0.195节点进行了多次添加删除操作，查看hosts文件如下：
# work node(s)
[kube_node]
10.1.0.197
10.1.0.196
10.1.0.195
10.1.0.195
10.1.30.44
10.1.30.44
10.1.30.43
10.1.31.10
10.1.30.43
10.1.30.43
10.1.0.195
10.1.0.195
10.1.0.195
10.1.0.164
10.1.0.165
10.1.0.166

**Comment by gjmzj** [comment]
这个问题在kubeasz 3.1.0 应该已经解决了

**Comment by jikunbupt** [comment]
OK
