### ISSUE TITLE
kubeasz-3.1.0  metrics-server获取不到资源使用率

### ISSUE THREAD

**Issue by wujunlin555** [easzlab/kubeasz#1017]
[root@k8s01 ~]# kubectl top node 
W0525 16:19:37.849858   16440 top_node.go:119] Using json format to get metrics. Next release will switch to protocol-buffers, switch early by passing --use-protocol-buffers flag
error: metrics not available yet

**Comment by gjmzj** [comment]
> [root@k8s01 ~]# kubectl top node
> W0525 16:19:37.849858 16440 top_node.go:119] Using json format to get metrics. Next release will switch to protocol-buffers, switch early by passing --use-protocol-buffers flag
> error: metrics not available yet

not available yet，一般来说部署完后需要等待3～5分钟才能出
