### ISSUE TITLE
离线 docker 方式安装时，安装机本身不能被加入到集群中

### ISSUE THREAD

**Issue by o2bit** [easzlab/kubeasz#1018]
如果 hosts 文件里添加了 安装机本身的 IP，会在配置 firewalled 时丢失 docker 路由，导致 container 无法和其他IP 通信，最后一直卡住。
用宿主机 ansible 方式安装则不存在此问题。

**Comment by waitingsong** [comment]
运行 docker 以及 k8s 的服务器最好关闭防火墙，或者直接卸载防火墙相关组件。
