### ISSUE TITLE
kubeasz 2X版本阿里公有云如果想从外部访问api-server怎么办？

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#1021]
目前我看２.0的架构使用nginx只实现了api-server内部负载均衡，那么阿里云公网外部如何访问api-server呢?kubeasz部署步骤里面我貌似没有找到，目前是基于阿里云的SLB反向代理到master节点上的kube-lb(nginx)监听的api-server端口,还有一个问题就是下面这个配置
```
[ex_lb]
192.168.1.6 LB_ROLE=backup EX_APISERVER_VIP=192.168.1.250 EX_APISERVER_PORT=8443
192.168.1.7 LB_ROLE=master EX_APISERVER_VIP=192.168.1.250 EX_APISERVER_PORT=8443
```
根据2x结构这个配置应该是不使用了吧，建议从配置里面去除ex_lb相关配置，容易引导产生歧义．所有部署都走2.0架构，这样可以使部署更加精简，兼容性更强(公有云跟私有云都可以适用)，避免让使用者产生部署混乱．

**Comment by gjmzj** [comment]
1.阿里云公有云上可以用SLB

2.[ex_lb]暂时保留，虽然2x结构不依赖它做集群高可用，但是仍旧可以选择部署[ex_lb]，用作集群外部访问k8s apiserver的入口，不会冲突，按需选择，默认不安装
