### ISSUE TITLE
ezdown使用-D参数疑问

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#1022]
ezdown工具使用参数-D进行下载为啥还要下载很多docker images镜像呢?我记得以前都是直接下载二进制文件安装,建议将脚本功能区分开，安装方式分为镜像安装与二进制安装，不要都同时下载．

**Comment by gjmzj** [comment]
ezdown-D 下载的docker 镜像是一些k8s组件 coredns/metrics-server/dashboard，还有网络组件等，这些在安装集群时肯定需要安装。

这样也方便离线安装部署
