### ISSUE TITLE
config.yaml配置文件疑问

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#1024]
1.ingress是否支持ingress-nginx，我看文档里面都是讲的traefik,并且部署的配置文件里面把ingress-nginx注释掉了？这是为啥？ingress-nginx好多企业跟个人都在使用呢．

2.prometheus的版本是否可以自定义修改,目前最高版本为14.0，执行ezdown -D 之后目录/etc/kubeasz/roles/cluster-addon/files下已经存在了离线文件kube-prometheus-stack-12.10.6.tgz跟traefik-9.12.3.tgz,是否可以在ezdown -D下载之前自定义版本呢？

![2021-06-01 17-16-09 的屏幕截图](https://user-images.githubusercontent.com/17851645/120299201-60b63380-c2fd-11eb-9ef5-9f684f8c45db.png)
![2021-06-01 17-42-23 的屏幕截图](https://user-images.githubusercontent.com/17851645/120303239-39f9fc00-c301-11eb-9dfb-5f7575cba376.png)

**Comment by gjmzj** [comment]
1. ingress 可以自己选择安装，不想在安装k8s集群的时候包括这个组件；traefik 后续也不一定继续更新
2. 当前prometheus 只有这个版本，后续会根据这个项目不定期更新https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by pj520** [comment]
问一下，如果根据kube-prometheus-stack自行替换最新的版本号，和values.yaml.j2文件中的镜像版本号，会有什么问题么？
