### ISSUE TITLE
k8s集群的测试、开发环境--单节点部署(aio) - kubelet启动失败

### ISSUE THREAD

**Issue by wangzy0327** [easzlab/kubeasz#1025]
运行docker exec -it kubeasz ezctl start-aio 安装aio集群最终得到：

FAILED - RETRYING: 轮询等待kubelet启动 (4 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (3 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (2 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (1 retries left).

TASK [kube-node : 轮询等待kubelet启动] ***************************************************************************************************
fatal: [10.18.127.5]: FAILED! => {"attempts": 4, "changed": true, "cmd": "systemctl status kubelet.service|grep Active", "delta": "0:00:00.027444", "end": "2021-06-01 23:36:29.478623", "rc": 0, "start": "2021-06-01 23:36:29.451179", "stderr": "", "stderr_lines": [], "stdout": "   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-06-01 23:36:28 EDT; 1s ago", "stdout_lines": ["   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-06-01 23:36:28 EDT; 1s ago"]}

查看日志journalctl -xe

The start-up result is done.
6月 02 01:07:49 comput5 systemd[49478]: Failed at step EXEC spawning /var/lib/minikube/binaries/v1.17.3/kubelet: No such file or directory
-- Subject: Process /var/lib/minikube/binaries/v1.17.3/kubelet could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /var/lib/minikube/binaries/v1.17.3/kubelet could not be executed and failed.

该怎么解决？

**Comment by gjmzj** [comment]
是因为你的系统环境以前装过minikube，没有清理干净；
请使用全新的系统安装

**Comment by wangzy0327** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月5日(星期六) 下午4:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [easzlab/kubeasz] k8s集群的测试、开发环境--单节点部署(aio) - kubelet启动失败 (#1025)





 
是因为你的系统环境以前装过minikube，没有清理干净；
 请使用全新的系统安装
