### ISSUE TITLE
KUBEASZ_VER 3.1.0部署nodelocaldns的几个问题

### ISSUE THREAD

**Issue by duudo** [easzlab/kubeasz#1027]
KUBEASZ_VER=3.1.0,有几个问题：

1. nodelocaldns-ipvs/iptables.yaml.j2中的images版本号是写死为1.16.0版本，而不是通过获取配置的 nodelocaldns版本号，导致yaml中镜像版本号和实际的配置文件中指定的不一致，进而启动时找不到镜像。
2. nodelocaldns-ipvs/iptables.yaml.j2中使用的是DaemonSet，但是cluster-addon的脚本中host只是node节点，这样会导致master节点没有导入相关的镜像，进而pod启动失败。
3. nodelocaldns的镜像分发只有对node节点的处理，master节点没有导入镜像。

**Comment by gjmzj** [comment]
问题1，之前也发现了，已经修复commit 1cc2ac039fd5dda02dbbccf5657356e91dcddc98

问题2/3，nodelocaldns 的镜像在 roles/kube-node/tasks/main.yml 中分发镜像，所以不管master/node节点都会有导入镜像

**Comment by LynnTh** [comment]
自己下载node-local-dns镜像后，该pod显示crashloopbackoff，日志显示：plugin/forward: no nameservers found 。大佬求解

**Comment by gjmzj** [comment]
> 自己下载node-local-dns镜像后，该pod显示crashloopbackoff，日志显示：plugin/forward: no nameservers found 。大佬求解

看着就是配置不对吧；看官网文档很详细的安装步骤，kubeasz也是完全参考它部署的
