### ISSUE TITLE
新安装的集群，若master数量小于等于2，则集群计算节点安装失败。

### ISSUE THREAD

**Issue by hellolittlewei** [easzlab/kubeasz#1037]
![image](https://user-images.githubusercontent.com/48649837/123060854-ae761580-d43d-11eb-9b03-b018bf8637a3.png)
具体原因如下：
kube-node/tasks/node_lb.yml
- block:
  - name: 替换 kubeconfig 的 apiserver 地址
    lineinfile:
      dest: "{{ item }}"
      regexp: "^    server"
      line: "    server: {{ KUBE_APISERVER }}"
    with_items:
    - "/root/.kube/config"
    - "/etc/kubernetes/kubelet.kubeconfig"
    - "/etc/kubernetes/kube-proxy.kubeconfig"
  
  - name: restart kube_node service
    service: name={{ item }} state=restarted
    with_items:
    - kubelet
    - kube-proxy
    ignore_errors: true
  when: "MASTER_CHG == 'yes' and groups['kube_master']|length < 3"
  tags: restart_lb

################################################
kube-node/task/main.yml
# 每个 node 节点运行 haproxy 连接到多个 apiserver
- import_tasks: node_lb.yml
  when: "inventory_hostname not in groups['kube_master']"

- name: 替换 kubeconfig 的 apiserver 地址
  lineinfile:
    dest: /root/.kube/config
    regexp: "^    server"
    line: "    server: {{ KUBE_APISERVER }}"

##----------kubelet 配置部分--------------
# 创建 kubelet 相关证书及 kubelet.kubeconfig
- import_tasks: create-kubelet-kubeconfig.yml

应该先运行create-kubelet-kubeconfig.yml生成config

**Comment by gjmzj** [comment]
新版本3.1.0已经优化这块内容了
