### ISSUE TITLE
3.1.0版本部署的v1.21.0集群，metric-server无法获取pod的cpu内存指标

### ISSUE THREAD

**Issue by 84372051** [easzlab/kubeasz#1038]
经过多次测试，v1.21.0下的pod均已经配置resources限制，都无法获取指标

![image](https://user-images.githubusercontent.com/45719547/123063401-f39b4700-d43f-11eb-9190-a297dd480146.png)

后降级为v1.20.5 ，其它都未改变，功能正常
![image](https://user-images.githubusercontent.com/45719547/123063539-188fba00-d440-11eb-80ab-79349b0653a7.png)

**Comment by hellolittlewei** [comment]
没有安装metric-server吧
