### ISSUE TITLE
异地云服务器部署集群

### ISSUE THREAD

**Issue by chenguod** [easzlab/kubeasz#1047]
4台云服务器，之间内网不通，都可以通过公网互相访问，按照文档部署失败，有大佬说说这个支持我这种异地云服务器搭建集群吗，蟹蟹。

**Comment by gjmzj** [comment]
k8s节点之间需要开放很多端口，不是简单的公网地址能ping通和部分端口通就可以

**Comment by Astrals24** [comment]
你是哪步失败了？可以详细说说
