### ISSUE TITLE
add node时，新加节点出现mynet0导致ip冲突

### ISSUE THREAD

**Issue by honkerwjk** [easzlab/kubeasz#1054]
执行ezctl命令进行安装新节点时，新加node多出一个mynet0网卡，导致ip冲突！从其它地方考证并不是都会出现，不知原因！

**Comment by cjmaliao** [comment]
我用3.1.0的时候add node也出现过这种情况，把mynet0网卡删除，dummpy网卡也删除，然后再启动新的pod就正常了
