### ISSUE TITLE
通过公网IP部署的时候，发现配置文件里面是公网地址

### ISSUE THREAD

**Issue by waxi-i** [easzlab/kubeasz#1058]
如题，这块多个云平台部署，跨公网的环境，现在想通过本地的电脑集中部署k8s集群，本地的电脑来管理，
这个时候会配置文件是公网IP的情况，我看取的变量是{{ inventory_hostname }}
目前出现了一个 etcd服务   取的是公网地址，然后就无法启动了

**Comment by Astrals24** [comment]
可以把监听全改为0.0.0.0试试
