### ISSUE TITLE
ezctl setup k8s-01 05失败

### ISSUE THREAD

**Issue by bluesky4485** [easzlab/kubeasz#1063]
前面的01-04任务都执行成功，执行到05的时候报下面的错，

TASK [kube-node : 创建kubelet的配置文件] **************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error                                                                          was: AnsibleUndefinedVariable: {%- if CONTAINER_RUNTIME == 'containerd' -%} systemd {%- el                                                                         se -%} {%- if DOCKER_VER|float >= 20.10 -%} systemd {%- else -%} cgroupfs {%- endif -%} {%-                                                                          endif -%}: 'DOCKER_VER' is undefined
fatal: [192.168.50.213]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {%                                                                         - if CONTAINER_RUNTIME == 'containerd' -%} systemd {%- else -%} {%- if DOCKER_VER|float >=                                                                          20.10 -%} systemd {%- else -%} cgroupfs {%- endif -%} {%- endif -%}: 'DOCKER_VER' is undefi                                                                         ned"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error                                                                          was: AnsibleUndefinedVariable: {%- if CONTAINER_RUNTIME == 'containerd' -%} systemd {%- el                                                                         se -%} {%- if DOCKER_VER|float >= 20.10 -%} systemd {%- else -%} cgroupfs {%- endif -%} {%-                                                                          endif -%}: 'DOCKER_VER' is undefined
fatal: [192.168.50.214]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {%                                                                         - if CONTAINER_RUNTIME == 'containerd' -%} systemd {%- else -%} {%- if DOCKER_VER|float >=                                                                          20.10 -%} systemd {%- else -%} cgroupfs {%- endif -%} {%- endif -%}: 'DOCKER_VER' is undefi                                                                         ned"}

PLAY RECAP ********************************************************************************
192.168.50.212             : ok=1    changed=0    unreachable=0    failed=0    skipped=42                                                                            rescued=0    ignored=0
192.168.50.213             : ok=22   changed=10   unreachable=0    failed=1    skipped=0                                                                             rescued=0    ignored=0
192.168.50.214             : ok=22   changed=10   unreachable=0    failed=1    skipped=0                                                                             rescued=0    ignored=0

3台机器都是裸机新装的系统。

使用本仓库最新版本的代码3.1.0。

**Comment by bluesky4485** [comment]
临时解决办法  直接把 DOCKER_VER 写死了

**Comment by baihailiang125** [comment]
请问在哪里改DOCKER_VER？
