### ISSUE TITLE
安装单节点1.22.0版本k8s时出现以下报错

### ISSUE THREAD

**Issue by Aaron-23** [easzlab/kubeasz#1067]
![image](https://user-images.githubusercontent.com/50609288/133879717-c9249ad1-e82e-4800-ae65-7fbcd8952a3b.png)
![image](https://user-images.githubusercontent.com/50609288/133879725-da81a164-83da-4449-9178-7d48e5122141.png)
  
手动执行依然报错

![image](https://user-images.githubusercontent.com/50609288/133879734-e9fe0b16-be40-4bfb-a7cb-5c61cb822b27.png)

**Comment by gjmzj** [comment]
你用的kubeasz版本是哪一个？我用kubeasz 3.1.0 版本安装k8s 1.22.x 没有问题的

**Comment by gjmzj** [comment]
The apiregistration.k8s.io/v1beta1 API version of APIService is no longer served as of v1.22.

把 apiregistration.k8s.io/v1beta1 替换成 apiregistration.k8s.io/v1就行
