### ISSUE TITLE
部署etcd服务报错

### ISSUE THREAD

**Issue by Buruilian** [easzlab/kubeasz#1069]
Sep 22 23:44:05 k8s-master1 etcd[82362]: rejected connection from "10.0.0.13:43146" (error "remote error: tls: bad certificate", ServerName "")
Sep 22 23:44:05 k8s-master1 etcd[82362]: rejected connection from "10.0.0.12:47532" (error "remote error: tls: bad certificate", ServerName "")
Sep 22 23:44:05 k8s-master1 etcd[82362]: rejected connection from "10.0.0.12:47536" (error "remote error: tls: bad certificate", ServerName "")

**Comment by gjmzj** [comment]
估计是机器间时间没有同步
