### ISSUE TITLE
第04步 轮询等待node达到Ready状态 一直超时 报错"Error from server (NotFound): nodes"

### ISSUE THREAD

**Issue by Astrals24** [easzlab/kubeasz#1074]
所有服务器上的所有服务检查均启动正常，日志也没有报错，服务器均能ssh互通，但是到这一步就一直等待。

[root@VM-4-14-centos kubeasz]# kubectl get node
No resources found

TASK [kube-node : 轮询等待kubelet启动] ***************************************************************
changed: [110.42.134.86]
FAILED - RETRYING: 轮询等待node达到Ready状态 (8 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (7 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (6 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (5 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (4 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (3 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (2 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (1 retries left).

TASK [kube-node : 轮询等待node达到Ready状态] *********************************************************
fatal: [110.42.134.86]: FAILED! => {"attempts": 8, "changed": true, "cmd": "/opt/kube/bin/kubectl get node 110.42.134.86|awk 'NR>1{print $2}'", "delta": "0:00:00.201391", "end": "2021-09-27 18:59:06.254475", "msg": "", "rc": 0, "start": "2021-09-27 18:59:06.053084", "stderr": "Error from server (NotFound): nodes \"110.42.134.86\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"110.42.134.86\" not found"], "stdout": "", "stdout_lines": []}

**Comment by gjmzj** [comment]
查看kubelet 日志，journalctl -u kubelet 仔细看看

**Comment by Astrals24** [comment]
用的2台 1核2G的腾讯云  1台阿里云  是否可能是内存问题？

**Comment by caihy05** [comment]
是不是安全组的问题？

**Comment by Monkey-D-Luffy-JT** [comment]
Hi，您的这个问题解决了吗？如何解决的，方便告知下吗？

**Comment by sunerpy** [comment]
离线安装
centos7.6
2master  2node   
同样出现这个问题  不过是node节点kubelet有问题  虽然服务是active  不过无法使用kubectl get nodes获取节点信息

**Comment by Astrals24** [comment]
> Hi，您的这个问题解决了吗？如何解决的，方便告知下吗？

我在服务器全部更换为腾讯云后成功，有可能是不同云厂商服务器有所区别或限制

**Comment by Astrals24** [comment]
> 

查看kubelet日志 是否发现了报错信息？

**Comment by Astrals24** [comment]
> 离线安装 centos7.6 2master 2node 同样出现这个问题 不过是node节点kubelet有问题 虽然服务是active 不过无法使用kubectl get nodes获取节点信息

查看kubelet日志 是否发现了报错信息
