### ISSUE TITLE
prometheus 配置告警邮件

### ISSUE THREAD

**Issue by krmao** [easzlab/kubeasz#1079]
根据 [prometheus 文档](https://github.com/easzlab/kubeasz/blob/master/docs/guide/prometheus.md) 不知道该怎么处理设置邮件告警, 写在哪个文件(文档中那个文件应该已经不存在了)，执行什么指令更新等, 新手无从下手, 希望能完善下新的文档步骤
![image](https://user-images.githubusercontent.com/7344437/137090611-9b47596f-456e-4158-bbbf-86a86cb9c14c.png)

**Comment by gjmzj** [comment]
这个文档确实需要更新了，这些组件迭代太快。。。
