### ISSUE TITLE
三个节点，三主三WORK，测试访问速度的时候，其中2个节点通过nodeport测试访问速度很慢

### ISSUE THREAD

**Issue by yetianyue** [easzlab/kubeasz#1081]
节点1：  10.6.1.12       32GB - 16CPU
节点2：  10.6.1.38       32GB - 16CPU
节点3：  10.6.1.39       32GB - 16CPU
--------------------------------------------------------------
`
[root@nginx-16 ~]# curl -o /dev/null -s -w %{time_namelookup}::%{time_connect}::%{time_pretransfer}::%{time_starttransfer}::%{time_total}::%{speed_download}"\n"  "http://10.6.1.12:30000/swagger/swagger-ui.html"
0.000::0.001::0.001::0.022::0.022::155756.000
[root@nginx-16 ~]# curl -o /dev/null -s -w %{time_namelookup}::%{time_connect}::%{time_pretransfer}::%{time_starttransfer}::%{time_total}::%{speed_download}"\n"  "http://10.6.1.38:30000/swagger/swagger-ui.html"
0.000::0.001::0.002::6.014::6.014::564.000
[root@nginx-16 ~]# curl -o /dev/null -s -w %{time_namelookup}::%{time_connect}::%{time_pretransfer}::%{time_starttransfer}::%{time_total}::%{speed_download}"\n"  "http://10.6.1.39:30000/swagger/swagger-ui.html"
0.000::0.001::0.001::6.018::6.018::563.000
`

![1634690625(1)](https://user-images.githubusercontent.com/15798673/138009451-c74c399b-1983-4043-a81b-defe70b4cf9f.png)
原先是通过Ingress暴露的，通过Nginx负载均衡过来，发现有时候访问很卡，排查Nginx后没有问题。就用nodeport开启对外访问的关口。
在另一台16节点上测试，访问内部部署的swagger服务。发现一个有意思的现象，访问12服务器正常速度，其他38,39的2个节点访问速度很慢，三台服务器的负载情况均为正常，有什么排查方向？？ 
![1634690979(1)](https://user-images.githubusercontent.com/15798673/138009883-b43b1800-d781-465e-b3d3-dc190b3f599c.png)
![1634691004(1)](https://user-images.githubusercontent.com/15798673/138009924-4530fc42-aa77-4eb7-89a6-e0ec77ca9f35.png)
![image](https://user-images.githubusercontent.com/15798673/138009944-cfd7c1d6-1c60-4c2d-b7c6-6ecbd00726ce.png)

**Comment by gjmzj** [comment]
看下pod实际在哪个节点上，然后确认下是不是pod所在节点nodePort比较快，而其他节点很慢

**Comment by lkad** [comment]
https://github.com/InfuseAI/k8s-iperf  可以先用这个工具测试下集群内部访问有没问题，然后再找外部的原因

**Comment by yetianyue** [comment]
> https://github.com/InfuseAI/k8s-iperf 可以先用这个工具测试下集群内部访问有没问题，然后再找外部的原因



> 看下pod实际在哪个节点上，然后确认下是不是pod所在节点nodePort比较快，而其他节点很慢
12节点测试
![image](https://user-images.githubusercontent.com/15798673/140300822-f5dad32a-80ed-4b5e-9dc5-214115d2217a.png)
38节点测试
![image](https://user-images.githubusercontent.com/15798673/140300858-92091111-446e-484a-add5-13b726ef9c1e.png)
39节点测试
![image](https://user-images.githubusercontent.com/15798673/140300894-c4163266-0531-4efd-92a7-b036e211682f.png)
还是一样，38,39节点很慢

**Comment by yetianyue** [comment]
解决了，发现calico开启隧道后很慢
