### ISSUE TITLE
kubeasz 3.1.1 版本问题反馈

### ISSUE THREAD

**Issue by piano-wow** [easzlab/kubeasz#1084]
kubectl get componentstatuses
报错：
controller-manager   Unhealthy   Get "https://127.0.0.1:10257/healthz": dial tcp 127.0.0.1:10257: connect: connection refused

截图：
![image](https://user-images.githubusercontent.com/35907674/139212713-96b628d9-e91b-4d48-85d2-b40e339e04a9.png)

**Comment by muziriyueliming** [comment]
解决了?

**Comment by muziriyueliming** [comment]
[root@k8s-aio ~]# kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE                         ERROR
scheduler            Healthy   ok
controller-manager   Healthy   ok
etcd-0               Healthy   {"health":"true","reason":""}

![image](https://user-images.githubusercontent.com/48202971/140079324-4f9e8284-2345-4ffc-a344-a5cd14d4fc4e.png)

/etc/systemd/system/kube-controller-manager.service
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/opt/kube/bin/kube-controller-manager \
  --bind-address=127.0.0.1 \     替换ip这个就好了
  --allocate-node-cidrs=true \
  --cluster-cidr=172.20.0.0/16 \
  --cluster-name=kubernetes \
  --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem \
  --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem \
  --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig \
  --leader-elect=true \
  --node-cidr-mask-size=24 \
  --root-ca-file=/etc/kubernetes/ssl/ca.pem \
  --service-account-private-key-file=/etc/kubernetes/ssl/ca-key.pem \
  --service-cluster-ip-range=10.68.0.0/16 \
  --use-service-account-credentials=true \
  --v=2
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by muziriyueliming** [comment]
![image](https://user-images.githubusercontent.com/48202971/140080583-599689d5-2def-46dc-8963-e095cfe7f1ee.png)
====================
 journalctl -xefu kubelet
![image](https://user-images.githubusercontent.com/48202971/140080914-103d11a6-96f4-438f-ada4-bba52d815bb6.png)
======
https://www.cnblogs.com/lajiao/p/15044705.html

**Comment by piano-wow** [comment]
这是来自QQ邮箱的自动回复邮件。来信已收到！

**Comment by piano-wow** [comment]
这是来自QQ邮箱的自动回复邮件。来信已收到！
