### ISSUE TITLE
想请教关于service ip不足的问题

### ISSUE THREAD

**Issue by adsszl** [easzlab/kubeasz#1088]
我在初始规划集群时，给了整个集群256个service IP地址，然而随着集群的扩大，svc的ip已经不能满足业务需要，但是此集群已经跑了很多核心业务，我改如何扩展我得svc IP

**Comment by gjmzj** [comment]
没有看到过能够扩大svc地址池的，不过可以考虑部分应用使用 headless svc 这样可以节省service 地址。。。
