### ISSUE TITLE
ezctl所在主机需要回收，请问如何迁移到另一个主机上呢？

### ISSUE THREAD

**Issue by licunzhi** [easzlab/kubeasz#1091]
ezctl所在主机需要回收，请问如何迁移到另一个主机上呢？

**Comment by gjmzj** [comment]
1./etc/kubeasz 整体目录打包迁移过去
2./root/.ssh 目录也迁移过去
3./root/.kube 迁移

大概这些，用个测试机器先试试

**Comment by licunzhi** [comment]
> 

好的
我尝试一下

**Comment by licunzhi** [comment]
实践认证方法可行

ssh文件中的内容重新生成并设置主机互信也是可以的
.kube文件中的内容没有拷贝

只是迁移了/etc/kubeasz原则上就是可以的
