### ISSUE TITLE
云主机安装ansiable报错

### ISSUE THREAD

**Issue by licunzhi** [easzlab/kubeasz#1098]
![image](https://user-images.githubusercontent.com/25954140/147014795-65117649-1cb1-4323-be82-c3b4b30eef71.png)

我尝试了这种解决办法是可以的，仅供参考
解决方式：更新setuptools
运行：pip install setuptools -U

**Comment by nangongchengfeng** [comment]
pip install --upgrade pip
pip install --upgrade setuptools
