### ISSUE TITLE
python3环境安装执行ezctl setup k8s-01 all ansible报错

### ISSUE THREAD

**Issue by caihy05** [easzlab/kubeasz#1101]
![image](https://user-images.githubusercontent.com/22835153/148733070-8300741e-6df7-4bce-91a7-a049c54acdf3.png)

问题：脚本roles/kube-node/tasks/node_lb.yml在线安装haproxy报错，fatal: [172.17.166.12]: FAILED! => {"changed": false, "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}

解决：修改oles/kube-node/tasks/node_lb.yml中package为dnf安装成功

建议：请针对python3做一个兼容

**Comment by gjmzj** [comment]
OK，不过新版本里面node_lb不需要haproxy了
