### ISSUE TITLE
主节点和etcd集群部署在一起，如果剔除其中一节点的etcd后，再add-etcd 进来，必现的错误，请帮忙看看

### ISSUE THREAD

**Issue by kuaiwenwu** [easzlab/kubeasz#1104]
kubeasz 版本 3.1.1

主节点+etcd 集群分别部署在以下三节点
172.18.207.147
172.18.207.148
172.18.207.149
 集群安装完后，现在ezctl del-etcd  k8s-01 172.18.207.148  可以成功剔除并启动正常
此时再使用命令ezctl add-etcd  k8s-01 172.18.207.148 把刚刚的剔除的etcd节点再次加入进来就会出错。
出错信息如下：
![image](https://user-images.githubusercontent.com/24381401/150097492-11ffc481-5bc8-43d8-8bbe-bf5bee9030f7.png)
请帮忙测试看看v问题吧

ps: 看148机器的etcd 启动不起来 ，错误信息如下：
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"warn","ts":"2022-01-19T16:45:19.646+0800","caller":"etcdserver/server.go:1142","msg":"server error","error":"the member has been permanently removed from the cluster"}
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"warn","ts":"2022-01-19T16:45:19.646+0800","caller":"etcdserver/server.go:1143","msg":"data-dir used by this member must be removed"}
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"warn","ts":"2022-01-19T16:45:19.646+0800","caller":"etcdserver/server.go:2038","msg":"stopped publish because server is stopped","local-member-id":"447d663938a973f8","local-member-a
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"info","ts":"2022-01-19T16:45:19.646+0800","caller":"rafthttp/peer.go:330","msg":"stopping remote peer","remote-peer-id":"350c259bd0828a6e"}
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"info","ts":"2022-01-19T16:45:19.646+0800","caller":"rafthttp/stream.go:294","msg":"stopped TCP streaming connection with remote peer","stream-writer-type":"unknown stream","remote-p
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"info","ts":"2022-01-19T16:45:19.646+0800","caller":"rafthttp/stream.go:294","msg":"stopped TCP streaming connection with remote peer","stream-writer-type":"unknown stream","remote-p
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"info","ts":"2022-01-19T16:45:19.646+0800","caller":"rafthttp/pipeline.go:85","msg":"stopped HTTP pipelining with remote peer","local-member-id":"447d663938a973f8","remote-peer-id":"
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"info","ts":"2022-01-19T16:45:19.646+0800","caller":"rafthttp/stream.go:442","msg":"stopped stream reader with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"info","ts":"2022-01-19T16:45:19.646+0800","caller":"rafthttp/stream.go:442","msg":"stopped stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"4
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"info","ts":"2022-01-19T16:45:19.646+0800","caller":"rafthttp/peer.go:335","msg":"stopped remote peer","remote-peer-id":"350c259bd0828a6e"}
Jan 19 16:45:19 k8s-master-02 etcd[13061]: {"level":"info","ts":"2022-01-19T16:45:19.651+0800","caller":"etcdmain/main.go:47","msg":"notifying init daemon"}
Jan 19 16:45:19 k8s-master-02 systemd[1]: Started Etcd Server.

**Comment by gjmzj** [comment]
报错好像是因为手动删除etcd节点后，再添加节点要用新ip；具体错误我得自己重现下看看
