### ISSUE TITLE
dashboard无法访问

### ISSUE THREAD

**Issue by shineycoding** [easzlab/kubeasz#1106]
在阿里云上创建的单节点，通过浏览器无法访问dashboard。
![image](https://user-images.githubusercontent.com/12545744/151125481-4f511902-6502-4fb2-aae4-6897fa1ee2c1.png)
![image](https://user-images.githubusercontent.com/12545744/151125877-ed8df02c-731e-4374-8515-cdabf2303598.png)
![image](https://user-images.githubusercontent.com/12545744/151467654-0a4b7ffa-e80c-4794-ba45-fed4f1e76493.png)

**Comment by gjmzj** [comment]
阿里云机器上安全组，没有开放30285端口吧
