### ISSUE TITLE
calico bgp rr模式，如何支持多k8s集群？

### ISSUE THREAD

**Issue by yuanqixun** [easzlab/kubeasz#1108]
如题，怎么配置calico bgp rr模式，支持多k8s集群，使之能够将多个k8s集群的pod能够互联互通？请赐教，谢谢。

**Comment by 21ki** [comment]
同求

**Comment by jmszg** [comment]
> 如题，怎么配置calico bgp rr模式，支持多k8s集群，使之能够将多个k8s集群的pod能够互联互通？请赐教，谢谢。

确实是个好idea，但是还没有玩过这种跨多集群的，在实际的生产环境这种场景多吗？
