### ISSUE TITLE
controller-manager 监控数据无法采集

### ISSUE THREAD

**Issue by taoshanghu** [easzlab/kubeasz#1113]
你好！
   首先表示你的项目很好，我通过你开源的工具部署K8S集群后，在K8S集群监控部署完成后，发现 controller-manager 无法采集到监控数据，通过手动调用，还是获取不到监控数据调用调用方法： curl -k https://ip:10257/metrics和curl http://ip:10257/metrics最后都返回异常

![image](https://user-images.githubusercontent.com/14832994/156085662-d4c990d7-0350-4c05-b990-e23dec28e99f.png)
![image](https://user-images.githubusercontent.com/14832994/156085695-ed990a65-1f25-46af-8407-69da0e31ff1c.png)
目前还没有找到问题原因，请问这是什么问题导致的

**Comment by 905839698** [comment]
我也遇到了

**Comment by Changego** [comment]
我也是

**Comment by doglas1999** [comment]
kube-controller-manager.service 启动参数
修改为
  --bind-address=0.0.0.0 \
增加
  --authentication-kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig \
  --authorization-kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig \
kube-scheduler 启动参数
修改为
  --bind-address=0.0.0.0 \
增加
  --authentication-kubeconfig=/etc/kubernetes/kube-scheduler.kubeconfig \
  --authorization-kubeconfig=/etc/kubernetes/kube-scheduler.kubeconfig \
第一个的修改捆绑ip是解决connect: connection refused问题
第二个增加认证和授权证书是解决server returned HTTP status 403 Forbidden问题
