### ISSUE TITLE
kubeasz 初始化 hosts 文件里能否使用对应的域名 不用ip 初始化集群

### ISSUE THREAD

**Issue by guangnensh** [easzlab/kubeasz#1115]
想要的效果
kubectl get nodes

hdxx.xx.host.com  master 
hdxx.xx.host.com node

**Comment by piano-wow** [comment]
这个问题早就有人提了
作者不改，有他的考虑
实际用起来，也没太大关系

**Comment by guangnensh** [comment]
> 这个问题早就有人提了 作者不改，有他的考虑 实际用起来，也没太大关系

主要是云上使用的时候，有这部分诉求，这样的话只能重签证书了

**Comment by piano-wow** [comment]
这是来自QQ邮箱的自动回复邮件。来信已收到！
