### ISSUE TITLE
使用kubeasz3.2.0版本安装harbor提示Destination /etc/cloud/templates/hosts.redhat.tmpl does not exist !

### ISSUE THREAD

**Issue by sunhuaxu** [easzlab/kubeasz#1116]
TASK [Update the trusted ca-certificates] *****************************************************************************
changed: [192.168.1.62]
changed: [192.168.1.63]
changed: [192.168.1.64]

TASK [restart containerd] *********************************************************************************************
changed: [192.168.1.62]
changed: [192.168.1.64]
changed: [192.168.1.63]

TASK [Adding an '/etc/hosts' entry for the HARBOR DOMAIN] *************************************************************
changed: [192.168.1.62]
changed: [192.168.1.64]
changed: [192.168.1.63]

TASK [Adding cloud-init hosts template (redhat) entry for the HARBOR DOMAIN] ******************************************
fatal: [192.168.1.62]: FAILED! => {"changed": false, "msg": "Destination /etc/cloud/templates/hosts.redhat.tmpl does not exist !", "rc": 257}
fatal: [192.168.1.64]: FAILED! => {"changed": false, "msg": "Destination /etc/cloud/templates/hosts.redhat.tmpl does not exist !", "rc": 257}
fatal: [192.168.1.63]: FAILED! => {"changed": false, "msg": "Destination /etc/cloud/templates/hosts.redhat.tmpl does not exist !", "rc": 257}

**Comment by bigxue** [comment]
你可以在节点机器创建个此文件，内容可以和/etc/hosts 内容保持一致，也可以修改下命令脚本 kubeasz/playbooks/11.harbor.yml 
将 /etc/cloud/templates/hosts.redhat.tmpl 换成 /etc/hosts
