### ISSUE TITLE
kubeasz 3.2.0  node节点kube-proxy报错 ：Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get "https://127.0.0.1:6443/apis/discover...": EOF

### ISSUE THREAD

**Issue by sunerpy** [easzlab/kubeasz#1129]
linux 版本： CentOS Linux release 7.6.1810
内核版本： 3.10.0-957.el7.x86_64
k8s 版本： Kubernetes 1.23.1
部署方式：offline

<html>
<body>
<div data-node-id="20220402194945-1hldk79" data-node-index="23" data-type="NodeTable" class="table protyle-wysiwyg--select" style="width: 100%; flex: 0 0 auto;" updated="20220403003335" colgroup="width: 203px;|width: 235px;|width: 302px;|width: 105px;|width: 113px;|width: 248px;"><div contenteditable="false" style="">

主机名称 | 主机IP | 节点角色 | CPU | 内存 | 操作系统
-- | -- | -- | -- | -- | --
k8snode1 | 192.168.122.246 | master | 4C | 8G | Centos7.6
k8snode2 | 192.168.122.245 | master | 4C | 8G | Centos7.6
k8snode3 | 192.168.122.244 | node | 4C | 8G | Centos7.6
k8snode4 | 192.168.122.243 | node | 4C | 8G | Centos7.6
harbor.io | 192.168.122.1 | KVM宿主机 ansible节点  harbor仓库 ntp服务器 | 24C | 64G | OracleLinux7.6

<div class="protyle-action__table"><div class="table__resize" data-col-index="4" style="height:238px;left: 829px;display:block"></div><div class="table__select" style="left:0px;top:0px;height:237px;width:985px;"></div></div></div><div class="protyle-attr" contenteditable="false"></div></div>​
</body>
</html>

（因特殊原因无法取得字符日志，只能截图提供……）

故障现象：k8snode1、k8snode2两个master节点正常，可发现master节点。k8snode3、k8snode4两个node节点失败

![image](https://user-images.githubusercontent.com/30691040/161393349-40116744-fc8c-4700-948a-7b79c8ddfa73.png)

4个k8s节点均为centos7.6最小化安装，每次都是node3和node4到这一步就会失败，且两个master节点运行正常，但是在kube-node等待node状态就会失败，kubelet日志如下：
![image](https://user-images.githubusercontent.com/30691040/161393465-06fc85a9-c708-44d3-922b-3a6e4b44f500.png)

![image](https://user-images.githubusercontent.com/30691040/161393360-93045ab7-4fa7-4c32-9319-03c71ad44aeb.png)

注：4个VM均做了初始化安装时候的快照，每次实验都是在快照恢复后进行的。也尝试过克隆k8snode1的最小化安装镜像作为k8snode3、k8snode4，均复现上述报错。经过对比发现失败的node节点`kube-proxy` 有如下报错：

![image](https://user-images.githubusercontent.com/30691040/161393369-295d7339-2a6f-47bc-9aaf-d061d7178964.png)

**Comment by zhenbin0805** [comment]
博主 请问 最后怎么修复的
