### ISSUE TITLE
一个master，一个node，完成部署后，master节点正常，但是node节点未能完成kubectl的安装，安装过程记录如下。

### ISSUE THREAD

**Issue by linjie830914** [easzlab/kubeasz#1130]
kubeasz 安装过程脚本记录：
[kubeasz-安装过程脚本记录.md](https://github.com/easzlab/kubeasz/files/8422770/kubeasz-.md)

**Comment by linjie830914** [comment]
在执行安装脚本之前，master和node两台服务器，需要做什么初始化设置吗？
1、同一局域网，192.168.100.50（master）,192.168.100.60（node）
2、账号root，密码都一样的
3、执行脚本前我已执行“yum update -y”
==4、默认待python2，执行脚本会升级到2.7.16，但是执行脚本过程中有如下提示，还请帮忙解答一下解决方案？==
```
[WARNING]: Distribution centos 7.9.2009 on host 192.168.100.50 should use /usr/bin/python, but is using /usr/bin/python2.7, since the discovered platform python interpreter was not
present. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [192.168.100.50]
```

**Comment by ssslkj123** [comment]
查到有关文章说在`./ansible.cfg` 或 ` ~/.ansible.cfg`   添加：
```
[defaults]
interpreter_python=auto_silent 
```
可忽略该问题，可以尝试验证一下。

**Comment by linjie830914** [comment]
> 貌似这里是个warning ， 还是可以过去的。此外安装文档当中有提到这样一句话，
> 
> ```
> 3.2 在ansible控制端配置免密码登录
> # 更安全 Ed25519 算法
> ssh-keygen -t ed25519 -N '' -f ~/.ssh/id_ed25519
> # 或者传统 RSA 算法
> ssh-keygen -t rsa -b 2048 -N '' -f ~/.ssh/id_rsa
> 
> ssh-copy-id $IPs #$IPs为所有节点地址包括自身，按照提示输入yes 和root密码
> 
> # 为每个节点设置python软链接
> ssh $IPs ln -s /usr/bin/python3 /usr/bin/python
> ```
> 
> 如果在centos当中，由于默认的yum 是基于 python2来进行编写的，如果按照 文档上说的，做了软链到 `/usr/bin/python` 那么就会导致 yum 无法使用的情况，不知道是否该报错与这有关。
谢谢您，yum默认使用python2的问题我已经使用如下脚本处理了,应该不是这个问题。
```
sed -i '1,2s/python/python2.7/g' /usr/bin/yum
sed -i '1,2s/python/python2.7/g' /usr/libexec/urlgrabber-ext-down
````
