### ISSUE TITLE
部署flannel插件，pause变量问题

### ISSUE THREAD

**Issue by unicornmillion** [easzlab/kubeasz#1138]
Warning  FailedCreatePodSandBox  40s (x3 over 3m29s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "easzlab/pause:__pause__": Error response from daemon: manifest for easzlab/pause:__pause__ not found: manifest unknown: manifest unknown

已经在config.yml，先后修改指定pause版本，重新部署失败，然后选择离线部署，本地已有pause:3.6镜像
# 可选离线安装系统软件包 (offline|online)
INSTALL_SOURCE: "offline"
# [containerd]基础容器镜像
SANDBOX_IMAGE: "easzlab/pause:3.6"

root@master-1:~# docker images
REPOSITORY                                TAG       IMAGE ID       CREATED         SIZE
easzlab/kubeasz                           3.2.0     cbf7e17a5ddb   4 months ago    164MB
easzlab/kubeasz-ext-bin                   1.0.0     ce7839fb3045   4 months ago    424MB
easzlab/kubeasz-sys-pkg                   0.4.2     222fb7c87bd2   4 months ago    67.2MB
easzlab/kubeasz-k8s-bin                   v1.23.1   ae2da67299c5   4 months ago    523MB
alpine                                    latest    c059bfaa849c   5 months ago    5.59MB
harbor.mzy.net/k8s-service/alpine         v2        c059bfaa849c   5 months ago    5.59MB
easzlab/metrics-server                    v0.5.2    f73640fb5061   5 months ago    64.3MB
harbor.mzy.net/k8s-service/flannel        v0.15.1   e6ea68648f0c   5 months ago    69.5MB
easzlab/flannel                           v0.15.1   e6ea68648f0c   5 months ago    69.5MB
kubernetesui/dashboard                    v2.4.0    72f07539ffb5   6 months ago    221MB
coredns/coredns                           1.8.6     a4ca41631cc7   7 months ago    46.8MB
easzlab/k8s-dns-node-cache                1.21.1    5bae806f8f12   7 months ago    104MB
calico/node                               v3.19.3   5ee77fcf72b4   7 months ago    154MB
calico/pod2daemon-flexvol                 v3.19.3   c34539dc5eef   7 months ago    21.7MB
calico/cni                                v3.19.3   71da92beaffe   7 months ago    146MB
calico/kube-controllers                   v3.19.3   ed1e25e26ab5   7 months ago    60.6MB
easzlab/pause                             3.6       6270bb605e12   8 months ago    683kB
kubernetesui/metrics-scraper              v1.0.7    7801cfc6d5c0   11 months ago   34.4MB
easzlab/nfs-subdir-external-provisioner   v4.0.2    932b0bface75   13 months ago   43.8MB

**Comment by one-two-my-gad** [comment]
请问最后如何解决的
