### ISSUE TITLE
centos7用3.3版本单机安装报错Config not found: /etc/kubernetes/kubelet.conf

### ISSUE THREAD

**Issue by qq5776569** [easzlab/kubeasz#1144]
changed: [192.168.0.104]
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (5 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (4 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (3 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (2 retries left).
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (1 retries left).

TASK [kube-master : 以轮询的方式等待master服务启动完成] *******************************************************************************************************************************************
fatal: [192.168.0.104]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/opt/kube/bin/kubectl", "get", "node"], "delta": "0:00:00.070775", "end": "2022-06-10 10:35:22.447366", "msg": "non-zero return code", "rc": 1, "start": "2022-06-10 10:35:22.376591", "stderr": "W0610 10:35:22.440657   14851 loader.go:221] Config not found: /etc/kubernetes/kubelet.conf\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?", "stderr_lines": ["W0610 10:35:22.440657   14851 loader.go:221] Config not found: /etc/kubernetes/kubelet.conf", "The connection to the server localhost:8080 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}

**Comment by lvxiaohu** [comment]
去 192.168.0.104 节点看看kubelet 、apiserver的log ？

**Comment by gjmzj** [comment]
应该是环境不干净，可能装过其他k8s集群；kubeasz项目从来没有生成过kubelet.conf；用干净的系统再装下

**Comment by qq5776569** [comment]
謝謝，我試試

**Comment by qq5776569** [comment]
好了，之前装了Rancher有影响
