### ISSUE TITLE
混合云环境部署（公网IP部署）---是否有成功案例，推荐网络模组？

### ISSUE THREAD

**Issue by hom7** [easzlab/kubeasz#1146]
混合云公网ip部署（fannel网络），各node节点内部pod，只能本机ping通，跨机pod内网ip无法ping通。

如：请求A服务器 公网IP访问应用集群，只能访问到A服务器下的pod，，，当应用集群轮询到B服务器上的pod就会无法访问。

求教解决方案?

**Comment by whxiewy** [comment]
Flannel host-gw模式 解决办法  。在两个node上添加到对方podip的路由，路由下一跳是对方pod所处主机的ip。

**Comment by whxiewy** [comment]
这是因为没有本机pod的包发到本机出口，查找路由表的时候没有对方podip的路由条目，所以ping不通。
如果是一个二层网路可以host-gw。  但如果是公网环境，那fannel也可以vxlan。

**Comment by hom7** [comment]
> 这是因为没有本机pod的包发到本机出口，查找路由表的时候没有对方podip的路由条目，所以ping不通。 如果是一个二层网路可以host-gw。 但如果是公网环境，那fannel也可以vxlan。

尝试了下，还是会出现内网不通问题，看来只能通过iptables转发的方法了
