### ISSUE TITLE
kubeasz 3.2.0 kube-controller-manager 报错No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.

### ISSUE THREAD

**Issue by Changego** [easzlab/kubeasz#1147]
你好！
kubeasz 3.2.0 kube-controller-manager 报错No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.

请问有什么办法修复吗？
```
-- Logs begin at Fri 2022-05-06 16:04:36 CST. --
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: I0615 17:54:02.634085   12024 serving.go:347] Generated self-signed cert in-memory
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: W0615 17:54:02.962972   12024 authentication.go:316] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: W0615 17:54:02.963010   12024 authentication.go:340] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: W0615 17:54:02.963034   12024 authorization.go:193] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: I0615 17:54:02.963082   12024 controllermanager.go:186] Version: v1.22.10
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: I0615 17:54:02.966100   12024 tlsconfig.go:200] "Loaded serving cert" certName="Generated self signed cert" certDetail="\"localhost@1655286842\" [serving] validServingFor=[127.0.0.1,localhost,localhost] issuer=\"localhost-ca@1655286842\" (2022-06-15 08:54:02 +0000 UTC to 2023-06-15 08:54:02 +0000 UTC (now=2022-06-15 09:54:02.966010295 +0000 UTC))"
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: I0615 17:54:02.966335   12024 named_certificates.go:53] "Loaded SNI cert" index=0 certName="self-signed loopback" certDetail="\"apiserver-loopback-client@1655286842\" [serving] validServingFor=[apiserver-loopback-client] issuer=\"apiserver-loopback-client-ca@1655286842\" (2022-06-15 08:54:02 +0000 UTC to 2023-06-15 08:54:02 +0000 UTC (now=2022-06-15 09:54:02.966291204 +0000 UTC))"
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: I0615 17:54:02.966397   12024 secure_serving.go:200] Serving securely on [::]:10257
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: I0615 17:54:02.966516   12024 tlsconfig.go:240] "Starting DynamicServingCertificateController"
Jun 15 17:54:02 k8s01 kube-controller-manager[12024]: I0615 17:54:02.966981   12024 leaderelection.go:248] attempting to acquire leader lease kube-system/kube-controller-manager...
```

**Comment by zy1135089881** [comment]
我也遇见相似的问题了。

`1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: W0116 04:01:33.315460   13532 authorization.go:194] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.315939   13532 controllermanager.go:182] Version: v1.26.0
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.315969   13532 controllermanager.go:184] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.317284   13532 tlsconfig.go:178] "Loaded client CA" index=0 certName="request-header::/etc/kubernetes/pki/front-proxy-ca.pem" certDetail="\"kubernetes\" [] issuer=\"<self>\" (2023-01-12 02:52:00 +0000 UTC to 2122-12-19 02:52:00 +0000 UTC (now=2023-01-15 20:01:33.317245743 +0000 UTC))"
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.317422   13532 tlsconfig.go:200] "Loaded serving cert" certName="Generated self signed cert" certDetail="\"localhost@1673812892\" [serving] validServingFor=[127.0.0.1,127.0.0.1,localhost] issuer=\"localhost-ca@1673812892\" (2023-01-15 19:01:32 +0000 UTC to 2024-01-15 19:01:32 +0000 UTC (now=2023-01-15 20:01:33.317401338 +0000 UTC))"
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.317520   13532 named_certificates.go:53] "Loaded SNI cert" index=0 certName="self-signed loopback" certDetail="\"apiserver-loopback-client@1673812893\" [serving] validServingFor=[apiserver-loopback-client] issuer=\"apiserver-loopback-client-ca@1673812893\" (2023-01-15 19:01:32 +0000 UTC to 2024-01-15 19:01:32 +0000 UTC (now=2023-01-15 20:01:33.317505621 +0000 UTC))"
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.317539   13532 secure_serving.go:210] Serving securely on 127.0.0.1:10257
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.317923   13532 dynamic_cafile_content.go:157] "Starting controller" name="request-header::/etc/kubernetes/pki/front-proxy-ca.pem"
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.317956   13532 tlsconfig.go:240] "Starting DynamicServingCertificateController"
1月 16 04:01:33 kubernetes-master-01 kube-controller-manager[13532]: I0116 04:01:33.318078   13532 leaderelection.go:248] attempting to acquire leader lease kube-system/kube-controller-manager...
`
