### ISSUE TITLE
如何删除集群创建的admin客户端证书呢

### ISSUE THREAD

**Issue by sunnoy** [easzlab/kubeasz#1148]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/19342276/175506226-04260228-972e-4e8f-9b57-f4eab3cfb0ed.png">

绑定的system:masters这个组，把默认的
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/19342276/175506284-0d791c19-e4fb-41e2-8d22-de2f9ec6e018.png">

删除仍然可以使用admin权限，如何轮换这个 除了换一套ca

**Comment by gjmzj** [comment]
可以把clusterrolebindings cluster-admin 删掉试试

**Comment by sunnoy** [comment]
> 可以把clusterrolebindings cluster-admin 删掉试试

这个删除了clusterrolebindings也是可以使用admin权限的
