### ISSUE TITLE
脚本对ARM64的机器不支持

### ISSUE THREAD

**Issue by Biaogo94** [easzlab/kubeasz#1149]
希望作者能添加arm64的脚本支持，包括镜像资源。谢谢

**Comment by gjmzj** [comment]
没有arm机器资源，无法测试或者开发，有好心人可以捐赠arm服务器做测试哈哈😄

**Comment by Biaogo94** [comment]
> 没有arm机器资源，无法测试或者开发，有好心人可以捐赠arm服务器做测试哈哈😄

可以去申请甲骨文云，上面有免费的arm资源

**Comment by gjmzj** [comment]
已经支持arm64（aarc64）架构了，正在测试中
