### ISSUE TITLE
按照单机部署方式 单机快速体验k8s集群的测试环境--AllinOne部署，验证安装失败

### ISSUE THREAD

**Issue by qinyudong89** [easzlab/kubeasz#1154]
**1. kubectl version # 验证集群版本** 

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

**2.  kubectl get node        # 验证节点就绪 (Ready) 状态**
No resources found

**Comment by Shuimo03** [comment]
我之前也遇到了，把之前所有的资源删除，保证干净，然后重新安装一次就好了
