### ISSUE TITLE
prepare变量错误

### ISSUE THREAD

**Issue by bluemooder** [easzlab/kubeasz#1155]
kubeasz 3.3.1版本中，prepare role中写入环境变量应该是{{bin_dir}}，不然部署节点上找不到相关二进制文件

- name: 写入环境变量$PATH
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: 'custom PATH'
    line: 'export PATH={{ base_dir }}/bin/:$PATH  # generated by kubeasz:custom PATH'

**Comment by gjmzj** [comment]
感谢反馈，已修复
