### ISSUE TITLE
生成config.yaml后如何配置呢？

### ISSUE THREAD

**Issue by andrew2558** [easzlab/kubeasz#1157]
在执行完命令：`docker exec -it kubeasz ezctl new k8s-01`,生成的两个配置文件，`'/etc/kubeasz/clusters/umaster/hosts'`
` '/etc/kubeasz/clusters/umaster/config.yml'`,有配置的说明文档吗？怎么根据自己的环境配置呢？

**Comment by gjmzj** [comment]
这两个文件基本是自说明的，打开进去看基本能看懂；
文档在https://github.com/easzlab/kubeasz/blob/master/docs/setup/config_guide.md
