### ISSUE TITLE
通过AllinOne部署完单master后，添加节点在要添加的节点机器上要安装哪些程序？

### ISSUE THREAD

**Issue by andrew2558** [easzlab/kubeasz#1158]
通过AllinOne部署完单master后，想要在AllinOne的master下添加node, 新的node机器，要执行哪些操作？
这个文档`https://github.com/easzlab/kubeasz/blob/master/docs/op/op-node.md`
是在master上执行的还是在node机器上执行的？谢谢，我是新手，问的问题可能有点太基础，请谅解,谢谢

**Comment by andrew2558** [comment]
按文档操作，最后运行命令：`ezctl add-master test-k8s 192.168.1.11`  
提示：
`easzctl: command not found`
请问怎么回事？哪位有一个allinone部署好master后，怎样再添加node的详细教程吗？

**Comment by HandsomeBoy01** [comment]
i think you should try it

**Comment by HandsomeBoy01** [comment]
部署好后。 直接在master 节点执行就行，前提是 需要在node节点上执行初始化命令 
 export release=3.3.1
wget https://github.com/easzlab/kubeasz/releases/download/${release}/ezdown
chmod +x ./ezdown
./ezdown -D

**Comment by andrew2558** [comment]
@HandsomeBoy01 谢谢，为什么我的master上没有ezctl命令呢？

**Comment by HandsomeBoy01** [comment]
默认安装的是在 /etc/kubeasz/ 路径下

**Comment by andrew2558** [comment]
@HandsomeBoy01 非常感谢，晚上回去看看

**Comment by HandsomeBoy01** [comment]
还有一种方法  docker exec -it kubeasz ezctl   来执行也可以

**Comment by andrew2558** [comment]
@HandsomeBoy01 再次感谢，总算是搭起来了！

**Comment by HandsomeBoy01** [comment]
@andrew2558   你试试 从master 上访问nodeport 看看能不能访问通？ 前提是pod在node节点上

**Comment by andrew2558** [comment]
@HandsomeBoy01 你指的访问是怎么访问？ping吗？
