### ISSUE TITLE
为什么node节点也可以执行kubectl的命令

### ISSUE THREAD

**Issue by wengzhenqi** [easzlab/kubeasz#1160]
[root@test-n1 ~]# ss -natulp |grep 6443
tcp    LISTEN     0      511    127.0.0.1:6443                  *:*                   users:(("kube-lb",pid=16087,fd=5),("kube-lb",pid=16086,fd=5))

**Comment by gjmzj** [comment]
node能执行kubectl命令是因为下发了 /root/.kube/config，这个配置文件可以不下发，这样kubeconfig 只存放在创建的机器上，减少暴露风险
