### ISSUE TITLE
failed to do request: Head "https://xxx/v2/minzhi/nginx/manifests/1.0": x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by yf1147** [easzlab/kubeasz#1163]
k8s拉取harbor镜像问题，harbor是https的
操作步骤：
1.在宿主机docker login https://xxxx:443   success
2.cat ~/.docker/config.json | base64 -w 0
3.创建secret
4.在deployment引用 secret
最后 pod启动 报错：failed to do request: Head "https://xxx/v2/minzhi/nginx/manifests/1.0": x509: certificate signed by unknown authority

**Comment by HandsomeBoy01** [comment]
看一下系统时间是否正常，

**Comment by yf1147** [comment]
> 看一下系统时间是否正常，

时间都是一样的

**Comment by yf1147** [comment]
我装的是v1.24.2，看了介绍在1.24.x以后，k8s废弃了docker,仅支持 containerd,就算我在所有节点上都装了docker也没什么用

**Comment by fengyonghui** [comment]
请问这个是怎么解决的？我也遇到同样的问题：
宿主机可以docker login和docker pull；但是pod中无法拉取
failed to do request: Head "https://harbor-001.yh:5000/v2/library/docker-demo/manifests/0.0.1-SNAPSHOT": x509: certificate signed by unknown authority
