### ISSUE TITLE
安装报错TASK [deploy : prepare some dirs] ****************************************************************************************************************************************** fatal: [localhost]: FAILED! => {"msg": "'cluster_dir' is undefined"}

### ISSUE THREAD

**Issue by chencjcj** [easzlab/kubeasz#1164]
TASK [deploy : prepare some dirs] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "'cluster_dir' is undefined"}

**Comment by cloud-chl** [comment]
你需要先把example里面的host模板复制到/etc/ansible下面进行修改，然后通过ansible-playbook -i host 90.setup.yaml 就可以安装了

**Comment by gjmzj** [comment]
请按照安装文档
