### ISSUE TITLE
按住第二步etcd起不来了

### ISSUE THREAD

**Issue by EricCaoHZ** [easzlab/kubeasz#1169]
3.2.0版本，昨天安装时候
dk ezctl setup k8s-01 02
这一步etcd始终开不起来，之前都是正常的

fatal: [192.168.122.14]: FAILED! => {"attempts": 8, "changed": true, "cmd": "systemctl is-active etcd.service", "delta": "0:00:00.005814", "end": "2022-08-27 10:18:46.719430", "msg": "non-zero return code", "rc": 3, "start": "2022-08-27 10:18:46.713616", "stderr": "", "stderr_lines": [], "stdout": "activating", "stdout_lines": ["activating"]}

**Comment by Hello-Linux** [comment]
请把你的etcd日志贴出来，我们这边看一下
```
journalctl -u etcd.service
```

**Comment by York-N** [comment]
我也遇到同样的问题，ezctl setup k8s-01 02 起不来。详情如下：
-- Logs begin at Sun 2022-09-25 14:05:01 CST, end at Sat 2022-10-08 17:06:35 CST. --
Oct 04 19:14:19 etcd01 systemd[1]: Starting Etcd Server...
Oct 04 19:14:19 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:19.449+0800","caller":"etcdmain/etcd.go:73","msg":"Running: ","args":["/usr/local/bin/etcd","--name=etcd-10.0.0.4","--cert-file=/etc/kubernetes/ssl/etcd.pem","--key-file=/>
Oct 04 19:14:19 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:19.450+0800","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["https://10.0.0.4:2380"]}
Oct 04 19:14:19 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:19.451+0800","caller":"embed/etcd.go:479","msg":"starting with peer TLS","tls-info":"cert = /etc/kubernetes/ssl/etcd.pem, key = /etc/kubernetes/ssl/etcd-key.pem, client-ce>
Oct 04 19:14:19 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:19.451+0800","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:2379","https://10.0.0.4:2379"]}
Oct 04 19:14:19 etcd01 etcd[7911]: {"level":"warn","ts":"2022-10-04T19:14:19.451+0800","caller":"embed/etcd.go:607","msg":"scheme is HTTP while key and cert files are present; ignoring key and cert files","client-url":"http://127.0.0.1:2379"}
Oct 04 19:14:19 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:19.452+0800","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4","git-sha":"08407ff76","go-version":"go1.16.15","go-os":"linux","go-arch":">
Oct 04 19:14:19 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:19.460+0800","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/etcd/member/snap/db","took":"7.588075ms"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.472+0800","caller":"etcdserver/raft.go:448","msg":"starting local member","local-member-id":"78ea405b479ca574","cluster-id":"a26a8f1055c6df66"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.473+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"78ea405b479ca574 switched to configuration voters=()"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.473+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"78ea405b479ca574 became follower at term 0"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.473+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"newRaft 78ea405b479ca574 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.473+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"78ea405b479ca574 became follower at term 1"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.473+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"78ea405b479ca574 switched to configuration voters=(3674520308350852002)"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.473+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"78ea405b479ca574 switched to configuration voters=(3674520308350852002 6759233895833241290)"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.473+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"78ea405b479ca574 switched to configuration voters=(3674520308350852002 6759233895833241290 8712847>
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"warn","ts":"2022-10-04T19:14:21.476+0800","caller":"auth/store.go:1220","msg":"simple token is not cryptographically signed"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.478+0800","caller":"mvcc/kvstore.go:415","msg":"kvstore restored","current-rev":1}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.481+0800","caller":"etcdserver/quota.go:117","msg":"enabled backend quota","quota-name":"v3-applier","quota-size-bytes":8589934592,"quota-size":"8.6 GB"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.483+0800","caller":"rafthttp/peer.go:133","msg":"starting remote peer","remote-peer-id":"32fe84c083361ba2"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.483+0800","caller":"rafthttp/pipeline.go:72","msg":"started HTTP pipelining with remote peer","local-member-id":"78ea405b479ca574","remote-peer-id":"32fe84c083361ba2"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.485+0800","caller":"rafthttp/stream.go:169","msg":"started stream writer with remote peer","local-member-id":"78ea405b479ca574","remote-peer-id":"32fe84c083361ba2"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.485+0800","caller":"rafthttp/stream.go:169","msg":"started stream writer with remote peer","local-member-id":"78ea405b479ca574","remote-peer-id":"32fe84c083361ba2"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.486+0800","caller":"rafthttp/peer.go:137","msg":"started remote peer","remote-peer-id":"32fe84c083361ba2"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.486+0800","caller":"rafthttp/transport.go:317","msg":"added remote peer","local-member-id":"78ea405b479ca574","remote-peer-id":"32fe84c083361ba2","remote-peer-urls":["h>
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.486+0800","caller":"rafthttp/peer.go:133","msg":"starting remote peer","remote-peer-id":"5dcd9f6a92eb86ca"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.486+0800","caller":"rafthttp/pipeline.go:72","msg":"started HTTP pipelining with remote peer","local-member-id":"78ea405b479ca574","remote-peer-id":"5dcd9f6a92eb86ca"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.486+0800","caller":"rafthttp/stream.go:395","msg":"started stream reader with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"78ea405b479ca574",>
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.486+0800","caller":"rafthttp/stream.go:395","msg":"started stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"78ea405b479ca574","r>
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.490+0800","caller":"rafthttp/stream.go:169","msg":"started stream writer with remote peer","local-member-id":"78ea405b479ca574","remote-peer-id":"5dcd9f6a92eb86ca"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.490+0800","caller":"rafthttp/stream.go:169","msg":"started stream writer with remote peer","local-member-id":"78ea405b479ca574","remote-peer-id":"5dcd9f6a92eb86ca"}
Oct 04 19:14:21 etcd01 etcd[7911]: {"level":"info","ts":"2022-10-04T19:14:21.491+0800","caller":"rafthttp/peer.go:137","msg":"started remote peer","remote-peer-id":"5dcd9f6a92eb86ca"}

**Comment by Hello-Linux** [comment]
@York-N 我看您的日志截取不完整，请把完整的etcd日志发出来
