### ISSUE TITLE
kubectl 命令环境变量添加有问题

### ISSUE THREAD

**Issue by 786951355** [easzlab/kubeasz#1170]
[root@Centos7-Temp ~]# cat .bashrc 
# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
export PATH=/etc/kubeasz/bin/:$PATH  # generated by kubeasz:custom PATH
source <(kubectl completion bash) # generated by kubeasz

这里的PATH里面的/etc/kubeasz/bin目录是部署端二进制所在的目录，在其他节点上应该是配置中文件中自定义的安装目录吧，所以ssh到每个节点都是提示找不到命令，这里是不是推送错了。

**Comment by gjmzj** [comment]
已经修改
