### ISSUE TITLE
关于3.3.1版本安装k8s1.2.4集群第六步calico安装无法下载镜像的问题,发现本地5000端口无法访问

### ISSUE THREAD

**Issue by JusticeGL** [easzlab/kubeasz#1175]
![8f0fa783cd36aca9649768a4da3e19e](https://user-images.githubusercontent.com/26926664/191021674-7891c93b-c020-4a3a-b294-387e85d7221c.jpg)
查看了一下配置文件，发现配置文件中配置的镜像地址无法访问，不知道是不是该原因造成calico安装失败
![image](https://user-images.githubusercontent.com/26926664/191021938-09eb0b4d-9734-45d7-b02e-eb9a89885ccc.png)

**Comment by JusticeGL** [comment]
我现在排查到了，是registry没有部署成功，导致的，但是我在配置文件里面是配置的true，其他都没有动过
![image](https://user-images.githubusercontent.com/26926664/191041338-f2f0865e-193e-49be-ae8a-a002dd3fef86.png)

**Comment by gjmzj** [comment]
重新./ezdown -D 执行下，应该会启动registry，是不是机器上5000端口被占用了

**Comment by JusticeGL** [comment]
> 

我也发现了这个问题，registry是在下载的时候开启的，但是我离线的怎么办，我是拷到服务器上的

**Comment by JusticeGL** [comment]
已经解决了，在离线环境中重新执行ezdown -D，这样会重新在当前机器上部署registry
