### ISSUE TITLE
啥时候支持麒麟统信等国产操作系统？

### ISSUE THREAD

**Issue by chinaboy007** [easzlab/kubeasz#1177]
啥时候支持麒麟统信等国产操作系统？

**Comment by gjmzj** [comment]
正在支持arm64(aarc64)架构

麒麟统信等国产操作系统具体是哪个架构，方便 uname -m 看下吗？

**Comment by chinaboy007** [comment]
[root@ecs-6220 ~]# uname -r
4.19.90-17.5.ky10.aarch64
[root@ecs-6220 ~]# 
[root@ecs-6220 ~]# uname -m
aarch64

**Comment by HandsomeBoy01** [comment]
支持大佬，我们就是用的华为的麒麟

**Comment by gjmzj** [comment]
> [root@ecs-6220 ~]# uname -r 4.19.90-17.5.ky10.aarch64 [root@ecs-6220 ~]# [root@ecs-6220 ~]# uname -m aarch64

支持的，目前已经提交dev3分支，马上release新版本
