### ISSUE TITLE
Verification path error in step 2

### ISSUE THREAD

**Issue by zyz9740** [easzlab/kubeasz#1180]
In link https://github.com/easzlab/kubeasz/blob/master/docs/setup/02-install_etcd.md#%E9%AA%8C%E8%AF%81etcd%E9%9B%86%E7%BE%A4 in step 2, the path of etcd.pem and etcd-key.pem is `/etc/etcd/ssl/`. However,  the  default value of `ca_dir` in ./roles/etcd/tasks/main.yml:26 is` /etc/kubernetes/ssl` (Set in host by default),  leading to error `Error: open /etc/etcd/ssl/etcd.pem: no such file or directory`

You should update you script in order to prevent misunderstanding.

**Comment by zyz9740** [comment]
Similar isse https://github.com/easzlab/kubeasz/issues/1070. But I don't know why it is closed.

**Comment by gjmzj** [comment]
sorry for the inconveniences, the document is outdated. 
`/etc/kubernetes/ssl` is the right path.
it will be updated, thanks.

**Comment by zyz9740** [comment]
Thanks for your fast reply !
