### ISSUE TITLE
关于runc导致的OCI runtime create failed 导致OCI runtime error的问题

### ISSUE THREAD

**Issue by ssslkj123** [easzlab/kubeasz#1181]
1、3.4.1 版本的kubeasz对于CentOS7的支持并不好，安装过程当中容器无法进行启动，其中提示：`
  Warning  FailedCreatePodSandBox  36m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/k8s.io/a72b3e137a0eace13a0fddd1bc2c853098e7d39053e1d77f97099abb7ab0cb53/log.json: no such file or directory): runc did not terminate successfully: exit status 127: unknown
  Warning  FailedCreatePodSandBox  2m41s (x151 over 35m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/k8s.io/cf2bfa71b1502065e54122b68e4860a032cb4aec6372f7d57d6abeb782282c45/log.json: no such file or directory): runc did not terminate successfully: exit status 127: unknown” `

的报错。
2、原因由于containerd的版本 runc 的版本使用1.1.4导致的，该版本对于centos自带的libseccomp 版本并不支持，centos自带的libseccomp 版本为“libseccomp-devel-2.3.1-4.el7.x86_64” 与 “libseccomp-2.3.1-4.el7.x86_64”
其中：“libseccomp-2.3.1-4.el7.x86_64” 存在众多的依赖，
```
# runc --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d
spec: 1.0.2-dev
go: go1.18.7
libseccomp: 2.5.1
```

该问题可以通过下载el8 当中libseccomp-devel 进行绕过进行跑起来，是否能够稳定运行尚未测试。

```
#!/bin/bash
wget http://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/libseccomp-2.5.1-1.el8.x86_64.rpm
for i in `rpm -qa | grep libseccomp`;
do
 rpm -e $i --nodeps
done
rpm -ivh libseccomp-2.5.1-1.el8.x86_64.rpm
```

**Comment by gjmzj** [comment]
我找时间确认，并尝试用这个方法修复看看

**Comment by gjmzj** [comment]
已经解决，之前runc编译时候没有静态链接libseccomp；改用官方repo下载的二进制就好了，参考https://github.com/opencontainers/runc/releases/tag/v1.1.4

解决commit：
https://github.com/easzlab/dockerfile-kubeasz-ext-bin/commit/2e26c204144e45de5eb6cd1a54987c3c6088c3a2
