### ISSUE TITLE
3.1.1 支持的1.22 中 kube-controller-manager 启动参数缺少 --authorization-kubeconfig and --authentication-kubeconfig

### ISSUE THREAD

**Issue by jianhaiqing** [easzlab/kubeasz#1182]
预期： 在 kube-controller-manager 启动参数中添加 --authorization-kubeconfig and --authentication-kubeconfig；
原因：1.22 中 废弃了--port, 需要通过 --secure-port 去采集metrics， 但通过token request 拉取kube-controller-manager 需要 开启 --authorization-kubeconfig and --authentication-kubeconfig 这两个参数

In addtion, please be careful that:

- controller-manager MUST start with --authorization-kubeconfig and --authentication-kubeconfig correctly set to get authentication/authorization working.
- liveness/readiness probes to controller-manager MUST use HTTPS now, and the default port has been changed to 10257.
- Applications that fetch metrics from controller-manager should use a dedicated service account which is allowed to access nonResourceURLs /metrics. (https://github.com/kubernetes/kubernetes/pull/96216, [@knight42](https://github.com/knight42)) [SIG API Machinery, Cloud Provider, Instrumentation and Testing]

[CHANGELOG-1.22.md#deprecation](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#deprecation)

**Comment by gjmzj** [comment]
确实如此，可以参考master分支设置--authorization-kubeconfig and --authentication-kubeconfig；
后面有个commit解决的这个配置问题 356a98ed4832e76130d43446ee88164a379e4146
