### ISSUE TITLE
建议完善k8s集群证书到期之后如何更新教程

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#1183]
如果用户生产上对于安全有相关要求，证书只能一年一换，我看咱们md教程文档没有关于证书到期如何更新的详细介绍，有时间完善一下吧，遇到这个问题的人很多,可以在使用指南里面再加一个介绍
比如这个叫altas的用户反馈他的k8s集群证书已经到期了，但是不知道如何更新过期证书，于是重新运行了node role命令 "ezctl setup k8s 05"
后失败
![003](https://user-images.githubusercontent.com/17851645/200102398-518f6d79-13f9-4541-9590-5bbac29ab6df.png)
![004](https://user-images.githubusercontent.com/17851645/200102402-1a919564-fdf1-4aaa-a5d0-a9d8fd1035f1.png)

**Comment by gjmzj** [comment]
收到，我整理下
