### ISSUE TITLE
是时候完全脱离docker了

### ISSUE THREAD

**Issue by shing-lee** [easzlab/kubeasz#1185]
最新版本kubeasz，对docker的依赖已经非常少了，目前只有一个本地registry和kubeasz容器。
docker主要优势是方便单机调试、镜像打包。
containerd官方github已经有个相对成熟的替代项目了"nerdctl"。
containerd + buildkit + nerdctl 几乎能很好的替代掉docker，本人已亲测。

**Comment by gjmzj** [comment]
docker 单独使用起来也很方便，只是不作为kubelet的运行时；各取所需吧
