### ISSUE TITLE
安装时如何配置ssh端口

### ISSUE THREAD

**Issue by tomfat** [easzlab/kubeasz#1188]
如题，由于server的ssh端口非默认端口22，如何配置才能是安装脚本正常运行

**Comment by gjmzj** [comment]
初始安装时，修改ansible hosts文件，类似如下

```
# 'etcd' cluster should have odd member(s) (1,3,5,...)
[etcd]
192.168.1.1 ansible_ssh_port=10022
192.168.1.2 ansible_ssh_port=10022
192.168.1.3 ansible_ssh_port=10022
...
```

增加节点命令行：
假设待添加节点192.168.2.1，ssh 端口 10022；然后执行

$ ssh-copy-id -p 10022 192.168.2.1
$ ssh -p10022 192.168.2.1 ln -s /usr/bin/python3 /usr/bin/python
$ ezctl add-node test-k8s 192.168.2.1 ansible_ssh_port=10022

**Comment by myysophia** [comment]
@gjmzj   你好，请教一下： ansible hosts怎么给每个服务器配置不一样的密码？

**Comment by gjmzj** [comment]
> @gjmzj 你好，请教一下： ansible hosts怎么给每个服务器配置不一样的密码？

项目不配置密码的，事先用ssh-copy-id进行免密登陆；

一定要用的话，参考https://blog.csdn.net/qq_21012319/article/details/107404761

**Comment by jaffe-fly** [comment]
> 初始安装时，修改ansible hosts文件，类似如下
> 
> ```
> # 'etcd' cluster should have odd member(s) (1,3,5,...)
> [etcd]
> 192.168.1.1 ansible_ssh_port=10022
> 192.168.1.2 ansible_ssh_port=10022
> 192.168.1.3 ansible_ssh_port=10022
> ...
> ```
> 
> 增加节点命令行： 假设待添加节点192.168.2.1，ssh 端口 10022；然后执行
> 
> $ ssh-copy-id -p 10022 192.168.2.1 $ ssh -p10022 192.168.2.1 ln -s /usr/bin/python3 /usr/bin/python $ ezctl add-node test-k8s 192.168.2.1 ansible_ssh_port=10022

如果已经运行了 `docker exec -it kubeasz ezctl start-aio` 这个命令，就修改`/etc/kubeasz/clusters/default/hosts`中，然后运行`docker exec -it kubeasz ezctl setup default all`
