### ISSUE TITLE
failed to find plugin "calico" in path [/opt/cni/bin] 需要如何修复

### ISSUE THREAD

**Issue by one-two-my-gad** [easzlab/kubeasz#1194]
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "7bba3d120818c44ccf356f7771b357f9ccc1955997807abf62cc67df7a4286da": failed to find plugin "calico" in path [/opt/cni/bin]

**Comment by gjmzj** [comment]
默认项目安装时会放到/opt/kube/bin 目录，如果没有的话，手动cp下，从/opt/kube/bin/ 复制到 /opt/cni/bin

**Comment by one-two-my-gad** [comment]
哥们 你这有哪个版本是可以正常部署高可用集群的么？ 我现在遇到kubelet报错Error reaching apiserver: taking a long time to check apiserver
以及caclio 卡在init阶段反复重试 但无报错

**Comment by lixie021** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/90956796/209147252-bba2ef09-c996-4fc6-a56b-d94b0f4f75d8.png">
我的问题是这个images在开始传递参数不正确导致的，手动改为以上就可以了
