### ISSUE TITLE
kubelet.service.j2需要获取config.yml中DOCKER_STORAGE_DIR的配置来设置docker-root

### ISSUE THREAD

**Issue by kayhu** [easzlab/kubeasz#1198]
背景：
版本1.23.1，运行时docker

部署前修改了config.yml中的DOCKER_STORAGE_DIR，由默认/var/lib/docker改成了/data/docker（因为/var磁盘空间太小）。
一段时间之后集群的某个节点出现调度失败，发现磁盘被应用的docker镜像占满，google一番了解到K8S自带有镜像垃圾回收的机制，
但是实际并没有触发。
https://v1-24.docs.kubernetes.io/zh-cn/docs/concepts/architecture/garbage-collection/#containers-images

经过尝试发现问题出在config.yml的DOCKER_STORAGE_DIR修改为/data/docker后，虽然docker的/etc/docker/daemon.json生效了，但是kubelet.service.j2缺少相应的配置，导致kubelet无法正确检测到GC触发的阈值，手动在kubelet.service增加参数--docker-root=/data/docker，问题解决。

`
[root@dev-89 ~]# cat /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
WorkingDirectory=/var/lib/kubelet
ExecStart=/opt/kube/bin/kubelet \
  --config=/var/lib/kubelet/config.yaml \
  --cni-bin-dir=/opt/kube/bin \
  --cni-conf-dir=/etc/cni/net.d \
  --hostname-override=XX.XX.XX.XX \
  --image-pull-progress-deadline=5m \
  --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
  --network-plugin=cni \
  --pod-infra-container-image=easzlab/pause:3.6 \
  --root-dir=/var/lib/kubelet \
  --docker-root=/data/docker \
  --v=2
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
`

**Comment by gjmzj** [comment]
赞，建议使用docker运行时的，并且修改了默认目录的集群都要设置一下👍
