### ISSUE TITLE
Saving key "/root/.ssh/id_rsa" failed: Permission denied

### ISSUE THREAD

**Issue by ldpiuaeng** [easzlab/kubeasz#1200]
when i excuting the commond as the tutorial ,i got an error:
https://github.com/easzlab/kubeasz/blob/master/docs/setup/quickStart.md

docker exec -it kubeasz ezctl start-aio
2022-11-27 10:24:54 INFO get local host ipadd: 192.168.1.7
2022-11-27 10:24:54 DEBUG generate ssh key pair
Saving key "/root/.ssh/id_rsa" failed: Permission denied

**Comment by gjmzj** [comment]
使用root权限运行

**Comment by zcerhub** [comment]
@gjmzj how about to add  ping test in ansible-playbook?
