### ISSUE TITLE
ezctl setup k8s-01 06 安装flannel  提示FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (15 retries left).

### ISSUE THREAD

**Issue by mark-make** [easzlab/kubeasz#1201]
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).

TASK [flannel : 轮询等待flannel 运行，视下载镜像速度而定] **************************************************************************************
fatal: [10.211.55.18]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'flannel'|grep ' 10.211.55.18 '|awk '{print $3}'", "delta": "0:00:00.098973", "end": "2022-11-26 13:50:16.200180", "msg": "", "rc": 0, "start": "2022-11-26 13:50:16.101207", "stderr": "No resources found in kube-system namespace.", "stderr_lines": ["No resources found in kube-system namespace."], "stdout": "", "stdout_lines": []}
...ignoring

**Comment by gjmzj** [comment]
kubectl get pod -A
kubectl logs 
看看flannel为啥没有正常运行

**Comment by Changego** [comment]
从google下载了。

**Comment by yjianzhu** [comment]
同样问题

**Comment by fritz1149** [comment]
主要还是k8s.gcr.io/pause这个镜像的问题，可以尝试手动从别的地方下然后再手动tag，或者加clash之类的代理

**Comment by hom7** [comment]
同求？

**Comment by BigFCat** [comment]
@Changego  在 /etc/systemd/system/kubelet.service  添加 --pod-infra-container-image=easzlab.io.local:5000/easzlab/pause:3.9  再重启kubelet，systemctl daemon-reload && systemctl restart kubelet
