### ISSUE TITLE
kubeasz 容器里面可以新增一个 sshpass 吗？

### ISSUE THREAD

**Issue by itswl** [easzlab/kubeasz#1207]
方便容器里执行脚本

**Comment by gjmzj** [comment]
使用 sshpass 是不安全的，因为所有系统上的用户可以看到密码。因此，在生产环境，建议使用 [密钥登录](https://www.cnblogs.com/usmile/p/15039307.html#%E5%AF%86%E9%92%A5%E7%99%BB%E5%BD%95)。

**Comment by itswl** [comment]
服务器禁止 root 用户登录，但可以 使用 非 root 用户登录，然后 sudo 。测试时发现 ansible 需要 sshpass 才能支持 非 root 用户登录，然后使用 become_true 进行 sudo 操作

**Comment by recall704** [comment]
> 服务器禁止 root 用户登录，但可以 使用 非 root 用户登录，然后 sudo 。测试时发现 ansible 需要 sshpass 才能支持 非 root 用户登录，然后使用 become_true 进行 sudo 操作

```
FROM easzlab/kubeasz:3.6.2

RUN apk add -U sshpass
```

自己重新打个镜像就可以了
