### ISSUE TITLE
容器化运行kubeasz如何升级k8s

### ISSUE THREAD

**Issue by kavenmo** [easzlab/kubeasz#1208]
容器化运行kubeasz如何升级k8s？当前k8s版本是1.25.1，想升级到1.25.4，不知道如何升级，也不知道下载的二进制文件放在哪里。
官方文档说放在/etc/ansible/bin，可是容器化运行kubeasz，根本没有/etc/ansible/bin这个路径啊，到达新下载的安装文件，是放在宿主机，还是放到容器里，升级又是执行什么命令？

**Comment by gjmzj** [comment]
文档需要更新，二进制放在 /etc/kubeasz/bin 下面，下载k8s 1.25.4 替换掉里面kube*开头的二进制，执行 dk ezctl upgrade xxx即可

**Comment by kavenmo** [comment]
好的，我在测试环境验证一下，谢谢

**Comment by kavenmo** [comment]
好的，我在测试环境验证一下，谢谢

**Comment by kavenmo** [comment]
1.25.1，可以直接升级到1.26.0吧？
