### ISSUE TITLE
prepare : ansible 控制端写入命令别名

### ISSUE THREAD

**Issue by lixie021** [easzlab/kubeasz#1216]
报错如下:
fatal: [192.168.1.101]: FAILED! => {"msg": "The conditional check 'inventory_hostname == ansible_env.SSH_CLIENT.split(' ')[0]' failed. The error was: error while evaluating conditional (inventory_hostname == ansible_env.SSH_CLIENT.split(' ')[0]): 'dict object' has no attribute 'SSH_CLIENT'\n\nThe error appears to be in '/etc/kubeasz/roles/prepare/tasks/main.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: ansible 控制端写入命令别名\n  ^ here\n"}
fatal: [192.168.1.102]: FAILED! => {"msg": "The conditional check 'inventory_hostname == ansible_env.SSH_CLIENT.split(' ')[0]' failed. The error was: error while evaluating conditional (inventory_hostname == ansible_env.SSH_CLIENT.split(' ')[0]): 'dict object' has no attribute 'SSH_CLIENT'\n\nThe error appears to be in '/etc/kubeasz/roles/prepare/tasks/main.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: ansible 控制端写入命令别名\n  ^ here\n"}
fatal: [192.168.1.104]: FAILED! => {"msg": "The conditional check 'inventory_hostname == ansible_env.SSH_CLIENT.split(' ')[0]' failed. The error was: error while evaluating conditional (inventory_hostname == ansible_env.SSH_CLIENT.split(' ')[0]): 'dict object' has no attribute 'SSH_CLIENT'\n\nThe error appears to be in '/etc/kubeasz/roles/prepare/tasks/main.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: ansible 控制端写入命令别名\n  ^ here\n"}
fatal: [192.168.1.103]: FAILED! => {"msg": "The conditional check 'inventory_hostname == ansible_env.SSH_CLIENT.split(' ')[0]' failed. The error was: error while evaluating conditional (inventory_hostname == ansible_env.SSH_CLIENT.split(' ')[0]): 'dict object' has no attribute 'SSH_CLIENT'\n\nThe error appears to be in '/etc/kubeasz/roles/prepare/tasks/main.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: ansible 控制端写入命令别名\n  ^ here\n"}
这个是我的配置
<img width="628" alt="image" src="https://user-images.githubusercontent.com/90956796/208852091-b6817651-b2f2-43db-9931-a4b9ebecd329.png">

**Comment by itswl** [comment]
ansible的版本问题吗，还是用的不是 root用户？获取不到 ansible_env.SSH_CLIENT

**Comment by gjmzj** [comment]
如果只有这句问题，把它注释掉就好了

**Comment by lixie021** [comment]
找到原因了，这个版本的代码太新了，换成3.1.1好了。
