### ISSUE TITLE
添加master或node之后，缺少在节点上配置harbor(若已安装)的步骤

### ISSUE THREAD

**Issue by FeiYing9** [easzlab/kubeasz#1217]
如标题

**Comment by gjmzj** [comment]
17cacf50665c852a1a64f045ce6b279aaaac86a7

这个commit已经加上了containerd相关配置

**Comment by FeiYing9** [comment]
> [17cacf5](https://github.com/easzlab/kubeasz/commit/17cacf50665c852a1a64f045ce6b279aaaac86a7)
> 
> 这个commit已经加上了containerd相关配置

如果没有选择部署harbor，这段配置不知道有没有问题呀

另外，，开这个issue指的是这一大段配置呀，貌似在添加新的节点时加上
https://github.com/easzlab/kubeasz/blob/95fe5b94e3dca1e60ce9c9134a56267b3deefebb/playbooks/11.harbor.yml#L21-L105

**Comment by FeiYing9** [comment]
部署集群 -> 部署harbor -> 添加节点(master\node)

**Comment by gjmzj** [comment]
这个原来的方式做得比较复杂，其实就是允许拉取insecure registry 配置下就好；所以不管有没有部署harbor，在containerd中增加一个配置就好，没啥关系
