### ISSUE TITLE
kubeasz 3.5.0版本kubelet与cri有兼容性问题

### ISSUE THREAD

**Issue by bogeit** [easzlab/kubeasz#1219]
kubelet无法安装成功，查看报错发现  journalctl -u kubelet.service：
rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService

根据containerd官方issue显示，有两种解决方案：
https://github.com/containerd/containerd/issues/7799

k8s降级成1.25版本 
或者
containerd升级为 v1.6版本或以上，但我看安装的版本已经是containerd v1.6.8了

**Comment by gjmzj** [comment]
什么操作系统，还有没有其他信息？
我一般在ubuntu2204/2004版本调试的，没有问题

**Comment by gjmzj** [comment]
刚试过在ubuntu2204/2004中 3.5.0 版本都是一键安装，没有复现问题，不知道是否是因为你的系统之前装过其他k8s

**Comment by bogeit** [comment]
出问题时的系统为CentOS 7.9，因为想装cilium，内核升级到了5.4.228-1.el7.elrepo.x86_64，系统是虚拟机新安装的。

后面换到了kubeasz-3.4.2， k8s版本 v1.25.4，没有问题。
