### ISSUE TITLE
kubeasz3.5.0版本部署集群是nodename问题

### ISSUE THREAD

**Issue by lizhaoyangre** [easzlab/kubeasz#1220]
操作系统为ubuntu20.04，kubeasz版本为3.5.0，在部署集群的时候部署完成后nodename默认显示的是ip地址，有没有办法让其显示为主机的hostname，按照这个issue的方法试过了，https://github.com/easzlab/kubeasz/issues/418。按这个issue做后在部署完成后会显示
![image](https://user-images.githubusercontent.com/41179562/210160105-0b370506-d327-43f7-a89e-1095bf0a2fc9.png)
主机名设置的为
![image](https://user-images.githubusercontent.com/41179562/210160571-534ee91c-78d2-4e91-bff1-09dab3b1c266.png)

**Comment by gjmzj** [comment]
目前项目就是显示ip的，因为nodename有些会重复，ip不会重复，所以项目一直显示的是ip；没必要去改这么一个显示问题

**Comment by gjmzj** [comment]
v3.5 分支和master分支，已经支持自定义nodename；支持两个方式：

- 1. 在clusters/xxxx/hosts 直接配置：比如

```
# work node(s), set unique 'k8s_nodename' for each node
[kube_node]
192.168.0.80 k8s_nodename=worker_01
192.168.0.79 k8s_nodename=worker_02
```

- 2. 在添加节点适合设置：比如

```
dk ezctl add-node xxxx 192.168.0.81 k8s_nodename=worker_03
```

**Comment by lizhaoyangre** [comment]
感谢
