### ISSUE TITLE
All in one 安装失败，轮询等待kubelet启动

### ISSUE THREAD

**Issue by yjianzhu** [easzlab/kubeasz#1221]
`fatal: [myip]: FAILED! => {"attempts": 4, "changed": true, "cmd": "systemctl is-active kubelet.service", "delta": "0:00:00.006448", "end": "2023-01-03 22:46:42.578614", "msg": "non-zero return code", "rc": 3, "start": "2023-01-03 22:46:42.572166", "stderr": "", "stderr_lines": [], "stdout": "activating", "stdout_lines": ["activating"]}`

小白，这个报错是说系统启动kubelet服务报错是吗，怎么解决

**Comment by yjianzhu** [comment]
`Failed to construct kubelet dependencies: unable to load client CA file /etc/kubernetes/ssl/ca.pem: open/etc/kubernetes/ssl/ca.pem: no such file`

**Comment by yjianzhu** [comment]
kubelet.service 报错显示没有CA file, 但是我看这个文件是存在的.

**Comment by yjianzhu** [comment]
查看 kubelet.service 报错日志已解决

**Comment by gordes317** [comment]
请问是怎么解决的。

**Comment by Mia-Dan** [comment]
> 请问是怎么解决的。

同问, 表现一样, 您解决了吗
