### ISSUE TITLE
网络部署的疑问

### ISSUE THREAD

**Issue by matribots** [easzlab/kubeasz#1223]
有一个疑问想请教一下，在[05-安装kube_node节点](https://github.com/easzlab/kubeasz/blob/master/docs/setup/05-install_kube_node.md#05-%E5%AE%89%E8%A3%85kube_node%E8%8A%82%E7%82%B9)这篇文档里，有一步是[创建cni 基础网络插件配置文件](https://github.com/easzlab/kubeasz/blob/master/docs/setup/05-install_kube_node.md#%E5%88%9B%E5%BB%BAcni-%E5%9F%BA%E7%A1%80%E7%BD%91%E7%BB%9C%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)。请问这一步的意义是什么？因为最终是要通过Calico、Flannel这种第三方网络插件来为K8s集群进行组网，那为什么还要先为每个节点配置“cni基础网络插件配置”，最后再删除呢？换句话问，为什么不能跳过这步，直接执行Calico或Flannel等的部署步骤？🤔

**Comment by gjmzj** [comment]
因为如果不配置/etc/cni/net.d/10-default.conf，在安装role: kube-node时，node会处于 NotReady 状态；

```
~# kubectl get node
NAME           STATUS     ROLES    AGE     VERSION
192.168.0.2   NotReady   <none>   5m33s   v1.24.9
```

安装脚本不好判断NotReady 状态是因为没装网络插件，还是其他错误引起，或者多个错误引起；只有装了基础网络插件，让node处于 Ready 状态，那才能确保安装是成功；况且这样操作一下也很方便，下一步部署第三方网络插件是再删除它也很方便。

**Comment by matribots** [comment]
哦哦，这步的主要目的是在kubeasz项目中给脚本判断状态用的。最近我在基于kubeasz研究和反推纯手动二进制部署；那个人在“纯手动”部署时，如果能够保证之前的步骤都正确（也就是node NotReady的状态只是因为第三方网络插件没有安装引起的），那么是可以跳过“基础网络插件”的配置哈？

**Comment by gjmzj** [comment]
> 个人在“

是的

**Comment by matribots** [comment]
好的明白了，感谢！🙏
