### ISSUE TITLE
kubectl exec 操作提示x509: certificate is not valid for any names

### ISSUE THREAD

**Issue by surel9** [easzlab/kubeasz#1225]
Kubeasz Version：3.3.3
Kubernetes Version：1.24.10
ContainerRuntime：containerd 1.6.14
OS To Ubuntu: 20.04.5

kubeasz节点执行kubectl exec进入容器内部操作提示【Error from server: error dialing backend: x509: certificate is not valid for any names, but wanted to match worker-02】

**Comment by gjmzj** [comment]
> 

安装步骤有没有其他特别的地方，怎么安装的过程，或者复现的过程贴一下

**Comment by gjmzj** [comment]
> Kubeasz Version：3.4.4 Kubernetes Version：1.25.6 ContainerRuntime：containerd 1.6.14 OS To Centos: 7.9 kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead. Error from server: error dialing backend: x509: certificate is not valid for any names, but wanted to match worker-01


安装步骤有没有其他特别的地方，怎么安装的过程，或者复现的过程贴一下

**Comment by wangxian776** [comment]
> Kubeasz Version：3.4.4 Kubernetes Version：1.25.6 ContainerRuntime：containerd 1.6.14 OS To Centos: 7.9 kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead. Error from server: error dialing backend: x509: certificate is not valid for any names, but wanted to match worker-01

我遇到同样的问题，版本信息如下：
Kubeasz Version：3.5.1
Kubernetes Version：1.26.1
ContainerRuntime：containerd 1.6.14
OS Ubuntu: 20.04

我尝试修改了node节点的kubelet证书签发文件
`root@master-01:~# cat /etc/kubeasz/roles/kube-node/templates/kubelet-csr.json.j2
{
  "CN": "system:node:{{ K8S_NODENAME }}",
  "hosts": [
    "127.0.0.1",
    "{{ inventory_hostname }}"i,
    "{{ K8S_NODENAME }}"
  ],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "CN",
      "ST": "HangZhou",
      "L": "XS",
      "O": "system:nodes",
      "OU": "System"
    }
  ]
}
`
然后清理之前的证书，重现部署环境，现在kubectl exec可以进入Pod了，希望对你有所帮助

**Comment by gjmzj** [comment]
> Kubeasz Version：3.4.4 Kubernetes Version：1.25.6 ContainerRuntime：containerd 1.6.14 OS To Centos: 7.9 kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead. Error from server: error dialing backend: x509: certificate is not valid for any names, but wanted to match worker-01

怎么复现，操作过程贴一下

**Comment by gjmzj** [comment]
> > Kubeasz Version：3.4.4 Kubernetes Version：1.25.6 ContainerRuntime：containerd 1.6.14 OS To Centos: 7.9 kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead. Error from server: error dialing backend: x509: certificate is not valid for any names, but wanted to match worker-01
> 
> 我遇到同样的问题，版本信息如下： Kubeasz Version：3.5.1 Kubernetes Version：1.26.1 ContainerRuntime：containerd 1.6.14 OS Ubuntu: 20.04
> 
> 我尝试修改了node节点的kubelet证书签发文件
> 
> ```
> root@master-01:~# cat /etc/kubeasz/roles/kube-node/templates/kubelet-csr.json.j2
> {
>   "CN": "system:node:{{ K8S_NODENAME }}",
>   "hosts": [
>     "127.0.0.1",
>     "{{ inventory_hostname }}",
>     "{{ K8S_NODENAME }}"
>   ],
>   "key": {
>     "algo": "rsa",
>     "size": 2048
>   },
>   "names": [
>     {
>       "C": "CN",
>       "ST": "HangZhou",
>       "L": "XS",
>       "O": "system:nodes",
>       "OU": "System"
>     }
>   ]
> }
> ```
> 
> 然后清理之前的证书，重新部署环境，现在kubectl exec可以进入Pod了，希望对你有所帮助

复现过程能贴一下吗？我自己环境一直无法复现啊

**Comment by wangxian776** [comment]
> > > Kubeasz Version：3.4.4 Kubernetes Version：1.25.6 ContainerRuntime：containerd 1.6.14 OS To Centos: 7.9 kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead. Error from server: error dialing backend: x509: certificate is not valid for any names, but wanted to match worker-01
> > 
> > 
> > 我遇到同样的问题，版本信息如下： Kubeasz Version：3.5.1 Kubernetes Version：1.26.1 ContainerRuntime：containerd 1.6.14 OS Ubuntu: 20.04
> > 我尝试修改了node节点的kubelet证书签发文件
> > ```
> > root@master-01:~# cat /etc/kubeasz/roles/kube-node/templates/kubelet-csr.json.j2
> > {
> >   "CN": "system:node:{{ K8S_NODENAME }}",
> >   "hosts": [
> >     "127.0.0.1",
> >     "{{ inventory_hostname }}",
> >     "{{ K8S_NODENAME }}"
> >   ],
> >   "key": {
> >     "algo": "rsa",
> >     "size": 2048
> >   },
> >   "names": [
> >     {
> >       "C": "CN",
> >       "ST": "HangZhou",
> >       "L": "XS",
> >       "O": "system:nodes",
> >       "OU": "System"
> >     }
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后清理之前的证书，重新部署环境，现在kubectl exec可以进入Pod了，希望对你有所帮助
> 
> 复现过程能贴一下吗？我自己环境一直无法复现啊

我就是按照正常的步骤去安装的，我贴一下安装步骤和hosts文件、config.yml文件，你看下
```
 ./ezctl setup cluster-1 01
 ./ezctl setup cluster-1 02
 ./ezctl setup cluster-1 03
 ./ezctl setup cluster-1 04
 ./ezctl setup cluster-1 04
 ./ezctl setup cluster-1 05
 ./ezctl setup cluster-1 06
 ./ezctl setup cluster-1 07

kubectl run client-pod --image=ubuntu:20.04 --command -- sleep 3600
kubectl exec -it pods/client-pod -- bash
```
[config-file.zip](https://github.com/easzlab/kubeasz/files/10637114/config-file.zip)

**Comment by gjmzj** [comment]
谢谢，我自己也复现问题了，临时解决方案需要两步：1是增加/etc/hosts解析，2是修改node节点的kubelet证书签发文件

root@master-01:~# cat /etc/kubeasz/roles/kube-node/templates/kubelet-csr.json.j2
{
  "CN": "system:node:{{ K8S_NODENAME }}",
  "hosts": [
    "127.0.0.1",
    "{{ inventory_hostname }}",
    "{{ K8S_NODENAME }}"
  ],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "CN",
      "ST": "HangZhou",
      "L": "XS",
      "O": "system:nodes",
      "OU": "System"
    }
  ]
}

我尽快发布修复版本

**Comment by gjmzj** [comment]
修复 @ a5b012e690935f58b2711a

**Comment by wxh512** [comment]
Kubeasz Version：3.5.2
Kubernetes Version：1.26.1
ContainerRuntime：containerd 1.6.14
OS To Centos: 7.9
--
-- The start-up result is done.
Feb 08 19:01:25 master-01 sshd[7153]: pam_unix(sshd:session): session opened for user root by (uid=0)
Feb 08 19:01:28 master-01 kube-apiserver[7146]: W0208 19:01:28.678558    7146 logging.go:59] [core] [Channel #3 SubChannel #5] grpc: addrConn.createTransport failed to connect to {
Feb 08 19:01:28 master-01 kube-apiserver[7146]: "Addr": "192.168.176.130:2379",
Feb 08 19:01:28 master-01 kube-apiserver[7146]: "ServerName": "192.168.176.130",
Feb 08 19:01:28 master-01 kube-apiserver[7146]: "Attributes": null,
Feb 08 19:01:28 master-01 kube-apiserver[7146]: "BalancerAttributes": null,
Feb 08 19:01:28 master-01 kube-apiserver[7146]: "Type": 0,
Feb 08 19:01:28 master-01 kube-apiserver[7146]: "Metadata": null
Feb 08 19:01:28 master-01 kube-apiserver[7146]: }. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time
Feb 08 19:01:28 master-01 etcd[3608]: {"level":"warn","ts":"2023-02-08T19:01:28.678+0800","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"192.168.176.130:5
Feb 08 19:01:29 master-01 kube-apiserver[7146]: W0208 19:01:29.059553    7146 logging.go:59] [core] [Channel #4 SubChannel #6] grpc: addrConn.createTransport failed to connect to {
Feb 08 19:01:29 master-01 kube-apiserver[7146]: "Addr": "192.168.176.130:2379",
Feb 08 19:01:29 master-01 kube-apiserver[7146]: "ServerName": "192.168.176.130",
Feb 08 19:01:29 master-01 kube-apiserver[7146]: "Attributes": null,
Feb 08 19:01:29 master-01 kube-apiserver[7146]: "BalancerAttributes": null,
Feb 08 19:01:29 master-01 kube-apiserver[7146]: "Type": 0,
Feb 08 19:01:29 master-01 kube-apiserver[7146]: "Metadata": null
Feb 08 19:01:29 master-01 kube-apiserver[7146]: }. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time
Feb 08 19:01:29 master-01 etcd[3608]: {"level":"warn","ts":"2023-02-08T19:01:29.059+0800","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"192.168.176.130:5
Feb 08 19:01:30 master-01 etcd[3608]: {"level":"warn","ts":"2023-02-08T19:01:30.163+0800","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"192.168.176.130:5
Feb 08 19:01:30 master-01 kube-apiserver[7146]: W0208 19:01:30.163907    7146 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
Feb 08 19:01:30 master-01 kube-apiserver[7146]: "Addr": "192.168.176.130:2379",
Feb 08 19:01:30 master-01 kube-apiserver[7146]: "ServerName": "192.168.176.130",
Feb 08 19:01:30 master-01 kube-apiserver[7146]: "Attributes": null,
Feb 08 19:01:30 master-01 kube-apiserver[7146]: "BalancerAttributes": null,
Feb 08 19:01:30 master-01 kube-apiserver[7146]: "Type": 0,
Feb 08 19:01:30 master-01 kube-apiserver[7146]: "Metadata": null
Feb 08 19:01:30 master-01 kube-apiserver[7146]: }. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time
Feb 08 19:01:32 master-01 kube-apiserver[7146]: E0208 19:01:32.983306    7146 run.go:74] "command failed" err="context deadline exceeded"
Feb 08 19:01:32 master-01 systemd[1]: kube-apiserver.service: main process exited, code=exited, status=1/FAILURE
Feb 08 19:01:33 master-01 systemd[1]: Failed to start Kubernetes API Server.
-- Subject: Unit kube-apiserver.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kube-apiserver.service has failed.
--
-- The result is failed.
Feb 08 19:01:33 master-01 systemd[1]: Unit kube-apiserver.service entered failed state.
Feb 08 19:01:33 master-01 systemd[1]: kube-apiserver.service failed.


安装master出现的问题

**Comment by wxh512** [comment]
> 已修复 [a5b012e](https://github.com/easzlab/kubeasz/commit/a5b012e690935f58b2711aea0defa8f7159e8b42)

帮忙看看这个问题3.5.2的版本安装master出的问题

**Comment by gjmzj** [comment]
> Feb 08 19:01:30 master-01 kube-apiserver[7146]: }. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time

@wxh512 已经提示你问题了，这个估计是因为节点之间时间不同步
