### ISSUE TITLE
nodeport无法访问

### ISSUE THREAD

**Issue by lexue100** [easzlab/kubeasz#1227]
ezctl setup k8s-01 07后，prometheus、grafana、altermanager的nodeport访问正常，但是执行 helm uninstall prometheus后，在执行：ezctl setup k8s-01 07 后，所以的pods、deployment、service 都运行正常，但外部无法通过nodeport访问
![image](https://user-images.githubusercontent.com/20296880/216820563-8c05023c-506d-456f-9a35-aeae46cf745d.png)

**Comment by lexue100** [comment]
kubeasz版本：3.3.1

**Comment by gjmzj** [comment]
网络端口问题，你可以部署网络测试插件：
https://github.com/easzlab/kubeasz/blob/master/docs/setup/network-plugin/network-check.md
