### ISSUE TITLE
./ezdown -D 报错：Job for docker .service failed because the control process exited with error code. se "systenctl status docer servce" and "jurmnalctl .e" for details.2023-02-06 04:57:35 ERROR Action failed: download_all

### ISSUE THREAD

**Issue by snailComing** [easzlab/kubeasz#1228]
# 国内环境
./ezdown -D 报错：
Job for docker .service failed because the control process exited with error code. se "systenctl status docer servce" and "jurmnalctl .e" for details.2023-02-06 04:57:35 ERROR Action failed: download_all

Ubuntu 16.04 server
DOCKER 20.10.1

**Comment by gjmzj** [comment]
docker 启动失败了，已经提示你了，使用systemctl status docker 或者 journalctl -u docker 看看错误信息
