### ISSUE TITLE
nc在debian系统下安装kubease后，端口会到处跳转

### ISSUE THREAD

**Issue by RuifMaxx** [easzlab/kubeasz#1231]
在debian系统下安装完k8s后，起一个22222的端口，会跳转到35383
![image](https://user-images.githubusercontent.com/75245181/218115889-633c73b6-dd4e-4032-bca3-fe8d97498757.png)
![image](https://user-images.githubusercontent.com/75245181/218116025-8e15c64b-1194-4df3-9cb2-e2c36eccc93e.png)

希望在debian系统下安装完成后，端口正常

**Comment by gjmzj** [comment]
😂 没遇到过，太奇怪了

**Comment by RuifMaxx** [comment]
kubectl version 1.26.0
Debian版本10.0

**Comment by RuifMaxx** [comment]
![Snipaste_2023-02-10_16-10-54](https://user-images.githubusercontent.com/75245181/218241835-c0d7d49a-17dd-4350-8e4c-153856e0dc30.png)

**Comment by gjmzj** [comment]
我也在debian服务器上复现了

**Comment by RuifMaxx** [comment]
请问大佬是在Debian服务器上复现了这个BUG了吗

**Comment by gjmzj** [comment]
是复现了，暂时没时间去排查

**Comment by RuifMaxx** [comment]
好的好的
