### ISSUE TITLE
Rockey安装时创建ETCD证书请求出错

### ISSUE THREAD

**Issue by y1li0** [easzlab/kubeasz#1232]
linux: Rockey 8.7 x86_64 minimal
kubeasz: 3.5.2

109.199 deploy
109.200 master
109.201 node1
109.202 node2

报错
![image](https://user-images.githubusercontent.com/30489944/218515612-24944332-7ece-4998-ace1-6a3dae36596e.png)
无etcd-csr.json
![image](https://user-images.githubusercontent.com/30489944/218515755-073776ac-32ff-4965-9ef2-88825fde9bde.png)

**Comment by y1li0** [comment]
只修改了节点配置
![image](https://user-images.githubusercontent.com/30489944/218517213-cb42e7fc-7389-4101-82dd-4ce149872828.png)
执行了
docker exec -it kubeasz ezctl new k8s-01
docker exec -it kubeasz ezctl setup k8s-01 all

**Comment by gjmzj** [comment]
确保部署机器上有 /usr/bin/python 可执行文件就行；

看你的输出日志，应该是再执行一遍就能成功；

**Comment by y1li0** [comment]
thx
