### ISSUE TITLE
3.5.2安装k8s1.26失败，关于 containerd 版本问题

### ISSUE THREAD

**Issue by Erchoc** [easzlab/kubeasz#1234]
CentOS Linux release 8.5.2111
centos 4.18.0-348.7.1.el8_5.x86_64
containerd github.com/containerd/containerd v1.6.13 78f51771157abb6c9ed224c22013cdf09962315d

```
[run.go:74] "command failed" err="failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

了解了一下 v1.26 要求 containerd 版本至少 v1.6，但我这版本已经更新了，systemd 也重启了，重新执行安装还是一直报错 kubelet 启动失败

**Comment by Erchoc** [comment]
all-in-one 版本

**Comment by gjmzj** [comment]
CentOS Linux release 8.5.2111 这个版本，阿里云ecs部署allinone我试了能成功；你有做其他配置吗

**Comment by Erchoc** [comment]
我是腾讯云这个配置，不是初始化的机器，已使用过一段时间。

all-in-one 有限制最低配置么？

**Comment by Erchoc** [comment]
重装系统切换到 centos9 初始化后可以正常使用
