### ISSUE TITLE
支持rocky linux 9吗？

### ISSUE THREAD

**Issue by younglicode** [easzlab/kubeasz#1239]

**Comment by gjmzj** [comment]
没有适配过，可以安装试试；只要有systemd 应该问题不大

**Comment by younglicode** [comment]
报错了。the connection to the server x.x.x.x:6443 was refused - did you specify the right host or port。但是我看apiserver状态正常的。

**Comment by ztdawang** [comment]
赶紧支持吧，9是大势所驱

**Comment by dylanyht** [comment]
后期会做适配吗？打算切换到rocky linux9试试呢

**Comment by ztdawang** [comment]
rocky linux9 没有almalinux 9好
