### ISSUE TITLE
python3找不到？？？？每一个节点我都看了，都有/usr/bin/python3,这是什么问题？

### ISSUE THREAD

**Issue by baozitao** [easzlab/kubeasz#1240]
ASK [kube-node : 准备kubelet 证书签名请求] ***********************************************************************************
fatal: [192.168.8.101]: FAILED! => {"msg": "Failed to get information on remote file (/etc/kubeasz/clusters/cluster/ssl/worker-01-kubelet-csr.json): /bin/sh: /usr/bin/python3: not found\n"}
fatal: [192.168.8.102]: FAILED! => {"msg": "Failed to get information on remote file (/etc/kubeasz/clusters/cluster/ssl/worker-02-kubelet-csr.json): /bin/sh: /usr/bin/python3: not found\n"}
fatal: [192.168.8.103]: FAILED! => {"msg": "Failed to get information on remote file (/etc/kubeasz/clusters/cluster/ssl/worker-03-kubelet-csr.json): /bin/sh: /usr/bin/python3: not found\n"}
fatal: [192.168.8.104]: FAILED! => {"msg": "Failed to get information on remote file (/etc/kubeasz/clusters/cluster/ssl/worker-04-kubelet-csr.json): /bin/sh: /usr/bin/python3: not found\n"}

**Comment by gjmzj** [comment]
其他信息？os版本？
