### ISSUE TITLE
使用的树莓派安装集群，ubuntu系统，没有 dummy内核模块，导致 node-local-dns报错

### ISSUE THREAD

**Issue by baozitao** [easzlab/kubeasz#1241]
使用的树莓派安装集群，ubuntu系统，没有 dummy内核模块报错

root@rasp5:/etc/kubeasz/clusters/default# kubectl get pod -A
NAMESPACE     NAME                                         READY   STATUS             RESTARTS        AGE
kube-system   calico-kube-controllers-7bbb6b796b-brqg8     1/1     Running            0               15m
kube-system   calico-node-d58pb                            0/1     PodInitializing    0               66s
kube-system   calico-node-zxpnc                            1/1     Running            0               15m
kube-system   coredns-6665999d97-j2mt2                     1/1     Running            0               14m
kube-system   dashboard-metrics-scraper-57566685b4-jf4ff   1/1     Running            0               14m
kube-system   kubernetes-dashboard-57db9bfd5b-ws6d7        1/1     Running            0               14m
kube-system   metrics-server-6bd9f986fc-9kb48              1/1     Running            0               14m
**kube-system   node-local-dns-77bn2                         0/1     Error              2 (28s ago)     66s**

node-local-dns错误，logs提示：
2023/03/06 14:55:21 [ERROR] Failed to add non-existent interface nodelocaldns: operation not supported
2023/03/06 14:55:21 [INFO] Added interface - nodelocaldns
2023/03/06 14:55:21 [ERROR] Error checking dummy device nodelocaldns - operation not supported
listen tcp 169.254.20.10:8080: bind: cannot assign requested address

也就是没有dummy模块，
查看 内核 lsmod | grep dummy为空，

这个local dns 可以禁用么？树莓派的系统没有 dummy模块

**Comment by gjmzj** [comment]
安装前，修改example/config.yml

```
ENABLE_LOCAL_DNS_CACHE: true
```
修改为false 即可
