### ISSUE TITLE
node没有ready,很奇怪，之前的步骤没有任何报错

### ISSUE THREAD

**Issue by baozitao** [easzlab/kubeasz#1244]
TASK [kube-node : 开启kube-proxy 服务] *********************************************************************************************************************************
changed: [192.168.0.101]

TASK [kube-node : 设置k8s_nodename 在/etc/hosts 地址解析] *****************************************************************************************************************
changed: [192.168.0.101 -> 192.168.0.101] => (item=192.168.0.101)

TASK [kube-node : 轮询等待kube-proxy启动] ********************************************************************************************************************************
changed: [192.168.0.101]

TASK [kube-node : 轮询等待kubelet启动] ***********************************************************************************************************************************
changed: [192.168.0.101]
FAILED - RETRYING: 轮询等待node达到Ready状态 (8 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (7 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (6 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (5 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (4 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (3 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (2 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (1 retries left).

TASK [kube-node : 轮询等待node达到Ready状态] *******************************************************************************************************************************
fatal: [192.168.0.101]: FAILED! => {"attempts": 8, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get node master-01|awk 'NR>1{print $2}'", "delta": "0:00:00.214314", "end": "2023-03-15 15:30:23.050373", "msg": "", "rc": 0, "start": "2023-03-15 15:30:22.836059", "stderr": "", "stderr_lines": [], "stdout": "NotReady", "stdout_lines": ["NotReady"]}

**Comment by baozitao** [comment]
TASK [calico : 轮询等待calico-node 运行] ******************************************************************************************************************************************************************************
changed: [192.168.0.101]
changed: [192.168.0.102]
FAILED - RETRYING: 轮询等待calico-node 运行 (12 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (11 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (10 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (9 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (8 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (7 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (6 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (5 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (4 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (3 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (2 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (1 retries left).
fatal: [192.168.0.188]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' worker-02 '|awk '{print $3}'", "delta": "0:00:00.334948", "end": "2023-03-16 02:40:32.751120", "msg": "", "rc": 0, "start": "2023-03-16 02:40:32.416172", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}

**Comment by jmgao1983** [comment]
node没有ready就看kubelet的日志就行，在问题节点上查看：

journalctl -u kubelet -f

**Comment by fuckyourname** [comment]
我执行命令journalctl -u kubelet -f，看了日志，这是什么意思？
Mar 23 19:07:37 node1 kubelet[6326]: E0323 19:07:37.531643    6326 kubelet.go:2855] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Mar 23 19:07:42 node1 kubelet[6326]: E0323 19:07:42.534062    6326 kubelet.go:2855] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Mar 23 19:07:43 node1 kubelet[6326]: E0323 19:07:43.889785    6326 controller.go:193] "Failed to update lease" err="Operation cannot be fulfilled on leases.coordination.k8s.io \"192.168.0.185\": the object has been modified; please apply your changes to the latest version and try again"
Mar 23 19:07:43 node1 kubelet[6326]: E0323 19:07:43.899209    6326 controller.go:193] "Failed to update lease" err="Operation cannot be fulfilled on leases.coordination.k8s.io \"192.168.0.185\": the object has been modified; please apply your changes to the latest version and try again"

**Comment by freshgeek** [comment]
> 同样，我用的3.6.2装的1.28.1版本的k8s，./ezctl setup k8s-cluster1 05 ，第五步报错了，我执行命令journalctl -u kubelet -f，看了日志，这是什么意思？ Mar 23 19:07:37 node1 kubelet[6326]: E0323 19:07:37.531643 6326 kubelet.go:2855] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized" Mar 23 19:07:42 node1 kubelet[6326]: E0323 19:07:42.534062 6326 kubelet.go:2855] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized" Mar 23 19:07:43 node1 kubelet[6326]: E0323 19:07:43.889785 6326 controller.go:193] "Failed to update lease" err="Operation cannot be fulfilled on leases.coordination.k8s.io "192.168.0.185": the object has been modified; please apply your changes to the latest version and try again" Mar 23 19:07:43 node1 kubelet[6326]: E0323 19:07:43.899209 6326 controller.go:193] "Failed to update lease" err="Operation cannot be fulfilled on leases.coordination.k8s.io "192.168.0.185": the object has been modified; please apply your changes to the latest version and try again"

同样的错误信息 ： 6月 11 18:12:57 node-153.esxi kubelet[4873]: E0611 18:12:57.147833    4873 kubelet.go:2855] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
