### ISSUE TITLE
老师们好，我想问一下，00.master高可用 架构图中的external-lb的作用

### ISSUE THREAD

**Issue by JusticeGL** [easzlab/kubeasz#1246]
我现在使用kubeasz部署了3master，3etcd，3node，有两个问题：1.目前想加入haproxy来做负载均衡，不知道修改配置文件后重新执行哪个过程可以实现，2.使用kubeasz部署的external-lb是在node和master之间的吗，我看架构图上高可用是用kube-lb实现的，这种架构在一台master宕机的情况下还能够实现高可用吗
<img width="522" alt="image" src="https://user-images.githubusercontent.com/26926664/226111218-58eb66f9-ab95-46f4-876c-05dcaa2fb22b.png">

**Comment by jmgao1983** [comment]
external-lb是可选的；在集群内的组件高可用已经用kube-lb实现；如果集群外部访问apiserver想高可用，可以使用external-lb
1.不需要haproxy也能做负载均衡，之前项目1.0架构也是用haproxy+keepalived的；
2.用kube-lb，一台master宕机当然可以高可用

**Comment by JusticeGL** [comment]
谢谢大佬，我明白了

**Comment by JusticeGL** [comment]
> external-lb是可选的；在集群内的组件高可用已经用kube-lb实现；如果集群外部访问apiserver想高可用，可以使用external-lb 1.不需要haproxy也能做负载均衡，之前项目1.0架构也是用haproxy+keepalived的； 2.用kube-lb，一台master宕机当然可以高可用

谢谢大佬，我明白了
