### ISSUE TITLE
安装master节点时，kube-proxy无法启动

### ISSUE THREAD

**Issue by wiluen** [easzlab/kubeasz#1251]
kube-proxy无法启动，状态一直是activating

**Comment by gjmzj** [comment]
看下日志，journalctl -u kube-proxy
另外需要os信息，k8s版本号，kubeasz版本号等

**Comment by wiluen** [comment]
command failed" err="can't use the IPVS proxier: error getting ipset version, error: executable file not found
Ubuntu 18.04.3 LTS       K8S 1.26      kubeasz3.5
