### ISSUE TITLE
redhat8.6 最小化安装 自动安装报错 /usr/libexec/platform-python :not found

### ISSUE THREAD

**Issue by daywan** [easzlab/kubeasz#1256]
![9cff6599a13f150801de0da1d31b215](https://user-images.githubusercontent.com/100251772/230757517-c845a3de-b6cd-47ed-8cf7-ad66320b80c9.png)

**Comment by daywan** [comment]
kubeasz version 3.5.2

**Comment by gjmzj** [comment]
重新执行一遍就好了；详见 /etc/kubeasz/roles/prepare/tasks/main.yml
```
# 某些系统没有/usr/bin/python，需要配置一个软链接，否则connection: local的任务会失败
# 如果仍旧出现任务失败，重新执行一遍即可 https://github.com/ansible/ansible/issues/64903
- name: symlink /usr/bin/python -> /usr/bin/python3
  raw: |
    if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
      ln --symbolic /usr/bin/python3 /usr/bin/python;
    fi

```

**Comment by thousmile** [comment]
@gjmzj 我使用的 Rocky Linux release 8.7 。也配置了 Python 和 pip 软连接，还是 /usr/libexec/platform-python :not found 。
Python 版本 3.9.13
https://github.com/ansible/ansible/issues/64903 这个有点看不太懂他的操作。能不能给个操作步骤。（实在不太会Python）
