### ISSUE TITLE
 unable to load bootstrap kubeconfig

### ISSUE THREAD

**Issue by JiangtaoZhao** [easzlab/kubeasz#1257]
kubaszVer: 3.5.2 ；
k8sVer:1.26.1；
启动master节点的时候kubelet无法正常启动：
查看journalctl -xeu  kubelet.service：

Apr 16 12:04:10 k8sMaster kubelet[7769]: I0416 12:04:10.793877 7769 server.go:415] "Kubelet version" kubeletVersion="v1.27.0"
Apr 16 12:04:10 k8sMaster kubelet[7769]: I0416 12:04:10.793982 7769 server.go:417] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Apr 16 12:04:10 k8sMaster kubelet[7769]: E0416 12:04:10.794442 7769 run.go:74] "command failed" err="failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory"
Apr 16 12:04:10 k8sMaster systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE

网上已有的解决方案都是已经部署好的k8s集群证书过期更新；目前部署阶段需要怎么处理？谢谢

**Comment by JiangtaoZhao** [comment]
Apr 16 12:04:10 k8sMaster kubelet[7769]: I0416 12:04:10.793877    7769 server.go:415] "Kubelet version" kubeletVersion="v1.27.0"
Apr 16 12:04:10 k8sMaster kubelet[7769]: I0416 12:04:10.793982    7769 server.go:417] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Apr 16 12:04:10 k8sMaster kubelet[7769]: E0416 12:04:10.794442    7769 run.go:74] "command failed" err="failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory"
Apr 16 12:04:10 k8sMaster systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE

ps: k8sVer:1.26.1

**Comment by gjmzj** [comment]
v1.27.0 还没适配，稍等！最近应该会抽时间更新的；kubeasz 集群其实不需要bootstrap-kubelet

**Comment by jjj960** [comment]
我使用3.6.5版本安装k8s 1.28.1集群，也出现这个错误了，是什么情况呢。

**Comment by yangjijian2121** [comment]
> 我使用3.6.5版本安装k8s 1.28.1集群，也出现这个错误了，是什么情况呢。

我这边是因为节点之前装过K8S导致的
