### ISSUE TITLE
怎么使多个集群用同一个证书

### ISSUE THREAD

**Issue by 13567436138** [easzlab/kubeasz#1260]
怎么使多个集群用同一个证书

**Comment by gjmzj** [comment]
可以把旧集群 /etc/kubeasz/clusters/xxxx/ssl 目录下内容，复制到新集群/etc/kubeasz/clusters/yyyy/ssl 

然后开始安装新集群，这样两个集群会使用同一套ca证书

**Comment by 13567436138** [comment]
如果集群已经部署了，能拷贝一个集群的/etc/kubernetes/ssl目录到另一个集群来实现么，但是已经产生的比如token用的ca会自动重新生成么
