### ISSUE TITLE
强烈要求支持Almalinux 9.1

### ISSUE THREAD

**Issue by ztdawang** [easzlab/kubeasz#1262]
RHEL 9系列是很优秀的系统，强烈要求支持这个版本。7弱爆了

**Comment by gjmzj** [comment]
不妨自己动手试下，应该简单改造一下就能支持；手头上没有Almalinux测试环境。。。

**Comment by ztdawang** [comment]
最主要是9使用nftables而不是iptables，影响到了kube-proxy

**Comment by gjmzj** [comment]
still working on it

**Comment by gjmzj** [comment]
已增加支持

**Comment by ztdawang** [comment]
感谢大佬的辛勤付出！
