### ISSUE TITLE
kubeasz 3.5.3 安装报 python3.7 找不到

### ISSUE THREAD

**Issue by xiaoaps** [easzlab/kubeasz#1264]
kubeasz 3.5.3 安装报 etcd 创建证书请求  /usr/bin/python3.7 not found, 退回kubeasz3.5.2 能正常安装。

**Comment by xiaoaps** [comment]
![微信图片_20230420111959](https://user-images.githubusercontent.com/12653494/233249904-e97128f7-e9b4-40d4-9458-8112e9c8cd08.png)

**Comment by xiaoaps** [comment]
是的 [AllinOne部署] 单机在线部署，试了三遍还是不行，回退kubeasz3.5.2的版本是可以的。

**Comment by gjmzj** [comment]
# 指定python版本，xxxx为集群名
source ~/.bashrc
dk ezctl setup xxxx all -e ansible_python_interpreter=/usr/bin/python3
