### ISSUE TITLE
国产操作系统支持问题

### ISSUE THREAD

**Issue by oceanftd** [easzlab/kubeasz#1267]
现在好多公司在国产化改造，操作系统用的麒麟v10，什么时候能支持。

**Comment by gjmzj** [comment]
可能只需要修改几行配置就能支持，可以看看文档
https://github.com/easzlab/kubeasz/blob/master/docs/setup/multi_os.md
https://github.com/easzlab/kubeasz/blob/master/docs/setup/multi_platform.md

也可以提供下可远程ssh的测试机器

**Comment by oceanftd** [comment]
> 可能只需要修改几行配置就能支持，可以看看文档 https://github.com/easzlab/kubeasz/blob/master/docs/setup/multi_os.md https://github.com/easzlab/kubeasz/blob/master/docs/setup/multi_platform.md
> 
> 也可以提供下可远程ssh的测试机器

组件版本问题，更换版本重新安装就好了，多谢。
