### ISSUE TITLE
在进行etcd 安装时，提示 /bin/sh: /usr/bin/python3.7: not found

### ISSUE THREAD

**Issue by itswl** [easzlab/kubeasz#1268]
### What happened? 发生了什么问题？

TASK [etcd : 创建etcd证书请求] *******************************************************
fatal: [192.168.2.134]: FAILED! => {"msg": "Failed to get information on remote file (                                                            /etc/kubeasz/clusters/k8s-bap/ssl/etcd-csr.json): /bin/sh: /usr/bin/python3.7: not found\n"}

NO MORE HOSTS LEFT *******************************************************************

PLAY RECAP ***************************************************************************
192.168.2.134              : ok=36   changed=11   unreachable=0    failed=1    skipped                                                            =105  rescued=0    ignored=0
192.168.2.135              : ok=35   changed=11   unreachable=0    failed=0    skipped                                                            =102  rescued=0    ignored=0
192.168.2.136              : ok=35   changed=11   unreachable=0    failed=0    skipped                                                            =102  rescued=0    ignored=0
localhost                  : ok=31   changed=21   unreachable=0    failed=0    skipped                                                            =13   rescued=0    ignored=0

### What did you expect to happen? 期望的结果是什么？

正常安装

```
- name: 创建etcd证书请求
  template: src=etcd-csr.json.j2 dest={{ cluster_dir }}/ssl/etcd-csr.json
  connection: local
  run_once: true
  tags: force_change_certs
```

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

ln -s /usr/bin/python3 /usr/bin/python3.7 后可以正常使用。

### Kubernetes version k8s 版本

<details>
1.27.1
</details>

### Kubeasz version

<details>
3.6.0
</details>

### OS version 操作系统版本

<details>
[root@bclinux01 ~]# cat /etc/os-release
NAME="BigCloud Enterprise Linux"
VERSION="21.10 (LTS-SP2)"
ID="bclinux"
VERSION_ID="21.10"
PRETTY_NAME="BigCloud Enterprise Linux For Euler 21.10 LTS"
ANSI_COLOR="0;31"

[root@bclinux01 ~]#  uname -a
Linux bclinux01 4.19.90-2107.6.0.0100.oe1.bclinux.x86_64 #1 SMP Wed Dec 1 19:59:44 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@bclinux01 ~]
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>
补充一下
用的 移动的 BCLinux 也是可以安装的，RedHat 系 https://mirrors.cmecloud.cn/bclinux/
```
bclinux01:/etc/kubeasz# ansible -i 192.168.2.134, all -m setup |grep ansible_distribution
[WARNING]: Platform linux on host 192.168.2.134 is using the discovered Python
interpreter at /usr/bin/python3.7, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.14/reference_appendices/interpreter_discovery.html for more information.
        "ansible_distribution": "BigCloud",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/redhat-release",
        "ansible_distribution_file_variety": "RedHat",
        "ansible_distribution_major_version": "21",
        "ansible_distribution_release": "LTS-SP2",
        "ansible_distribution_version": "21.10",
```
</details>

**Comment by gjmzj** [comment]
这个结果是符合预期的；是ansible 使用connection: local 一个副作用；

临时可以添加一个参数去安装
```
source ~/.bashrc
dk ezctl setup xxxx all -e ansible_python_interpreter=/usr/bin/python3
```
