### ISSUE TITLE
calico小bug

### ISSUE THREAD

**Issue by ztdawang** [easzlab/kubeasz#1273]
/etc/kubeasz/example/config.yml 的值写错了
CALICO_NETWORKING_BACKEND: "brid"

![image](https://github.com/easzlab/kubeasz/assets/22386267/09db0ff3-4ad1-4f0c-a51f-9df848781245)

![image](https://github.com/easzlab/kubeasz/assets/22386267/ec8472a4-bdaa-4054-a1a0-8b4735d98558)

**Comment by gjmzj** [comment]
看来这个backend 默认就是bird，即便写错了，也是bird；

已在后续版本修改

**Comment by windy629** [comment]
意思是还是写bird，将错就错？不会影响安装？
