### ISSUE TITLE
请教下kubeasz部署的k8s，在哪里修改service-node-port-range 范围？

### ISSUE THREAD

**Issue by xiaoaps** [easzlab/kubeasz#1276]
### What happened? 发生了什么问题？

需要修改k8s 默认30000+ 端口范围，/etc/kubeasz/clusters/k8s-01/hosts [all:vars]  NODE_PORT_RANGE="30000-32767" 修改后，如何使生效？

### What did you expect to happen? 期望的结果是什么？

修改默认端口范围

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

service-node-port-range 默认端口范围

### Kubernetes version k8s 版本

<details>

</details>

### Kubeasz version

<details>
v1.26
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
centos7
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
是的，安装前，修改这个配置以后，再安装k8s集群就能生效；

**Comment by linorwang** [comment]
如果集群安装之后，修改重新部署才能生效嘛
