### ISSUE TITLE
节点没有config文件

### ISSUE THREAD

**Issue by mortalxu** [easzlab/kubeasz#1278]
### What happened? 发生了什么问题？

使用kubeasz 3.3.5 部署ha k8s v1.24.13 后，所有节点下都没有config文件。
执行kubectl get nodes 的时候报错： `The connection to the server localhost:8080 was refused - did you specify the right host or port?`

### What did you expect to happen? 期望的结果是什么？

所有部署节点都有config文件

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

**OS：Ubuntu 20.04.5 LTS
Kernel:  5.4.0-137-generic**

### Kubernetes version k8s 版本

<details>
3.3.5
</details>

### Kubeasz version

<details>
v1.24.13
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux master01 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
by design

**Comment by DerNarrrrr** [comment]
我也是一样的情况，我是用的是1.27.2版本k8s对应的kubeasz。部署完成后在master节点“kubectl get nodes”会报错“The connection to the server localhost:8080 was refused - did you specify the right host or port?”

最后排查出来是所有节点的“/etc/kubernetes”和“/root/.kube/”下都没有admin的证书。

然后我就把“/etc/kubernetes”下的kubelet.kubeconfig文件重命名成了admin.config，之后“get pod/node”就好使了，但是查看更高级的资源比如deployment还是权限不足。

如果是设计如此的话，我理解是需要咱们自己通过RABC的接口设置新的权限吗？

**Comment by gjmzj** [comment]
> 我也是一样的情况，我是用的是1.27.2版本k8s对应的kubeasz。部署完成后在master节点“kubectl get nodes”会报错“The connection to the server localhost:8080 was refused - did you specify the right host or port?”
> 
> 最后排查出来是所有节点的“/etc/kubernetes”和“/root/.kube/”下都没有admin的证书。
> 
> 然后我就把“/etc/kubernetes”下的kubelet.kubeconfig文件重命名成了admin.config，之后“get pod/node”就好使了，但是查看更高级的资源比如deployment还是权限不足。
> 
> 如果是设计如此的话，我理解是需要咱们自己通过RABC的接口设置新的权限吗？

集群高级权限kubeconfig是需要保护的， 目前项目不会默认下发给master或者node节点；只有在部署节点有(~/.kube/config)；自己按需复制吧

**Comment by suyanhj** [comment]
> > 我也是一样的情况，我是用的是1.27.2版本k8s对应的kubeasz。部署完成后在master节点“kubectl get nodes”会报错“The connection to the server localhost:8080 was refused - did you specify the right host or port?”
> > 最后排查出来是所有节点的“/etc/kubernetes”和“/root/.kube/”下都没有admin的证书。
> > 然后我就把“/etc/kubernetes”下的kubelet.kubeconfig文件重命名成了admin.config，之后“get pod/node”就好使了，但是查看更高级的资源比如deployment还是权限不足。
> > 如果是设计如此的话，我理解是需要咱们自己通过RABC的接口设置新的权限吗？
> 
> 集群高级权限kubeconfig是需要保护的， 目前项目不会默认下发给master或者node节点；只有在部署节点有(~/.kube/config)；自己按需复制吧

我最近部署也发现这个事情，方便在ezctl脚本中加一个config push功能不，可以省去手写同步脚本，支持多个节点和单节点同步就行

**Comment by DerNarrrrr** [comment]
> > 我也是一样的情况，我是用的是1.27.2版本k8s对应的kubeasz。部署完成后在master节点“kubectl get nodes”会报错“The connection to the server localhost:8080 was refused - did you specify the right host or port?”
> > 最后排查出来是所有节点的“/etc/kubernetes”和“/root/.kube/”下都没有admin的证书。
> > 然后我就把“/etc/kubernetes”下的kubelet.kubeconfig文件重命名成了admin.config，之后“get pod/node”就好使了，但是查看更高级的资源比如deployment还是权限不足。
> > 如果是设计如此的话，我理解是需要咱们自己通过RABC的接口设置新的权限吗？
> 
> 集群高级权限kubeconfig是需要保护的， 目前项目不会默认下发给master或者node节点；只有在部署节点有(~/.kube/config)；自己按需复制吧

好的，感谢您～我真的在部署节点的路径下发现了高权限的那个config文件，然后把文件传输到master节点的“/etc/kubernetes/admin.conf”就可以了。
