### ISSUE TITLE
kubeasz部署lb,keepalived的vip网络问题

### ISSUE THREAD

**Issue by suyanhj** [easzlab/kubeasz#1280]
环境：
  kubeasz 3.3.5
  k8s: 1.24.x
    ipvs、calico默认配置、iptables未做限制

问题： 部署lb的时候，ansible提示访问vip的apiserver超时报错
解决： 经过初步排查，除了有vip的主机自己能ping通vip，其他主机访问均超时，apiserver是正常运行的，在vip主机tcpdump抓包，只能看到请求者发包，vip并没有回复包，怀疑keepalived配置有问题，后看配置，验证猜测是对的，在配置修改后，其他主机均可访问vip

图一是backup节点的配置，原先单播地址指定的是master节点的宿主机ip，后来把单播地址改为vip地址
![image](https://github.com/easzlab/kubeasz/assets/95021771/d5ba3d11-df61-4884-8b16-d1c6b4011ccf)

图二是master节点的配置，原先单播地址的源ip是本机的宿主机ip，后改为vip
![image](https://github.com/easzlab/kubeasz/assets/95021771/def36aed-9079-45e6-97da-9638857d9fc0)

**Comment by gjmzj** [comment]
keepalived vrrp本来就是工作同一个网段的；你贴出的两个图，unicast_src 和 unicast_peer地址根本是两个网段，所以不会通
