### ISSUE TITLE
多节点部署时node没有设置/etc/hosts导致部署失败

### ISSUE THREAD

**Issue by wrype** [easzlab/kubeasz#1283]
### What happened? 发生了什么问题？

playbook打印
```
TASK [kube-node : 轮询等待node达到Ready状态] ***********************************
fatal: [192.168.126.11]: FAILED! => {"attempts": 8, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get node worker-01|awk 'NR>1{print $2}'", "delta": "0:00:00.051701", "end": "2023-06-08 16:45:12.647310", "msg": "", "rc": 0, "start": "2023-06-08 16:45:12.595609", "stderr": "Error from server (NotFound): nodes \"worker-01\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"worker-01\" not found"], "stdout": "", "stdout_lines": []}
```
node节点kubelet服务异常
```
# systemctl status kubelet -l
Jun 08 16:51:08 localhost.localdomain kubelet[12672]: E0608 16:51:08.328563   12672 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"worker-01\" not found" node="worker-01"
```

### What did you expect to happen? 期望的结果是什么？

多节点部署时集群正常运行

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

/etc/kubeasz/clusters/k8s-01/hosts 配置
```
[kube_master]
192.168.126.10 k8s_nodename='master-01'

[kube_node]
192.168.126.11 k8s_nodename='worker-01'
```

### Anything else we need to know? 其他需要说明的情况

 修复PR：#1282 

### Kubernetes version k8s 版本

<details>
与 k8s 版本无关
</details>

### Kubeasz version

<details>
已测试确认：3.6.1、3.3.5，其他版本估计有同样问题
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux localhost.localdomain 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
这个配置没有问题，可以创建集群

```
root@iZbp1fx9l06rw4t7s0ucukZ:/etc/kubeasz# kubectl get node
NAME        STATUS                     ROLES    AGE    VERSION
master-01   Ready,SchedulingDisabled   master   106s   v1.26.5
worker-01   Ready                      node     67s    v1.26.5


root@iZbp1fx9l06rw4t7s0ucukZ:/etc/kubeasz# cat clusters/default/hosts
...
[etcd]
192.168.0.100

[kube_master]
192.168.0.100 k8s_nodename='master-01'

[kube_node]
192.168.0.101 k8s_nodename='worker-01'
...
```

其中master-01上 /etc/hosts

```
root@iZbp1fx9l06rw4t7s0ucukZ:/etc/kubeasz# cat /etc/hosts
...

192.168.0.100    easzlab.io.local
192.168.0.100    master-01
192.168.0.101    worker-01
```

worker-01机器上/etc/hosts

```
root@iZbp1fx9l06rw4t7s0uculZ:~# cat /etc/hosts
...

192.168.0.100    easzlab.io.local
```

**Comment by gjmzj** [comment]
原来代码的逻辑是只需要在集群master节点上的/etc/hosts 配置所有节点`K8S_NODENAME `的地址解析；因为apiserver 会访问kubelet，而worker节点之间不需要类似访问，所以worker节点上不需要配置类似/etc/hosts

**Comment by gjmzj** [comment]
worker节点之间应该不需要互相访问；你能否再用干净的机器仔细测试下，看看开始kubelet不能启动是怎么引起的

**Comment by wrype** [comment]
我的安装操作是：
```
docker exec -it kubeasz ezctl new k8s-01
docker exec -it kubeasz ezctl setup k8s-01 all
```
```
# cat /etc/kubeasz/clusters/k8s-01/hosts
[etcd]
192.168.126.10

[kube_master]
192.168.126.10 k8s_nodename='master-01'

[kube_node]
192.168.126.11 k8s_nodename='worker-01'
```

playbook 日志：
```
TASK [kube-node : 轮询等待kubelet启动] *****************************************
changed: [192.168.126.11]
FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (8 retries left).
FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (7 retries left).
FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (6 retries left).
FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (5 retries left).
FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (4 retries left).
FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (3 retries left).
FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (2 retries left).
FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (1 retries left).

TASK [kube-node : 轮询等待node达到Ready状态] ***********************************
fatal: [192.168.126.11]: FAILED! => {"attempts": 8, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get node worker-01|awk 'NR>1{print $2}'", "delta": "0:00:00.056531", "end": "2023-06-12 17:07:50.825391", "msg": "", "rc": 0, "start": "2023-06-12 17:07:50.768860", "stderr": "Error from server (NotFound): nodes \"worker-01\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"worker-01\" not found"], "stdout": "", "stdout_lines": []}
```

node节点上kubelet的错误日志：
```
# systemctl status kubelet -l
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2023-06-12 17:14:11 CST; 24s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 11749 ExecStartPre=/bin/mount -o remount,rw /sys/fs/cgroup (code=exited, status=0/SUCCESS)
 Main PID: 11751 (kubelet)
    Tasks: 11
   Memory: 28.0M
   CGroup: /system.slice/kubelet.service
           └─11751 /opt/kube/bin/kubelet --config=/var/lib/kubelet/config.yaml --hostname-override=worker-01 --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --root-dir=/var/lib/kubelet --v=2

Jun 12 17:14:16 localhost.localdomain kubelet[11751]: I0612 17:14:16.914343   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
Jun 12 17:14:16 localhost.localdomain kubelet[11751]: I0612 17:14:16.974425   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
Jun 12 17:14:17 localhost.localdomain kubelet[11751]: I0612 17:14:17.251142   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
Jun 12 17:14:17 localhost.localdomain kubelet[11751]: E0612 17:14:17.251160   11751 csi_plugin.go:295] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "worker-01" not found
Jun 12 17:14:17 localhost.localdomain kubelet[11751]: E0612 17:14:17.727020   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Jun 12 17:14:21 localhost.localdomain kubelet[11751]: E0612 17:14:21.408877   11751 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"worker-01\" not found" node="worker-01"
Jun 12 17:14:22 localhost.localdomain kubelet[11751]: E0612 17:14:22.728560   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Jun 12 17:14:27 localhost.localdomain kubelet[11751]: E0612 17:14:27.760599   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Jun 12 17:14:31 localhost.localdomain kubelet[11751]: E0612 17:14:31.556765   11751 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"worker-01\" not found" node="worker-01"
Jun 12 17:14:32 localhost.localdomain kubelet[11751]: E0612 17:14:32.767884   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
```

我猜测是不是`kubelet.service`中`--hostname-override=worker-01`这个参数的原因？

**Comment by gjmzj** [comment]
> 我的安装操作是：
> ```
> docker exec -it kubeasz ezctl new k8s-01
> docker exec -it kubeasz ezctl setup k8s-01 all
> ```
> ```
> # cat /etc/kubeasz/clusters/k8s-01/hosts
> [etcd]
> 192.168.126.10
> 
> [kube_master]
> 192.168.126.10 k8s_nodename='master-01'
> 
> [kube_node]
> 192.168.126.11 k8s_nodename='worker-01'
> ```
> 
> playbook 日志：
> ```
> TASK [kube-node : 轮询等待kubelet启动] *****************************************
> changed: [192.168.126.11]
> FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (8 retries left).
> FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (7 retries left).
> FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (6 retries left).
> FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (5 retries left).
> FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (4 retries left).
> FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (3 retries left).
> FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (2 retries left).
> FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (1 retries left).
> 
> TASK [kube-node : 轮询等待node达到Ready状态] ***********************************
> fatal: [192.168.126.11]: FAILED! => {"attempts": 8, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get node worker-01|awk 'NR>1{print $2}'", "delta": "0:00:00.056531", "end": "2023-06-12 17:07:50.825391", "msg": "", "rc": 0, "start": "2023-06-12 17:07:50.768860", "stderr": "Error from server (NotFound): nodes \"worker-01\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"worker-01\" not found"], "stdout": "", "stdout_lines": []}
> ```
> 
> node节点上kubelet的错误日志：
> ```
> # systemctl status kubelet -l
> ● kubelet.service - Kubernetes Kubelet
>    Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
>    Active: active (running) since Mon 2023-06-12 17:14:11 CST; 24s ago
>      Docs: https://github.com/GoogleCloudPlatform/kubernetes
>   Process: 11749 ExecStartPre=/bin/mount -o remount,rw /sys/fs/cgroup (code=exited, status=0/SUCCESS)
>  Main PID: 11751 (kubelet)
>     Tasks: 11
>    Memory: 28.0M
>    CGroup: /system.slice/kubelet.service
>            └─11751 /opt/kube/bin/kubelet --config=/var/lib/kubelet/config.yaml --hostname-override=worker-01 --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --root-dir=/var/lib/kubelet --v=2
> 
> Jun 12 17:14:16 localhost.localdomain kubelet[11751]: I0612 17:14:16.914343   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
> Jun 12 17:14:16 localhost.localdomain kubelet[11751]: I0612 17:14:16.974425   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
> Jun 12 17:14:17 localhost.localdomain kubelet[11751]: I0612 17:14:17.251142   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
> Jun 12 17:14:17 localhost.localdomain kubelet[11751]: E0612 17:14:17.251160   11751 csi_plugin.go:295] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "worker-01" not found
> Jun 12 17:14:17 localhost.localdomain kubelet[11751]: E0612 17:14:17.727020   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> Jun 12 17:14:21 localhost.localdomain kubelet[11751]: E0612 17:14:21.408877   11751 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"worker-01\" not found" node="worker-01"
> Jun 12 17:14:22 localhost.localdomain kubelet[11751]: E0612 17:14:22.728560   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> Jun 12 17:14:27 localhost.localdomain kubelet[11751]: E0612 17:14:27.760599   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> Jun 12 17:14:31 localhost.localdomain kubelet[11751]: E0612 17:14:31.556765   11751 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"worker-01\" not found" node="worker-01"
> Jun 12 17:14:32 localhost.localdomain kubelet[11751]: E0612 17:14:32.767884   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> ```
> 
> 我猜测是不是`kubelet.service`中`--hostname-override=worker-01`这个参数的原因？

这个设置和我运行的一样，没有复现问题😓

**Comment by wrype** [comment]
> > 我的安装操作是：
> > ```
> > docker exec -it kubeasz ezctl new k8s-01
> > docker exec -it kubeasz ezctl setup k8s-01 all
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > # cat /etc/kubeasz/clusters/k8s-01/hosts
> > [etcd]
> > 192.168.126.10
> > 
> > [kube_master]
> > 192.168.126.10 k8s_nodename='master-01'
> > 
> > [kube_node]
> > 192.168.126.11 k8s_nodename='worker-01'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > playbook 日志：
> > ```
> > TASK [kube-node : 轮询等待kubelet启动] *****************************************
> > changed: [192.168.126.11]
> > FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (8 retries left).
> > FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (7 retries left).
> > FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (6 retries left).
> > FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (5 retries left).
> > FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (4 retries left).
> > FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (3 retries left).
> > FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (2 retries left).
> > FAILED - RETRYING: [192.168.126.11]: 轮询等待node达到Ready状态 (1 retries left).
> > 
> > TASK [kube-node : 轮询等待node达到Ready状态] ***********************************
> > fatal: [192.168.126.11]: FAILED! => {"attempts": 8, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get node worker-01|awk 'NR>1{print $2}'", "delta": "0:00:00.056531", "end": "2023-06-12 17:07:50.825391", "msg": "", "rc": 0, "start": "2023-06-12 17:07:50.768860", "stderr": "Error from server (NotFound): nodes \"worker-01\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"worker-01\" not found"], "stdout": "", "stdout_lines": []}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > node节点上kubelet的错误日志：
> > ```
> > # systemctl status kubelet -l
> > ● kubelet.service - Kubernetes Kubelet
> >    Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
> >    Active: active (running) since Mon 2023-06-12 17:14:11 CST; 24s ago
> >      Docs: https://github.com/GoogleCloudPlatform/kubernetes
> >   Process: 11749 ExecStartPre=/bin/mount -o remount,rw /sys/fs/cgroup (code=exited, status=0/SUCCESS)
> >  Main PID: 11751 (kubelet)
> >     Tasks: 11
> >    Memory: 28.0M
> >    CGroup: /system.slice/kubelet.service
> >            └─11751 /opt/kube/bin/kubelet --config=/var/lib/kubelet/config.yaml --hostname-override=worker-01 --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --root-dir=/var/lib/kubelet --v=2
> > 
> > Jun 12 17:14:16 localhost.localdomain kubelet[11751]: I0612 17:14:16.914343   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
> > Jun 12 17:14:16 localhost.localdomain kubelet[11751]: I0612 17:14:16.974425   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
> > Jun 12 17:14:17 localhost.localdomain kubelet[11751]: I0612 17:14:17.251142   11751 nodeinfomanager.go:401] Failed to publish CSINode: nodes "worker-01" not found
> > Jun 12 17:14:17 localhost.localdomain kubelet[11751]: E0612 17:14:17.251160   11751 csi_plugin.go:295] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "worker-01" not found
> > Jun 12 17:14:17 localhost.localdomain kubelet[11751]: E0612 17:14:17.727020   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> > Jun 12 17:14:21 localhost.localdomain kubelet[11751]: E0612 17:14:21.408877   11751 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"worker-01\" not found" node="worker-01"
> > Jun 12 17:14:22 localhost.localdomain kubelet[11751]: E0612 17:14:22.728560   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> > Jun 12 17:14:27 localhost.localdomain kubelet[11751]: E0612 17:14:27.760599   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> > Jun 12 17:14:31 localhost.localdomain kubelet[11751]: E0612 17:14:31.556765   11751 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"worker-01\" not found" node="worker-01"
> > Jun 12 17:14:32 localhost.localdomain kubelet[11751]: E0612 17:14:32.767884   11751 kubelet.go:2281] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我猜测是不是`kubelet.service`中`--hostname-override=worker-01`这个参数的原因？
> 
> 这个设置和我运行的一样，没有复现问题😓

node节点上`ping worker-01`试试，看看是不是其他地方配置了域名？

**Comment by wrype** [comment]
需要我提供什么日志吗？

**Comment by gjmzj** [comment]
只需要在集群master节点上的/etc/hosts 配置所有节点K8S_NODENAME 的地址解析；因为apiserver 会访问kubelet，而worker节点之间不需要类似访问，所以worker节点上不需要配置类似/etc/hosts

所以node节点上ping worker-01通不通无所谓

**Comment by wrype** [comment]
那node上的kubelet为什么会启动异常呢？
