### ISSUE TITLE
最新版3.6.1遇到的kubeReserved问题，想请教下。

### ISSUE THREAD

**Issue by sceosun** [easzlab/kubeasz#1286]
### What happened? 发生了什么问题？

我在部署第四步结束时，ansiabl任务到轮询等待kubelet启动，查看kubelet启动状态是失败的。查看日志是/var/lib/kubelet/config.yaml有配置是有问题的；
报错如下：
Flag --container-runtime-endpoint has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 20 00:29:11 k8s-master1.sunce.io kubelet[41902]: E0620 00:29:11.805054   41902 run.go:74] "command failed" err="failed to load kubelet config file, error: failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to decode: json: cannot unmarshal number into Go struct field KubeletConfiguration.kubeReserved of type string, path: /var/lib/kubelet/config.yaml"

我看到是有关于kubeReserved字段的错误；(这个文件是自动生成的)
而 /var/lib/kubelet/config.yaml文件是这样的：
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: 0.0.0.0
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/ssl/ca.pem
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: systemd 
cgroupsPerQOS: true
clusterDNS:
- 169.254.20.10
clusterDomain: sunce.local
configMapAndSecretChangeDetectionStrategy: Watch
containerLogMaxFiles: 3 
containerLogMaxSize: 10Mi
enforceNodeAllocatable:
- pods
- kube-reserved
eventBurst: 10
eventRecordQPS: 5
evictionHard:
  imagefs.available: 15%
  memory.available: 300Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: true
fileCheckFrequency: 40s
hairpinMode: hairpin-veth 
healthzBindAddress: 0.0.0.0
healthzPort: 10248
httpCheckFrequency: 40s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
kubeReservedCgroup: /podruntime.slice
kubeReserved:
  cpu: 200m
  memory: 400Mi
  pid: 1000
kubeAPIBurst: 100
kubeAPIQPS: 50
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxParallelImagePulls: 5
maxPods: 200
nodeLeaseDurationSeconds: 40
nodeStatusReportFrequency: 1m0s
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: 1024
port: 10250
#disable readOnlyPort 
readOnlyPort: 0
resolvConf: /run/systemd/resolve/resolv.conf
runtimeRequestTimeout: 2m0s
serializeImagePulls: false
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
tlsCertFile: /etc/kubernetes/ssl/kubelet.pem
tlsPrivateKeyFile: /etc/kubernetes/ssl/kubelet-key.pem

似乎是配置文件中字段kubeReserved:的写法不对，和字符转换有关，之后我把配置文件一些必要值留着，换了其他配置文件。在/etc/kubeasz/roles/kube-node/templates目录中替换了kubelet-config.yaml.j2这个文件，成功启动kubelet;
我安装的k8s版本是最新的1.27.2；
我想知道以上这个有报错的yaml文件kubeReserved部分到底哪里有错误，麻烦了！

### What did you expect to happen? 期望的结果是什么？

想知道报错的原因

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

三个master，三个worker，三个master节点安装etcd，

### Anything else we need to know? 其他需要说明的情况

我的控制端节点和master01是复用的，顺便说一下，做互信的话，master01自己和自己也要做互信！

### Kubernetes version k8s 版本

<details>

</details>
1.27.2

### Kubeasz version

<details>

</details>
3.6.1

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>
Ubuntu2004

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>
使用的是calico插件，

**Comment by gjmzj** [comment]
是的，主要是kube-reserved 设置pid的时候是需要填写字符串而非数字

这个commit已经解决了 9150e54352cd280c99197933784b5c2c9bd7fd4c

**Comment by sceosun** [comment]
好的，非常感谢!
