### ISSUE TITLE
在推荐版本里面，如何用最新的kubeasz自定义指定Kubernetes version版本

### ISSUE THREAD

**Issue by kanghuikai** [easzlab/kubeasz#1287]
### What happened? 发生了什么问题？

1） 在使用# ./ezdown -k v1.23.1 -D #指定版本，不会下载对应k8s镜像，仍然是默认版本

# docker images  |grep k8s-bin
easzlab/kubeasz-k8s-bin                              v1.24.13   b3fbd5744b8f   2 months ago    1.17GB

2）尝试修改ezdown 脚本
cat ezdown |grep -i k8s_bin_ver
K8S_BIN_VER=v1.24.13
    -k <ver>   set kubeasz-k8s-bin version, default "$K8S_BIN_VER"
  logger info "downloading kubernetes: $K8S_BIN_VER binaries"
  docker pull easzlab/kubeasz-k8s-bin:"$K8S_BIN_VER" && \
  docker run -d --name temp_k8s_bin easzlab/kubeasz-k8s-bin:${K8S_BIN_VER} && \
          K8S_BIN_VER="$OPTARG"
3) 定义config.yaml 也不生效
# cat /etc/kubeasz/clusters/sunday/config.yml |grep -i k8s_ver
K8S_VER: "1.24.13"

### What did you expect to happen? 期望的结果是什么？

想了解下运行机制，脚本如何传参 自定义K8S_BIN_VER变量

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

运行命令ezdown -k v1.23.1 -D   // -S   ； 修改脚本  ； config.yaml  自定义版本K8S_BIN_VER不生效 

### Kubernetes version k8s 版本

<details>
Client Version: v1.24.13
Kustomize Version: v4.5.4
Server Version: v1.24.13
</details>

### Kubeasz version

<details>
3.3.5 
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
uname  -a
Linux tm-sunday-master-01 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
理论上按照推荐的kubeasz版本和k8s版本对照表去安装；因为这是经过验证的；

部分k8s版本之间，可以使用同一kubeasz版本，比如：kubeasz 3.6 可以部署 k8s 1.27 和 1.26；但是k8s版本跨越比较大的话，因为k8s本身api变动，无法兼容的

随着k8s越来越稳定和成熟，后续项目尽量会使用同个kubeasz版本支持多个k8s版本。
