### ISSUE TITLE
无法在浏览器中访问prometheus、alertmanager、grafana、bashboard的web界面

### ISSUE THREAD

**Issue by liushuai1206** [easzlab/kubeasz#1288]
### What happened? 发生了什么问题？

NAMESPACE     NAME                                                         READY   STATUS    RESTARTS        AGE
jenkins       pod/jenkins-59fb75bd65-k4s2k                                 1/1     Running   0               42m
kube-system   pod/calico-kube-controllers-7ccf856ff8-59pdr                 1/1     Running   1 (8m57s ago)   42m
kube-system   pod/calico-node-5pppf                                        0/1     Running   0               41m
kube-system   pod/calico-node-qpdkr                                        1/1     Running   0               41m
kube-system   pod/calico-node-tl7c4                                        1/1     Running   0               41m
kube-system   pod/coredns-6557d7db9c-xbnlt                                 1/1     Running   0               41m
kube-system   pod/dashboard-metrics-scraper-5c876f54bd-ffsfk               1/1     Running   0               41m
kube-system   pod/kubernetes-dashboard-89b5448d6-m7wn5                     1/1     Running   0               41m
kube-system   pod/metrics-server-57fbbb5957-gqmdq                          1/1     Running   0               41m
kube-system   pod/nfs-client-provisioner-599c8d6664-lpwzs                  1/1     Running   4 (9m4s ago)    41m
kube-system   pod/node-local-dns-p2n9m                                     1/1     Running   0               41m
kube-system   pod/node-local-dns-r775p                                     1/1     Running   0               41m
kube-system   pod/node-local-dns-swtn9                                     1/1     Running   0               41m
monitor       pod/alertmanager-prometheus-kube-prometheus-alertmanager-0   2/2     Running   1 (40m ago)     41m
monitor       pod/prometheus-grafana-b45f55d49-sjdx9                       3/3     Running   0               41m
monitor       pod/prometheus-kube-prometheus-operator-856bdf57cc-l4q75     1/1     Running   0               41m
monitor       pod/prometheus-kube-state-metrics-587f7d7ddb-hj8tm           1/1     Running   0               41m
monitor       pod/prometheus-prometheus-kube-prometheus-prometheus-0       2/2     Running   0               41m
monitor       pod/prometheus-prometheus-node-exporter-6c4nd                1/1     Running   0               41m
monitor       pod/prometheus-prometheus-node-exporter-g5s5m                1/1     Running   0               41m
monitor       pod/prometheus-prometheus-node-exporter-mdcf9                1/1     Running   0               41m

NAMESPACE     NAME                                                         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
default       service/kubernetes                                           ClusterIP   10.68.0.1       <none>        443/TCP                        31m
kube-system   service/dashboard-metrics-scraper                            ClusterIP   10.68.121.28    <none>        8000/TCP                       30m
kube-system   service/kube-dns                                             ClusterIP   10.68.0.2       <none>        53/UDP,53/TCP,9153/TCP         30m
kube-system   service/kubernetes-dashboard                                 NodePort    10.68.32.202    <none>        443:30116/TCP                  30m
kube-system   service/metrics-server                                       ClusterIP   10.68.3.2       <none>        443/TCP                        30m
kube-system   service/prometheus-kube-prometheus-coredns                   ClusterIP   None            <none>        9153/TCP                       7m10s
kube-system   service/prometheus-kube-prometheus-kube-controller-manager   ClusterIP   None            <none>        10257/TCP                      7m10s
kube-system   service/prometheus-kube-prometheus-kube-etcd                 ClusterIP   None            <none>        2379/TCP                       7m10s
kube-system   service/prometheus-kube-prometheus-kube-proxy                ClusterIP   None            <none>        10249/TCP                      7m10s
kube-system   service/prometheus-kube-prometheus-kube-scheduler            ClusterIP   None            <none>        10259/TCP                      7m10s
kube-system   service/prometheus-kube-prometheus-kubelet                   ClusterIP   None            <none>        10250/TCP,10255/TCP,4194/TCP   28m
monitor       service/alertmanager-operated                                ClusterIP   None            <none>        9093/TCP,9094/TCP,9094/UDP     30m
monitor       service/prometheus-grafana                                   NodePort    10.68.109.182   <none>        80:30903/TCP                   7m10s
monitor       service/prometheus-kube-prometheus-alertmanager              NodePort    10.68.129.155   <none>        9093:30902/TCP                 7m10s
monitor       service/prometheus-kube-prometheus-operator                  NodePort    10.68.195.79    <none>        443:30900/TCP                  7m10s
monitor       service/prometheus-kube-prometheus-prometheus                NodePort    10.68.83.99     <none>        9090:30901/TCP                 7m10s
monitor       service/prometheus-kube-state-metrics                        ClusterIP   10.68.229.238   <none>        8080/TCP                       7m10s
monitor       service/prometheus-operated                                  ClusterIP   None            <none>        9090/TCP                       30m
monitor       service/prometheus-prometheus-node-exporter                  ClusterIP   10.68.120.139   <none>        9100/TCP                       7m10s

NAMESPACE     NAME                                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/calico-node                           3         3         2       3            2           kubernetes.io/os=linux   65m
kube-system   daemonset.apps/node-local-dns                        3         3         3       3            3           <none>                   63m
monitor       daemonset.apps/prometheus-prometheus-node-exporter   3         3         3       3            3           <none>                   62m

NAMESPACE     NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
jenkins       deployment.apps/jenkins                               1/1     1            1           48m
kube-system   deployment.apps/calico-kube-controllers               1/1     1            1           65m
kube-system   deployment.apps/coredns                               1/1     1            1           63m
kube-system   deployment.apps/dashboard-metrics-scraper             1/1     1            1           63m
kube-system   deployment.apps/kubernetes-dashboard                  1/1     1            1           63m
kube-system   deployment.apps/metrics-server                        1/1     1            1           63m
kube-system   deployment.apps/nfs-client-provisioner                1/1     1            1           55m
monitor       deployment.apps/prometheus-grafana                    1/1     1            1           62m
monitor       deployment.apps/prometheus-kube-prometheus-operator   1/1     1            1           62m
monitor       deployment.apps/prometheus-kube-state-metrics         1/1     1            1           62m

NAMESPACE     NAME                                                             DESIRED   CURRENT   READY   AGE
jenkins       replicaset.apps/jenkins-59fb75bd65                               1         1         1       48m
kube-system   replicaset.apps/calico-kube-controllers-7ccf856ff8               1         1         1       65m
kube-system   replicaset.apps/coredns-6557d7db9c                               1         1         1       63m
kube-system   replicaset.apps/dashboard-metrics-scraper-5c876f54bd             1         1         1       63m
kube-system   replicaset.apps/kubernetes-dashboard-89b5448d6                   1         1         1       63m
kube-system   replicaset.apps/metrics-server-57fbbb5957                        1         1         1       63m
kube-system   replicaset.apps/nfs-client-provisioner-599c8d6664                1         1         1       55m
monitor       replicaset.apps/prometheus-grafana-b45f55d49                     1         1         1       62m
monitor       replicaset.apps/prometheus-kube-prometheus-operator-856bdf57cc   1         1         1       62m
monitor       replicaset.apps/prometheus-kube-state-metrics-587f7d7ddb         1         1         1       62m

NAMESPACE   NAME                                                                    READY   AGE
monitor     statefulset.apps/alertmanager-prometheus-kube-prometheus-alertmanager   1/1     62m
monitor     statefulset.apps/prometheus-prometheus-kube-prometheus-prometheus       1/1     62m

### What did you expect to happen? 期望的结果是什么？

- 访问prometheus的web界面：`http://$NodeIP:30901`
- 访问alertmanager的web界面：`http://$NodeIP:30902`
- 访问grafana的web界面：`http://$NodeIP:30903
- 访问dashboarf的web页面:`https://$NodeIP:targetport`

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

初始化命令:  ./ezctl  setup k8s all

### Anything else we need to know? 其他需要说明的情况

无

### Kubernetes version k8s 版本

<details>
1.27.1
</details>

### Kubeasz version

<details>
3.6.0
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
ubuntu 22.04
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>
calico
</details>

**Comment by gjmzj** [comment]
kube-system pod/calico-node-5pppf 0/1 Running 0 41m

这个calico 节点不正常，是不是网络有问题，可以安装网络检测组件测试下

**Comment by liushuai1206** [comment]
好的，我对calico这个组件不是特别熟悉，不知道该如何去排查，能否指点一下🥹
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月24日 22:49 |
| 收件人 | easzlab/kubeasz ***@***.***> |
| 抄送人 | liushuai1206 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [easzlab/kubeasz] 无法在浏览器中访问prometheus、alertmanager、grafana、bashboard的web界面 (Issue #1288) |

kube-system pod/calico-node-5pppf 0/1 Running 0 41m

这个calico 节点不正常，是不是网络有问题，可以安装网络检测组件测试下
