### ISSUE TITLE
数据备份失败

### ISSUE THREAD

**Issue by linkypi** [easzlab/kubeasz#1290]
### What happened? 发生了什么问题？

服务器 centos7 ， 未在机器安装 ansible 任何版本
kubeasz 版本 3.6.1， 使用 ezdown -S启动 docker 容器后使用 dk ezctl setup cluster all 部署集群完成后
使用命令备份集群报错，实际在backup目录下没有生成任何备份文件
``` sh
dk ezctl backup esop
```
![9f313f488ce84e11e7cc1f21105f00d](https://github.com/easzlab/kubeasz/assets/4386639/f2f6ab07-20eb-4a7b-8cdc-be31bb020bb0)

### What did you expect to happen? 期望的结果是什么？

希望可以正常在backup目录下生成备份文件

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

之前先安装的 kubeasz 3.6.0, 后来删除/etc/kubeasz/bin 下的二进制文件后升级到 3.6.1 。
紧接着就是使用命令部署集群，然后执行备份操作

### Kubernetes version k8s 版本

<details>
  
</details>
 k8s 版本  v1.27.2

### Kubeasz version

<details>
    
</details>
kubeasz 版本  3.6.1

### OS version 操作系统版本

<details>

[root@k8s esop]# uname -a
Linux k8s.node1 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@k8s esop]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
排除掉3.6.0版本影响；请在干净的机器安装3.6.1
