### ISSUE TITLE
kubeasz 3.6.1 部署失败

### ISSUE THREAD

**Issue by linkypi** [easzlab/kubeasz#1291]
### What happened? 发生了什么问题？

机器原本安装有 kubeasz 3.6.0, 后来在没有对3.6.0做任何操作的情况下，按照官方文档安装了3.6.1
安装过程提示部分二进制文件无法找到，实际部分二进制文件已经放到相关目录下

![4333bcaa60974ea34be7df9f3e0c49b](https://github.com/easzlab/kubeasz/assets/4386639/bc4f4a35-8dd7-418d-8540-a57b4096d49d)

![d47a20e6f186b22df2b7143e9c7072b](https://github.com/easzlab/kubeasz/assets/4386639/f5c46c42-76cf-42a3-854e-31855948cdaa)

### What did you expect to happen? 期望的结果是什么？

希望可以成功部署集群

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

机器原本安装有 kubeasz 3.6.0, 后来在没有对3.6.0做任何操作的情况下，按照官方文档安装了3.6.1

### Kubernetes version k8s 版本

<details>

</details>

### Kubeasz version

<details>

</details>
k8s v1.27.2

### OS version 操作系统版本

<details>

[root@k8s esop]# uname -a
Linux k8s.node1 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

[root@k8s esop]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
如果装过3.6.0版本，想要使用kubeasz 3.6.1；可以按照如下步骤：
1.删除3.6.0 安装的k8s集群
2.删除kubeasz 3.6.0： rm -rf /etc/kubeasz
3.按照3.6.1的正常安装

**Comment by opszhou** [comment]
我部署的过程中，在步骤06，也就是 ezctl setup <cluster> 06 报错，定位到 master01节点 containerd 不正常，原因是在playbook中，使用了 systemctl is-active containerd 去判断 containerd 存在与否，再进行部署。由于master01 已经装了docker，造成执行 systemctl is-active containerd 的结果为 active. 直接跳过了配置步骤。
