### ISSUE TITLE
kube-proxy在prometheus无法抓取到监控项 

### ISSUE THREAD

**Issue by wsw136** [easzlab/kubeasz#1296]
### What would you like to be added?

已经建立ep，servicemonitor，svc对kube-proxy进行捕捉，但prometheus无法抓取到指标

### Why is this needed?

已经建立ep，servicemonitor，svc对kube-proxy进行捕捉，但prometheus无法抓取到指标

**Comment by gjmzj** [comment]
进入prometheus web界面，查看 target 那里，看看什么原因没法拉取到kube-proxy的指标
