### ISSUE TITLE
使用物理机搭建K8S集群，单节点运行POD卡住问题处理

### ISSUE THREAD

**Issue by wangyc26** [easzlab/kubeasz#1297]
### What happened? 发生了什么问题？

最近，使用 kubeasz 工具在我们几台物理服务器上部署了一套K8S集群，在使用过程中遇到了一些问题。单台服务器配置：64C、256G，问题现象主要是单台机器运行的pod数量 (差不多超过18个) 比较多的时候，新创建的pod会一直处于ContainerCreating ，然后节点状态就会由Ready变成NotReady，单个POD限制的资源是1C、2G这样。我理解这样的服务器配置，是远远超出这些POD的资源使用限制的，正常不会有问题才对。

节点NotReady的时候，我有查过节点的状态，显示是PLEG is not healthy这样，我不知道如何处理，就把docker和kubelet进行了重启处理，然后节点就恢复正常了，之前不能创建的pod也可以正常运行了。

<img width="1359" alt="企业微信截图_45a16b4b-6761-41c8-833a-7e528d7d61df" src="https://github.com/easzlab/kubeasz/assets/21526883/446336a2-77cf-49aa-9b06-bc483eef8dfa">
<img width="1439" alt="企业微信截图_42af736e-9f05-4f5f-bc05-03a5443bd465" src="https://github.com/easzlab/kubeasz/assets/21526883/2e22d695-5c93-4c6e-8e59-a9a99bb3ebc4">

### What did you expect to happen? 期望的结果是什么？

不知道是否要升级docker版本，还是把容器运行时更新为containerd

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

集群节点不可用

### Kubernetes version k8s 版本

<details>
1.20.5
</details>

### Kubeasz version

<details>
3.0.1
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
$ uname -a
Linux ufin-app01 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by wangyc26** [comment]
服务器CPU配置信息

<img width="1912" alt="image" src="https://github.com/easzlab/kubeasz/assets/21526883/bf6b1cb0-1ebb-46a3-8059-6607c6bdb97a">

**Comment by wangyc26** [comment]
目前各节点使用情况

<img width="781" alt="image" src="https://github.com/easzlab/kubeasz/assets/21526883/b2e0c280-219e-42ae-a9d1-f9ce513737ba">

**Comment by wangyc26** [comment]
本来打算三台master节点只用于部署master节点组件和其他组件的，不用于部署应用POD，但是通过测试发现Node节点总是异常，只能先临时把master节点也用起来了，目前几台节点都是正常的，但是这个时候如果更新服务，Pod滚动更新或者新加POD  就会出现前面描述的情况。

**Comment by gjmzj** [comment]
物理机安装k8s，因为单台机器资源充足，第一要做的事情是修改每台机器上最多可运行的pod数，默认每台机器最多110个pod；

集群1.20 版本比较老，问题比较难定位；如果不是生产环境，建议故障时先别着急重启kubelet恢复，多看看日志，然后搜索下错误日志的原因；

能升级的话，建议早点升级到新版本，k8s官方也只维护最新4个版本，目前是1.24，1.25，1.26，1.27；还有容器运行时还是跟着官方走，用containerd

**Comment by wangyc26** [comment]
POD数量目前应该远远没有达到，这两天我也在看，想办法先把docker切换到containerd，如果还不行再进行升级K8S集群版本

**Comment by wangyc26** [comment]
把docker切换到containerd之后，目前运行的POD副本数量过多之后，还是会有部分pod处于ContainerCreating 状态

<img width="1559" alt="image" src="https://github.com/easzlab/kubeasz/assets/21526883/9fa5c0f0-b2e9-4943-a328-3d5c76fa8d31">

查看Pod卡住的原因，显示内容如下，我不知道是不是和CNI网络插件有关系，我们现在用的网络插件是Flannel
<img width="1062" alt="image" src="https://github.com/easzlab/kubeasz/assets/21526883/bd7e1936-46c9-4602-9ca5-589b07313133">
<img width="1509" alt="image" src="https://github.com/easzlab/kubeasz/assets/21526883/3a4ac078-45f7-4525-bea8-a98fc00d7229">

**Comment by wangyc26** [comment]
目前单个节点可以使用的资源是足够的，且POD数量也没有达到110个

**Comment by wangyc26** [comment]
集群版本升级到1.26.4 后问题解决

<img width="1678" alt="image" src="https://github.com/easzlab/kubeasz/assets/21526883/8d532d30-aefa-4d79-98b0-85e3107d9797">
