### ISSUE TITLE
无法删除k8s集群节点

### ISSUE THREAD

**Issue by 2469598244** [easzlab/kubeasz#1306]
### What happened? 发生了什么问题？

root@k8s-deployment:/etc/kubeasz# kubectl get nodes
NAME           STATUS                     ROLES    AGE    VERSION
k8s-master01   Ready,SchedulingDisabled   master   176m   v1.27.1
k8s-master02   Ready,SchedulingDisabled   master   176m   v1.27.1
k8s-master03   Ready,SchedulingDisabled   master   176m   v1.27.1
k8s-node01     Ready                      node     174m   v1.27.1
k8s-node02     Ready                      node     174m   v1.27.1

root@k8s-deployment:/etc/kubeasz# kubectl config get-contexts
CURRENT   NAME                    CLUSTER         AUTHINFO   NAMESPACE
*         context-k8s-cluster01   k8s-cluster01   admin

root@k8s-deployment:/etc/kubeasz# ./ezctl del-master k8s-cluster01 10.1.200.190
2023-08-18 14:25:59 ERROR master 10.1.200.190 not existed!

### What did you expect to happen? 期望的结果是什么？

可以删除k8s节点

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

无法删除k8s集群节点

### Kubernetes version k8s 版本

<details>

k8s-v1.27.1

</details>

### Kubeasz version

<details>

3.6

</details>

### OS version 操作系统版本

<details>

Ubuntu 20.04.6 LTS \n \l

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

calico-v3.24.5

</details>

**Comment by 2469598244** [comment]
root@k8s-deployment:/etc/kubeasz# kubectl get pods -A -o wide
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE    IP              NODE           NOMINATED NODE   READINESS GATES
kube-system   calico-kube-controllers-76d48b6cf-b7lfj   1/1     Running   0          58m    10.1.200.179    k8s-node02     <none>           <none>
kube-system   calico-node-6xxnn                         1/1     Running   0          58m    10.1.200.189    k8s-master02   <none>           <none>
kube-system   calico-node-7q9jn                         1/1     Running   0          58m    10.1.200.188    k8s-master03   <none>           <none>
kube-system   calico-node-7wpbl                         1/1     Running   0          58m    10.1.200.190    k8s-master01   <none>           <none>
kube-system   calico-node-gbzdf                         1/1     Running   0          58m    10.1.200.179    k8s-node02     <none>           <none>
kube-system   calico-node-qz2cg                         1/1     Running   0          58m    10.1.200.180    k8s-node01     <none>           <none>
myserver      net-test1                                 1/1     Running   0          116s   172.20.85.193   k8s-node01     <none>           <none>
myserver      net-test2                                 1/1     Running   0          116s   172.20.58.193   k8s-node02     <none>           <none>
myserver      net-test3                                 1/1     Running   0          114s   172.20.85.194   k8s-node01     <none>           <none>

**Comment by gjmzj** [comment]
看下/etc/kubeasz/clusters/k8s-cluster01/hosts 文件内容

另外，默认的部署节点就是master01节点，这个注意下
