### ISSUE TITLE
版本对照

### ISSUE THREAD

**Issue by liuxinglan13** [easzlab/kubeasz#1311]
### What happened? 发生了什么问题？

![image](https://github.com/easzlab/kubeasz/assets/8065828/8b4ac91f-dbe8-412d-8864-cd0550c58b7d)
是不是我想装Kubernetes:1.26  就得使用对应的 kubeasz：3.5.3

还是说我也可以用 kubeasz：3.6.1 安装 Kubernetes:1.26

### What did you expect to happen? 期望的结果是什么？

1

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

1

### Kubernetes version k8s 版本

<details>

</details>
1

### Kubeasz version

<details>

</details>
1

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>
1

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
可以的，版本对照会更新一下
