### ISSUE TITLE
支持ipv6

### ISSUE THREAD

**Issue by diandiankou** [easzlab/kubeasz#1315]
### What happened? 发生了什么问题？

作者您好？请问目前kubeasz支持ipv6的计划吗？比如根据配置，搭建支持ipv4单栈，ipv6单栈，ipv6+ipv4双栈的集群，谢谢！

### What did you expect to happen? 期望的结果是什么？

无

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

无

### Kubernetes version k8s 版本

<details>

</details>

### Kubeasz version

<details>

</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
我理解k8s集群内部应用运行相对闭环的；无所谓ipv4或者ipv6；支持ipv6设置还挺麻烦的，感觉不值得这个投入

**Comment by diandiankou** [comment]
@gjmzj ，主要现在运营商大部分都在推行ipv6,有时候新的现场会有这个要求，目前别的同事拿着一些别的安装工具在魔改，但我还是更倾向使用kubeasz。

**Comment by 13567436138** [comment]
支持ipv6很重要啊
