### ISSUE TITLE
重启系统后swap分区依然存在

### ISSUE THREAD

**Issue by liu-yfeng** [easzlab/kubeasz#1317]
### What happened? 发生了什么问题？

重启系统后swap分区依然存在，导致 kubelet 无法启动，节点显示 NotReady

### What did you expect to happen? 期望的结果是什么？

需要使用 systemctl mask xxxx.swap 命令永久关闭 swap

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

需要使用 systemctl mask xxxx.swap 命令永久关闭 swap

### Kubernetes version k8s 版本

<details>
v1.28.1
</details>

### Kubeasz version

<details>
最新
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>
AlamLinux9.2

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by liu-yfeng** [comment]
找到swap分区
![image](https://github.com/easzlab/kubeasz/assets/8706840/f56600c6-4248-4fda-a2c3-98a9a1a19dd4)
禁止开机启动
systemctl mask dev-nvme0n1p4.swap
重启就不会有了

**Comment by gjmzj** [comment]
ok，我先把这个手动操作记录到 almalinux的安装文档
