### ISSUE TITLE
calico未能正常运行

### ISSUE THREAD

**Issue by Lu-Lucifer** [easzlab/kubeasz#1319]
### What happened? 发生了什么问题？

长时间在TASK [calico : 准备 calicoctl配置文件]，卡住了好一会

然后

TASK [calico : 轮询等待calico-node 运行] ***********************************************************************************************************************************************************************************************
fatal: [192.168.1.132]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' node-02 '|awk '{print $3}'", "delta": "0:00:00.190244", "end": "2023-10-08 14:40:02.358196", "msg": "", "rc": 0, "start": "2023-10-08 14:40:02.167952", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring
fatal: [192.168.1.133]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' node-01 '|awk '{print $3}'", "delta": "0:00:00.305475", "end": "2023-10-08 14:40:02.637498", "msg": "", "rc": 0, "start": "2023-10-08 14:40:02.332023", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring
fatal: [192.168.1.134]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' master-01 '|awk '{print $3}'", "delta": "0:00:00.280676", "end": "2023-10-08 14:40:03.254357", "msg": "", "rc": 0, "start": "2023-10-08 14:40:02.973681", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring

貌似是镜像拉取不下来

### What did you expect to happen? 期望的结果是什么？

希望能解决TASK [calico : 准备 calicoctl配置文件]，卡住的问题

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

按照文档进行安装集群，master，node-1，node-2，在TASK [calico : 准备 calicoctl配置文件]，卡住了，下一步就报错了

### Kubernetes version k8s 版本

<details>
1.28.1
</details>

### Kubeasz version

<details>
3.6.2
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by mushroomlb** [comment]
同样遇到了，重试15次后失败跳过

**Comment by Lu-Lucifer** [comment]
@mushroomlb 是images下载不下来，要配置个harbor

**Comment by fuckyourname** [comment]
TASK [calico : 准备 calicoctl配置文件] *******************************************************************************************************************************************************************************************************************************
ok: [192.168.0.12]
ok: [192.168.0.11]
ok: [192.168.0.14]
ok: [192.168.0.13]
ok: [192.168.0.15]
ok: [192.168.0.16]
FAILED - RETRYING: 轮询等待calico-node 运行 (15 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (15 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (15 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (15 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (15 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (14 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (14 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (14 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (14 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (14 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (13 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (13 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (13 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (13 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (13 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (12 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (12 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (12 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (12 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (12 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (11 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (11 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (11 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (11 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (11 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (10 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (10 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (10 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (10 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (10 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (9 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (9 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (9 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (9 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (9 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (8 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (8 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (8 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (8 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (8 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (7 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (7 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (7 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (7 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (7 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (6 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (6 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (6 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (6 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (6 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (5 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (5 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (5 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (5 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (5 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (4 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (4 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (4 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (4 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (4 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (3 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (3 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (3 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (3 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (3 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (2 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (2 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (2 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (2 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (2 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (1 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (1 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (1 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (1 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (1 retries left).

TASK [calico : 轮询等待calico-node 运行] *****************************************************************************************************************************************************************************************************************************
fatal: [192.168.0.13]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' master3 '|awk '{print $3}'", "delta": "0:00:00.067300", "end": "2025-04-21 23:00:14.133906", "rc": 0, "start": "2025-04-21 23:00:14.066606", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring
fatal: [192.168.0.15]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' node2 '|awk '{print $3}'", "delta": "0:00:00.066401", "end": "2025-04-21 23:00:14.292029", "rc": 0, "start": "2025-04-21 23:00:14.225628", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring
FAILED - RETRYING: 轮询等待calico-node 运行 (15 retries left).
fatal: [192.168.0.11]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' master1 '|awk '{print $3}'", "delta": "0:00:00.080189", "end": "2025-04-21 23:00:14.579416", "rc": 0, "start": "2025-04-21 23:00:14.499227", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring
fatal: [192.168.0.12]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' master2 '|awk '{print $3}'", "delta": "0:00:00.082298", "end": "2025-04-21 23:00:14.589593", "rc": 0, "start": "2025-04-21 23:00:14.507295", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring
fatal: [192.168.0.14]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' node1 '|awk '{print $3}'", "delta": "0:00:00.072156", "end": "2025-04-21 23:00:14.713640", "rc": 0, "start": "2025-04-21 23:00:14.641484", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring
FAILED - RETRYING: 轮询等待calico-node 运行 (14 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (13 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (12 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (11 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (10 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (9 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (8 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (7 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (6 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (5 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (4 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (3 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (2 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行 (1 retries left).
fatal: [192.168.0.16]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/etc/kubeasz/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' node3 '|awk '{print $3}'", "delta": "0:00:00.067090", "end": "2025-04-21 23:04:02.025115", "rc": 0, "start": "2025-04-21 23:04:01.958025", "stderr": "", "stderr_lines": [], "stdout": "Init:0/2", "stdout_lines": ["Init:0/2"]}
...ignoring

PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************



**### 3.6.3版本，安装1.29.0版k8s，这是我执行第6步报错了，试了好几次，不知道为什么，太难受了，前面5步都完事了**


root@master1:/etc/kubeasz# kubectl get pods -A
NAMESPACE     NAME                                         READY   STATUS              RESTARTS   AGE
kube-system   calico-kube-controllers-5994f46b69-r8t6j     0/1     ContainerCreating   0          48m
kube-system   calico-node-29jt8                            0/1     Init:0/2            0          48m
kube-system   calico-node-2dtnp                            0/1     Init:0/2            0          48m
kube-system   calico-node-46x55                            0/1     Init:0/2            0          48m
kube-system   calico-node-4sssr                            0/1     Init:0/2            0          48m
kube-system   calico-node-ksthv                            0/1     Init:0/2            0          48m
kube-system   calico-node-tkwvx                            0/1     Init:0/2            0          48m
kube-system   coredns-6db9bd4cd7-5fwgx                     0/1     ContainerCreating   0          18m
kube-system   dashboard-metrics-scraper-77b667b99d-p5g6v   0/1     ContainerCreating   0          18m
kube-system   kubernetes-dashboard-74fb9f77fb-rmwrk        0/1     ContainerCreating   0          18m
kube-system   metrics-server-dfb478476-bskf6               0/1     ContainerCreating   0          18m
kube-system   node-local-dns-28fn9                         0/1     ContainerCreating   0          18m
kube-system   node-local-dns-hvcfr                         0/1     ContainerCreating   0          18m
kube-system   node-local-dns-rs6xj                         0/1     ContainerCreating   0          18m
kube-system   node-local-dns-vctdk                         0/1     ContainerCreating   0          18m
kube-system   node-local-dns-z44j8                         0/1     ContainerCreating   0          18m
kube-system   node-local-dns-z5fm6                         0/1     ContainerCreating   0          18m

**Comment by Lu-Lucifer** [comment]
@fuckyourname image拉取不下来
