### ISSUE TITLE
v3.6.2 containerd无法启动成功

### ISSUE THREAD

**Issue by lexue100** [easzlab/kubeasz#1320]
### What happened? 发生了什么问题？

环境：操作系统：centos-7.9 ，内核：5.4，选择k8s版本：v1.28.1
异常：执行dk ezctl setup xports 04 ，显示containerd轮询启动失败
<img width="1190" alt="image" src="https://github.com/easzlab/kubeasz/assets/20296880/27003246-0305-4b0c-bb06-f891a6902dfe">
<img width="1163" alt="image" src="https://github.com/easzlab/kubeasz/assets/20296880/8fb7b431-f874-425e-9053-258707ad5f99">

### What did you expect to happen? 期望的结果是什么？

请帮忙看下解决方案

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

.

### Anything else we need to know? 其他需要说明的情况

无

### Kubernetes version k8s 版本

<details>

</details>

### Kubeasz version

<details>

</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by lexue100** [comment]
<img width="1168" alt="image" src="https://github.com/easzlab/kubeasz/assets/20296880/a8b7b938-2935-467f-b6a2-63eb34dbed2b">

**Comment by gjmzj** [comment]
提示网络插件没有安装，按正常的流程在kubelet启动时会有一个默认的网络插件安装的；
