### ISSUE TITLE
关于节点IP网段更换后的最佳实践

### ISSUE THREAD

**Issue by lzd-1230** [easzlab/kubeasz#1323]
想问一下当使用kubeasz进行3节点集群部署
- 192.168.1.1(master)
- 192.168.1.2
- 192.168.1.3
突然需要更换所有主机的网段 -> 10.16.xx.xx/16 的网段 IP, 是否可以使用 `kubeasz` 的功能进行修改。
我尝试着将 kubelet, kube-proxy, etcd 等等的 `systemd`配置文件全部更新IP, 但是目前仍然服务器仍未恢复
- systemctl status etcd
  ```
  Oct 17 01:56:55 k8s-node1 etcd[818]: rejected connection from "10.16.28.113:56640" (error "remote error: tls: bad certificate", ServerName "")
  ```
- kubelet
  ```
  Oct 17 01:58:47 k8s-node1 kubelet[900]: E1017 01:58:47.842009     900 kubelet.go:2243] node "10.16.28.113" not found
  ```
- controller-manager
  ```
  "https://10.16.28.113:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=10s": dial tcp 10.16.28.113:6443: connect: connection refused
  ```
- apiserver服务无法启动
  ```
  Err :connection error: desc = "transport: Error while dialing dial tcp 10.16.45.24:2379: connect: connection refused
  ```
我不太清楚 kubeasz 是否已经有了更广泛使用的更换节点 IP 之后服务自动恢复最佳实践, 还是说我需要重新安装集群更加快速？

**Comment by lzd-1230** [comment]
直接使用`ezctl destroy <cluster>`之后，修改/etc/kubeasz/cluster/<cluster>/hosts 文件
然后运行 `ezctl new <cluster-name>` 进行重建的效果最佳, 并且快速。

**Comment by lzd-1230** [comment]
首先修改`/etc/kubeasz/cluster/<cluster-name>/hosts`文件, 重新写入现在主机的ip
使用 `ezctl destroy <cluster-name>`完成集群组建的销毁
然后再次重建`ezctl new <cluster-name> && ezctl setup <cluster-name> all`

**Comment by yogaxu** [comment]
[更优解](https://blog.csdn.net/wen328/article/details/121009302)
