### ISSUE TITLE
arm架构的适配进展

### ISSUE THREAD

**Issue by Teo90** [easzlab/kubeasz#1328]
### What would you like to be added?

作者开发的这么好的工具是否已根据国内国情做了ARM架构的适配计划，请问计划进展如何能否告知。

### Why is this needed?

中国政企都在加速国产化的研发，未来必然是百花齐放的态，国内这块项目也不少。比如龙芯、ARM等架构。

**Comment by gjmzj** [comment]
目前已经支持ARM架构的，arm64；不过需要部署机，所有节点都是arm64架构；不支持arm64和amd64混合部署

**Comment by Teo90** [comment]
不需要其他配置即可适配是吧。只要都是arm的架构

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
