### ISSUE TITLE
kubeasz version3.6.2

### ISSUE THREAD

**Issue by bangyongfeng** [easzlab/kubeasz#1329]
### What happened? 发生了什么问题？

kubeasz version3.6.2 [AllinOne部署](https://github.com/easzlab/kubeasz/blob/master/docs/setup/quickStart.md) 后，集群正常，但是集群中没有 kubeadm命令。这是正常的吗？
[root@localhost ~]# kubeadm
-bash: kubeadm: command not found

### What did you expect to happen? 期望的结果是什么？

希望有kubadm命令

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

null

### Kubernetes version k8s 版本

<details>
v1.26
</details>

### Kubeasz version

<details>
3.6.2
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
centos7.9
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
项目不依赖kubeadm，是属于二进制模式安装，两种安装模式
