### ISSUE TITLE
online  local-path-storage报错

### ISSUE THREAD

**Issue by khan-ai** [easzlab/kubeasz#1331]
### What would you like to be added?

报错内容如下

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/etc/kubeasz/bin/kubectl apply -f /etc/kubeasz/clusters/k8s-01/yml/local-storage/local-path-storage.yaml", "delta": "0:00:02.337174", "end": "2023tart": "2023-11-15 17:17:38.845114", "stderr": "Error from server: error when creating \"/etc/kubeasz/clusters/k8s-01/yml/local-storage/local-path-storage.yaml\": rpc error: code = Unavailable desc = err03:2379: read: connection reset by peer\nError from server: error when retrieving current configuration of:\nResource: \"rbac.authorization.k8s.io/v1, Resource=clusterrolebindings\", GroupVersionKind: \"cal-path-provisioner-bind\", Namespace: \"\"\nfrom server for: \"/etc/kubeasz/clusters/k8s-01/yml/local-storage/local-path-storage.yaml\": rpc error: code = Unavailable desc = error reading from server: n reset by peer", "stderr_lines": ["Error from server: error when creating \"/etc/kubeasz/clusters/k8s-01/yml/local-storage/local-path-storage.yaml\": rpc error: code = Unavailable desc = error reading fd: connection reset by peer", "Error from server: error when retrieving current configuration of:", "Resource: \"rbac.authorization.k8s.io/v1, Resource=clusterrolebindings\", GroupVersionKind: \"rbac.autth-provisioner-bind\", Namespace: \"\"", "from server for: \"/etc/kubeasz/clusters/k8s-01/yml/local-storage/local-path-storage.yaml\": rpc error: code = Unavailable desc = error reading from server: readset by peer"], "stdout": "clusterrole.rbac.authorization.k8s.io/local-path-provisioner-role created\ndeployment.apps/local-path-provisioner created\nstorageclass.storage.k8s.io/local-path created\nconfigauthorization.k8s.io/local-path-provisioner-role created", "deployment.apps/local-path-provisioner created", "storageclass.storage.k8s.io/local-path created", "configmap/local-path-config created"]}

### Why is this needed?

有人遇到同样问题吗？希望指点一二。

**Comment by gjmzj** [comment]
apiserver没有正常运行
或者执行命令节点与master节点网络不通
