### ISSUE TITLE
ubuntu 22.04 开启系统加固后k8s pod之间网络不同

### ISSUE THREAD

**Issue by richzhu369** [easzlab/kubeasz#1338]
### What happened? 发生了什么问题？

我使用最新版的 v3.6.2 ，安装集群进行配置时，更改了数据默认目录和开启了系统加固，安装好集群后 pod之间无法通讯

### What did you expect to happen? 期望的结果是什么？

可以放心开启系统加固功能

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

使用ubuntu 22.04 关闭 apparmor 和开启 apparmor 都可以，安装必复现，我删了装 装了删，好几次都一样的问题

### Kubernetes version k8s 版本

<details>
k8s 1.28.1
</details>

### Kubeasz version

<details>
v3.6.2
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux aws-hk-all-pro-front-k8s-master01 6.2.0-1016-aws #16~22.04.1-Ubuntu SMP Sun Nov  5 20:08:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>
containerd, calico
</details>

**Comment by gjmzj** [comment]
不建议开启os-harden，没有更新上游项目，没有测试最近几个k8s版本的集群安装；已更新文档说明

**Comment by chenpx0128** [comment]
**centsos7安装集群开启kube-proxy安装就失败。如果不安装kube-proxy可以安装成功，但是pod的nodeport端口只能是pod所在的k8s节点才能访问，其他k8s节点ip加nodeport端口无法访问。**
<img width="1086" alt="11111" src="https://github.com/easzlab/kubeasz/assets/67548015/1c5d599f-2b01-494c-bcea-471c4ff17e22">
<img width="1724" alt="2222" src="https://github.com/easzlab/kubeasz/assets/67548015/6b3c5b29-4b13-429e-bb68-acda56e1a317">
