### ISSUE TITLE
无法修改kubeasz workspace 目录

### ISSUE THREAD

**Issue by richzhu369** [easzlab/kubeasz#1342]
### What happened? 发生了什么问题？

我把除了 ca_dir 以外的值都改了，但是发现当我修改 base_dir的时候，无法进行安装：
修改的值为：
![image](https://github.com/easzlab/kubeasz/assets/152697677/63aec8d1-a39d-4518-8f92-f33fe6c205df)

安装时候的报错为：
![image](https://github.com/easzlab/kubeasz/assets/152697677/546ead2f-0b24-4ac6-aa44-2221084c4ad8)
![image](https://github.com/easzlab/kubeasz/assets/152697677/f543e1d3-c41a-48a3-bf76-7c36732b7e6c)

我看了下，这个的原因好像是因为你们在 ezdown中已经写死了一个值，变量名字为 BASE，可以通过 vim ezdown来看到这个BASE值

但是当我修改了 ezdown中的BASE值后，还是会有一些奇怪的报错

### What did you expect to happen? 期望的结果是什么？

修改 kubeasz workspace的值，来指定kubeasz的工作目录

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

只要是3.6.3版本，必现，其他版本没测

### Kubernetes version k8s 版本

<details>
1.29.0
</details>

### Kubeasz version

<details>
3.6.3
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
# Linux zy-tw-ph-pro-ops-k8s-kubespray 5.4.201-1.el7.elrepo.x86_64 #1 SMP Fri Jun 24 08:59:49 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>
calico
</details>

**Comment by gjmzj** [comment]
是的，目前不支持修改；有很多地方需要调整；一个目录而已，如果没有特别的原因就不必纠结了
