### ISSUE TITLE
在 A 机器上访问正常，在 B 机器上访问得到 401

### ISSUE THREAD

**Issue by isshe** [easzlab/kubeasz#1344]
你好，

我用这个安装了一个单节点的 k8s 环境，在 A 机器上访问正常，在 B 机器上访问得到 401，请问知道是什么原因吗？

机器 A 和 k8s 环境在同一个内网。
机器 B 和 k8s 环境不在一个内网，但是使用 wireguard 进行连接了。

返回的 401 结果如下：

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

谢谢。

**Comment by gjmzj** [comment]
补充一些信息，怎么配置的，怎么执行命令的。。。

**Comment by isshe** [comment]
系统是 centos 7，就是按照这个快速指南来安装的：https://github.com/easzlab/kubeasz/blob/master/docs/setup/quickStart.md

```
./ezdown -D
./ezdown -S
docker exec -it kubeasz ezctl start-aio
```

同一内网的其他机器可以访问，但是外部机器通过 wireguard 访问则不行。（外部机器通过 wireguard 可以访问内网所以机器。）
