### ISSUE TITLE
3.6.3版本使用cilium网络插件开启hubble时下载镜像失败

### ISSUE THREAD

**Issue by wuganzhi** [easzlab/kubeasz#1347]
### What happened? 发生了什么问题？

使用了3.6.3版本进行的k8s集群安装，网络插件使用cilium，开启了hubble。其他参数默认。
集群安装完毕以后 kubectl get pod -A发现hubble-ui这个pod拉取镜像错误：
 Warning  Failed     12m                  kubelet            Error: ErrImagePull
  Warning  Failed     11m (x2 over 12m)    kubelet            Error: ImagePullBackOff
  Normal   BackOff    11m (x2 over 12m)    kubelet            Back-off pulling image "easzlab.io.local:5000/cilium/hubble-ui-backend:v0.12.1@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe"
  Warning  Failed     11m (x2 over 12m)    kubelet            Error: ImagePullBackOff
  Normal   Pulling    11m (x3 over 12m)    kubelet            Pulling image "easzlab.io.local:5000/cilium/hubble-ui:v0.12.1@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267"
  Warning  Failed     11m (x3 over 12m)    kubelet            Failed to pull image "easzlab.io.local:5000/cilium/hubble-ui:v0.12.1@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267": rpc error: code = NotFound desc = failed to pull and unpack image "easzlab.io.local:5000/cilium/hubble-ui@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267": failed to resolve reference "easzlab.io.local:5000/cilium/hubble-ui@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267": easzlab.io.local:5000/cilium/hubble-ui@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267: not found
  Warning  Failed     11m (x3 over 12m)    kubelet            Error: ErrImagePull
  Normal   Pulling    11m (x3 over 12m)    kubelet            Pulling image "easzlab.io.local:5000/cilium/hubble-ui-backend:v0.12.1@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe"
  Warning  Failed     11m (x3 over 12m)    kubelet            Failed to pull image "easzlab.io.local:5000/cilium/hubble-ui-backend:v0.12.1@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe": rpc error: code = NotFound desc = failed to pull and unpack image "easzlab.io.local:5000/cilium/hubble-ui-backend@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe": failed to resolve reference "easzlab.io.local:5000/cilium/hubble-ui-backend@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe": easzlab.io.local:5000/cilium/hubble-ui-backend@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe: not found
  Normal   BackOff    2m1s (x43 over 12m)  kubelet            Back-off pulling image "easzlab.io.local:5000/cilium/hubble-ui:v0.12.1@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267"

通过kubectl edit 编辑pod的镜像，删除@后面的值以后pod拉取成功，该问题试了两会都出现了。

### What did you expect to happen? 期望的结果是什么？

pod正常运行

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

使用3.6.3版本安装k8s，选择cilium作为网络插件，开启hubble

### Kubernetes version k8s 版本

<details>
1.26.12、1.29.0
</details>

### Kubeasz version

<details>
3.6.3
</details>

### OS version 操作系统版本

<details>
openEuler 23.09
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>
cilium
</details>

**Comment by gjmzj** [comment]
确实是有个bug，之前我也遇到了，并且3.6.3发布以后已经有commit 修复改问题，详见 21376465de7f44d1ec997bde096afc7404ce45c5

**Comment by wuganzhi** [comment]
关了
