### ISSUE TITLE
prometheus的持久化存储

### ISSUE THREAD

**Issue by LiTeng51** [easzlab/kubeasz#1349]
### What happened? 发生了什么问题？

在哪里可以修改prometheus的持久化存储为nfs

### What did you expect to happen? 期望的结果是什么？

修改prometheus的持久化存储为nfs

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

修改prometheus的持久化存储为nfs

### Kubernetes version k8s 版本

<details>
3.6.2
</details>

### Kubeasz version

<details>
1.28.1
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux proxy 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by gjmzj** [comment]
查看它的helm chart 配置，chart文件在roles/cluster-addon/files/kube-prometheus-stack-xx.xx.xx.tgz

然后对应修改下clusters/xxxx/yml/prom-values.yaml

**Comment by LiTeng51** [comment]
> 查看它的helm chart 配置，chart文件在roles/cluster-addon/files/kube-prometheus-stack-xx.xx.xx.tgz
> 
> 然后对应修改下clusters/xxxx/yml/prom-values.yaml
1.修改 /etc/kubeasz/clusters/xxxx/config.yml 中配置项 prom_install: "yes"
2.下载镜像 /etc/kubeasz/ezdown -X prometheus
3.安装 /etc/kubeasz/ezctl setup xxxx 07
生成的charts自定义配置在/etc/kubeasz/clusters/xxxx/yml/prom-values.yaml

根据教程进行安装时，并没有生成prom-values.yaml文件

**Comment by gjmzj** [comment]
> > 查看它的helm chart 配置，chart文件在roles/cluster-addon/files/kube-prometheus-stack-xx.xx.xx.tgz
> > 然后对应修改下clusters/xxxx/yml/prom-values.yaml
> 
> 1.修改 /etc/kubeasz/clusters/xxxx/config.yml 中配置项 prom_install: "yes" 2.下载镜像 /etc/kubeasz/ezdown -X prometheus 3.安装 /etc/kubeasz/ezctl setup xxxx 07 生成的charts自定义配置在/etc/kubeasz/clusters/xxxx/yml/prom-values.yaml 根据教程进行安装时，不执行第三项，会生成prom-values.yaml文件吗

不会

**Comment by LiTeng51** [comment]
> > > 查看它的helm chart 配置，chart文件在roles/cluster-addon/files/kube-prometheus-stack-xx.xx.xx.tgz
> > > 然后对应修改下clusters/xxxx/yml/prom-values.yaml
> > 
> > 
> > 1.修改 /etc/kubeasz/clusters/xxxx/config.yml 中配置项 prom_install: "yes" 2.下载镜像 /etc/kubeasz/ezdown -X prometheus 3.安装 /etc/kubeasz/ezctl setup xxxx 07 生成的charts自定义配置在/etc/kubeasz/clusters/xxxx/yml/prom-values.yaml 根据教程进行安装时，不执行第三项，会生成prom-values.yaml文件吗
> 
> 不会


我要先安装prometheus后，再进行修改它的持久化存储吗？
因为不安装，无法生成修改这个prom-values.yaml文件

**Comment by LiTeng51** [comment]
> > > 查看它的helm chart 配置，chart文件在roles/cluster-addon/files/kube-prometheus-stack-xx.xx.xx.tgz
> > > 然后对应修改下clusters/xxxx/yml/prom-values.yaml
> > 
> > 
> > 1.修改 /etc/kubeasz/clusters/xxxx/config.yml 中配置项 prom_install: "yes" 2.下载镜像 /etc/kubeasz/ezdown -X prometheus 3.安装 /etc/kubeasz/ezctl setup xxxx 07 生成的charts自定义配置在/etc/kubeasz/clusters/xxxx/yml/prom-values.yaml 根据教程进行安装时，不执行第三项，会生成prom-values.yaml文件吗
> 
> 不会


请问有没有修改持久化存储的安装指南

**Comment by gjmzj** [comment]
把 roles/cluster-addon/files/kube-prometheus-stack-xx.xx.xx.tgz 解压出来，然后进去解压后目录看到里面有个 values.yaml配置下，你看看，里面有持久化存储安装的配置，然后对应修改到prom-values.yaml文件里面就可以了；

helm 安装就是这个套路啊
