### ISSUE TITLE
添加Longhorn使用镜像和依赖包

### ISSUE THREAD

**Issue by wxh512** [easzlab/kubeasz#1356]
### What would you like to be added?

现在的k8s没有对Longhorn的分布式存储，会导致work很多资源浪费

### Why is this needed?

1、需要yum apt-get install open-iscsi  # Debian 和 Ubuntu 系统命令 centos需要 yum install -y iscsi-initiator-utils 不能离线安装
2、需要Longhorn镜像以及yaml文件
3、Longhorn性能要远超nfs-client-provisioner提供的存储性能（2-3倍）

**Comment by gjmzj** [comment]
感谢推荐，需要花点时间集成到kubeasz里面
