### ISSUE TITLE
安装Prometheus 安装不上

### ISSUE THREAD

**Issue by junnl** [easzlab/kubeasz#1372]
### What happened? 发生了什么问题？

按照教程下载后改了配置文件
dk ezctl setup k8s-01 07

TASK [cluster-addon : helm 创建 kube-prometheus-stack 45.23.0] **************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/etc/kubeasz/bin/helm upgrade prometheus --install -n monitor -f /etc/kubeasz/clusters/k8s-01/yml/prom-values.yaml /etc/kubeasz/roles/cluster-addon/files/kube-prometheus-stack-45.23.0.tgz", "delta": "0:00:04.544547", "end": "2024-04-11 13:14:01.501360", "msg": "non-zero return code", "rc": 1, "start": "2024-04-11 13:13:56.956813", "stderr": "Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress", "stderr_lines": ["Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress"], "stdout": "", "stdout_lines": []}

### What did you expect to happen? 期望的结果是什么？

不知道怎么解决这个问题

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

安装完集群后，安装Prometheus，dk ezctl setup k8s-01 07 这一步之后，一直报错

### Kubernetes version k8s 版本

<details>

*   kubernetes: v1.29.0
*   etcd: v3.5.10
*   calico: v3.26.4

</details>

### Kubeasz version

<details>
DOCKER_VER=24.0.7
KUBEASZ_VER=3.6.3
K8S_BIN_VER=v1.29.0

</details>

### OS version 操作系统版本

<details>

CentOS Linux 7 (Core)
Linux node-1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by flichote** [comment]
when  I use  yum -y install ansible. it is  ok!
