### ISSUE TITLE
kube-flannel 资源限制优化问题

### ISSUE THREAD

**Issue by Auggie321** [easzlab/kubeasz#1377]
### What would you like to be added?

在环境使用老版本部署工具 kubeasz 2.1.0 的时候，经过历史的实践和教训，会持续迭代 kubeasz 2.1.0 部署工具。发现了一些小问题，比如kube-system svc kubernetes-dashboard 和 traefik-ingress-service nodeport直接改为clusterIP默认端口安全会更加省心一些。在编辑configmap coredns的时候，coredns副本默认从2改为1，编辑的时候在重启就更加方便。遇到了flannel oom的问题，在服务器网络负载/iptables规则条数较高的时候，flannel默认消耗的内存就会更多一些。这个部分当然也可以edit ds 限制，或者自行编辑 kube-flannel.yaml.j2 设置。flannel oom的问题，比较隐晦，一般服务量起来了，就无法避免。

### Why is this needed?

https://github.com/flannel-io/flannel/pull/1694
https://github.com/flannel-io/flannel/issues/1415
https://github.com/rancher/rancher/issues/40228

基于一些问题，flannel官方已经去掉了ds资源的限制，建议这块kubeasz也可以考虑的。kubeasz挺好用的，希望越办越好，个人建议，仅供参考。

**Comment by gjmzj** [comment]
确实，flannel组件简单易用，ds资源限制就参考flannel官网文档；

我觉得kubeasz这个工具的最大的优势在于易于理解组件交互过程，这样即便有点问题，很快能找到原因去排除
