### ISSUE TITLE
easzlab image repo is down

### ISSUE THREAD

**Issue by whsasf** [easzlab/kubeasz#1378]
### What happened? 发生了什么问题？

easzlab image repo is down

**error pulling image configuration: download failed after attempts=6: dial tcp 124.11.210.175:443: connect: connection refused**

### What did you expect to happen? 期望的结果是什么？

pull success

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

./ezdown -D

### Kubernetes version k8s 版本

<details>

</details>

### Kubeasz version

3.6.4

### OS version 操作系统版本

ubuntu22.04

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by Hello-Linux** [comment]
@whsasf  目前docker hub镜像国内已经被限流了，耐心等待国内镜像同步

**Comment by freshgeek** [comment]
我特意在国外aws ec2上面试了下也很慢，使用的是：./ezdown -D -m standard

**Comment by freshgeek** [comment]
<img width="1403" alt="image" src="https://github.com/easzlab/kubeasz/assets/20513615/b443b30f-47a5-445a-af26-41ce7590534c">


下面卡着不动，上面下载 docker 都0.5s搞定 138M/s

**Comment by freshgeek** [comment]
https://github.com/docker/hub-feedback/issues/2390 也许我的是因为这个
