### ISSUE TITLE
etcd : 创建etcd证书请求报错

### ISSUE THREAD

**Issue by zv246** [easzlab/kubeasz#1379]
### What happened? 发生了什么问题？

TASK [etcd : 创建etcd证书请求]报错 ***************************************************************************************************************************
fatal: [192.168.44.10]: FAILED! => {"msg": "Failed to get information on remote file (/etc/kubeasz/clusters/default/ssl/etcd-csr.json): /bin/sh: /usr/bin/python2.7: not found\n"}

### What did you expect to happen? 期望的结果是什么？

成功创建

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

执行docker exec -it kubeasz ezctl start-aio部署报错，没有etcd-csr.json文件。

### Anything else we need to know? 其他需要说明的情况
低版本好像都有这个问题，我试过3.1.1和3.5.0都报错同样的问题

### Kubernetes version k8s 版本

v1.22.2

### Kubeasz version

3.1.1

### OS version 操作系统版本

  Operating System: Anolis OS 8.9
            Kernel: Linux 5.10.134-16.3.an8.x86_64
      Architecture: x86-64

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by zv246** [comment]
可以把所需镜像拿取到国内仓库吗？目前dockerhub已经封禁完了，所有云服务商加速器都失效了

**Comment by Hello-Linux** [comment]
@zv246 你好我们这边看了一下，dockerhub针对easzlab下的镜像确实全部封禁了，后面我们这里会通知作者 @gjmzj @jmgao1983  同步更新到国内镜像仓库，感谢您的及时反馈，其次您可以暂时使用国内的代理地址进行镜像的拉取，命令模板如下所示。
```
docker pull docker.m.daocloud.io/easzlab/kubeasz:3.6.3
```
之后重新对镜像打tag为原来的镜像名称即可正常使用

**Comment by zv246** [comment]
> @zv246 你好我们这边看了一下，目前docker hub镜像国内已经被限流了，等待限流解除，后续考虑使用国内镜像仓库。感谢您的及时反馈，其次您可以暂时使用国内的代理地址进行镜像的拉取，命令模板如下所示。
> ```
> docker pull docker.m.daocloud.io/easzlab/kubeasz:3.6.3
> ```
> 之后重新对镜像打tag为原来的镜像名称即可正常使用

好的，感谢！

**Comment by zv246** [comment]
> @zv246 你好我们这边看了一下，目前docker hub镜像国内已经被限流了，等待限流解除，后续考虑使用国内镜像仓库。感谢您的及时反馈，其次您可以暂时使用国内的代理地址进行镜像的拉取，命令模板如下所示。
> ```
> docker pull docker.m.daocloud.io/easzlab/kubeasz:3.6.3
> ```
> 之后重新对镜像打tag为原来的镜像名称即可正常使用

低版本部署到我试过3.1.1和3.5.0，TASK [etcd : 创建etcd证书请求]时会报错。没有etcd-csr.json文件。我试着手动创建这个手机也会报错，我用到系统是龙蜥8.6。使用容器执行的，麻烦大佬看看呀

**Comment by zv246** [comment]
> @zv246 你好我们这边看了一下，目前docker hub镜像国内已经被限流了，等待限流解除，后续考虑使用国内镜像仓库。感谢您的及时反馈，其次您可以暂时使用国内的代理地址进行镜像的拉取，命令模板如下所示。
> ```
> docker pull docker.m.daocloud.io/easzlab/kubeasz:3.6.3
> ```
> 之后重新对镜像打tag为原来的镜像名称即可正常使用

大佬，低版本在执行到TASK [etcd : 创建etcd证书请求]时会报错，没有etcd-csr.json文件。这个问题麻烦您看一下呀。
我试过3.1.1和3.5.0都有这个问题。

**Comment by Hello-Linux** [comment]
根据你的报错可能是因为ansible识别节点的python的路径有问题，您可以手动配置一下python解释器变量的路径，下面是两种解决方法，你这边尝试看看是否可以修复这个问题

01 在ansible的hosts文件(/etc/kubeasz/clusters/集群名称路径下)，修改ansible_python_interpreter="节点的python解释器路径"。

02 或者针对本地的python解释器添加一个软连接到路径/usr/bin/python2.7，让ansible可以找到python正确的路径。
