### ISSUE TITLE
easzlab.io.local:5000 can't access

### ISSUE THREAD

**Issue by Hexiaopi** [easzlab/kubeasz#1384]
### What happened? 发生了什么问题？

Back-off pulling image "easzlab.io.local:5000/calico/cni:v3.26.4"

### What did you expect to happen? 期望的结果是什么？

pod running

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

docker pull easzlab.io.local:5000/calico/cni:v3.26.4
Error response from daemon: Get "https://easzlab.io.local:5000/v2/": EOF

### Kubernetes version k8s 版本

<details>
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1
</details>

### Kubeasz version

<details>
3.6.4
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by 457352727** [comment]
你好，我也碰到了这个问题，找到解决办法了不

**Comment by kevinniu666** [comment]
我也遇到这个问题了，使用的是离线的方式。K8S版本1.26.15，ezdown版本3.6.2,看起来是:5000的端口没有起

**Comment by kevinniu666** [comment]
看了一下源码，这个registry的服务是在./ezdown -D的时候启动的，我的环境是先在本地下载了以后再上传到服务器的。所以到了新的环境，这个服务在管理节点就没有启动了。解决这个问题只需要在运行Kubeasz的节点再执行一下./ezdown -D就会启动registry的容器并将5000端口host到宿主机上。

**Comment by y1li0** [comment]
是否配置了docker代理？我这边发生了同样的问题，首先是无法获取镜像，通过配置了docker代理，解决了镜像的问题。但随之而来的是无法推送到registry:5000，通过修改代理除外规则解决了推送的问题。
修改docker代理设置
`vi /etc/systemd/system/docker.service.d/http-proxy.conf`
代理使用的clash
![image](https://github.com/user-attachments/assets/a067d0e6-1fe6-4b19-9ab2-52849443b66b)
`[Service]
Environment="HTTP_PROXY=192.168.1.4:7890"
Environment="HTTPS_PROXY=192.168.1.4:7890"
Environment="NO_PROXY=localhost,127.0.0.1,easzlab.io.local"`
重启docker服务
`systemctl daemon-reload
systemctl restart docker`

**Comment by leeonfu** [comment]
HI, consider the issue is a feature, fix it by automatic

**Comment by zhangyichen534** [comment]
vpn关了就可以了

**Comment by ZEDEZR** [comment]
得先./ezdown -S
