### ISSUE TITLE
执行 ./ezdown -D后无法下载easzlab/kubeasz:3.6.1

### ISSUE THREAD

**Issue by EVE-Molok** [easzlab/kubeasz#1385]
### What happened? 发生了什么问题？

[root@vm-1718177269 kubeasz-3.6.1]# ./ezdown -D
2024-06-22 18:38:16 INFO Action begin: download_all
2024-06-22 18:38:16 WARN docker binaries already existed
2024-06-22 18:38:19 WARN docker is already running.
2024-06-22 18:38:19 INFO downloading kubeasz: 3.6.1
3.6.1: Pulling from easzlab/kubeasz
f56be85fc22e: Retrying in 1 second 
ea5757f4b3f8: Retrying in 1 second 
bd0557c686d8: Retrying in 1 second 
37d4153ce1d0: Retrying in 1 second 
b39eb9b4269d: Retrying in 1 second 
a3cff94972c7: Retrying in 1 second 
4f7f893dc9cc: Retrying in 1 second 
error pulling image configuration: download failed after attempts=6: dial tcp 202.53.137.209:443: i/o timeout
2024-06-22 18:41:32 DEBUG  run a temporary container
Unable to find image 'easzlab/kubeasz:3.6.1' locally
3.6.1: Pulling from easzlab/kubeasz
f56be85fc22e: Retrying in 1 second 
ea5757f4b3f8: Retrying in 1 second 
bd0557c686d8: Retrying in 1 second 
37d4153ce1d0: Retrying in 1 second 
b39eb9b4269d: Retrying in 1 second 
a3cff94972c7: Retrying in 1 second 
4f7f893dc9cc: Retrying in 1 second 
docker: error pulling image configuration: download failed after attempts=6: dial tcp 31.13.94.36:443: i/o timeout.
See 'docker run --help'.
2024-06-22 18:44:44 ERROR failed.

### What did you expect to happen? 期望的结果是什么？

此时根据脚本里面的命令，应该是docker pull easzlab/kubeasz:3.6.1命令（版本为变量），但无法下载

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

我尝试更换了其他的镜像仓库也无济于事

### Kubernetes version k8s 版本

<details>
1.30和1.27我都尝试了
</details>

### Kubeasz version

<details>
3.6.1和最新版3.6.4我都尝试过，均无法下载
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
Linux vm-1718177269.06.novalocal 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
centos7.6版本
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by newfzk** [comment]
我也想知道，在目前国内大部分镜像站都关闭的情况下，如何方便的下载镜像，求大神告知，感谢

**Comment by caozhengyx** [comment]
国内的docker镜像加速都没用了，目前只能通过梯子代理下载了。

**Comment by newfzk** [comment]
好工具分享： https://github.com/wukongdaily/DockerTarBuilder

各位可以fork这个项目，借助github action，完成镜像离线包的下载

**Comment by ffxgamer** [comment]
其实可以给个 option来增加docker-mirror的地址,现在的-m只能用来配置是不是CN以决定下载docker安装包的地址而已.如果作者不改的话,我建议各位自己修改ezdown这个bash脚本,替换daemon.json里的docker-mirror的部分即可.

**Comment by Hello-Linux** [comment]
@EVE-Molok 你好，目前中国已经无法使用dockerhub，我们后期会考虑将镜像同步至国内镜像仓库，同时这里给出以下几种解决办法

    从网上寻找可以继续使用的docker镜像加速地址进行尝试
    使用github action进行镜像转接至国内镜像仓库比如阿里云
    终极大招： 自己有梯子的话，配置docker 代理使用梯子，快速拉取docker镜像
