### ISSUE TITLE
在大陆镜像地址不能用了

### ISSUE THREAD

**Issue by showsmall** [easzlab/kubeasz#1386]
### What happened? 发生了什么问题？

 Registry Mirrors:
  https://docker.nju.edu.cn/
  https://kuamavit.mirror.aliyuncs.com/   成都电信机房不能使用了

Jun 25 17:48:20 k8s-master1 dockerd: time="2024-06-25T17:48:20.887457536+08:00" level=debug msg="Calling HEAD /_ping" spanID=4c6a302c4df4d8e3 traceID=e06809554bedae10be20afcb61a807a3
Jun 25 17:48:20 k8s-master1 dockerd: time="2024-06-25T17:48:20.892616970+08:00" level=debug msg="Calling POST /v1.45/images/create?fromImage=easzlab%2Fkubeasz&tag=3.6.4" spanID=12f242ec77585c55 traceID=27cbcb67ef77665ec9140eb648b5c094
Jun 25 17:48:20 k8s-master1 dockerd: time="2024-06-25T17:48:20.965432516+08:00" level=debug msg="hostDir: /etc/docker/certs.d/docker.nju.edu.cn"
Jun 25 17:48:21 k8s-master1 dockerd: time="2024-06-25T17:48:21.001568416+08:00" level=debug msg="hostDir: /etc/docker/certs.d/kuamavit.mirror.aliyuncs.com"
Jun 25 17:48:21 k8s-master1 dockerd: time="2024-06-25T17:48:21.001638580+08:00" level=debug msg="Trying to pull easzlab/kubeasz from https://docker.nju.edu.cn/" spanID=12f242ec77585c55 traceID=27cbcb67ef77665ec9140eb648b5c094
Jun 25 17:48:21 k8s-master1 dockerd: time="2024-06-25T17:48:21.001703317+08:00" level=debug msg="Trying to pull easzlab/kubeasz from https://docker.nju.edu.cn/" spanID=12f242ec77585c55 traceID=27cbcb67ef77665ec9140eb648b5c094
Jun 25 17:48:21 k8s-master1 dockerd: time="2024-06-25T17:48:21.423432067+08:00" level=warning msg="Error getting v2 registry: Get \"https://docker.nju.edu.cn/v2/\": EOF" spanID=12f242ec77585c55 traceID=27cbcb67ef77665ec9140eb648b5c094
Jun 25 17:48:21 k8s-master1 dockerd: time="2024-06-25T17:48:21.423517634+08:00" level=info msg="Attempting next endpoint for pull after error: Get \"https://docker.nju.edu.cn/v2/\": EOF" spanID=12f242ec77585c55 traceID=27cbcb67ef77665ec9140eb648b5c094
Jun 25 17:48:21 k8s-master1 dockerd: time="2024-06-25T17:48:21.423562737+08:00" level=debug msg="Trying to pull easzlab/kubeasz from https://kuamavit.mirror.aliyuncs.com/" spanID=12f242ec77585c55 traceID=27cbcb67ef77665ec9140eb648b5c094
Jun 25 17:48:21 k8s-master1 dockerd: time="2024-06-25T17:48:21.423595010+08:00" level=debug msg="Trying to pull easzlab/kubeasz from https://kuamavit.mirror.aliyuncs.com/" spanID=12f242ec77585c55 traceID=27cbcb67ef77665ec9140eb648b5c094
Jun 25 17:48:52 k8s-master1 dockerd: time="2024-06-25T17:48:52.146660491+08:00" level=info msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown" spanID=12f242ec77585c55 traceID=27cbcb67ef77665ec9140eb648b5c094

### What did you expect to happen? 期望的结果是什么？

需要更换可用的地址

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

需要更换可用的地址

### Kubernetes version k8s 版本

<details>
1.30
</details>

### Kubeasz version

<details>
3.6.4
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
centos 7 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by Hello-Linux** [comment]
@showsmall  你好，目前中国已经无法使用dockerhub，我们后期会考虑将镜像同步至国内镜像仓库，同时这里给出以下几种解决办法
1. 从网上寻找可以继续使用的docker镜像加速地址进行尝试
2. 使用github action进行镜像转接至国内镜像仓库比如阿里云
3. 终极大招： 自己有梯子的话，配置docker 代理使用梯子，快速拉取docker镜像
