### ISSUE TITLE
docker exec -it kubeasz ezctl start-aio 报错

### ISSUE THREAD

**Issue by cloud-arrow** [easzlab/kubeasz#1388]
### What happened? 发生了什么问题？
执行报错

PLAY [kube_master,kube_node,etcd] *************************************************************************************************************************************

TASK [prepare : 删除centos/redhat默认安装] ****************************************************************************************************************************
fatal: [10.206.17.55]: FAILED! => {"changed": false, "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}
...ignoring

TASK [prepare : 安装基础软件包] ***************************************************************************************************************************************
fatal: [10.206.17.55]: FAILED! => {"changed": false, "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}

### What did you expect to happen? 期望的结果是什么？

安装成功

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

```
export release=3.6.3
wget https://github.com/easzlab/kubeasz/releases/download/${release}/ezdown
chmod +x ezdown
./ezdown -D
./ezdown -S
docker exec -it kubeasz ezctl start-aio
```

### Anything else we need to know? 其他需要说明的情况

一直报错，安装不成功，大佬帮忙看你看

### Kubernetes version k8s 版本

1.29的版本

### Kubeasz version

3.6.3的版本

### OS version 操作系统版本

```console
# On Linux:
$ cat /etc/os-release
export release=3.6.3
wget https://github.com/easzlab/kubeasz/releases/download/${release}/ezdown
chmod +x ezdown
./ezdown -D
./ezdown -S
docker exec -it kubeasz ezctl start-aio
$ uname -a
Linux iZj6cb2t64g89by08v35xrZ 5.10.134-16.3.al8.x86_64 #1 SMP Tue Mar 26 18:54:05 CST 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by jaffe-fly** [comment]
大佬 安装怎么成功没，我的一直报错`Failed to download metadata for repo 'nvidia-container-toolkit': Cannot download repomd.xml: `
