### ISSUE TITLE
ezdown使用代理

### ISSUE THREAD

**Issue by ilanni2460** [easzlab/kubeasz#1406]
### What happened? 发生了什么问题？

大佬，部署服务器在内网无法直接访问公网，但是可以通过配置代理去访问公网，现在需要给ezdown配置代理，要如何配置呢？

### What did you expect to happen? 期望的结果是什么？

ezdown通过代理访问外网

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

大佬，部署服务器在内网无法直接访问公网，但是可以通过配置代理去访问公网，现在需要给ezdown配置代理，要如何配置呢？

### Kubernetes version k8s 版本

<details>

</details>

### Kubeasz version

任何

### OS version 操作系统版本

rockylinux9

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by huningfei** [comment]
解决了没有？

**Comment by ilanni2460** [comment]
@huningfei 没有解决

**Comment by sujingclg** [comment]
这个项目是不是不维护了，上次提交还是 docker 镜像没被 ban 的时候

**Comment by ilanni2460** [comment]
@sujingclg 维护的

**Comment by sujingclg** [comment]
> @sujingclg 维护的

nju的那个docker镜像代理好像用不了了，辛苦能不能把这个配置暴露出来，用户可以自己去cloudflare搭建代理节点用呢？

**Comment by anbulang** [comment]
需要配置两个代理：
① shell 代理
export http_proxy=http://<你的htt代理IP>:<端口>
export https_proxy=http://<你的htt代理IP>:<端口>
export no_proxy=127.0.0.1,localhost,easzlab.io.local,<其他不需要代理的地址>

② Docker代理
修改/lib/systemd/system/docker.service，在[Service]中添加上述代理
systemctl daemon-reload
systemctl restart docker
