### ISSUE TITLE
使用 ./ezdown -D 无法下载镜像

### ISSUE THREAD

**Issue by huningfei** [easzlab/kubeasz#1408]
### What happened? 发生了什么问题？

![image](https://github.com/user-attachments/assets/1543e608-ba58-4a89-b1cb-1222539aced6)

### What did you expect to happen? 期望的结果是什么？

期望执行 ./ezdown -D 可以正常下载

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

export release=3.5.0
wget https://github.com/easzlab/kubeasz/releases/download/${release}/ezdown
chmod +x ./ezdown
./ezdown -D 

即可复现

### Kubernetes version k8s 版本

<details>
1.26
</details>

### Kubeasz version

<details>
3.5.0
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
[root@k8s-master1 k8s]# cat /etc/redhat-release 
Rocky Linux release 9.2 (Blue Onyx)

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by etcxy** [comment]
mirror可能要随时调整，可以试试这个，群友提供的：
```
cat > /etc/docker/daemon.json << "EOF"
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "registry-mirrors": [
    "https://docker.registry.cyou",
    "https://docker-cf.registry.cyou",
    "https://dockercf.jsdelivr.fyi",
    "https://docker.jsdelivr.fyi",
    "https://dockertest.jsdelivr.fyi",
    "https://mirror.aliyuncs.com",
    "https://dockerproxy.com",
    "https://mirror.baidubce.com",
    "https://docker.m.daocloud.io",
    "https://docker.nju.edu.cn",
    "https://docker.mirrors.sjtug.sjtu.edu.cn",
    "https://docker.mirrors.ustc.edu.cn",
    "https://mirror.iscas.ac.cn",
    "https://docker.rainbond.cc"
  ],
  "insecure-registries": ["http://easzlab.io.local:5000"],
  "max-concurrent-downloads": 10,
  "log-driver": "json-file",
  "log-level": "warn",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
    },
  "data-root": "/var/lib/docker"
}
EOF
```

**Comment by huningfei** [comment]
试了一下上面的daemon.json，，还是提示上面的错误，看来都已经不能用了

**Comment by huningfei** [comment]
> 目前大陆已经放开docker仓库的限制！！！可以拉取镜像。

我目前测试的不行，开了一个香港地区的服务器，下载没有任何问题

**Comment by huningfei** [comment]
> mirror可能要随时调整，可以试试这个，群友提供的：
> 
> ```
> cat > /etc/docker/daemon.json << "EOF"
> {
>   "exec-opts": ["native.cgroupdriver=systemd"],
>   "registry-mirrors": [
>     "https://docker.registry.cyou",
>     "https://docker-cf.registry.cyou",
>     "https://dockercf.jsdelivr.fyi",
>     "https://docker.jsdelivr.fyi",
>     "https://dockertest.jsdelivr.fyi",
>     "https://mirror.aliyuncs.com",
>     "https://dockerproxy.com",
>     "https://mirror.baidubce.com",
>     "https://docker.m.daocloud.io",
>     "https://docker.nju.edu.cn",
>     "https://docker.mirrors.sjtug.sjtu.edu.cn",
>     "https://docker.mirrors.ustc.edu.cn",
>     "https://mirror.iscas.ac.cn",
>     "https://docker.rainbond.cc"
>   ],
>   "insecure-registries": ["http://easzlab.io.local:5000"],
>   "max-concurrent-downloads": 10,
>   "log-driver": "json-file",
>   "log-level": "warn",
>   "log-opts": {
>     "max-size": "10m",
>     "max-file": "3"
>     },
>   "data-root": "/var/lib/docker"
> }
> EOF
> ```

试了一下上面的daemon.json，，还是提示上面的错误，看来都已经不能用了

**Comment by opser-gavin** [comment]
是的，还是不行啊

**Comment by huningfei** [comment]
> cat > /etc/docker/daemon.json << "EOF"
> {
>   "exec-opts": ["native.cgroupdriver=systemd"],
>   "registry-mirrors": [
>     "https://docker.registry.cyou",
>     "https://docker-cf.registry.cyou",
>     "https://dockercf.jsdelivr.fyi",
>     "https://docker.jsdelivr.fyi",
>     "https://dockertest.jsdelivr.fyi",
>     "https://mirror.aliyuncs.com",
>     "https://dockerproxy.com",
>     "https://mirror.baidubce.com",
>     "https://docker.m.daocloud.io",
>     "https://docker.nju.edu.cn",
>     "https://docker.mirrors.sjtug.sjtu.edu.cn",
>     "https://docker.mirrors.ustc.edu.cn",
>     "https://mirror.iscas.ac.cn",
>     "https://docker.rainbond.cc"
>   ],
>   "insecure-registries": ["http://easzlab.io.local:5000"],
>   "max-concurrent-downloads": 10,
>   "log-driver": "json-file",
>   "log-level": "warn",
>   "log-opts": {
>     "max-size": "10m",
>     "max-file": "3"
>     },
>   "data-root": "/var/lib/docker"
> }
> EOF

今天又重新开了个新机器，居然又可以下载了，赞！！！

**Comment by sujingclg** [comment]
> 目前大陆已经放开docker仓库的限制！！！可以拉取镜像。

刚试了下并不行，北京，教育网 & 中国移动

**Comment by huningfei** [comment]
> 遇到同样的问题。 猜测可能与` ./ezdown`参数读取失败有关。能帮忙看下为什么这些会失败吗？
> 
> ```
> root@hostname:~# ./ezdown -m "CN"
> 2024-09-27 12:20:38 ERROR illegal option
> Usage: ezdown [options] [args]
>   option:
>     -C         stop&clean all local containers
>     -D         download default binaries/images into "/etc/kubeasz"
>     -P <OS>    download system packages of the OS (ubuntu_22,debian_11,...)
>     -R         download Registry(harbor) offline installer
>     -S         start kubeasz in a container
>     -X <opt>   download extra images
>     -d <ver>   set docker-ce version, default "24.0.5"
>     -e <ver>   set kubeasz-ext-bin version, default "1.8.0"
>     -k <ver>   set kubeasz-k8s-bin version, default "v1.28.1"
>     -m <str>   set docker registry mirrors, default "CN"(used in Mainland,China)
>     -z <ver>   set kubeasz version, default "3.6.2"
> root@hostname:~# ./ezdown -d "24.0.5"
> 2024-09-27 12:20:55 ERROR illegal option
> Usage: ezdown [options] [args]
>   option:
>     -C         stop&clean all local containers
>     -D         download default binaries/images into "/etc/kubeasz"
>     -P <OS>    download system packages of the OS (ubuntu_22,debian_11,...)
>     -R         download Registry(harbor) offline installer
>     -S         start kubeasz in a container
>     -X <opt>   download extra images
>     -d <ver>   set docker-ce version, default "24.0.5"
>     -e <ver>   set kubeasz-ext-bin version, default "1.8.0"
>     -k <ver>   set kubeasz-k8s-bin version, default "v1.28.1"
>     -m <str>   set docker registry mirrors, default "CN"(used in Mainland,China)
>     -z <ver>   set kubeasz version, default "3.6.2"
> ```

-D 试过吗，你的这两个参数我还从来没用过

**Comment by Mia-Dan** [comment]
> > 遇到同样的问题。 猜测可能与` ./ezdown`参数读取失败有关。能帮忙看下为什么这些会失败吗？
> 
> -D 试过吗，你的这两个参数我还从来没用过

-D的报错和您的完全一致

**Comment by huningfei** [comment]
> > > 遇到同样的问题。 猜测可能与` ./ezdown`参数读取失败有关。能帮忙看下为什么这些会失败吗？
> > 
> > 
> > -D 试过吗，你的这两个参数我还从来没用过
> 
> -D的报错和您的完全一致

-D 报错，
第一更改ezdown文件内容wget处 ：
      wget --header="User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" --no-check-certificate "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }

第二 就是使用上面的daemon.json文件内容，然后就可以正常下载了

**Comment by Mia-Dan** [comment]
> > > > 遇到同样的问题。 猜测可能与` ./ezdown`参数读取失败有关。能帮忙看下为什么这些会失败吗？
> > > 
> > > 
> > > -D 试过吗，你的这两个参数我还从来没用过
> > 
> > 
> > -D的报错和您的完全一致
> 
> -D 报错， 第一更改ezdown文件内容wget处 ： wget --header="User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" --no-check-certificate "$DOCKER_URL" || { logger error "downloading docker failed"; exit 1; }
> 
> 第二 就是使用上面的daemon.json文件内容，然后就可以正常下载了

非常感谢您！

**Comment by chaser3821** [comment]
> > > > 遇到同样的问题。猜测可能与参数读取失败有关。能帮忙看下为什么这些会失败吗？` ./ezdown`
> > > 
> > > 
> > > -D 试过吗，你的这两个参数我还从来没用过
> > 
> > 
> > -D的报错和您的完全一致
> 
> -D 报错， 第一更改ezdown文件内容wget处 ： wget --header=“User-Agent：Mozilla/5.0 （Windows NT 10.0;Win64 的;x64） AppleWebKit/537.36 （KHTML，如 Gecko） Chrome/126.0.0.0 Safari/537.36“ --no-check-certificate ”$DOCKER_URL“ ||{ logger 错误 “下载 docker 失败”;退出 1; }
> 
> 第二 就是使用上面的daemon.json文件内容，然后就可以正常下载了
现在又不可以了 有什么解决办法吗
