### ISSUE TITLE
开启ex-lb后keepalived的问题

### ISSUE THREAD

**Issue by Vexation9** [easzlab/kubeasz#1419]
### What happened? 发生了什么问题？

使用ex-lb后，部署了nacos集群发现nacos连一会后就会断开，排查后发现可能是keepalived的问题。每次重启vip节点上的keepalived后就可以短暂的连上一会，过一会又会连不上

### What did you expect to happen? 期望的结果是什么？

求大佬帮忙看一下

### How can we reproduce it (as minimally and precisely as possible)? 尽可能最小化、精确地描述如何复现问题

l4lb配置如下
user root;
worker_processes 1;

error_log  /etc/l4lb/logs/error.log warn;

events {
    worker_connections  3000;
}

stream {
    upstream apiservers {
        server 10.116.3.139:6443    max_fails=2 fail_timeout=3s;
        server 10.116.5.17:6443    max_fails=2 fail_timeout=3s;
    }

    server {
        listen 0.0.0.0:8443;
        proxy_connect_timeout 1s;
        proxy_pass apiservers;
    }

	upstream nacos-cluster {
        server 10.116.2.190:8848    max_fails=2 fail_timeout=3s;
        server 10.116.3.31:8848    max_fails=2 fail_timeout=3s;
        server 10.116.3.84:8848    max_fails=2 fail_timeout=3s;
    }
	
	server {
        listen 0.0.0.0:8848;
        proxy_connect_timeout 1s;
        proxy_pass nacos-cluster;
    }

	upstream nacos-grpc {
        server 10.116.2.190:9848    max_fails=2 fail_timeout=3s;
        server 10.116.3.31:9848    max_fails=2 fail_timeout=3s;
        server 10.116.3.84:9848    max_fails=2 fail_timeout=3s;
    }
	
	server {
        listen 0.0.0.0:9848;
        proxy_connect_timeout 1s;
        proxy_pass nacos-grpc;
    }

}

keepalived的配置如下
global_defs {
}

vrrp_track_process check-l4lb {
    process l4lb
    weight -60
    delay 3
}

vrrp_instance VI-01 {
    state MASTER
    priority 120
    unicast_src_ip 10.116.3.139
    unicast_peer {
        10.116.5.17
    }
    dont_track_primary
    interface ens33
    virtual_router_id 223
    advert_int 3
    track_process {
        check-l4lb
    }
    virtual_ipaddress {
        10.116.3.188
    }
}

### Kubernetes version k8s 版本

<details>
1.28.5
</details>

### Kubeasz version

<details>
3.6.3
</details>

### OS version 操作系统版本

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
openEuler 22.03 (LTS-SP4)
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable) 其他网络插件等需要说明的情况

<details>

</details>

**Comment by tzwken** [comment]
你这个应该是nginx配置的问题，keepalived只是维护了一个VIP。看你ng的配置，应该是超时配置和upstream检查相关的能数需要调整。kube-apiserver是一个长连接并且会有心跳检测。你需要检查井nacos的空闲超时和ng的代理超时参数。
