### ISSUE TITLE
更快的二进制文件下载以及自动化的ansible和k8s环境初始化方式

### ISSUE THREAD

**Issue by Code2Life** [easzlab/kubeasz#165]
k8s使用到的相关二进制文件, 从百度网盘同步到了个人的七牛CDN上, 比百度云更快, 欢迎大家下载:
[http://filecdn.code2life.top/](http://filecdn.code2life.top/)
另外还提供了一个脚本放在CDN上, 实现自动化安装ansible, 下载二进制文件, clone kubeasz项目代码等功能, 自动化了linux裸机安装相关环境的操作. #164 
`curl http://filecdn.code2life.top/kubeasz-basic-env-setup.sh | sh -s`
shell水平有限, 不足之处欢迎大家指正.

**Comment by gjmzj** [comment]
不错的工具脚本，放在目录/etc/ansible/tools下；
另外七牛的CDN真赞~

**Comment by dowson521** [comment]
感谢感谢。非常不错。

**Comment by luokeli59** [comment]
非常感谢您的脚本！和CDN，速度很赞！

**Comment by 21ki** [comment]
想问下您的文件服务器是用什么搭建的 界面很好看，是否是开源的软件

**Comment by Code2Life** [comment]
打包的文件很久没更新了，大家还是用作者发布的新版本吧，没用啥软件，只是手写的index.html放到七牛CDN的bucket里面

**Comment by 21ki** [comment]
能否给一个index.html文件，自己有阿里云oss仿照您的做一个个人下载工具。谢谢麻烦您了

**Comment by 21ki** [comment]
不用了，我自己谢了一个，多谢了

**Comment by linjie830914** [comment]
http://filecdn.code2life.top/k8s.1100.tar.gz这个地址无法下载了

**Comment by Code2Life** [comment]
以前这里放的版本都太老了，不建议用这个方式下载了

**Comment by Code2Life** [comment]
参考项目推荐的方式下载离线包： https://github.com/easzlab/kubeasz/blob/master/docs/setup/offline_install.md
