### ISSUE TITLE
kube-proxy 报错

### ISSUE THREAD

**Issue by longbinma** [easzlab/kubeasz#174]
[root@localhost ~]# kubectl get node
NAME            STATUS                     ROLES     AGE       VERSION
192.168.1.130   Ready                      <none>    1d        v1.9.6
192.168.1.168   Ready,SchedulingDisabled   <none>    1d        v1.9.6
192.168.1.30    Ready,SchedulingDisabled   <none>    1d        v1.9.6

[root@localhost ~]#journalctl -u kube-proxy
-- Logs begin at Sat 2018-04-28 12:43:45 CST, end at Sat 2018-04-28 14:08:23 CST. --
Apr 28 13:49:50 localhost.localdomain systemd[1]: Stopping Kubernetes Kube-Proxy Server...
Apr 28 13:49:50 localhost.localdomain systemd[1]: Started Kubernetes Kube-Proxy Server.
Apr 28 13:49:50 localhost.localdomain systemd[1]: Starting Kubernetes Kube-Proxy Server...
Apr 28 13:49:50 localhost.localdomain kube-proxy[16132]: W0428 13:49:50.586560   16132 server.go:185] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
Apr 28 13:49:50 localhost.localdomain kube-proxy[16132]: W0428 13:49:50.868332   16132 server_others.go:289] Flag proxy-mode="" unknown, assuming iptables proxy
Apr 28 13:49:50 localhost.localdomain kube-proxy[16132]: I0428 13:49:50.898387   16132 server_others.go:138] Using iptables Proxier.
Apr 28 13:49:50 localhost.localdomain kube-proxy[16132]: W0428 13:49:50.898547   16132 proxier.go:468] clusterCIDR not specified, unable to distinguish between internal and external traffic
Apr 28 13:49:50 localhost.localdomain kube-proxy[16132]: I0428 13:49:50.898771   16132 server_others.go:171] Tearing down inactive rules.
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: E0428 13:49:51.027636   16132 proxier.go:792] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: invalid option -- '5'
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: iptables-restore: line 7 failed
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: )
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.086138   16132 server.go:426] Version: v1.9.6
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.094846   16132 server.go:452] Running in resource-only container "/kube-proxy"
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.101043   16132 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.101153   16132 conntrack.go:52] Setting nf_conntrack_max to 131072
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.101228   16132 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.101282   16132 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.109105   16132 config.go:202] Starting service config controller
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.109148   16132 controller_utils.go:1019] Waiting for caches to sync for service config controller
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.109211   16132 config.go:102] Starting endpoints config controller
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.109228   16132 controller_utils.go:1019] Waiting for caches to sync for endpoints config controller
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.509383   16132 controller_utils.go:1026] Caches are synced for endpoints config controller
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.509516   16132 proxier.go:984] Not syncing iptables until Services and Endpoints have been received from master
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.509553   16132 controller_utils.go:1026] Caches are synced for service config controller
Apr 28 13:49:51 localhost.localdomain kube-proxy[16132]: I0428 13:49:51.509641   16132 proxier.go:329] Adding new service port "default/kubernetes:https" at 10.68.0.1:443/TCP

**Comment by gjmzj** [comment]
第二段日志显示你集群kube-proxy的rbac配置好像有问题，你可以检查是否有如下配置：
``` bash
$ kubectl describe clusterrolebinding system:node-proxier
Name:         system:node-proxier
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate=true
Role:
  Kind:  ClusterRole
  Name:  system:node-proxier
Subjects:
  Kind  Name               Namespace
  ----  ----               ---------
  User  system:kube-proxy  
```

**Comment by longbinma** [comment]
[root@localhost ~]# kubectl describe clusterrolebinding system:node-proxier
Name:         system:node-proxier
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate=true
Role:
  Kind:  ClusterRole
  Name:  system:node-proxier
Subjects:
  Kind  Name               Namespace
  ----  ----               ---------
  User  system:kube-proxy

**Comment by 4220182** [comment]
我是一样的问题：

3月 04 08:10:35 master kube-proxy[1081]: E0304 08:10:35.883858    1081 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.Service: services is forbidden: User "system:kube-proxy" cannot list services at the cluster scope

有什么好的解决方法？

**Comment by 4220182** [comment]
启动顺序的问题，报kube-proxy 重启一次，就没这个错误了。
