### ISSUE TITLE
TodoList

### ISSUE THREAD

**Issue by gjmzj** [easzlab/kubeasz#188]
## 前言

`kubeasz`项目开始于`2017.11`，半年多时间以来，从最开始单一的ansible部署脚本朝着提供部署高可用 K8S集群的完整解决方案的目标不断前进，接下去项目的发展需要各位的共同参与和贡献，希望越做越好，为国内k8s学习、实践者提供更多帮助。  
现在是很好的时间节点，梳理项目的`TodoList`/`Milestones`，以下是现有的一些想法，欢迎大家在[这里](https://github.com/gjmzj/kubeasz/issues/188)参与讨论。

### 项目 TodoList 
<table border="0">
    <tr>
        <th>类型</th>
        <th>描述</th>
        <th>备注</th>
    </tr>
    <tr>
        <td>集群部署</td>
        <td>集群内时间同步-Chrony</td>
        <td>暂取消</td>
    </tr>
    <tr>
        <td>集群部署</td>
        <td>服务器基础安全加固与参数优化</td>
        <td>已完成</td>
    </tr>
    <tr>
        <td>基础服务</td>
        <td>集群监控告警-prometheus</td>
        <td>已完成基础，待优化</td>
    </tr>
    <tr>
        <td>应用服务</td>
        <td>CI/CD 集成</td>
        <td>更新jenkins</td>
    </tr>
    <tr>
        <td>集群部署</td>
        <td>kube-router网络插件</td>
        <td>已完成</td>
    </tr>
    <tr>
        <td>基础服务</td>
        <td>metrics server</td>
        <td>已完成</td>
    </tr>
    <tr>
        <td>集群部署</td>
        <td>ipvs代理模式跟进</td>
        <td>已完成</td>
    </tr>
    <tr>
        <td>应用服务</td>
        <td>服务治理-istio跟进</td>
        <td></td>
    </tr>
</table>

**Comment by gjmzj** [comment]
K8S应用的CI/CD流程集成，使用git ci，有些经验

**Comment by yfm10** [comment]
Metrics Server 替换 Heapster

**Comment by lusyoe** [comment]
之前有过k8s应用jenkins CI的实践经验，我可以来补充点这方面的吧

**Comment by xiongraorao** [comment]
请问有ceph分布式存储方案的文档吗，我照着官网安装出问题了

**Comment by likakuli** [comment]
最后那个是istio

**Comment by gjmzj** [comment]
项目todolist，大家请多提意见、建议；任何功能性或者稳定性提升的问题；特别的，如果有熟悉其他k8s集群安装方式的（kubeadm/kubespray/kops等），可以把其他安装方式有优势的功能集成到kubeasz当中来:)

**Comment by wangycc** [comment]
集群日志可收集进去。
filebeat+ELK+kafka 也可以做到类似Prometheus SD这种通过annotations来控制哪些pod日志需要被采集。

**Comment by kitepad** [comment]
istio还是很重要的，建议优先级调高，这样再配合amabassador对于微服务架构还是很有意义的。

**Comment by sunshanpeng** [comment]
楼主有考虑过加入LXCFS吗？

<https://github.com/lxc/lxcfs>
<https://yq.aliyun.com/articles/566208>

**Comment by ly-wjj** [comment]
部署etcd时可以再加上一个监控检测的job。确保etcd启动后服务正常。
