### ISSUE TITLE
master 节点没有flannel 虚拟网卡

### ISSUE THREAD

**Issue by longbinma** [easzlab/kubeasz#212]
根据教程安装了多主多节点，但是发现有一个master节点没有flannel虚拟网卡，
根据教程又添加了一个master节点，但是新加的master节点依然没有flannel虚拟网卡
没有flannel 虚拟网卡的master节点均ping不通pod
根据教程又添加了一个node节点，node节点正常

**Comment by longbinma** [comment]
![image](https://user-images.githubusercontent.com/16474596/40764225-d4b3f9f4-64da-11e8-9d75-8f0955147803.png)

**Comment by longbinma** [comment]
![image](https://user-images.githubusercontent.com/16474596/40764582-396d1a00-64dc-11e8-9716-b523fd6fe894.png)

**Comment by longbinma** [comment]
kubectl logs 和 kubectl describe master节点的flannel pod  没发现异常，服务器之前没有配置过flannel

**Comment by kobehaha** [comment]
尝试下先把master 节点删除，从新加入集群试下吗？
