### ISSUE TITLE
swagger-ui 不能通过hosts中的用户名密码登录

### ISSUE THREAD

**Issue by leeyan85** [easzlab/kubeasz#222]
swagger-ui 不能通过hosts中的用户名密码登录
`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"admin\" cannot get path \"/swagger-ui\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}`

**Comment by gjmzj** [comment]
对swagger-ui没试过；你可以尝试这样操作，
1. kubectl delete -f /etc/ansible/manifests/dashboard/ui-admin-rbac.yaml
2. 修改/etc/ansible/manifests/dashboard/ui-admin-rbac.yaml为如下内容后，保存
``` bash
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ui-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
```
3.kubectl apply -f /etc/ansible/manifests/dashboard/ui-admin-rbac.yaml
