### ISSUE TITLE
多kubernetes监控方案

### ISSUE THREAD

**Issue by kobehaha** [easzlab/kubeasz#228]
目前大多数方案. prometheus + grafana and  heapster  + influxdb + grafana 都对监控一个集群比较好，有考虑增对多集群的监控方案吗？ 类似于每个kubernetes一个prometheus 监控中心. 然后中心prometheus 去拉去每个prometheus 的数据，做一个数据聚合，然后也能做监控告警.AlertManager. 现在有这样的需求，不过没有比较好的方案

**Comment by gjmzj** [comment]
这个prometheus本来就支持联邦的

**Comment by kobehaha** [comment]
可以是支持的，不过聚合数据后怎么显示呢？比如我需要加一个idc的标签，不同区域需要做个区分，数据聚合后都会在一起了
