### ISSUE TITLE
had a problem in what install prommetheus minitor by helm

### ISSUE THREAD

**Issue by mrhjx2** [easzlab/kubeasz#230]
Error: release monitor failed: namespaces "monitoring" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "monitoring"

**Comment by gjmzj** [comment]
你的helm的rbac设置有问题，把helm的sa绑定cluster-admin权限，或者参考项目里的helm rbac设置吧

**Comment by Mrhjx2** [comment]
好的 谢谢 但我不加证书的话是正常的

**Comment by peterpijing** [comment]
@Mrhjx2 部署grafana 有遇到报错Error: failed to prepare subPath for volumeMount "config" of container "download-dashboards" 么？
