### ISSUE TITLE
prometheus服务安装正常, grafana helm部署出错如下，请大神解答下

### ISSUE THREAD

**Issue by peterpijing** [easzlab/kubeasz#232]
Error: failed to prepare subPath for volumeMount "config" of container "download-dashboards"
![image](https://user-images.githubusercontent.com/14362373/41402426-dac7b3ba-6ff4-11e8-8780-f79a7a5db767.png)

**Comment by gjmzj** [comment]
项目的prom grafana 部署使用的都是官方的helm charts，一般比较稳定的，我反复装过，都没碰到你的问题，你可以去官方charts那边提提问题看
