### ISSUE TITLE
安装flannel验证

### ISSUE THREAD

**Issue by samlyhuang** [easzlab/kubeasz#238]
安装完flannel，查看结果，发现ip与node是同一个地址，如下所示：
[root@server1 ~]# kubectl get pod --all-namespaces -o wide|head -n 4
NAMESPACE     NAME                            READY                STATUS    RESTARTS   AGE       IP               NODE
kube-system   kube-flannel-ds-2pwbk   1/1       Running   1          14m       192.168.31.150   192.168.31.150
kube-system   kube-flannel-ds-dzq7b   1/1       Running   1          14m       192.168.31.152   192.168.31.152
kube-system   kube-flannel-ds-mplcd   1/1       Running   1          14m       192.168.31.151   192.168.31.151

查看flannel发现网络端口是up的
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether ee:9a:29:e1:42:82 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::ec9a:29ff:fee1:4282/64 scope link 
       valid_lft forever preferred_lft forever

请教大神这个是什么原因？

**Comment by gjmzj** [comment]
正常就是这样的，flannel daemonset本来使用的就是host网络；你是想看看业务pod会分配什么地址？
执行kubectl run busy --image=busybox --replicas=3 sleep 36000；成功后等会再次查看，就能看到pod地址分配情况了；
项目文档里面有介绍验证步骤https://github.com/gjmzj/kubeasz/blob/master/docs/06.flannel.md

**Comment by samlyhuang** [comment]
非常感谢，我去看一下
