### ISSUE TITLE
使用了清除网络插件的脚本  无法修改 FLANNEL IP  

### ISSUE THREAD

**Issue by a33151** [easzlab/kubeasz#263]
您好，我这边使用了清除网络插件的脚本，更改了hosts上对应CLUSTER_CIDR的IP 但是发现获取的还是旧的IP  这个有办法解决吗？ 我没有更改网络插件类型  还是用flannel，只是想更换IP 
以下是一些信息
root@k8s-node4:/u01/shells# cat /run/flannel/subnet.env
FLANNEL_NETWORK=172.20.0.0/16
FLANNEL_SUBNET=182.20.3.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true

root@k8s-node4:/u01/shells# ip route
default via 10.0.222.1 dev ens3 onlink 
10.0.222.0/24 dev ens3  proto kernel  scope link  src 10.0.222.204 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
182.20.0.0/24 via 182.20.0.0 dev flannel.1 onlink 
182.20.1.0/24 via 182.20.1.0 dev flannel.1 onlink 
182.20.2.0/24 via 182.20.2.0 dev flannel.1 onlink 
182.20.3.0/24 dev cni0  proto kernel  scope link  src 182.20.3.1

**Comment by gjmzj** [comment]
可以更换，我整理一个脚本吧

**Comment by a33151** [comment]
我这边的版本号补充一下： k8s：v1.10 
                          flannel   ：  jmgao1983/flannel                              v0.10.0-amd64

**Comment by gjmzj** [comment]
之前低估了修改cluster_cidr的问题，自己测试了几次都没成功 >.< ; 
大概需要以下一些操作
1. 网络插件要重新安装，因为新cidr肯定需要网络插件的ipadm重新生产地址
2. kube-proxy需要重新做服务代理
3. kube-controller-manager 重新配置重启

**Comment by gjmzj** [comment]
暂时没找到可行的方法，

**Comment by a33151** [comment]
好的 感谢 我也去尝试一下！

**Comment by mawennan** [comment]
您好 我安装的flannel网络， 路由如下

172.20.1.0/24 via 172.20.1.0 dev flannel.1 onlink 
172.20.3.0/24 via 172.20.3.0 dev flannel.1 onlink 

这个不正常吧？我服务器ip是1.1.1.x

**Comment by a33151** [comment]
这个集群网络的IP与你机器的IP无关 @mawennan
