### ISSUE TITLE
efk配置动态存储问题

### ISSUE THREAD

**Issue by mrhjx2** [easzlab/kubeasz#264]
pvc的状态
[root@k8s-m1 k8s-pv]# kubectl get pvc -n kube-system
NAME                                            STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
elasticsearch-logging-elasticsearch-logging-0   Bound     pvc-c44e7516-8a71-11e8-9de2-02aacf308d56   25Gi       RWX            nfs-dynamic-class   14m
elasticsearch-logging-elasticsearch-logging-1   Bound     pvc-c6f70bc9-8a71-11e8-9de2-02aacf308d56   25Gi       RWX            nfs-dynamic-class   14m

nfs挂载状态
10.1.1.20:/home/share/k8s-pv/kube-system-elasticsearch-logging-elasticsearch-logging-0-pvc-c44e7516-8a71-11e8-9de2-02aacf308d56 nfs        36G   17G   19G  48% /var/lib/kubelet/pods/c44fb1d3-8a71-11e8-9de2-02aacf308d56/volumes/kubernetes.io~nfs/pvc-c44e7516-8a71-11e8-9de2-02aacf308d56

10.1.1.20:/home/share/k8s-pv/kube-system-elasticsearch-logging-elasticsearch-logging-1-pvc-c6f70bc9-8a71-11e8-9de2-02aacf308d56 nfs        36G   17G   19G  48% /var/lib/kubelet/pods/c6f922ef-8a71-11e8-9de2-02aacf308d56/volumes/kubernetes.io~nfs/pvc-c6f70bc9-8a71-11e8-9de2-02aacf308d56

上面都是正常的 可是es一直起不来
一直报错

error：：
 pod has unbound PersistentVolumeClaims (repeated 7 times)
Back-off restarting failed container 

Jul 18 18:20:32 rzjf-55 kubelet: I0718 18:20:32.717933    5770 kuberuntime_manager.go:513] Container {Name:elasticsearch-logging Image:harbor.51rz.com/soft/elasticsearch:v5.6.4 Command:[] Args:[] WorkingDir: Ports:[{Name:db HostPort:0 ContainerPort:9200 Protocol:TCP HostIP:} {Name:transport HostPort:0 ContainerPort:9300 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:NAMESPACE Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] Resources:{Limits:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI}] Requests:map[cpu:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI}]} VolumeMounts:[{Name:elasticsearch-logging ReadOnly:false MountPath:/data SubPath: MountPropagation:<nil>} {Name:elasticsearch-logging-token-t2h6j ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jul 18 18:20:32 rzjf-55 kubelet: I0718 18:20:32.718095    5770 kuberuntime_manager.go:757] checking backoff for container "elasticsearch-logging" in pod "elasticsearch-logging-1_kube-system(c6f922ef-8a71-11e8-9de2-02aacf308d56)"
Jul 18 18:20:32 rzjf-55 kubelet: I0718 18:20:32.718242    5770 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-1_kube-system(c6f922ef-8a71-11e8-9de2-02aacf308d56)
Jul 18 18:20:32 rzjf-55 kubelet: E0718 18:20:32.718285    5770 pod_workers.go:186] Error syncing pod c6f922ef-8a71-11e8-9de2-02aacf308d56 ("elasticsearch-logging-1_kube-system(c6f922ef-8a71-11e8-9de2-02aacf308d56)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-1_kube-system(c6f922ef-8a71-11e8-9de2-02aacf308d56)"

**Comment by gjmzj** [comment]
下次请把日志部分用 markdown 代码格式复制上来，方便查看，再检查下pv,pvc的详细描述；
注意pvc 使用STORAGECLASS 要与实际提供的一致
``` bash
$ kubectl get pv

$ kubectl get pvc -n kube-system

$ kubectl describe pv 
```

**Comment by Mrhjx2** [comment]
感谢
