### ISSUE TITLE
执行ansible-playbook 04.kube-master.yml失败connected refused

### ISSUE THREAD

**Issue by PeterSun0317** [easzlab/kubeasz#266]
执行这个yml文件的时候报这个错，应该是连不上k8s api server，但是为什么连不上呢，配置的时候是否真的配置成功了呢这个好像没有日志可以查看
fatal: [192.168.251.148]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/opt/kube/bin/kubectl", "get", "node"], "delta": "0:00:00.119841", "end": "2018-07-19 19:30:32.053663", "msg": "non-zero return code", "rc": 1, "start": "2018-07-19 19:30:31.933822", "stderr": "The connection to the server 192.168.251.148:8443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server 192.168.251.148:8443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}

**Comment by gjmzj** [comment]
apiserver日志查看`journalctl -u kube-apiserver `

**Comment by BlankRain** [comment]
日志发现监听IP是 127.0.0.1  而不是 0.0.0.0

**Comment by djkdeveloper** [comment]
@PeterSun0317  我也有这个问题 你解决了吗
