### ISSUE TITLE
问题：kublet与Containerd的直接集成

### ISSUE THREAD

**Issue by xaclincoln** [easzlab/kubeasz#274]
containerd 1.1版本内部实现了CRI，并且在docker-ce 18.06版本中已正式集成了containerd 1.1版本。有个问题，如果使用18.06版本的docker-ce，如何正确地集成kublet 与 containerd？
我查了一些资料，kublet的命令行参数如下，不知道是否正确。
`  --container-runtime=remote 
  --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock `

**Comment by gjmzj** [comment]
我也没有实际使用cri和containerd的经验，只是看过介绍，你可以实践测试起来；如果玩好了，我们可以集成到项目中来，作为一个可配置的候选runtime

**Comment by xaclincoln** [comment]
昨天用1.10的K8s和18.06 ce版本试了，发现kubelet无法正常启动，查看了docker-containerd了日志，发现cri插件因为端口冲突无法正常启动。到containerd的github查找issule，发现了[https://github.com/containerd/containerd/issues/2483](#2483)。从这意思看，1.11版本应该可以成功了，我有空再试下。

**Comment by SmileSees** [comment]
Hi @gjmzj , calico 我之前也试过，也是同样的问题。
pod的节点会出现网段重复， 重启后status会变成Unknown。

**Comment by xaclincoln** [comment]
我这些天使用1.13.3 k8s ，1.2.4 Containerd又尝试了一次，可以正常工作，代码分支https://github.com/xaclincoln/kubeasz/tree/containerd。
在试验过程中，发现Kube-Router无法正常工作，具体原因没有找到。此外，我把Containerd和相关的Containerd-Shim，runc等组件放到/usr/bin/目录中，如果放到/opt/kube/bin目录中，containerd总是报:Containerd-shim not found in $PATH，这个问题也让我百恩不得其解。
@gjmzj

**Comment by gjmzj** [comment]
👍 containerd 报找不到 containerd-shim，可能是因为containerd 启动时不是在它当前目录找Containerd-shim；而在systemd管理的服务启动时是不会去找自定义环境 PATH 目录的，所以报找不到
