### ISSUE TITLE
coredns解析有问题

### ISSUE THREAD

**Issue by or0or1** [easzlab/kubeasz#279]
环境： k8s 1.11.0  allinone

’‘’
[root@MiWiFi-R1CM-srv ansible]# kubectl run nginx --image=nginx --expose --port=80
service/nginx created
deployment.apps/nginx created
[root@MiWiFi-R1CM-srv ansible]# /opt/kube/bin/kubectl get po,svc,ing -n kube-system
NAME                                           READY     STATUS    RESTARTS   AGE
pod/calico-kube-controllers-7466d75b64-hbhxp   1/1       Running   0          9m
pod/calico-node-82kj9                          2/2       Running   0          9m
pod/calico-node-fjnw8                          2/2       Running   0          9m
pod/coredns-868d999555-jtv48                   1/1       Running   0          9m
pod/coredns-868d999555-kkjns                   1/1       Running   0          9m
pod/kubernetes-dashboard-b644d546b-tb4h4       1/1       Running   0          8m
pod/metrics-server-6774f57dd4-g7zcw            1/1       Running   0          8m

NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
service/kube-dns               ClusterIP   10.68.0.2       <none>        53/UDP,53/TCP   9m
service/kubernetes-dashboard   NodePort    10.68.31.171    <none>        443:27611/TCP   8m
service/metrics-server         ClusterIP   10.68.158.122   <none>        443/TCP         8m
[root@MiWiFi-R1CM-srv ansible]# /opt/kube/bin/kubectl get po,svc,ing
NAME                         READY     STATUS              RESTARTS   AGE
pod/nginx-6f858d4d45-djncr   0/1       ContainerCreating   0          14s

NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.68.0.1     <none>        443/TCP   12m
service/nginx        ClusterIP   10.68.21.12   <none>        80/TCP    14s
[root@MiWiFi-R1CM-srv ansible]# kubectl run busybox --rm -it --image=busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # cat /etc/resolv.conf
nameserver 10.68.0.2
search default.svc.cluster.local. svc.cluster.local. cluster.local.
options ndots:5
/ # nslookup nginx.default.svc.cluster.local
Server:         10.68.0.2
Address:        10.68.0.2:53

Name:   nginx.default.svc.cluster.local
Address: 10.68.21.12

*** Can't find nginx.default.svc.cluster.local: No answer

/ # nslookup kubernetes.default.svc.cluster.local
Server:         10.68.0.2
Address:        10.68.0.2:53

*** Can't find kubernetes.default.svc.cluster.local: No answer

/ # nslookup www.baidu.com
Server:         10.68.0.2
Address:        10.68.0.2:53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com

*** Can't find www.baidu.com: No answer

/ #
/ # ^C
/ # nslookup www.baidu.com
Server:         10.68.0.2
Address:        10.68.0.2:53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com

*** Can't find www.baidu.com: No answer

/ # nslookup kubernetes.default.svc.cluster.local
Server:         10.68.0.2
Address:        10.68.0.2:53

*** Can't find kubernetes.default.svc.cluster.local: No answer
‘’‘

**Comment by gjmzj** [comment]
可以在容器里面尝试ping www.baidu.com，如果通的话，解析应该没有问题，这个nslookup貌似有点问题

**Comment by szbalx** [comment]
环境 k8s 1.11 multi-master
kubedns也出现一样的问题

kubectl get svc --all-namespaces -o wide
NAMESPACE     NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE       SELECTOR
default       kubernetes   ClusterIP   10.68.0.1      <none>        443/TCP         21h       <none>
default       nginx        ClusterIP   10.68.19.184   <none>        80/TCP          16h       run=nginx
kube-system   kube-dns     ClusterIP   10.68.0.2      <none>        53/UDP,53/TCP   20h       k8s-app=kube-dns

kubectl run busybox --rm -it --image=busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # cat /etc/resolv.conf 
nameserver 10.68.0.2
search default.svc.cluster.local. svc.cluster.local. cluster.local.
options ndots:5
/ # nslookup nginx.default.svc.cluster.local
Server:		10.68.0.2
Address:	10.68.0.2:53

Name:	nginx.default.svc.cluster.local
Address: 10.68.19.184

*** Can't find nginx.default.svc.cluster.local: No answer

/ # nslookup www.baidu.com
Server:		10.68.0.2
Address:	10.68.0.2:53

Non-authoritative answer:
www.baidu.com	canonical name = www.a.shifen.com
Name:	www.a.shifen.com
Address: 14.215.177.39
Name:	www.a.shifen.com
Address: 14.215.177.38

*** Can't find www.baidu.com: No answer

**Comment by luolizhi** [comment]
[root@cty-kftest06 ~]$ kubectl run b1 -it --rm --image=alpine /bin/sh
If you don't see a command prompt, try pressing enter.
/ # nslookup kubernetes.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'kubernetes.default.svc.cluster.local': Try again
/ # cat /etc/resolv.conf 
nameserver 10.68.0.2
search default.svc.cluster.local. svc.cluster.local. cluster.local.
options ndots:5

/ # ping www.baidu.com
^C
/ # nslookup www.baidu.com
nslookup: can't resolve '(null)': Name does not resolve

**Comment by pansir1314** [comment]
遇到了相同的问题，请问有解决的方法吗？
