### ISSUE TITLE
calico网络问题

### ISSUE THREAD

**Issue by luolizhi** [easzlab/kubeasz#282]
**现象**：使用calico网络插件，jenkins（使用nodeport）无法访问，日志不报错，启动完成一直卡顿。
![image](https://user-images.githubusercontent.com/14789043/43817942-cda597de-9b0e-11e8-87f9-7fd13cc3035d.png)

**解决方案**：将calico换成flannel后成功访问。
**原因**：未知。还请知道的指点。

其它：

kibana和dashboard类似，无法通过kubectl cluster-info得到的地址访问，换成flannel可以访问。

**环境**
一主多从，ubuntu16.04，虚拟机是在openstack上创建。

**Comment by gjmzj** [comment]
在deploy节点上执行：
`ansible kube-node -m shell -a 'calicoctl node sttus'`
`ansible kube-master -m shell -a 'calicoctl node sttus'`
看看

**Comment by Mrhjx2** [comment]
我也是碰到同样的问题：
之前用的是flannel是集群内dns是可以通的，后来换成了calico后
在起coredns或者kubedns时报无法路由：
## Aug 16 16:14:46 k8s-n5 kube-proxy: I0816 16:14:46.137568   44025 service.go:310] Adding new service port "kube-system/kube-dns:dns" at 10.96.0.2:53/UDP
## Aug 16 16:14:46 k8s-n5 kube-proxy: I0816 16:14:46.137612   44025 service.go:310] Adding new service port "kube-system/kube-dns:dns-tcp" at 10.96.0.2:53/TCP
## Aug 16 16:14:47 k8s-n5 kube-proxy: I0816 16:14:47.421048   44025 proxier.go:637] Stale udp service kube-system/kube-dns:dns -> 10.96.0.2
## Aug 16 16:14:47 k8s-n5 kube-proxy: E0816 16:14:47.453644   44025 proxier.go:1319] Failed to delete stale service IP 10.96.0.2 connections, error: error deleting connection tracking state for UDP service IP: 10.96.0.2, error: error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH
## Aug 16 16:15:09 k8s-n5 kubelet: I0816 16:15:09.132097   43680 container_manager_linux.go:427] [ContainerManager]: Discovered runtime cgroups name: /system.slice/docker.service

集群的pod情况
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE       IP               NODE
default       nginx-768979984b-24c9m                     1/1       Running   0          34m       172.20.118.1     10.1.1.41
default       nginx1-6fcd4f9cfd-5mh8l                    1/1       Running   0          4m        172.20.215.67    10.1.1.21
default       nginx1-6fcd4f9cfd-gt6zt                    1/1       Running   0          4m        172.20.88.131    10.1.1.42
default       nginx1-6fcd4f9cfd-jpvb7                    1/1       Running   0          4m        172.20.111.195   10.1.1.22
default       test-76f97b47fb-2pz2b                      1/1       Running   0          2h        172.20.88.129    10.1.1.42
default       test-76f97b47fb-9nzns                      1/1       Running   0          2h        172.20.215.65    10.1.1.21
default       test-76f97b47fb-qkwxl                      1/1       Running   0          2h        172.20.57.193    10.1.1.23
kube-system   calico-kube-controllers-556b5f787d-j44zl   1/1       Running   0          4h        10.1.1.43        10.1.1.43
kube-system   calico-node-4dtkt                          2/2       Running   0          4h        10.1.1.41        10.1.1.41
kube-system   calico-node-6jsjp                          2/2       Running   0          4h        10.1.1.20        10.1.1.20
kube-system   calico-node-glgqt                          2/2       Running   0          4h        10.1.1.21        10.1.1.21
kube-system   calico-node-h9nxs                          2/2       Running   0          4h        10.1.1.43        10.1.1.43
kube-system   calico-node-hzmcv                          2/2       Running   0          4h        10.1.1.23        10.1.1.23
kube-system   calico-node-lljbg                          2/2       Running   0          4h        10.1.1.22        10.1.1.22
kube-system   calico-node-tql85                          2/2       Running   0          4h        10.1.1.40        10.1.1.40
kube-system   calico-node-trrn5                          2/2       Running   0          4h        10.1.1.42        10.1.1.42
kube-system   kube-dns-665f86b87c-b455m                  3/3       Running   0          13m       172.20.57.195    10.1.1.23
帮忙看看

**Comment by gjmzj** [comment]
#291
