### ISSUE TITLE
halm安装报错 Error: cannot connect to Tiller

### ISSUE THREAD

**Issue by zhaop33** [easzlab/kubeasz#284]
Error: cannot connect to Tiller
每个节点运行yum install socat命令也是一样

**Comment by zhaop33** [comment]
还有就是集成jenkins文档里面 的nfs-client一个链接失效了

**Comment by gjmzj** [comment]
你的helm是自己安装的，还是用项目的helm role安装的，先看下helm文档https://github.com/gjmzj/kubeasz/blob/master/docs/guide/helm.md
