### ISSUE TITLE
keepalived配置多于2个节点的bug

### ISSUE THREAD

**Issue by or0or1** [easzlab/kubeasz#286]
keepalived.conf 中设置

 unicast_peer {
        192.168.2.54192.168.2.56
    }

正确的应该是：
unicast_peer {
        192.168.2.54
        192.168.2.56
    }

**Comment by gjmzj** [comment]
lb节点建议1主1备2个节点就够了；所以不需要考虑 1主多备的lb设置；
当然你说的问题最新master 代码已经修复：
https://github.com/gjmzj/kubeasz/commit/ced4f34aae9d78e0abe7c2cbc80e04ba2667aba5
https://github.com/gjmzj/kubeasz/commit/0fb1f7ddf37a5b270262f12799febf466930144e
感谢提出问题

**Comment by gjmzj** [comment]
提出问题，请尽量跟踪反馈下，是否解决了自己的问题。。。
