### ISSUE TITLE
calico网络问题

### ISSUE THREAD

**Issue by mrhjx2** [easzlab/kubeasz#291]
IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 10.1.1.27    | node-to-node mesh | up    | 03:47:16 | Established |
| 10.1.1.40    | node-to-node mesh | up    | 03:47:16 | Established |
| 10.1.1.22    | node-to-node mesh | up    | 03:47:15 | Established |
| 10.1.1.23    | node-to-node mesh | up    | 03:47:15 | Established |
| 10.1.1.41    | node-to-node mesh | up    | 03:47:15 | Established |
| 10.1.1.42    | node-to-node mesh | up    | 03:47:15 | Established |
| 10.1.1.43    | node-to-node mesh | up    | 03:47:15 | Established |
+--------------+-------------------+-------+----------+-------------+

这个10.1.1.27是vip
而没有绑定节点ip，导致无法跳转过去
通过etcd可以修改回到节点ip吗

**Comment by gjmzj** [comment]
这个问题最新代码已经修复了；
如果已经出这个问题了，可以用两步修复

**Comment by gjmzj** [comment]
提出问题，请尽量跟踪反馈下，是否解决了问题。。。
