### ISSUE TITLE
grafana 安装问题

### ISSUE THREAD

**Issue by longlong2018** [easzlab/kubeasz#292]
helm 安装prometheus没有问题，但通过helm安装grafana时报错：
Error: render error in "grafana/templates/deployment.yaml": template: grafana/templates/deployment.yaml:109:20: executing "grafana/templates/deployment.yaml" at <$value>: wrong type for value; expected map[string]interface {}; got string

麻烦大神帮忙看看

**Comment by gjmzj** [comment]
你使用的是什么k8s版本，刚我试了1.11.2版本没啥问题
