### ISSUE TITLE
关于云上贵州（公有云）多master多node节点问题

### ISSUE THREAD

**Issue by Candyient** [easzlab/kubeasz#295]
你好，有个问题。虚拟机申请在云上贵州公有云，配置多master多node。在配置Master VIP时，把lb地址写成了master的外网地址，master vip 写了同网段的另一个外网地址，结果node无法访问vip 8443端口。请问，ib地址是配置为mater的内网地址还是外网地址，同时master vip 地址是配置为内网地址还是外网地址，需要从外网访问

**Comment by gjmzj** [comment]
lb节点要用内网地址，master vip也要用内网的地址；
但是一般公有云上是不允许自行创建VIP的，因此公有云上LB节点一般不要设置，直接用云上的负载均衡，配置完后吧负载均衡的监听地址作为master vip，然后进行集群安装

**Comment by gjmzj** [comment]
公有云上注意node节点之间网络访问，安全组规则要放开

**Comment by neo-feng** [comment]
@gjmzj 新年好， 我碰到类似问题 看到该回复终于知道在云上不需要自己配置lb， 按照提示 我在阿里云上做了如下操作
1. 创建内网负载均衡 地址 172.19.89.212， 监听端口8443， 后台对应虚拟服务器 两台 213:6443/216:6443
2. hosts文件内将masterip设置为172.19.89.212
部署到步骤kubemaster -- 执行/kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap时报错：Unable to connect to the server: dial tcp 172.19.89.212:8443: i/o timeout。
负载均衡访问控制并未开启，213和216两台的8443和6443端口均已开放。

目前没有思路怎么解决此问题， 任何建议都非常感谢

**Comment by gjmzj** [comment]
@neo-feng 你的kubeasz是不是没更新，之前为了配合公有云上安装，代码专门优化过的

**Comment by neo-feng** [comment]
@gjmzj 确实没有更新，我用的是去年9月份的版本，我更新merge一下再试试看。确认一下，优化过后的版本是支持公有云ecs直接部署lb+vip 还是必须要用公有云的负载均衡？

**Comment by neo-feng** [comment]
@gjmzj 已经merge了最新版本， 看到了最新的针对cloud的exmple host。重新执行后到kubemaster一步 - /opt/kube/bin/kubectl label node 172.19.89.216  时 会报错 -- Unable to connect to the server: dial tcp 172.19.89.212:8443。 查看journalctl -u kube-apiserver 发现如下报错： http: TLS handshake error from 100.116.69.129:32858: read tcp 172.19.89.213:6443->100.116.69.129:32858: read: connection reset by peer。 执行 kubectl get node也会报Unable to connect to the server: dial tcp 172.19.89.212:8443。
 
任何建议和线索都非常感谢

**Comment by neo-feng** [comment]
@gjmzj 刚刚看到关于云上部署的guide，以下部分应该就是我上述问题的解释。非常感谢博主的付出。
···
4. 部分云厂商负载均衡使用四层负载模式时不支持添加进后端云服务器池的 ECS 既作为 Real Server，又作为客户端向所在的 SLB 实例发送请求；因此注意不要在 master节点执行 kubectl，会出现时通时不通的情况；
···

**Comment by 240325184** [comment]
> @gjmzj 刚刚看到关于云上部署的guide，以下部分应该就是我上述问题的解释。非常感谢博主的付出。
> ···
> 4. 部分云厂商负载均衡使用四层负载模式时不支持添加进后端云服务器池的 ECS 既作为 Real Server，又作为客户端向所在的 SLB 实例发送请求；因此注意不要在 master节点执行 kubectl，会出现时通时不通的情况；
> ···

问下这种问题如何解决呢，如果在公有云上部署。

**Comment by huanzui** [comment]
> @gjmzj 刚刚看到关于云上部署的guide，以下部分应该就是我上述问题的解释。非常感谢博主的付出。
> ···
> 4. 部分云厂商负载均衡使用四层负载模式时不支持添加进后端云服务器池的 ECS 既作为 Real Server，又作为客户端向所在的 SLB 实例发送请求；因此注意不要在 master节点执行 kubectl，会出现时通时不通的情况；
> ···

我这边也出现这种情况，在阿里云上用SLB后，在两个master节点kubectl get node 后时通时不通的情况，其它服务器是交叉返回两个master节点的内容

**Comment by gjmzj** [comment]
@huanzui 新版本kubeasz 2.x.x 自身高可用又不依赖外部slb的；可以阅读最新的文档
