### ISSUE TITLE
- import_tasks: debian.yml发生错误

### ISSUE THREAD

**Issue by yuxiaoba** [easzlab/kubeasz#318]
root@R740-1-1:/etc/ansible# ansible-playbook 01.prepare.yml
ERROR! no action detected in task

The error appears to have been in '/etc/ansible/roles/prepare/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

## 系统基础软件环境
- import_tasks: debian.yml
  ^ here
请问这里的ansible_distribution哪里配置啊？

**Comment by gjmzj** [comment]
你的ansible版本是不是太低？

**Comment by R1hug0** [comment]
我也碰到了这个错误,是什么原因呢 

> 
> 
> root@R740-1-1:/etc/ansible# ansible-playbook 01.prepare.yml
> ERROR! no action detected in task
> 
> The error appears to have been in '/etc/ansible/roles/prepare/tasks/main.yml': line 2, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> ## 系统基础软件环境
> 
>     * import_tasks: debian.yml
>       ^ here
>       请问这里的ansible_distribution哪里配置啊？

**Comment by yuxiaoba** [comment]
@R1hug0 你看看是不是节点上没有安装python 环境吧，很久了我也忘了怎么搞的了
