### ISSUE TITLE
安装harbor出现问题

### ISSUE THREAD

**Issue by aminglinux** [easzlab/kubeasz#321]
TASK [harbor : 安装 harbor] *******************************************************************************************************************************************************************
fatal: [172.7.15.117]: FAILED! => {"changed": true, "cmd": "cd /data/harbor && export PATH=/opt/kube/bin:$PATH && ./install.sh --with-clair", "delta": "0:02:24.719375", "end": "2018-09-11 11:01:09.511073", "msg": "non-zero return code", "rc": 1, "start": "2018-09-11 10:58:44.791698", "stderr": "tput: No value for $TERM and no -T specified\ntput: No value for $TERM and no -T specified\ntput: No value for $TERM and no -T specified\ntput: No value for $TERM and no -T specified\ntput: No value for $TERM and no -T specified\ntput: No value for $TERM and no -T specified\ntput: No value for $TERM and no -T specified\ntput: No value for $TERM and no -T specified\nTraceback (most recent call last):\n  File \"./prepare\", line 222, in <module>\n    validate(rcp, args)\n  File \"./prepare\", line 81, in validate\n    redis_host = rcp.get(\"configuration\", \"redis_host\")\n  File \"/usr/lib64/python2.7/ConfigParser.py\", line 340, in get\n    raise NoOptionError(option, section)\nConfigParser.NoOptionError: No option u'redis_host' in section: u'configuration'", "stderr_lines": ["tput: No value for $TERM and no -T specified", "tput: No value for $TERM and no -T specified", "tput: No value for $TERM and no -T specified", "tput: No value for $TERM and no -T specified", "tput: No value for $TERM and no -T specified", "tput: No value for $TERM and no -T specified", "tput: No value for $TERM and no -T specified", "tput: No value for $TERM and no -T specified", "Traceback (most recent call last):", "  File \"./prepare\", line 222, in <module>", "    validate(rcp, args)", "  File \"./prepare\", line 81, in validate", "    redis_host = rcp.get(\"configuration\", \"redis_host\")", "  File \"/usr/lib64/python2.7/ConfigParser.py\", line 340, in get", "    raise NoOptionError(option, section)", "ConfigParser.NoOptionError: No option u'redis_host' in section: u'configuration'"], "stdout": "\n[Step 0]: checking installation environment ...\n\nNote: docker version: 18.03.1\n\nNote: docker-compose version: 1.21.2\n\n[Step 1]: loading Harbor images ...\nLoaded image: goharbor/harbor-adminserver:v1.6.0\nLoaded image: goharbor/redis-photon:v1.6.0\nLoaded image: goharbor/nginx-photon:v1.6.0\nLoaded image: goharbor/registry-photon:v2.6.2-v1.6.0\nLoaded image: goharbor/notary-server-photon:v0.5.1-v1.6.0\nLoaded image: goharbor/notary-signer-photon:v0.5.1-v1.6.0\nLoaded image: goharbor/harbor-ui:v1.6.0\nLoaded image: goharbor/harbor-log:v1.6.0\nLoaded image: goharbor/harbor-db:v1.6.0\nLoaded image: goharbor/harbor-jobservice:v1.6.0\nLoaded image: goharbor/clair-photon:v2.0.5-v1.6.0\nLoaded image: goharbor/harbor-migrator:v1.6.0\nLoaded image: goharbor/chartmuseum-photon:v0.7.1-v1.6.0\n\n\n[Step 2]: preparing environment ...", "stdout_lines": ["", "[Step 0]: checking installation environment ...", "", "Note: docker version: 18.03.1", "", "Note: docker-compose version: 1.21.2", "", "[Step 1]: loading Harbor images ...", "Loaded image: goharbor/harbor-adminserver:v1.6.0", "Loaded image: goharbor/redis-photon:v1.6.0", "Loaded image: goharbor/nginx-photon:v1.6.0", "Loaded image: goharbor/registry-photon:v2.6.2-v1.6.0", "Loaded image: goharbor/notary-server-photon:v0.5.1-v1.6.0", "Loaded image: goharbor/notary-signer-photon:v0.5.1-v1.6.0", "Loaded image: goharbor/harbor-ui:v1.6.0", "Loaded image: goharbor/harbor-log:v1.6.0", "Loaded image: goharbor/harbor-db:v1.6.0", "Loaded image: goharbor/harbor-jobservice:v1.6.0", "Loaded image: goharbor/clair-photon:v2.0.5-v1.6.0", "Loaded image: goharbor/harbor-migrator:v1.6.0", "Loaded image: goharbor/chartmuseum-photon:v0.7.1-v1.6.0", "", "", "[Step 2]: preparing environment ..."]}

harbor 版本  1.6.0

**Comment by gjmzj** [comment]
harbor 1.6.0 还未测试支持，最新是支持到1.5.2

**Comment by better0332** [comment]
能换用这里的吗？https://github.com/goharbor/harbor-helm
