### ISSUE TITLE
推荐一个helm charts的镜像地址，阿里的镜像地址更新的并不是很及时，这个很及时

### ISSUE THREAD

**Issue by loverto** [easzlab/kubeasz#327]
镜像地址

https://burdenbear.github.io/kube-charts-mirror/

**Comment by gjmzj** [comment]
谢谢
我一般是直接把 https://github.com/helm/charts 直接git pull到本地了 :)

**Comment by yoli799480165** [comment]
http://mirror.azure.cn/kubernetes/charts/
微软的比较新
