### ISSUE TITLE
云功能与gpu支持

### ISSUE THREAD

**Issue by kaka-milan-22** [easzlab/kubeasz#330]
项目目前，没有支持云的一些功能，cloudprovider=aws,还希望支持gpu功能。希望可以早些支持。

**Comment by gjmzj** [comment]
目前我打算写个较详细的公有云部署kubeasz文档，看看按文档方式能否在aws创建，gpu目前个人没有计划

**Comment by zhangkaka** [comment]
gpu,我试着修改一下吧
