### ISSUE TITLE
使用kubenetes的hpa时，发现target为unknown

### ISSUE THREAD

**Issue by samlyhuang** [easzlab/kubeasz#331]
` [root@server1 ~]# kubectl get hpa php-apache`
`NAME                          REFERENCE               TARGETS         MINPODS   MAXPODS   REPLICAS   AGE`
`php-apache   Deployment/php-apache   <unknown>/50%   1                   10                 1           8m`

##### 不知这个是什么原因？

**Comment by huruizhi** [comment]
为什么master与worker不能在一台服务器上部署？

**Comment by gjmzj** [comment]
@samlyhuang 备注下你环境的信息，比如k8s版本，安装的集群常用组件（kubectl get pod -n kube-system），另外hpa target unknown是需要几分钟以后才会变化。

@huruizhi 可以在一台服务器上部署啊，allinone部署，可以查看项目的快速指南

**Comment by junly917** [comment]
我也遇到了同样的问题
1. 版本信息
 ~# kubectl version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

2. controller-manager 配置
~# cat /etc/systemd/system/kube-controller-manager.service 
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/opt/kube/bin/kube-controller-manager \
  --address=127.0.0.1 \
  --allocate-node-cidrs=true \
  --cluster-cidr=172.24.0.0/16 \
  --cluster-name=kubernetes \
  --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem \
  --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem \
  --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig \
  --leader-elect=true \
  --node-cidr-mask-size=24 \
  --root-ca-file=/etc/kubernetes/ssl/ca.pem \
  --service-account-private-key-file=/etc/kubernetes/ssl/ca-key.pem \
  --service-cluster-ip-range=10.68.0.0/16 \
  --use-service-account-credentials=true \
  --horizontal-pod-autoscaler-use-rest-clients=false \
  --v=2
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

3. deploy 配置部分
...
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tomcat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tomcat
    spec:
      containers:
      - image: tomcat:9
        imagePullPolicy: IfNotPresent
        name: tomcat
        ports:
        - containerPort: 8080
          name: data
          protocol: TCP
        resources:
          requests:
            cpu: 1m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
...
5.  metrics-server.yaml  镜像版本信息和args参数
container.metrrics-server
image: mirrorgooglecontainers/metrics-server-amd64:v0.3.6        
Args:                                                                                                                                                                                 │
│       --cert-dir=/tmp                                                                                                                                                                     │
│       --secure-port=4443                                                                                                                                                                  │
│       --kubelet-insecure-tls                                                                                                                                                              │
│       --kubelet-preferred-address-types=InternalIP                                                                                                                                                                                                                             

7. 获取资源信息
~# kubectl top pods tomcat-6bcd8d8f94-2rkwb
NAME                      CPU(cores)   MEMORY(bytes)   
tomcat-6bcd8d8f94-2rkwb   11m          172Mi       
    
kubectl top nodes 192.168.0.241
NAME            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
192.168.0.241   3555m        16%    18430Mi         58%       

8. hpa的的Target是unknown 状态
~# kubectl get hpa 
NAME     REFERENCE           TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
tomcat   Deployment/tomcat   <unknown>/10%   1         10        1          7m48s

~# kubectl describe hpa  tomcat
Name:                                                  tomcat
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 22 Nov 2022 17:55:23 +0800
Reference:                                             Deployment/tomcat
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 10%
Min replicas:                                          1
Max replicas:                                          10
Deployment pods:                                       1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Events:
  Type     Reason                        Age                     From                       Message
  ----     ------                        ----                    ----                       -------
  Warning  FailedComputeMetricsReplicas  5m41s (x12 over 8m29s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
  Warning  FailedGetResourceMetric       3m24s (x21 over 8m29s)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)

这个问题如何来解决..
