### ISSUE TITLE
harbor项目用nginx反向代理至公网报错

### ISSUE THREAD

**Issue by kaka-milan-22** [easzlab/kubeasz#332]
[root@laopang-t1 multi-user.target.wants]# telnet harbor.k8s.com 443
Trying x.x.x.x..
Connected to harbor.k8s.com.
Escape character is '^]'.
^]

telnet> quit
Connection closed.
[root@laopang-t1 multi-user.target.wants]# docker login harbor.k8s.com
Username: admin
Password:
Error response from daemon: Get https://harbor.k8s.com/v2/: Get https://10.0.2.35/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

**Comment by gjmzj** [comment]
nginx 反向代理harbor，如果要启用https，一般是这样做：
证书安装在nginx上，后端harbor只启用http

**Comment by zhangkaka** [comment]
不是证书的问题，是harbor.cfg.json hostname = {{ inventory_hostname }},改为harbor的域名，然后，把域名加入,harbor的host主机，则可以外网，可以下常访问，inventory_hostname 默认为host的内网ip,在ansible的host中配置的。

**Comment by SheldonXLD** [comment]
> 
> 
> 不是证书的问题，是harbor.cfg.json hostname = {{ inventory_hostname }},改为harbor的域名，然后，把域名加入,harbor的host主机，则可以外网，可以下常访问，inventor�y_hostname 默认为host的内网ip,在ansible的host中配置的。

是否已经成功搭建成功了呢？
我自己搭建了下，docker login 域名 一直不成功，您这边有没有一些步骤指导手册呢？
