### ISSUE TITLE
安装执行到 获取csr 请求信息 kubectl get csr 时，报错

### ISSUE THREAD

**Issue by klgd** [easzlab/kubeasz#335]
```
TASK [kube-node : 获取csr 请求信息] ************************************************************************************************************************************************************************************************************************************************
fatal: [172.168.1.100 -> 172.168.1.100]: FAILED! => {"changed": true, "cmd": "sleep 3 && /opt/kube/bin/kubectl get csr", "delta": "0:00:04.485564", "end": "2018-10-09 15:05:39.298273", "msg": "non-zero return code", "rc": 1, "start": "2018-10-09 15:05:34.812709", "stderr": "error: the server doesn't have a resource type \"csr\"", "stderr_lines": ["error: the server doesn't have a resource type \"csr\""], "stdout": "", "stdout_lines": []}
```

手动执行
```sh
[root@k8s-m-100 ansible]# /opt/kube/bin/kubectl get csr
No resources found.
```
网上搜了一下，好像跟 TLS Bootstrapping 有关，不知道是不是这个 commit 导致
https://github.com/gjmzj/kubeasz/commit/cdf778b6aba5887077f4c4f62b52430ff303e3bb

**Comment by gjmzj** [comment]
是最新kubeasz的代码吗? 取消 TLS Bootstrap 跟这个没有关系

**Comment by klgd** [comment]
@gjmzj 对 是最新的master

**Comment by klgd** [comment]
@gjmzj 昨天还是原样的东西又重新安装了，结果成功了，后来重复安装了几次（都是全新环境），有成功有失败
我觉得可能是网络原因，有没有可能是在启动 `kubelet` 时  mirrorgooglecontainers/pause-amd64 pull失败导致的呢

**Comment by koala2012** [comment]
@gjmzj 我也遇到相同问题，重试很多次，还是不能通过，k8s版本是1.11

TASK [kube-node : 获取csr 请求信息] **********************************************************************************************************************
fatal: [172.16.62.167 -> 172.16.62.167]: FAILED! => {"changed": true, "cmd": "sleep 3 && /opt/kube/bin/kubectl get csr", "delta": "0:00:05.644438", "end": "2018-10-14 05:54:20.855988", "msg": "non-zero return code", "rc": 1, "start": "2018-10-14 05:54:15.211550", "stderr": "error: the server doesn't have a resource type \"csr\"", "stderr_lines": ["error: the server doesn't have a resource type \"csr\""], "stdout": "", "stdout_lines": []}

**Comment by windghoul** [comment]
我也是执行kubectl get csr 报错，报错原因是没有任何resource，kubenetes 二进制版本1.11.3

**Comment by windghoul** [comment]
> 我也是执行kubectl get csr 报错，报错原因是没有任何resource，kubenetes 二进制版本1.11.3

TASK [kube-csr : approve-kubelet-csr 认证] ********************************************
fatal: [10.151.160.21]: FAILED! => {"changed": true, "cmd": "/usr/bin/kubectl get csr|grep 'Pending' | awk 'NR>0{print $1}'| xargs /usr/bin/kubectl certificate approve", "delta": "0:00:00.127357", "end": "2018-10-30 03:47:29.357316", "msg": "non-zero return code", "rc": 123, "start": "2018-10-30 03:47:29.229959", "stderr": "No resources found.\nerror: one or more CSRs must be specified as <name> or -f <filename>", "stderr_lines": ["No resources found.", "error: one or more CSRs must be specified as <name> or -f <filename>"], "stdout": "", "stdout_lines": []}

**Comment by yaoshifo** [comment]
TASK [kube-node : 获取csr 请求信息] ***********************************************************************
task path: /home/hanming/orion_playbook/roles/kube-node/tasks/main.yml:98
fatal: [10.xx.119.xx -> 10.xx.119.xx]: FAILED! => {"changed": true, "cmd": "sleep 20 && /opt/kube/bin/kubectl get csr", "delta": "0:00:22.520045", "end": "2018-11-23 16:31:26.685974", "msg": "non-zero return code", "rc": 1, "start": "2018-11-23 16:31:04.165929", "stderr": "error: the server doesn't have a resource type \"csr\"", "stderr_lines": ["error: the server doesn't have a resource type \"csr\""], "stdout": "", "stdout_lines": []}

**Comment by yaoshifo** [comment]
me too.

**Comment by kitepad** [comment]
me too.

**Comment by kitepad** [comment]
再执行一次，就不报错了。

**Comment by lixianyang** [comment]
感觉 csr 只有 kubelet 需要使用 apiserver 代理签名的时候需要，项目目前的方式是直接通过 cfssl 用 ca 证书去签名，就不需要执行 kubectl get csr 和 approve-kubelet-csr 的步骤，默认注册上就是 Ready 的 @gjmzj

**Comment by gjmzj** [comment]
@lixianyang 确实如此，kubeasz 0.3.1之后的版本取消了 Node节点 Bootstrap机制，因此没有csr请求了

**Comment by 2714222609** [comment]
localhost解析不到127.0.01，apiserver没有起来，在/etc/hosts里添加127.0.0.1   localhost 后重试即可

**Comment by 2714222609** [comment]
localhost解析不到127.0.0.1，apiserver没有起来，在/etc/hosts里添加127.0.0.1 localhost 后重试即可
