### ISSUE TITLE
关于k8s flannel的部署方式问题

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#336]
我看ansible现在部署flannel插件使用kubectl yaml 资源文件方式, 我想使用二进制方式部署更能体现安装的每个部署流程,  加深用户对于插件的安装过程体验,  建议后期能不能把flannel的部署方式改成跟etcd 以及docker一样的二进制方式部署呢？  既然是二进制打包部署不如就都搞成二进制实现真正的离线部署,镜像部署的话用户还要了解你的镜像制作过程以及启动的参数

**Comment by Hello-Linux** [comment]
官方的kubeadm现在使用的是容器部署flannel 但是我感觉ansible还是用二进制比较直观
![1](https://user-images.githubusercontent.com/17851645/46665117-77ac3280-cbf5-11e8-925e-1491ecfe6651.png)

**Comment by ilibx** [comment]
嗯嗯，这个确实需要阅读文档之后，才能了解它里面需要配置什么内容

**Comment by xiaozhiqi2000** [comment]
容器部署flannel网络插件，使用CNI插件方式，部署calico的时候好像只能用CNI的方式部署。这样能通用一些。使用flannel网络功能，calico的网络策略，这种结合的方式值得试试

**Comment by Hello-Linux** [comment]
我还是建议用传统的二进制方式 方便新入门用户

**Comment by gjmzj** [comment]
确实主要是考虑cni daemonset的方式通用性比较好；项目有个分支`closed`就是使用二进制方式部署flannel的
