### ISSUE TITLE
添加新节点后域名无法解析，老节点可以正常解析

### ISSUE THREAD

**Issue by xylb12** [easzlab/kubeasz#352]
执行 ansible-playbook 20.addnode.yml添加新节点，节点添加成功后，新节点上创建的POD域名解析失败

[root@centos7 ~]# kubectl get node
NAME             STATUS                     ROLES     AGE       VERSION
192.168.38.200   Ready,SchedulingDisabled   master    3h        v1.11.0
192.168.38.201   Ready                      node      3h        v1.11.0
192.168.38.202   Ready                      node      3h        v1.11.0
192.168.38.205   Ready                      node      1h        v1.11.0

[root@centos7 ~]# kubectl get pod -o wide
NAME                      READY     STATUS    RESTARTS   AGE       IP               NODE
nginx-1-b5ddccc9f-sh2bx   1/1       Running   0          1h        172.20.129.143   192.168.38.205

[root@centos7 ~]# kubectl exec -it nginx-1-b5ddccc9f-sh2bx -- ping kube-dns.kube-system
ping: unknown host
command terminated with exit code 1

老节点域名解析正常

**Comment by gjmzj** [comment]
用了什么网络插件，是否是公有云机器；会不会是新的节点与dns所在的节点之间网络被隔离了

**Comment by xylb12** [comment]
使用的是calico网络，dns使用coredns，不是公有云的机器，节点之间都是二层网，在私有云上测试有这个情况，然后在vmware里面也是新节点域名解析失败。
奇怪的是，我今天什么也没做，域名可以解析了。
