### ISSUE TITLE
kubelet无法进入Pod以及查看pod日志

### ISSUE THREAD

**Issue by xiyangxixi** [easzlab/kubeasz#359]
我使用您的添加node的脚本添加了3个node，在测试中发现，凡是在新添加的3个node上的pod均无法使用kubectl logs pod_name查看日志，无法通过kubectl exec -it进入Pod，提示error: You must be logged in to the server (the server has asked for the client to provide credentials或error: unable to upgrade connection: Unauthorized。经个人排查一段时间后仍无法解决。请您看一下。谢谢！

**Comment by gjmzj** [comment]
是不是你之前的集群是很早时间安装的，最近更新了kubeasz代码，然后最近添加Node出现问题？
或者还有其他特殊的情况，你说的现象在正常的安装中不会存在的。

**Comment by xiyangxixi** [comment]
我这里是今年6月拉取下来的kubeasz代码 未更新至最新 所以采用的是6月份的代码 不知道会不会是这个原因

**Comment by gjmzj** [comment]
集群创建以后，kubeasz代码不用去更新；只要确保你创建集群时使用的kubeasz代码跟后续添加节点时的代码一致，应该不会有问题
