### ISSUE TITLE
阿里云服务器安装问题

### ISSUE THREAD

**Issue by xiawanyingtest** [easzlab/kubeasz#365]
**1.阿里云系统版本**
   centos7.4,k8s 1.12
单机，没有购买任何负载slb服务，etc/ansible/hosts中ip设置的为内网地址172.16.119.*
**2.错误信息**
fatal: [172.16.119.8 -> 172.16.119.8]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/opt/kube/bin/kubectl", "get", "node"], "delta": "0:00:00.096254", "end": "2018-11-08 15:59:51.663207", "msg": "non-zero return code", "rc": 1, "start": "2018-11-08 15:59:51.566953", "stderr": "The connection to the server 172.16.119.8:8443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server 172.16.119.8:8443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}

**3.问题：**
   （1）是不是因为我公有云部署不对，我是把公有云部署集群版的配置文件在example中的改成单机版的，公有云部署有单机版的吗？
     (2)   阿里公有云是不是不支持部署单机版的？

**Comment by gjmzj** [comment]
在公有云上部署`单节点`和`单主多节点`集群的节点规划与自有环境没有差异;
你只要按照example/hosts.allinone.example 的模板修改下IP即可

**Comment by gjmzj** [comment]
@TophillZK kubeasz 需要在deploy节点ssh免密码登陆其他所有节点，并且必须为root用户，是否是因为这个原因

**Comment by TophillZK** [comment]
@gjmzj 
1、在10.20.54.1设备上做了如下操作
ssh-copy-id 10.20.54.1
ssh-copy-id 10.20.54.10
2、测试了 ssh 10.20.54.1 和 ssh 10.20.54.10 都可以以root用户正常登录
3、在10.20.54.1使用远程同步操作（也就是报错语句部分的命令）
/usr/bin/rsync --rsh=/usr/bin/ssh /root/123 10.20.54.10:/root/123
在10.20.54.10主机上检查确认是同步过去了
4、报错的语句有部分被github给转义了， "--out-format=<<CHANGED>>%i %n%L"
5、两台设备操作系统版本“CentOS Linux release 7.4.1708”，还有我使用的hosts模版为hosts.s-master.example。还有单节点部署没有问题。

上述为我这边能够提供的情况，请大神帮忙看看问题出在哪儿，如果还需要我提供其他信息也请告诉我，谢谢~~
