### ISSUE TITLE
efk相关 

### ISSUE THREAD

**Issue by shfpflyawei** [easzlab/kubeasz#368]
通过nfs 创建静态efk 时, es镜像无法启动   日志提示启动到 
+ export NODE_NAME=elasticsearch-logging-0
+ NODE_NAME=elasticsearch-logging-0
+ export NODE_MASTER=true
+ NODE_MASTER=true
+ export NODE_DATA=true
+ NODE_DATA=true
+ export HTTP_PORT=9200
+ HTTP_PORT=9200
+ export TRANSPORT_PORT=9300
+ TRANSPORT_PORT=9300
+ export MINIMUM_MASTER_NODES=2
+ MINIMUM_MASTER_NODES=2
+ chown -R elasticsearch:elasticsearch /data
chown: changing ownership of '/data': Invalid argument

chown 这步出错  能否将Docker file发下我重新创建镜像 将chown 这步去掉？ 我可以直接把nfs 目录授权给elasticsearch:elasticsearch

**Comment by gjmzj** [comment]
你的问题感觉不是目录问题，Docker file为官方的，我没有做定制：https://github.com/kubernetes/kubernetes/blob/release-1.8/cluster/addons/fluentd-elasticsearch/es-image/Dockerfile
