### ISSUE TITLE
kubelet和kube-proxy不应该访问 localhost 

### ISSUE THREAD

**Issue by zhangguanzhang** [easzlab/kubeasz#370]
kubectl和各组件访问localhost的话有单点

**Comment by gjmzj** [comment]
项目多master安装的话，是用keepalive+haproxy实现多master的HA；
你如果没有配置成功的话，是否是因为机器环境不干净，或者/etc/ansible/hosts配置文件有问题？

**Comment by zhangguanzhang** [comment]
你master上的组件访问的都是localhost，正确姿势是访问VIP

**Comment by SmileSees** [comment]
@gjmzj 我在azure上面又两个master，我可以把vip设置成这两个master当中的一个吗？会有什么影响吗？

**Comment by zhangguanzhang** [comment]
无论非公有云还是公有云，公有云我在SDN取消了网卡的mac和ip绑定后照样用vip一样用

**Comment by SmileSees** [comment]
@zhangguanzhang @gjmzj 谢谢。
@gjmzj 这个确实看起来可行，不过暂时没有权限做这个。
@zhangguanzhang 你说的那个取消mac和ip绑定有参考吗？vip设置在hosts里面的时候找一个同一网段下不可达的ip吗，是随便取得吗？

**Comment by zhangguanzhang** [comment]
我这就是搞公有云的,不拿公有云来说vip选一个没用的ip即可，让vip飘在master上即可

**Comment by SmileSees** [comment]
@gjmzj 我觉得ha master是不是可以只在一台机器上装control manager和 scheduler，然后只是每一台都装apiserver？

**Comment by TimeBye** [comment]
Kubenertes安装脚本在Github上遍地开花，有使用kubeadm安装的、使用docker镜像安装的、二进制安装的各式各样，并不仅仅是本项目。实际应用场景又繁多复杂，再加上作者也无法实际部署和兼容所有场景，项目由作者一个人来完善难免有疏忽的地方，开源项目需要大家共同的努力来维护它，使它更加强大。

在Kubenertes这条路上我们可能还会遇到很多的问题，所以我们应该清醒和全面地认识它并解决它，再在此基础上总结经验与大家进行分享。

提出问题与大家进行讨论这是很好的事情，但也请虚心的进行交流，不要造成一些“语感”的不适，这样就不好了。

所以，同学们希望您在使用此项目时，也能为此项目做做贡献[提交PR](https://github.com/gjmzj/kubeasz/blob/master/docs/mixes/HowToContribute.md)，使它变得更好更完美。
