### ISSUE TITLE
AWS EC2上执行报错

### ISSUE THREAD

**Issue by Code2Life** [easzlab/kubeasz#378]
报错信息: (另外还有一个已经解决的问题, 如果ansible用 -b --become-user root 参数来执行的话, 在main.yml的mv kube-proxy.kubeconfig 写死了 /root/kube-proxy.kubeconfig 路径, 但是实际上生成的文件在/home/ec2-user下, 是否需要改成模板更好一些)

TASK [deploy : 复制 manifests至 deploy节点] *******************************************************************************************************************
fatal: [192.168.78.75]: FAILED! => {"msg": "The conditional check 'ansible_env['SSH_CLIENT'].split(' ')[0] != inventory_hostname' failed. The error was: error while evaluating conditional (ansible_env['SSH_CLIENT'].split(' ')[0] != inventory_hostname): 'dict object' has no attribute 'SSH_CLIENT'\n\nThe error appears to have been in '/etc/ansible/roles/deploy/tasks/main.yml': line 100, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# --- 以下为兼容ansible执行节点与deploy节点分离情况-------\n- name: 复制 manifests至 deploy节点\n  ^ here\n"}

**Comment by gjmzj** [comment]
1. 可以用 ~ 来代替 /root
2.是不是ansible版本不对？报错说没有 SSH_CLIENT 属性，你可以用如下命令查看下：
```
ansible deploy -m setup > tmp.out
grep 'SSH_CLIENT' tmp.out
```

**Comment by xiuxiu** [comment]
我约遇到了一样的问题，在一台Ubuntu上尝试给自己安装k8s，SSH_CLIENT说找不到，请问问题解决了吗？

**Comment by gjmzj** [comment]
ubuntu 装完默认使用的普通用户；
su - root 切换到root用户，并且修改下 /etc/ssh/sshd_config 文件中 "PermitRootLogin yes"后保存重启sshd（systemctl restart sshd） 
以后用root登陆操作即可

**Comment by ZLZhang1** [comment]
按照 https://stackoverflow.com/questions/34560622/best-way-to-get-the-ip-address-of-the-ansible-control-machine 这里的说法，使用become以后就拿不到ssh-client参数了，ansible deploy -m setup的输出也确实没有这个参数。
把 roles/deploy/tasks/main.yml 中的 ansible_env['SSH_CLIENT'].split(' ')[0] 替换成 'ansible_all_ipv4_addresses'[0] 后正常跑通了

**Comment by crazy-canux** [comment]
TASK [deploy : 移动 kube-proxy.kubeconfig] ***************************************************************************************************
fatal: [10.103.239.40]: FAILED! => {"changed": true, "cmd": "mv ~/kube-proxy.kubeconfig /etc/kubernetes/", "delta": "0:00:00.023248", "end": "2019-04-24 10:04:23.521374", "msg": "non-zero return code", "rc": 1, "start": "2019-04-24 10:04:23.498126", "stderr": "mv: cannot stat '/root/kube-proxy.kubeconfig': No such file or directory", "stderr_lines": ["mv: cannot stat '/root/kube-proxy.kubeconfig': No such file or directory"], "stdout": "", "stdout_lines": []}

为什么我改成 ～ 用的是 -b 怎么还是 /root
