### ISSUE TITLE
部署ingress-service的负载均衡--说明文档有误

### ISSUE THREAD

**Issue by ilanni2460** [easzlab/kubeasz#382]
docs/guide/ingress.md文档中，有关部署`ingress-service`的负载均衡，
- 1. 修改 `roles/lb/vars/main.yml` 文件，设置 `INGRESS_NODEPORT_LB: "yes"`

这行中的roles/lb/vars/main.yml，实际应该是roles/lb/defaults/main.yml

**Comment by gjmzj** [comment]
谢谢，近期会更新ingress文档，还会包括 ingress https的例子

**Comment by duanzhanling** [comment]
好啊，很不错呢。
能不能更新下nginx-ingress相关的例子呢？
traefik真心不熟悉呢
