### ISSUE TITLE
新安装完成后无法访问集群地址10.68.0.1

### ISSUE THREAD

**Issue by qq516249940** [easzlab/kubeasz#393]
这里是我的路由，CNI组件状态是起来的。
[root@http ansible]# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    100    0        0 eth0
10.0.60.0       0.0.0.0         255.255.255.0   U     100    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-6d3f1ea4b920
172.19.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-33d37d9728d5
172.20.248.128  0.0.0.0         255.255.255.192 U     0      0        0 *
172.20.248.129  0.0.0.0         255.255.255.255 UH    0      0        0 cali9dcfc4f7d5e
172.20.248.130  0.0.0.0         255.255.255.255 UH    0      0        0 calibcb13c6d05a
172.20.248.131  0.0.0.0         255.255.255.255 UH    0      0        0 cali0a68ffa356c

172.20.248.132  0.0.0.0         255.255.255.255 UH    0      0        0 cali02986a6d2f9
172.21.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-e3714bddecff

**上面路由上也没有走10.68.0.0/16的网段，直接走向了我的路由器地址为10.0.1.253。**
[root@http ansible]# ping 10.68.0.1
PING 10.68.0.1 (10.68.0.1) 56(84) bytes of data.
From 10.0.1.253 icmp_seq=1 Time to live exceeded
From 10.0.1.253 icmp_seq=2 Time to live exceeded
From 10.0.1.253 icmp_seq=3 Time to live exceeded
^C
--- 10.68.0.1 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2002ms

**通过tracer跟踪发现数据包一直回环直至丢失。**
[root@http ansible]# traceroute 10.68.0.1 -n             
traceroute to 10.68.0.1 (10.68.0.1), 30 hops max, 60 byte packets
 1  10.0.60.254  0.605 ms  1.092 ms  1.238 ms
 2  10.0.1.253  0.452 ms  0.536 ms  0.615 ms
 3  10.0.1.254  2.486 ms  2.644 ms  2.895 ms
 4  10.0.1.253  1.043 ms  1.168 ms  0.982 ms
 5  10.0.1.254  4.820 ms  4.354 ms  4.500 ms
 6  * * *
 7  10.0.1.254  6.019 ms  6.176 ms  6.235 ms
 8  * * *
 9  10.0.1.254  5.926 ms * *
10  * * *
11  10.0.1.254  4.878 ms  3.657 ms *
12  * * *
13  10.0.1.254  2.140 ms  1.139 ms  1.153 ms
14  * 10.0.1.253  1.054 ms  1.016 ms
15  * * *
16  10.0.1.253  1.363 ms  1.303 ms  1.534 ms
17  * * *
18  * * *
19  * * *
20  * * *
21  * 10.0.1.254  3.984 ms *
22  10.0.1.253  1.409 ms  1.491 ms  1.638 ms
23  * * *
24  10.0.1.253  2.071 ms  2.027 ms *
25  * * *
26  * * *
27  * 10.0.1.254  4.659 ms *
28  * * *
29  * * *
30  10.0.1.253  1.722 ms  1.863 ms  1.484 ms

[root@http ansible]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether ca:c0:35:e8:bb:98 brd ff:ff:ff:ff:ff:ff
    inet 10.0.60.51/24 brd 10.0.60.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::9eb6:4081:21bd:d8e7/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: br-33d37d9728d5: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:6a:33:8b:8c brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 brd 172.19.255.255 scope global br-33d37d9728d5
       valid_lft forever preferred_lft forever
4: br-6d3f1ea4b920: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:36:ba:ac:29 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-6d3f1ea4b920
       valid_lft forever preferred_lft forever
6: br-e3714bddecff: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:df:dc:93:24 brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.1/16 brd 172.21.255.255 scope global br-e3714bddecff
       valid_lft forever preferred_lft forever
    inet6 fe80::42:dfff:fedc:9324/64 scope link 
       valid_lft forever preferred_lft forever
47: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 172.20.248.128/32 brd 172.20.248.128 scope global tunl0
       valid_lft forever preferred_lft forever
55: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:51:b0:b7:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
56: cali9dcfc4f7d5e@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
57: calibcb13c6d05a@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
58: cali0a68ffa356c@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
59: cali02986a6d2f9@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever

[root@http ansible]# kubectl get pod --all-namespaces 
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-647f446b89-828ws   1/1     Running   0          12m
kube-system   calico-node-kzq9c                          2/2     Running   0          12m
kube-system   coredns-56684f94d6-95hzt                   1/1     Running   0          12m
kube-system   coredns-56684f94d6-bhtvv                   1/1     Running   0          12m
kube-system   kubernetes-dashboard-69dcdb65fd-ndhqf      1/1     Running   0          12m
kube-system   metrics-server-868fdcf88c-n4mmr            1/1     Running   0          12m

请问该如何解决访问内部集群地址？？

**Comment by pingod** [comment]
我也遇到这个问题
