### ISSUE TITLE
把Kubernetes的endpoint（node）端关机了，为什么pod的状态还是running?

### ISSUE THREAD

**Issue by xiang228068791** [easzlab/kubeasz#409]
把Kubernetes的endpoint（node）端关机了，为什么pod的状态还是running?

**Comment by weilinqwe** [comment]
kubelet停掉了，不影响docker运行着

**Comment by ilanni2460** [comment]
看看这个pod是不是被调度到另外的node上了

**Comment by gjmzj** [comment]
从node 关机，pod需要等待几分钟才能调度到其他节点

**Comment by zhangjiongdev** [comment]
> 把Kubernetes的endpoint（node）端关机了，为什么pod的状态还是running?

不要用 kubectl -n kube-system get pod -o wide 查看
用 kubectl get nodes 查看

**Comment by NoBugBoy** [comment]
我也遇到了这个问题，2个mster 关闭其中一个 node的状态变为notready， 但是对应的pod依然是ready and running，查看log说找不到路由主机
