### ISSUE TITLE
将一台已经安装有docker的服务器添加为NODE时，会对原来的镜像有影响吗

### ISSUE THREAD

**Issue by zhaop33** [easzlab/kubeasz#416]
将一台已经安装有docker的服务器添加为NODE时，会对原来的服务器已经运行在上面的镜像有影响吗，我有一台已经安装了docker的服务器，上面运行了其它容器，不知道我把这台服务器添加到k8s上面，会不会破坏已经运行在这台服务器上的容器

**Comment by TimeBye** [comment]
这样是不行的，使用本项目是会使用二进制文件安装docker的，这会与你已安装的docker发生冲突。除非你已安装的docker是按本项目的方式进行安装的

**Comment by ilanni2460** [comment]
建议把原来的docker删除，然后再重新添加

**Comment by zhaop33** [comment]
好的，感谢
