### ISSUE TITLE
添加节点时安装calico失败

### ISSUE THREAD

**Issue by yexq** [easzlab/kubeasz#419]
添加master时，流程卡在 TASK [calico : 准备 calicoctl配置文件] 步骤
![image](https://user-images.githubusercontent.com/10626343/50270180-b0754d00-046b-11e9-9d1c-6a619a9e16d8.png)
查看目标节点上 已经有了calico.tar包和calico镜像，但calico进程未启动，calico-node容器未启动
尝试作为node添加 也是同样情况
注：这个节点原先是master，被删除后，再进行添加的
麻烦帮忙看下问题，谢谢

**Comment by gjmzj** [comment]
这个节点不能上网吗？最新升级的calico版本确实没有离线包；
可以使用kubectl describe 看看这个节点的calico pod情况
