### ISSUE TITLE
metallb参照示例，选了2个节点标记并部署speaker，测试应用分配的IP无法访问

### ISSUE THREAD

**Issue by GeomaticM** [easzlab/kubeasz#425]
参照作者的metallb文档，选了2个节点打标记，部署speaker。
然后test-nginx分配的externalIp无法访问，查看speaker的日志，没有发起arp请求。
google查了半天，包括查看metallb的源码，也没发现问题。
后来灵机一动，在所有节点打标记，部署speaker，问题解决。
后来验证了下，test-nginx的pod被调度的节点的speaker输出了arp请求日志，其他节点跟之前一样。

**Comment by 4220182** [comment]
我也碰到一样的问题.
