### ISSUE TITLE
kube-controller-manager 和 schedule 是否计划升级为 https

### ISSUE THREAD

**Issue by ixiaoyi93** [easzlab/kubeasz#432]
+ 目前 prometheus 监控 kube-controller-manager 和 schedule 需要把服务监听到 0.0.0.0 ，处于安全考虑是否都应该开启 https 服务呢？

+ 官方建议 kubelet 个别配置通过 config.json 的形式进行，具体链接：https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

多谢群主！

**Comment by gjmzj** [comment]
1.暂时不考虑开启https服务
2.kubelet 目前还未使用 json/yaml文件方式配置是为了兼容老版本k8s安装，等后续新版只能支持这种方式时候我会及时更新过来。
