### ISSUE TITLE
Any playbook for etcd node add？

### ISSUE THREAD

**Issue by zhxiaom5** [easzlab/kubeasz#452]
Just like the title，is there any playbook to add etcd node？ thanks

**Comment by gjmzj** [comment]
Adding nodes in etcd-cluster only increases stability, not performance;
I'll try to work on it.

**Comment by gjmzj** [comment]
Increasing the cluster size can enhance failure tolerance and provide better read performance. Since clients can read from any member, increasing the number of members increases the overall serialized read throughput.

**Comment by gjmzj** [comment]
playbook to add etcd node:  https://github.com/gjmzj/kubeasz/blob/dev/docs/op/AddEtcd.md

**Comment by zhxiaom5** [comment]
really helpfull，thanks
