### ISSUE TITLE
使用单主多节点默认方式安装，集群运行在8080上？

### ISSUE THREAD

**Issue by DanceKiddle** [easzlab/kubeasz#461]
**如题，使用单主多节点默认配置安装完后，运行kubectl cluster-info 发现集群运行在localhost:8080上，按配置不应该是6443？**
**hosts文件主要配置如下：**
---------集群主要参数---------------
集群部署模式：allinone, single-master, multi-master
DEPLOY_MODE=single-master

集群主版本号，目前支持: v1.8, v1.9, v1.10，v1.11, v1.12, v1.13
K8S_VER="v1.13"

集群 MASTER IP，自动生成
MASTER_IP="{{ groups['kube-master'][0] }}"
KUBE_APISERVER="https://{{ MASTER_IP }}:6443"

 集群网络插件，目前支持calico, flannel, kube-router, cilium
CLUSTER_NETWORK="flannel"

**$ kubectl cluster-info**
Kubernetes master is running at http://localhost:8080
Elasticsearch is running at http://localhost:8080/api/v1/namespaces/kube-system/services/elasticsearch-logging/proxy
Kibana is running at http://localhost:8080/api/v1/namespaces/kube-system/services/kibana-logging/proxy
CoreDNS is running at http://localhost:8080/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at http://localhost:8080/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

**请问该如何让集群运行在6443端口？**

**Comment by gjmzj** [comment]
应该是会运行在6443端口，不知道你环境哪里出问题了，或者你的环境不干净，之前装过其他的；
建议使用 99.clean.yml 清理后重新安装。

**Comment by DanceKiddle** [comment]
> 应该是会运行在6443端口，不知道你环境哪里出问题了，或者你的环境不干净，之前装过其他的；
> 建议使用 99.clean.yml 清理后重新安装。

我删了所有能删的，运行了好几次clean.yml，重新安装还是不行。这个apiserver的端口配置需要在哪里清空？
