### ISSUE TITLE
关于docker 18.09.2 

### ISSUE THREAD

**Issue by klgd** [easzlab/kubeasz#462]
在 https://download.docker.com/linux/static/stable/x86_64/ 中没有找到 18.09.2-ce，只有18.09.2，这个docker版本是做了什么大的变动吗？，而且文件名也不一样了

![image](https://user-images.githubusercontent.com/8554422/53062933-6b1ddc00-34fd-11e9-87b4-f8ce78188fe1.png)

**Comment by gjmzj** [comment]
是的，确实名字变化了，现在各个分支我已经提交了修复，可以兼容 18.09.x的安装
