### ISSUE TITLE
basic_image 版本不全

### ISSUE THREAD

**Issue by smartxff** [easzlab/kubeasz#472]
我从百度云下载最新的版本为0.4，没有与master分支对应的basic_image版本。
导致的问题：
      镜像版本号不一致，然后没网环境下推送，启动镜像失败。
能不能传一份与master对应的basic_image版本的包

**Comment by gjmzj** [comment]
最近再更新测试部分版本，后续会传的

**Comment by waitingsong** [comment]
最新版本应该是 1.0 么？
