### ISSUE TITLE
部署jenkins出错。

### ISSUE THREAD

**Issue by LiuYuanZhe** [easzlab/kubeasz#473]
使用项目中的chart部署jenkins，pod一直显示pending状态，查看了一下，是pvc一直在显示pending状态，文件中貌似没有创建pv的yaml，只创建了pvc，我是不是需要自己创建一个pv来让pv绑定？

**Comment by gjmzj** [comment]
https://github.com/gjmzj/kubeasz/blob/master/docs/guide/jenkins.md
写着可以参考创建动态PV存储
https://github.com/gjmzj/kubeasz/blob/master/docs/setup/08-cluster-storage.md

**Comment by LiuYuanZhe** [comment]
谢谢作者大大，启动了之后pod一直停在init:0/1状态是在下载插件么？

**Comment by luanweijie** [comment]
同问，我用的helm最新版的，有同样问题，解决了吗
