### ISSUE TITLE
执行03docker.yml报符号：错误

### ISSUE THREAD

**Issue by z11220857** [easzlab/kubeasz#476]
ansible-playbook 03.docker.yml
ERROR! Syntax Error while loading YAML.
  could not find expected ':'

The error appears to have been in '/etc/ansible/roles/docker/tasks/main.yml': line 13, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

<<<<<<< HEAD
  tags: upgrade_docker, download_docker
      ^ here

**Comment by gjmzj** [comment]
直接 git clone 下来的代码可以跑，不要在老代码上用git pull；因为这次更新了大版本
