### ISSUE TITLE
安装docker报错

### ISSUE THREAD

**Issue by cncentoscn** [easzlab/kubeasz#477]
[root@master ansible]# ansible-playbook 03.docker.yml

PLAY [kube-master,kube-node] *******************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [192.168.1.210]
ok: [192.168.1.212]
ok: [192.168.1.211]
ok: [192.168.1.213]

TASK [docker : 获取是否运行名为'kubeasz'的容器] ***********************************************************************************************************************************************************
changed: [192.168.1.213]
changed: [192.168.1.210]
changed: [192.168.1.212]
changed: [192.168.1.211]

TASK [docker : 获取docker版本信息] *******************************************************************************************************************************************************************
changed: [192.168.1.210]

TASK [docker : 转换docker版本信息为浮点数] ***************************************************************************************************************************************************************
ok: [192.168.1.210]
ok: [192.168.1.213]
ok: [192.168.1.211]
ok: [192.168.1.212]

TASK [docker : 准备docker相关目录] *******************************************************************************************************************************************************************
ok: [192.168.1.213] => (item=/opt/kube/bin)
ok: [192.168.1.210] => (item=/opt/kube/bin)
ok: [192.168.1.212] => (item=/opt/kube/bin)
ok: [192.168.1.211] => (item=/opt/kube/bin)
ok: [192.168.1.213] => (item=/etc/docker)
ok: [192.168.1.210] => (item=/etc/docker)
ok: [192.168.1.212] => (item=/etc/docker)
ok: [192.168.1.211] => (item=/etc/docker)

TASK [docker : 下载 docker 二进制文件(>= 18.09.x)] ****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.210] (item=containerd) => {"changed": false, "item": "containerd", "msg": "Could not find or access '/etc/ansible/bin/containerd' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.213] (item=containerd) => {"changed": false, "item": "containerd", "msg": "Could not find or access '/etc/ansible/bin/containerd' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.211] (item=containerd) => {"changed": false, "item": "containerd", "msg": "Could not find or access '/etc/ansible/bin/containerd' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.210] (item=containerd-shim) => {"changed": false, "item": "containerd-shim", "msg": "Could not find or access '/etc/ansible/bin/containerd-shim' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.212] (item=containerd) => {"changed": false, "item": "containerd", "msg": "Could not find or access '/etc/ansible/bin/containerd' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.213] (item=containerd-shim) => {"changed": false, "item": "containerd-shim", "msg": "Could not find or access '/etc/ansible/bin/containerd-shim' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.211] (item=containerd-shim) => {"changed": false, "item": "containerd-shim", "msg": "Could not find or access '/etc/ansible/bin/containerd-shim' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.212] (item=containerd-shim) => {"changed": false, "item": "containerd-shim", "msg": "Could not find or access '/etc/ansible/bin/containerd-shim' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
ok: [192.168.1.213] => (item=docker-init)
ok: [192.168.1.210] => (item=docker-init)
ok: [192.168.1.212] => (item=docker-init)
ok: [192.168.1.211] => (item=docker-init)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.213] (item=runc) => {"changed": false, "item": "runc", "msg": "Could not find or access '/etc/ansible/bin/runc' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.212] (item=runc) => {"changed": false, "item": "runc", "msg": "Could not find or access '/etc/ansible/bin/runc' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.210] (item=runc) => {"changed": false, "item": "runc", "msg": "Could not find or access '/etc/ansible/bin/runc' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.211] (item=runc) => {"changed": false, "item": "runc", "msg": "Could not find or access '/etc/ansible/bin/runc' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
ok: [192.168.1.213] => (item=docker)
ok: [192.168.1.210] => (item=docker)
ok: [192.168.1.212] => (item=docker)
ok: [192.168.1.211] => (item=docker)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.213] (item=ctr) => {"changed": false, "item": "ctr", "msg": "Could not find or access '/etc/ansible/bin/ctr' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.210] (item=ctr) => {"changed": false, "item": "ctr", "msg": "Could not find or access '/etc/ansible/bin/ctr' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.212] (item=ctr) => {"changed": false, "item": "ctr", "msg": "Could not find or access '/etc/ansible/bin/ctr' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [192.168.1.211] (item=ctr) => {"changed": false, "item": "ctr", "msg": "Could not find or access '/etc/ansible/bin/ctr' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
ok: [192.168.1.213] => (item=dockerd)
ok: [192.168.1.210] => (item=dockerd)
ok: [192.168.1.212] => (item=dockerd)
ok: [192.168.1.211] => (item=dockerd)
ok: [192.168.1.213] => (item=docker-proxy)
ok: [192.168.1.210] => (item=docker-proxy)
ok: [192.168.1.212] => (item=docker-proxy)
ok: [192.168.1.211] => (item=docker-proxy)

PLAY RECAP *************************************************************************************************************************************************************************************
192.168.1.210              : ok=5    changed=2    unreachable=0    failed=1   
192.168.1.211              : ok=4    changed=1    unreachable=0    failed=1   
192.168.1.212              : ok=4    changed=1    unreachable=0    failed=1   
192.168.1.213              : ok=4    changed=1    unreachable=0    failed=1

**Comment by gjmzj** [comment]
提示很清楚写着在 /etc/ansible/bin 目录找不到containerd/containerd-shim/runc/ctr等文件；
你装的是什么版本的docker？

**Comment by cncentoscn** [comment]
不是运行这个命令安装docker么 ansible-playbook 03.docker.yml？难道是得先手动安装docker么

**Comment by technologynongmin** [comment]
我也是装docker的时候报错，加上-C 参数获取浮点数就报错了

**Comment by gjmzj** [comment]
@cncentoscn 倒不是需要手动安装docker，是用ansible脚本自动安装的；不过的先下载好对应的二进制文件，然后配置ansible hosts，才能运行 ansible-playbook 03.docker.yml;
- 如果要完整安装k8s，请看这里步骤 https://github.com/gjmzj/kubeasz/blob/master/docs/setup/00-planning_and_overall_intro.md
- 如果想单独只安装docker，可以单独下载 docker相关二进制放进/etc/ansible/bin目录，然后配置ansible hosts 把需要安装docker的主机加入kube-node组，然后仅执行 ansible-playbook 03.docker.yml 即可

**Comment by liuts** [comment]
https://pan.baidu.com/s/1c4RFaA
我在这里下载1-11-6.tar.gz，解压到bin后，执行安装也出现上面的错误，帮助看一下，是不是包里面漏了文件

**Comment by liuts** [comment]
你看下是不是这个原因
目录中文件的名字，和yml中文件名字不一致造成。比如：/etc/ansible/bin/docker-containerd   重命名为   /etc/ansible/bin/containerd

**Comment by liuts** [comment]
https://github.com/gjmzj/kubeasz/commit/ca2e9a22709169984dc71c181d5bf52d48db4026  这个提交的问题

**Comment by technologynongmin** [comment]
> 提示很清楚写着在 /etc/ansible/bin 目录找不到containerd/containerd-shim/runc/ctr等文件；
> 你装的是什么版本的docker？



> [ca2e9a2](https://github.com/gjmzj/kubeasz/commit/ca2e9a22709169984dc71c181d5bf52d48db4026) 判断docker版本有问题

对的  那块判断有点问题 。

**Comment by liuts** [comment]
是不是可以根据  docker-containerd  这个文件是否存在，判断版本呢。

**Comment by weilinqwe** [comment]
我也碰到了，应该是判断docker版本问题。 我的版本是17.03，但是进入了>= 18.09.x的分支。
`
TASK [docker : debug info] *********************************************************************************************************
ok: [192.168.11.62] => {
    "DOCKER_VER": "17.03"
}
ok: [192.168.11.63] => {
    "DOCKER_VER": "17.03"
}
ok: [192.168.11.64] => {
    "DOCKER_VER": "17.03"
}
ok: [192.168.11.65] => {
    "DOCKER_VER": "17.03"
}
ok: [192.168.11.66] => {
    "DOCKER_VER": "17.03"
}

TASK [docker : 准备docker相关目录] *******************************************************************************************************
ok: [192.168.11.65] => (item=/opt/kube/bin)
ok: [192.168.11.66] => (item=/opt/kube/bin)
ok: [192.168.11.64] => (item=/opt/kube/bin)
ok: [192.168.11.65] => (item=/etc/docker)
ok: [192.168.11.62] => (item=/opt/kube/bin)
ok: [192.168.11.63] => (item=/opt/kube/bin)
ok: [192.168.11.64] => (item=/etc/docker)
ok: [192.168.11.66] => (item=/etc/docker)
ok: [192.168.11.62] => (item=/etc/docker)
ok: [192.168.11.63] => (item=/etc/docker)

TASK [docker : 下载 docker 二进制文件(>= 18.09.x)] ****************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
。。。。
`

**Comment by weilinqwe** [comment]
@gjmzj  daemon.json文件里data-root属性也跟版本相关，17.03版本认不出来

**Comment by cncentoscn** [comment]
安装包的问题，换了一个安装包解决了。

**Comment by chengmingwei** [comment]
> 
> 
> 安装包的问题，换了一个安装包解决了。

兄弟，我也遇到和你一样的问题。请问你换的是哪一个安装包？ 文档中说的安装包与百度网盘里的都对应不上，麻烦兄弟告诉一下你使用的安装包版本，谢谢

**Comment by liuts** [comment]
用最新版本那个k8s就好了

**Comment by magickun** [comment]
应该是 download.sh 有问题，手动把 docker-18.09.2.tgz 下载下来，解压缩是能看到 8 个文件
`~/Downloads/docker » ls
containerd      containerd-shim ctr             docker          docker-init     docker-proxy    dockerd         runc`
在 download.sh 里只 mv 了 docker* 的 4 个文件过去，所以后边就报错了
`### prepare docker binaries
if [ -f "docker-${DOCKER_VER}.tgz" ]; then
  echo "\nextracting docker binaries..."
  tar zxf docker-${DOCKER_VER}.tgz
  mv -f docker/docker* ../bin
  if [ -f "docker/completion/bash/docker" ]; then
    mv -f docker/completion/bash/docker ../roles/docker/files/docker
  fi
else
  echo Please download 'docker-${DOCKER_VER}.tgz' first
fi`
