### ISSUE TITLE
dashboard CrashLoopBackOff

### ISSUE THREAD

**Issue by talway** [easzlab/kubeasz#480]
kubectl describe pod kubernetes-dashboard-6685cb584f-xjzw9 -n kube-system
Name:           kubernetes-dashboard-6685cb584f-xjzw9
Namespace:      kube-system
Node:           192.168.1.93/192.168.1.93
Start Time:     Thu, 14 Mar 2019 10:12:00 +0800
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=6685cb584f
Annotations:    <none>
Status:         Running
IP:             172.20.2.2
Controlled By:  ReplicaSet/kubernetes-dashboard-6685cb584f
Containers:
  kubernetes-dashboard:
    Container ID:  docker://671cac50989d55c76dbd2925e666634a444bf6a123b11d71f500ece642950bfd
    Image:         mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.10.0
    Image ID:      docker://sha256:0dab2435c100b32892e676b9709978617a5472390ac951f764c292950b902b1f
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --auto-generate-certificates
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 14 Mar 2019 10:13:25 +0800
      Finished:     Thu, 14 Mar 2019 10:13:25 +0800
    Ready:          False
    Restart Count:  4
    Liveness:       http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-v99mg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  kubernetes-dashboard-token-v99mg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-v99mg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
Events:
  Type     Reason     Age                  From                   Message
  ----     ------     ----                 ----                   -------
  Normal   Scheduled  104s                 default-scheduler      Successfully assigned kube-system/kubernetes-dashboard-6685cb584f-xjzw9 to 192.168.1.93
  Normal   Pulled     19s (x5 over 102s)   kubelet, 192.168.1.93  Container image "mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.10.0" already present on machine
  Normal   Created    19s (x5 over 102s)   kubelet, 192.168.1.93  Created container
  Normal   Started    19s (x5 over 102s)   kubelet, 192.168.1.93  Started container
  Warning  BackOff    19s (x10 over 101s)  kubelet, 192.168.1.93  Back-off restarting failed container

kubectl logs kubernetes-dashboard-6685cb584f-xjzw9 -n kube-system
---
 No request provided. Skipping authorization
2019/03/14 02:13:25 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service account's configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.68.0.1:443/version: dial tcp 10.68.0.1:443: getsockopt: connection refused
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 10.0.2.3

**Comment by weilinqwe** [comment]
很大的原因 10.68.0.1:443不能访问了，估计你的coredns也是CrashLoopBackOff了

**Comment by talway** [comment]
排查出
1.etcd的hostname没修改；
2.dashboard 运行在node节点..
在排查

**Comment by waitingsong** [comment]
@talway 
`dashboard 运行在node节点` 这个有啥问题呢？

**Comment by yangwen7983** [comment]
您好！我也遇见此种问题，请问解决了吗
