### ISSUE TITLE
dashboard访问提示401

### ISSUE THREAD

**Issue by Tobewont** [easzlab/kubeasz#482]
```bash
# kubectl cluster-info 
Kubernetes master is running at https://192.168.1.52:8443
CoreDNS is running at https://192.168.1.52:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://192.168.1.52:8443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

浏览器访问显示：

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

应该是最近一两周的更新导致的，我反复分步安装及一键安装，都是没问题的，但访问都是提示这个，更换了之前的dashboard版本也没用。

**Comment by Tobewont** [comment]
今天又用之前一两周左右下载的zip包进行了安装，dashboard是可以正常访问的

**Comment by mainiubaba** [comment]
用1.0.0rc1那个版本的就行

**Comment by ghjacky** [comment]
```
kubectl get svc -n kube-system
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
kube-dns               ClusterIP   10.68.0.2       <none>        53/UDP,53/TCP,9153/TCP   108m
kubernetes-dashboard   NodePort    10.68.70.242    <none>        443:40027/TCP            108m
metrics-server         ClusterIP   10.68.31.179    <none>        443/TCP                  108m
tiller-deploy          ClusterIP   10.68.118.195   <none>        44134/TCP                93m
```
`vim manifests/dashboard/kubernetes-dashboard.yaml`
```
args:
    - --auto-generate-certificates
    - --heapster-host=metrics-server
```
(args下边新加`- --heapster-host=metrics-server`)
然后，`kubectl apply -f manifests/dashboard/kubernetes-dashboard.yaml`
就OK了

**Comment by shaojielinux** [comment]
我也遇到了这个问题  我用的版本是1.13.4 ，请问你是怎么解决的

**Comment by selifm** [comment]
相同问题

**Comment by fxdjjn1234** [comment]
我也是这个问题，但是使用了@ghjacky 无法起效
我的版本是k8s.1-10-13.tar.gz

**Comment by gjmzj** [comment]
跟k8s版本没有关系；原因是kubeasz 1.0.0 开始默认关闭了basic_auth；如果像和之前版本一样，修改 roles/kube-master/defaults/main.yml中变量BASIC_AUTH_ENABLE: "yes"后重新安装kube-master即可；

**Comment by yzijun** [comment]
我也有相同问题，按照@gimzj上面说的做了已经解决。项目不错一直在关注和实践中和大家一同学习。

**Comment by selifm** [comment]
[root@iZbp11u9ywulp5kk86jdenZ ~]# kubectl get pod --all-namespaces
NAMESPACE     NAME                                    READY   STATUS             RESTARTS   AGE
kube-system   coredns-74cdd5bb6f-6lcdl                1/1     Running            0          2m10s
kube-system   coredns-74cdd5bb6f-hcrhn                1/1     Running            0          2m10s
kube-system   kube-flannel-ds-2mf9p                   1/1     Running            0          2m25s
kube-system   kube-flannel-ds-gsk2c                   1/1     Running            0          2m25s
kube-system   kube-flannel-ds-k5pgw                   1/1     Running            0          2m25s
kube-system   kubernetes-dashboard-6685cb584f-2dvtv   0/1     CrashLoopBackOff   4          114s
kube-system   metrics-server-79558444c6-mktzj         0/1     CrashLoopBackOff   4          2m5s
[root@iZbp11u9ywulp5kk86jdenZ ~]# kubectl get svc --all-namespaces
NAMESPACE     NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             ClusterIP   10.68.0.1       <none>        443/TCP         5m9s
kube-system   kube-dns               ClusterIP   10.68.0.2       <none>        53/UDP,53/TCP   3m43s
kube-system   kubernetes-dashboard   NodePort    10.68.160.241   <none>        443:23358/TCP   3m27s
kube-system   metrics-server         ClusterIP   10.68.44.50     <none>        443/TCP         3m38s

我还是 CrashLoopBackOff

**Comment by gjmzj** [comment]
CrashLoopBackOff 的话，使用 kubectl describe /kubectl logs 查看原因
