### ISSUE TITLE
怎么利用NFS动态提供Kubernetes后端存储卷

### ISSUE THREAD

**Issue by deep-cds** [easzlab/kubeasz#484]
你好，我在配置NFS动态提供Kubernetes后端存储卷 的时候失败 
![image](https://user-images.githubusercontent.com/44251514/54667219-c526b700-4b26-11e9-83c8-bfa5e2edfe1d.png)
![image](https://user-images.githubusercontent.com/44251514/54667243-ce178880-4b26-11e9-86f6-277b8ed95446.png)
![image](https://user-images.githubusercontent.com/44251514/54667418-40886880-4b27-11e9-8cc9-c8dfe1715d4f.png)
![image](https://user-images.githubusercontent.com/44251514/54667432-4d0cc100-4b27-11e9-997a-bf4509846834.png)

![image](https://user-images.githubusercontent.com/44251514/54667162-a7595200-4b26-11e9-9bc2-d691cfebc601.png)

如果要部署 利用 nfs动态提供Kubernetes后端存储卷 ，应该怎么部署呢 ？ 

请开发的同学帮忙看看，谢谢 。  

参考文档 
 https://jimmysong.io/kubernetes-handbook/practice/using-nfs-for-persistent-storage.html

**Comment by yexq** [comment]
现在是pod没有启动成功，你可以看下rs的详情看下，或看下具体的pod有没有创建，失败的日志看下

**Comment by gjmzj** [comment]
项目里面有相关文档
https://github.com/gjmzj/kubeasz/blob/master/docs/setup/08-cluster-storage.md
