### ISSUE TITLE
keepalive的vip问题

### ISSUE THREAD

**Issue by liuwenzhi0318** [easzlab/kubeasz#486]
您好，我使用的是云平台按照keepalive+haproxy，现在问题是keepalive的vip地址给node节点完全ping不通。这个问题不知道有没有其他人遇到。手动重启keepavlived后又能ping一阵子，过一会又不通了

**Comment by liuwenzhi0318** [comment]
[root@k8s-test-master2 keepalived]# journalctl -u keepalived
-- Logs begin at Thu 2019-03-21 10:48:23 CST, end at Thu 2019-03-21 15:08:01 CST. --
Mar 21 13:47:23 k8s-test-master2 systemd[1]: Starting LVS and VRRP High Availability Monitor...
Mar 21 13:47:23 k8s-test-master2 Keepalived[21693]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Mar 21 13:47:23 k8s-test-master2 Keepalived[21693]: Opening file '/etc/keepalived/keepalived.conf'.
Mar 21 13:47:23 k8s-test-master2 Keepalived[21694]: Starting Healthcheck child process, pid=21695
Mar 21 13:47:23 k8s-test-master2 Keepalived_healthcheckers[21695]: Initializing ipvs
Mar 21 13:47:23 k8s-test-master2 systemd[1]: Started LVS and VRRP High Availability Monitor.
Mar 21 13:47:23 k8s-test-master2 Keepalived[21694]: Starting VRRP child process, pid=21696
Mar 21 13:47:23 k8s-test-master2 Keepalived_healthcheckers[21695]: Opening file '/etc/keepalived/keepalived.conf'.
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: Registering Kernel netlink reflector
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: Registering Kernel netlink command channel
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: Registering gratuitous ARP shared channel
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: Opening file '/etc/keepalived/keepalived.conf'.
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: WARNING - script `killall` resolved by path search to `/usr/bin/killall`. Please specify full path.
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: VRRP_Instance(VI-kube-master) removing protocol VIPs.
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: Using LinkWatch kernel netlink reflector...
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: VRRP sockpool: [ifindex(2), proto(112), unicast(1), fd(10,11)]
Mar 21 13:47:23 k8s-test-master2 Keepalived_vrrp[21696]: VRRP_Script(check-haproxy) succeeded
Mar 21 13:47:26 k8s-test-master2 Keepalived_vrrp[21696]: VRRP_Instance(VI-kube-master) Transition to MASTER STATE
Mar 21 13:47:29 k8s-test-master2 Keepalived_vrrp[21696]: VRRP_Instance(VI-kube-master) Entering MASTER STATE
Mar 21 13:47:29 k8s-test-master2 Keepalived_vrrp[21696]: VRRP_Instance(VI-kube-master) setting protocol VIPs.
Mar 21 13:47:29 k8s-test-master2 Keepalived_vrrp[21696]: Sending gratuitous ARP on eth0 for 192.168.12.100
Mar 21 13:47:29 k8s-test-master2 Keepalived_vrrp[21696]: VRRP_Instance(VI-kube-master) Sending/queueing gratuitous ARPs on eth0 for 192.168.12.100
Mar 21 13:47:29 k8s-test-master2 Keepalived_vrrp[21696]: Sending gratuitous ARP on eth0 for 192.168.12.100
Mar 21 13:47:29 k8s-test-master2 Keepalived_vrrp[21696]: Sending gratuitous ARP on eth0 for 192.168.12.100
Mar 21 13:47:29 k8s-test-master2 Keepalived_vrrp[21696]: Sending gratuitous ARP on eth0 for 192.168.12.100
Mar 21 13:47:29 k8s-test-master2 Keepalived_vrrp[21696]: Sending gratuitous ARP on eth0 for 192.168.12.100
Mar 21 13:47:34 k8s-test-master2 Keepalived_vrrp[21696]: Sending gratuitous ARP on eth0 for 192.168.12.100

**Comment by liuwenzhi0318** [comment]
我找到原因了，我把keepalive的单播模式关掉就好了。还有老大，我这个不是太懂，为什么部署的时候开启单播形式呢

**Comment by gjmzj** [comment]
单播模式是为了同网段的，多个keepalive组不互相影响；能否稍详细说明你问题及解决方法

**Comment by zhangj3** [comment]
最近我在企业内部redhat openstack平台部署kubernetes HA cluster的时候也出现了在其他backup 节点无法ping通keepalived的Virtual IP的情况，VIP漂移是正常的，搞了一周后发现是openstack的neutron的锅
解决思路分两步，1是创建一个fixed ip做vip, 2是在虚机的interneal IP上加上vip 做allowed-address-pair
参见https://docs.catalystcloud.io/tutorials/deploying-highly-available-instances-with-keepalived.html

**Comment by gjmzj** [comment]
@zhangj3 👍
做k8s集群HA，建议在任何公有云、openstack等平台使用平台本身提供的负载均衡；一般自建不了，要不就是很麻烦
