### ISSUE TITLE
allinone部署完成后怎么访问dashboard

### ISSUE THREAD

**Issue by kigkrazy** [easzlab/kubeasz#493]
![image](https://user-images.githubusercontent.com/11622206/55048480-4b8d4c80-5083-11e9-91c5-809cc8d14edc.png)
![image](https://user-images.githubusercontent.com/11622206/55048500-5b0c9580-5083-11e9-9f17-6e58a946f807.png)

下面几个都放完失败了：
http://192.168.10.33:8080/
http://192.168.10.33:443/
http://192.168.10.33:24908/

**Comment by gjmzj** [comment]
https://192.168.10.33:24908/
项目文档里面有写 https://github.com/gjmzj/kubeasz/blob/master/docs/guide/dashboard.md#%E6%BC%94%E7%A4%BA%E6%96%B0%E7%99%BB%E9%99%86%E6%96%B9%E5%BC%8F
