### ISSUE TITLE
集群添加node后调度的pod只能当前node访问，其他node无法访问

### ISSUE THREAD

**Issue by lyy910203** [easzlab/kubeasz#494]
新加入集群的node有一个网卡和pod ip段冲突，重启节点正常，或者手动down这个网卡删除flanned才能正常
```
4: mynet0: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 9a:49:90:fd:d1:17 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/16 scope global mynet0
       valid_lft forever preferred_lft forever
```
忘大佬看看，是个大坑

**Comment by lyy910203** [comment]
添加完node   node  ip状态
`[root@VM_2_174_centos ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 52:54:00:04:05:3e brd ff:ff:ff:ff:ff:ff
    inet 10.105.2.174/18 brd 10.105.63.255 scope global eth0
       valid_lft forever preferred_lft forever
3: veth59390810@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master mynet0 state UP group default 
    link/ether fa:54:56:1a:0b:a5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
10: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
21: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:4f:8d:1c:63 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
22: mynet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 5a:ed:4f:ad:45:aa brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/16 scope global mynet0
       valid_lft forever preferred_lft forever
23: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 4a:e7:46:b9:a4:92 brd ff:ff:ff:ff:ff:ff
    inet 172.20.6.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
`
flanel报错ip冲突

**Comment by gjmzj** [comment]
mynet0这个网卡是默认cni配置产生的网卡，有这个网卡，可能是安装flannel网络时候没有成功

**Comment by lyy910203** [comment]
那估计是当时没有成功，但是后面成功了，但是这个网卡以及配置还在导致，目前我这边集群添加node都会出现  暂时性只能重启node

**Comment by lyy910203** [comment]
因为flannel的网络的镜像当时获取很慢

**Comment by shaojielinux** [comment]
我也遇到这个问题了，请问你是怎么解决的

**Comment by gjmzj** [comment]
在你的ansible集群上，执行 `ansible all -m file -a 'name=/etc/cni/net.d/10-default.conf state=absent'`即可

**Comment by smartxff** [comment]
# 删除原有cni配置
- name: 删除默认cni配置
  file: path=/etc/cni/net.d/10-default.conf state=absent

# 删除原有cni插件网卡mynet0
- name: 删除默认cni插件网卡mynet0
  shell: "ip link del mynet0"
  ignore_errors: true

加到ansible脚本里面去吧。被mynet0坑惨了。

**Comment by smartxff** [comment]
`
# 删除原有cni配置
- name: 删除默认cni配置
  file: path=/etc/cni/net.d/10-default.conf state=absent

# 删除原有cni插件网卡mynet0
- name: 删除默认cni插件网卡mynet0
  shell: "ip link del mynet0"
  ignore_errors: true
`
加到ansible脚本里面去吧，被mynet0坑惨了。

**Comment by smartxff** [comment]
```
# 删除原有cni配置
- name: 删除默认cni配置
  file: path=/etc/cni/net.d/10-default.conf state=absent

# 删除原有cni插件网卡mynet0
- name: 删除默认cni插件网卡mynet0
  shell: "ip link del mynet0"
  ignore_errors: true
```
加到ansible脚本里面去吧，被mynet0坑惨了。

**Comment by TonyBian** [comment]
在大家的基础上增加的代码，依然是很脏的方案，不过可以稳定解决这个问题了

- name: 删除默认cni配置
  file:
    path: /etc/cni/net.d/10-default.conf
    state: absent

- name: 获取是否存在cni默认网卡mynet0
  shell: echo $(ip a | grep -o "mynet0:")
  register: _cni_mynet0

- block:
    - name: 删除cni默认网卡mynet0
      shell: |
        ip link set mynet0 down
        ip link del mynet0

    - name: 重新启动node服务
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        state: restarted
        enabled: yes
      with_items:
        - docker
        - kubelet
        - kube-proxy

    - name: 获取服务状态
      service_facts:

    - name: 验证服务已经启动
      assert:
        that:
          - ansible_facts.services['{{ item }}.service'].state == "running"
      with_items:
        - docker
        - kubelet
        - kube-proxy
  when: _cni_mynet0.stdout

- name: 等待30s
  wait_for:
    timeout: 30
  delegate_to: localhost
  connection: local
  run_once: yes

- name: 获取启动失败的flannel容器所在主机ip
  shell: |
    {{ bin_dir }}/kubectl get pod -n kube-system -o wide | grep kube-flannel-ds | grep -v "Running" | awk '{print $7}'
  register: _failed_flannel_host
  run_once: yes

- name: 重新启动docker服务
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: _failed_flannel_host.stdout_lines
  delegate_to: "{{ item }}"
  with_items: "{{ _failed_flannel_host.stdout_lines }}"

# 等待网络插件部署成功，视下载镜像速度而定
- name: 轮询等待 flannel 运行
  shell: |
    {{ bin_dir }}/kubectl get daemonset -n kube-system kube-flannel-ds-amd64 -o=jsonpath='{.status.numberAvailable}'
  register: _flannel_status
  until: _flannel_status.stdout | int == groups['kube_master'] | length + groups['kube_node'] | length
  retries: 20
  delay: 3
