### ISSUE TITLE
hpa TARGETS 未知状态

### ISSUE THREAD

**Issue by shaojielinux** [easzlab/kubeasz#504]
做了memory hpa 但是一直显示未知，k8s版本1.13.3
![image](https://user-images.githubusercontent.com/28892865/55847702-e5252580-5b7c-11e9-9caf-cf0e6c2258db.png)

**Comment by gjmzj** [comment]
一般需要几分钟等待时间

**Comment by shaojielinux** [comment]
好几天了都是这个状态

**Comment by shaojielinux** [comment]
不知道是哪里出问题了

**Comment by gjmzj** [comment]
你是按照什么文档安装的，看看 metrics-server 是否正常
kubectl get pod --all-namespaces |grep metrics-server

**Comment by shaojielinux** [comment]
服务器是正常的，但是我看log里面有几个错误


mp for metric point for container "tomcat" in pod default/tomcat-6b7c7bb6cc-k96fw on node "10.8.197.90", discarding data: no non-zero timestamp on either CPU or memory, unable to get a valid timestamp for metric point for container "tomcat" in pod default/tomcat-6b7c7bb6cc-t2gqf on node "10.8.197.90", discarding data: no non-zero timestamp on either CPU or memory]
E0410 15:47:35.843366       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:10.8.197.90: unable to get a valid timestamp for metric point for container "tomcat" in pod default/tomcat-6b7c7bb6cc-lx46w on node "10.8.197.90", discarding data: no non-zero timestamp on either CPU or memory
E0410 15:48:05.830532       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:10.8.197.90: unable to get a valid timestamp for metric point for container "tomcat" in pod default/tomcat-6b7c7bb6cc-lx46w on node "10.8.197.90", discarding data: no non-zero timestamp on either CPU or memory
E0411 03:45:05.840953       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:10.8.197.90: unable to get CPU for container "grafana" in pod monitoring/grafana-7ff96f776f-flkhg on node "10.8.197.90", discarding data: missing cpu usage metric
E0411 03:54:05.837187       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:10.8.199.217: unable to get CPU for container "grafana" in pod monitoring/grafana-796ffb9558-mm99g on node "10.8.199.217", discarding data: missing cpu usage metric

**Comment by gjmzj** [comment]
试试这两个命令 
kubectl top node
kubectl describe apiservice v1beta1.metrics.k8s.io

**Comment by gjmzj** [comment]
https://github.com/kubernetes-incubator/metrics-server/issues/130 这里有人碰到问题跟你一样，最后那个stafot说得比较靠谱

**Comment by shaojielinux** [comment]
我配置hpa cpu是可以获取到的，只有内存指标获取不到。 理论上说证书肯定么问题。 是不是内存接口有变化

**Comment by liupeng0518** [comment]
哪个版本？

https://github.com/kubernetes-incubator/metrics-server/issues/192
