### ISSUE TITLE
master ha的问题

### ISSUE THREAD

**Issue by lingyang2109** [easzlab/kubeasz#506]
环境：3 master a,b,c 1.13.4 版本
A:10.9.66.91
B:10.9.66.92
C:10.9.66.93
通过kubease 部署kube-apiserver 里的etcd配置
--etcd-servers=https://10.9.66.91:2379,https://10.9.66.92:2379,https://10.9.66.93:2379
ha测试的时候，停掉 B跟C任何一个，kubectl以及dashboard都能正常，停掉A之后，B跟C kubectl以及dashboard都会超时，其他服务都是正常，再深入测试，发现是停掉etcd就会出现这样的情况，后面通过修改--etcd-servers的顺序，把停掉的etcd位置后移即可恢复，但是测试api的时候又是正常的，整个etcd集群也是没问题的，也就是说当--etcd-servers列表第一个出现无法访问，kubectl及dashboard就不能访问了，这个现象对于整个部署是正常的吗？

**Comment by waitingsong** [comment]
不知道是否和这个 commit 相关 8319b3217b

**Comment by lingyang2109** [comment]
嗯，应该是这个原因，一个月前安装的，今天测试出来了，没注意到已经修复了。

**Comment by gjmzj** [comment]
这个其实是etcd的bug；我这边只是绕过了；后续etcd更新应该也能修复

**Comment by liupeng0518** [comment]
这个修复只是调整下csr文件就可以么？

**Comment by gjmzj** [comment]
是的
