### ISSUE TITLE
ansible-playbook 04.kube-master.yml 报connected refused错

### ISSUE THREAD

**Issue by muercy** [easzlab/kubeasz#507]
安装失败，端口可以Telnet通。
![image](https://user-images.githubusercontent.com/3224084/55890214-e0945780-5be4-11e9-90ad-0e989f31d4b7.png)

日志中这句话./apiserver-1.log:Apr 10 10:36:04 node3 kube-apiserver[13621]: E0410 10:36:04.198892   13621 repair.go:171] the cluster IP 10.96.0.10 for service kube-dns/kube-system is not within the service CIDR 10.68.0.0/24; please recreate。
未配置过10.96.0.10网段。机器进程都是完好的。

请问该如何解决？

**Comment by gjmzj** [comment]
是不是你安装环境不干净，机器曾经装过k8s集群；建议清理下环境试试，ansible-playbook 99.clean.yml

**Comment by muercy** [comment]
厉害，确实不干净，我弄个干净重装试试

**Comment by muercy** [comment]
重装了干净环境，这个问题还在.rhel7.5的os，安装k8s1.13版本，请帮忙看下，谢谢
![image](https://user-images.githubusercontent.com/3224084/55994893-9515a280-5ce5-11e9-9a10-f61ab8f957a8.png)

**Comment by gjmzj** [comment]
hosts配置不对；你是单机集群，还是多节点高可用集群？

**Comment by muercy** [comment]
应该是我把网络方案先空着的原因。因为我准备对接其他网络方案。
![image](https://user-images.githubusercontent.com/3224084/56077412-8545ad80-5e0e-11e9-8b38-402f8720c306.png)
