### ISSUE TITLE
etcd集群多节点创建证书重复

### ISSUE THREAD

**Issue by yushengyin** [easzlab/kubeasz#517]
etcd集群的ansible-playbook部署的yml文件，在创建etcd集群证书时，每个etcd节点都执行了一次证书的创建，这个建议可以在一个etcd节点上创建，然后推送到其余的etcd集群节点上去

**Comment by gjmzj** [comment]
是的，可以优化，不过其实每个节点创建也很快速

**Comment by huangzhuxing** [comment]
有解决方案了吗？
