### ISSUE TITLE
建议增加master节点和etcd节点迁移方案

### ISSUE THREAD

**Issue by ilanni2460** [easzlab/kubeasz#519]
建议增加master节点和etcd节点迁移方案

目前遇到的问题，master节点和etcd节点需要迁移，迁移后master节点，etcd节点的IP地址全部更换为最新的。
不知道如何进行迁移，群主是否有这方面的经验。
如果有的话，可以分享下，谢谢！！！

**Comment by gjmzj** [comment]
etcd集群迁移，可以通过 easzctl add-etcd 和 easzctl del-etcd 完成；
如果不修改master vip的地址，那么master迁移可以类似去做；
如果需要改变master vip的话，那么会更复杂，可以结合参考这个文档 https://github.com/gjmzj/kubeasz/blob/master/docs/op/ChangeVIP.md；
后续可以考虑出这些操作文档

**Comment by ilanni2460** [comment]
etcd集群迁移，已经按照你的文档操作成功。

**Comment by ilanni2460** [comment]
master节点这块，我目前使用的是flannel插件。我先按照你这个文档进行操作下。
https://github.com/gjmzj/kubeasz/blob/master/docs/op/ChangeVIP.md
