### ISSUE TITLE
新建操作系统用户，默认kubectl可以直接读取k8s集群信息

### ISSUE THREAD

**Issue by liupeng0518** [easzlab/kubeasz#526]
都不需要配置 ~/.kube/config，这样是不是不7安全

**Comment by gjmzj** [comment]
~/.kube/config 这个是kubectl 使用的配置文件，这跟kubelet 没啥关系；
是不是表述不对了

**Comment by liupeng0518** [comment]
修改了，不好意思

我新建了操作系统用户 kubectl get node 直接能获取 ，无需配置kube/config

**Comment by gjmzj** [comment]
感谢反馈，待我测试验证下

**Comment by gjmzj** [comment]
ubuntu 1604 测试系统新用户无法执行kubectl命令
