### ISSUE TITLE
看不到master节点

### ISSUE THREAD

**Issue by althe** [easzlab/kubeasz#529]
kubectl get nodes 看不到master节点正常吗？

**Comment by waitingsong** [comment]
不正常，我的这样：
```
[root@deploy ~]# kubectl get nodes
NAME         STATUS                     ROLES    AGE   VERSION
10.0.8.188   Ready,SchedulingDisabled   master   21m   v1.13.5
10.0.8.209   Ready                      node     21m   v1.13.5
10.0.8.217   Ready                      node     21m   v1.13.5
10.0.8.48    Ready,SchedulingDisabled   master   21m   v1.13.5
10.0.8.61    Ready,SchedulingDisabled   master   21m   v1.13.5
```

**Comment by althe** [comment]
> 不正常，我的这样：
> 
> ```
> [root@deploy ~]# kubectl get nodes
> NAME         STATUS                     ROLES    AGE   VERSION
> 10.0.8.188   Ready,SchedulingDisabled   master   21m   v1.13.5
> 10.0.8.209   Ready                      node     21m   v1.13.5
> 10.0.8.217   Ready                      node     21m   v1.13.5
> 10.0.8.48    Ready,SchedulingDisabled   master   21m   v1.13.5
> 10.0.8.61    Ready,SchedulingDisabled   master   21m   v1.13.5
> ```
你比我好点，能看到master,我只能看到worker节点...  其他都正常。
