### ISSUE TITLE
efk的日志怎么自动定期删除

### ISSUE THREAD

**Issue by jacky-neo** [easzlab/kubeasz#539]
随着时间记累，日志会越来越多。除了手工通过kinana界面执行DELTE, 能否支持定时任务删除日志？

**Comment by gjmzj** [comment]
自动删除这个我没实践过，网上搜索看看，或者其他人有实践经验；
我理解就是去es集群里面删除对应的记录就行

**Comment by xunchangguo** [comment]
日志是存在ES里的，按照时间删除对应的索引就可以啊。

**Comment by jacky-neo** [comment]
> 日志是存在ES里的，按照时间删除对应的索引就可以啊。

这个知道，通过kibana界面操作可以。想做成日程自动的删除过期的日志。但efk安装后，es是https(如https://xx.xx.xx.xx:6443/api/v1/namespaces/kube-system/services/elasticsearch-logging/proxy)， 无法通过curl -X DELETE调用

**Comment by kubeasz** [comment]
可以参考这个提交去自动清理 f9dc71c15ab9a63dc3d36efb15d2ad615038ff4d

**Comment by uglyliu** [comment]
没用k8s部署的elk集群，我这里是用官方提供的工具curator删除过期索引

**Comment by jacky-neo** [comment]
> 可以参考这个提交去自动清理 [f9dc71c](https://github.com/easzlab/kubeasz/commit/f9dc71c15ab9a63dc3d36efb15d2ad615038ff4d)

按此操作，很好，谢谢！！！
需注意的是安装完后，只能看到cronjob. pod和log只有任务执行完后，才能看到，即第二天，一开始以为没装对呢：）

**Comment by jacky-neo** [comment]
> 可以参考这个提交去自动清理 [f9dc71c](https://github.com/easzlab/kubeasz/commit/f9dc71c15ab9a63dc3d36efb15d2ad615038ff4d)
> 默认是每天1点3分去执行日志清理，默认最多保留30天日志，可以配置https://github.com/easzlab/kubeasz/blob/master/manifests/efk/es-index-rotator/rotator.yaml

清理过期日志，是按个数来算的，不是按日期。 我的一个环境的efk, 不知什么原因，没有连续记录日志，我要保留最近7天的日志，但结果最近7天的都没了。只有昨天和今天的。今是5-15，应该是5-8前删除，但5-14也被删除了。下面是日志。我看了下sh脚本，貌似用索引个数算，有点问题
+ curl 'elasticsearch-logging:9200/_cat/indices?'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   924  100   924    0     0   2834      0 --:--:-- --:--:-- --:--:--  2834
++ cat /tmp/indices
++ wc -l
++ grep logstash
+ curr_days_of_log=9
+ curr_days_of_log=7
+ [[ 7 -gt 7 ]]
++ date -d '7 days ago' +%Y.%m.%d
+ first_day=2019.05.07
++ cat /tmp/indices
++ grep logstash
++ cut '-d ' -f3
++ cut -d- -f2
++ sort
++ sed -n 1,/2019.05.07/p
+ rotate='2019.04.30
2019.05.05
2019.05.08
2019.05.09
2019.05.10
2019.05.11
2019.05.12
2019.05.13
2019.05.14'
。。。
100    21  100    21    0     0      9      0  0:00:02  0:00:02 --:--:--     9
+ for day in $rotate
+ curl -X DELETE elasticsearch-logging:9200/logstash-2019.05.14
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0      8      0  0:00:02  0:00:02 --:--:--     8

**Comment by jacky-neo** [comment]
> > 可以参考这个提交去自动清理 [f9dc71c](https://github.com/easzlab/kubeasz/commit/f9dc71c15ab9a63dc3d36efb15d2ad615038ff4d)
> > 默认是每天1点3分去执行日志清理，默认最多保留30天日志，可以配置https://github.com/easzlab/kubeasz/blob/master/manifests/efk/es-index-rotator/rotator.yaml
> 
> 清理过期日志，是按个数来算的，不是按日期。 我的一个环境的efk, 不知什么原因，没有连续记录日志，我要保留最近7天的日志，但结果最近7天的都没了。只有昨天和今天的。执行时是5.15，应该是5.7前删除，但5.14也被删除了。下面是日志。我看了下sh脚本，貌似5.7找不到，就用剩下的算了，有点问题
> 
> * curl 'elasticsearch-logging:9200/_cat/indices?'
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   100   924  100   924    0     0   2834      0 --:--:-- --:--:-- --:--:--  2834
>   ++ cat /tmp/indices
>   ++ wc -l
>   ++ grep logstash
> * curr_days_of_log=9
> * curr_days_of_log=7
> * [[ 7 -gt 7 ]]
>   ++ date -d '7 days ago' +%Y.%m.%d
> * first_day=2019.05.07
>   ++ cat /tmp/indices
>   ++ grep logstash
>   ++ cut '-d ' -f3
>   ++ cut -d- -f2
>   ++ sort
>   ++ sed -n 1,/2019.05.07/p
> * rotate='2019.04.30
>   2019.05.05
>   2019.05.08
>   2019.05.09
>   2019.05.10
>   2019.05.11
>   2019.05.12
>   2019.05.13
>   2019.05.14'
>   。。。
>   100    21  100    21    0     0      9      0  0:00:02  0:00:02 --:--:--     9
> * for day in $rotate
> * curl -X DELETE elasticsearch-logging:9200/logstash-2019.05.14
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   100    21  100    21    0     0      8      0  0:00:02  0:00:02 --:--:--     8

我修改了下rotate.sh, 在删除前加入判断，能避免类似问题
