### ISSUE TITLE
腾讯云 CVM 安装文档补充

### ISSUE THREAD

**Issue by waitingsong** [easzlab/kubeasz#550]
original commit: 69f62d6207f4

[源码克隆](https://github.com/gjmzj/kubeasz/blob/69f62d6207f4a6ad8d45b090ac5bf294875b5a0a/docs/setup/kubeasz_on_tencent_cloud.md#3-%E8%B5%84%E6%BA%90%E5%87%86%E5%A4%87)
```sh
git clone --depth=1 -b cvm https://github.com/waitingsong/kubeasz.git /etc/ansible
```

这个链接版本删除了某些关于 CentOS 组建安装、卸载的配置，而是在创建的 [自定义镜像](https://github.com/waitingsong/blog/blob/master/201904/CentOS7-initialize-cvm-boilerplate.md) 中实现的。 我更新了原文[添加了链接](https://github.com/waitingsong/blog/commit/704ac09767d77d507bbf1e27bd1feb7e7303defc)  。

你可以同步更新或者直接替换克隆命令为 kubeasz 原始的:
```sh
git clone --depth=1 https://github.com/gjmzj/kubeasz.git /etc/ansible
```

**Comment by gjmzj** [comment]
你的cvm自定义动作可真不少:D

**Comment by waitingsong** [comment]
@gjmzj  
- yaml 改动主要是对 centos 组建的安装和删除在自定义镜像里面先准备好
 - 自定义镜像里面很多安装包及配置是一直来的（单机）系统模板，原先的还要多些（包括了 nginx, php, mail, db 等等多个服务安装、编译需要用到的环境）。进入容器时代后会逐步精简

**Comment by waitingsong** [comment]
fixed
