### ISSUE TITLE
最新版master部署网络插件cni时报错

### ISSUE THREAD

**Issue by Polaris0112** [easzlab/kubeasz#553]
版本信息如下，集群可以正常启动，但是安装cni插件的时候发生报错
![image](https://user-images.githubusercontent.com/35207012/57614796-ae439480-75ac-11e9-93ae-1aa25008fe93.png)
![image](https://user-images.githubusercontent.com/35207012/57614876-e519aa80-75ac-11e9-8842-b3e50ce20126.png)
kubelet[24269]: W0513 18:28:09.863788   24269 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d

 /etc/cni/net.d这个目录下没有生成cni对应的配置文件

使用的网络插件是calico v3.4.3

**Comment by kubeasz** [comment]
No networks found in /etc/cni/net.d 这个告警信息是暂时的；
等calico相关容器镜像拉取完成后，kubectl get pod -n kube-system|grep calico运行正常后，/etc/cni/net.d这个目录下自然就有配置

**Comment by Polaris0112** [comment]
> No networks found in /etc/cni/net.d 这个告警信息是暂时的；
> 等calico相关容器镜像拉取完成后，kubectl get pod -n kube-system|grep calico运行正常后，/etc/cni/net.d这个目录下自然就有配置

感谢回复，在这个问题发生之后我大概用了半天的时候搜索三种解决方案：
第一个就是作者说的
第二个就是部分节点的文件缺失，补全就是（但是并不是现在这种情况）
第三个就是把kubelet启动参数把关于cni的参数都注释（治标不治本）

最后发现是配置文件中分配的网段设置范围太少？导致的
># 服务网段 (Service CIDR），注意不要与内网已有网段冲突
>SERVICE_CIDR="10.1.32.0/24"
>
># POD 网段 (Cluster CIDR），注意不要与内网已有网段冲突
>CLUSTER_CIDR="10.1.33.0/26"

我也找了相关calico的ip pool resource配置文档：
https://docs.projectcalico.org/v3.5/reference/calicoctl/resources/ippool
里面提及到cidr的范围必须满足must be at least big enough to fit a single block (by default /26 for IPv4 or /122 for IPv6)

不过这个配置应该是pod和svc的网段设置过低导致吧
