### ISSUE TITLE
使用旧版安装的 etcd 会出现这个kubernetes #72102 问题,有没有办法解决呢. 

### ISSUE THREAD

**Issue by a33151** [easzlab/kubeasz#555]
您好!感谢抽空查看这个issue ,有个问题想问一下

看到1.01版本上有关于这个bug的问题
*  修复首个etcd成员故障时apiserver也故障的bug，详见 kubernetes issue #72102
检查了一下当前集群,的确是存在的, 想问问有办法解决吗?

使用的版本:kubeasz 0.4.0

**Comment by kubeasz** [comment]
找到你项目中文件 roles/etcd/templates/etcd-csr.json.j2；然后按照kubeasz新版对应文件修改更新；
然后执行一遍 ansible-playbook /etc/ansible/02.etcd.yml 成功即可。

**Comment by a33151** [comment]
@kubeasz 感谢,会不会影响etcd用数据,?因为是生产环境.

**Comment by gjmzj** [comment]
不会影响，只是重启下并使用新的etcd 证书

**Comment by a33151** [comment]
非常感谢回复,之后我会尝试修改!

**Comment by sunshanpeng** [comment]
测试过可用，老版本除了roles/etcd/templates/etcd-csr.json.j2还要按照最新版修改roles/etcd/tasks/main.yaml
