### ISSUE TITLE
 kernel: Memory cgroup out of memory: Kill process 1841 (exe) score 0 or sacrifice child

### ISSUE THREAD

**Issue by wrightxu** [easzlab/kubeasz#556]
May 15 17:05:42 qh-billsrm kernel: Task in /kubepods/pod5e3c4bcb-760b-11e9-bcb4-5c260afbd27c/56f14365daad5b7ea9d7960ec1ddf31777941d7ce80221d373668ca637fdf6fa killed as a result of limit of /kubepods/pod5e3c4bcb-760b-11e9-bcb4-5c260afbd27c
May 15 17:05:42 qh-billsrm kernel: memory: usage 51200kB, limit 51200kB, failcnt 840635
May 15 17:05:42 qh-billsrm kernel: memory+swap: usage 51200kB, limit 9007199254740988kB, failcnt 0
May 15 17:05:42 qh-billsrm kernel: kmem: usage 51196kB, limit 9007199254740988kB, failcnt 0
May 15 17:05:42 qh-billsrm kernel: Memory cgroup stats for /kubepods/pod5e3c4bcb-760b-11e9-bcb4-5c260afbd27c: cache:4KB rss:0KB rss_huge:0KB mapped_file:0KB swap:0KB inactive_anon:0KB active_anon:4KB inactive_file:0KB active_file:0KB unevictable:0KB
May 15 17:05:42 qh-billsrm kernel: Memory cgroup stats for /kubepods/pod5e3c4bcb-760b-11e9-bcb4-5c260afbd27c/56f14365daad5b7ea9d7960ec1ddf31777941d7ce80221d373668ca637fdf6fa: cache:0KB rss:0KB rss_huge:0KB mapped_file:0KB swap:0KB inactive_anon:0KB active_anon:0KB inactive_file:0KB active_file:0KB unevictable:0KB
May 15 17:05:42 qh-billsrm kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
May 15 17:05:42 qh-billsrm kernel: [ 1841]     0  1841     1637       65       7        0          -999 exe
May 15 17:05:42 qh-billsrm kernel: Memory cgroup out of memory: Kill process 1841 (exe) score 0 or sacrifice child
May 15 17:05:42 qh-billsrm kernel: Killed process 1841 (exe) total-vm:6548kB, anon-rss:64kB, file-rss:196kB, shmem-rss:0kB

**Comment by gjmzj** [comment]
能否提供一下你kubelet的运行配置 /etc/systemd/system/kubelet.service;
出问题的节点是否资源不足了（cpu/内存等）

**Comment by wrightxu** [comment]
问题主机资源是比较足，配置和其他主机一致。现在问题已经解决，分析方法如下：
            问题主机上，每个po上均出现内存不足的问题；
            查docker物理主机的kubelet日志，发现出现以下问题信息：process_linux.go:293，write init-p: broken pipe\"": unknown.

            百度上有人指出来：
                导致此问题的原因是docker版本是18.09.2，centos7的内核版本是3.xxxx版本，需要将centos的内核升级到4.20版本即可。

                centos内核升级教程链接：https://www.tecmint.com/install-upgrade-kernel-version-in-centos-7/

                参考资料链接：https://forums.docker.com/t/centos7-docker-hello-world-fails/68941/2
            11.131内核升级到最新版5.1.2后，问题消失了。
            但该节点还未能调度，将节点纳入集群：
                 kubectl patch node 192.168.11.131 -p '{"spec":{"unschedulable":false}}'

**Comment by waitingsong** [comment]
CentOS7的内核比较古老，虽然 back porting 了不少东西，单对于docker的支持还是不够理想。
升级内核，或者等 CentOS8吧（内核好像是 4.19）。
