### ISSUE TITLE
harbor镜像拉取失败

### ISSUE THREAD

**Issue by jiangzhikele** [easzlab/kubeasz#558]
k8s一主一从。
harbor部署在master节点，此节点pull镜像正常获取到
![image](https://user-images.githubusercontent.com/38905258/57909478-7a6eb480-78b5-11e9-911e-3dd4af5caea4.png)
但是node节点一直pull失败
![image](https://user-images.githubusercontent.com/38905258/57909519-983c1980-78b5-11e9-9057-e14af994545d.png)
怎么回事？

**Comment by gjmzj** [comment]
你的harbor是安装在k8s之上吗？
我只用过单独使用docker-compose安装的harbor，没遇到过你的问题

**Comment by jiangzhikele** [comment]
OK了   是镜像的问题  可能是镜像的某些依赖下载不下来
