### ISSUE TITLE
fluentd-es-ds.yaml 2.4.0版本有问题

### ISSUE THREAD

**Issue by longdajiangjun** [easzlab/kubeasz#559]
fluentd-es-ds.yaml，创建pod时，v2.4.0版本有问题，会有个pod一直报CrashLoopBackOff 。

**Comment by longdajiangjun** [comment]
kube-system   fluentd-es-v2.4.0-4mfb6                 1/1     Running            0          60m
kube-system   fluentd-es-v2.4.0-7hhhv                 1/1     Running            0          60m
kube-system   fluentd-es-v2.4.0-8htgk                 0/1     CrashLoopBackOff   9          60m
kube-system   fluentd-es-v2.4.0-fbz2z                 1/1     Running            0          60m

**Comment by gjmzj** [comment]
1.kubectl describe 查看具体pod报错信息
2.kubectl get pod -n kube-system -o wide 具体查看报错节点上kubelet有什么错误日志

**Comment by longdajiangjun** [comment]
用的是k8s1.14，
[root@szjcqfg-centos-0 efk]# kubectl logs -n kube-system fluentd-es-v2.4.0-9dwsm -f
2019-05-20 03:24:01 +0000 [error]: [journald-container-runtime] failed to read data from plugin storage file path="/var/log/journald-container-runtime.pos/worker0/storage.json" error_class=Fluent::ConfigError error="Invalid contents (not object) in plugin storage file: '/var/log/journald-container-runtime.pos/worker0/storage.json'"
2019-05-20 03:24:01 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Unexpected error: failed to read data from plugin storage file: '/var/log/journald-container-runtime.pos/worker0/storage.json'"

**Comment by longdajiangjun** [comment]
kubectl describe pod fluentd-es-v2.4.0-9dwsm -n kube-system
.......
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  varlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:  
  varlibdockercontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers
    HostPathType:  
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      fluentd-es-config-v0.2.0
    Optional:  false
  fluentd-es-token-7tsg2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  fluentd-es-token-7tsg2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  51m                   default-scheduler  Successfully assigned kube-system/fluentd-es-v2.4.0-9dwsm to 10.7.1.3
  Normal   Pulled     49m (x5 over 51m)     kubelet, 10.7.1.3  Container image "mirrorgooglecontainers/fluentd-elasticsearch:v2.4.0" already present on machine
  Normal   Created    49m (x5 over 51m)     kubelet, 10.7.1.3  Created container fluentd-es
  Normal   Started    49m (x5 over 51m)     kubelet, 10.7.1.3  Started container fluentd-es
  Warning  BackOff    105s (x224 over 51m)  kubelet, 10.7.1.3  Back-off restarting failed container

**Comment by gjmzj** [comment]
`[error]: config error file="/etc/fluent/fluent.conf"`
是不是你改了fluentd-es-configmap的配置，提示是你的配置错误

**Comment by longdajiangjun** [comment]
https://github.com/fluent/fluentd-kubernetes-daemonset/issues/245
谢谢大神，在这里找到了答案，解决办法是在出错的机器上去执行
rm -rf /var/lib/journald-container-runtime.pos/

**Comment by longdajiangjun** [comment]
Yes. I fixed it by stopping docker, then `rm -rf` ing all `*.pos`
directories under the host's /var/log. I think there are some json files as well
