### ISSUE TITLE
kubernetes无法垃圾回收

### ISSUE THREAD

**Issue by Michael754267513** [easzlab/kubeasz#560]
新建一个namespaces，新建一个pod，svc在该ns下面，然后删除namespace发现namespace删不掉，namespace下面的资源也没法回收

**Comment by weifan01** [comment]
@Michael754267513  这么点信息不好判断，也没法复现啊，有没有日志啥的或者任何其他信息

**Comment by Michael754267513** [comment]
我这边也看不到什么日志，执行kubectl delete ns test 发现namespace test一直是terminating 状态无法被回收掉

**Comment by Michael754267513** [comment]
terminating 状态下执行kubectl delete ns test 下面报错信息，但是实际这个处于terminating的ns删不掉，回收不了
Error from server (Conflict): Operation cannot be fulfilled on namespaces "hptestenv132": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.

**Comment by waitingsong** [comment]
该 namespace 下还有其它资源存在？
