### ISSUE TITLE
FAILED - RETRYING: 以轮询的方式等待master服务启动完成 (5 retries left)

### ISSUE THREAD

**Issue by crazywjj** [easzlab/kubeasz#563]
TASK [kube-master : 以轮询的方式等待master服务启动完成] *****************************************************************************************************************************************
task path: /etc/ansible/roles/kube-master/tasks/main.yml:97
fatal: [172.17.0.116 -> 172.17.0.116]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/opt/kube/bin/kubectl", "get", "node"], "delta": "0:02:00.142652", "end": "2019-05-21 11:31:19.851596", "msg": "non-zero return code", "rc": 1, "start": "2019-05-21 11:29:19.708944", "stderr": "Unable to connect to the server: dial tcp 192.168.5.200:8443: i/o timeout", "stderr_lines": ["Unable to connect to the server: dial tcp 192.168.5.200:8443: i/o timeout"], "stdout": "", "stdout_lines": []}

我已经将hosts中的，集群模式改为了DEPLOY_MODE=single-master，但是还是无法启动master

**Comment by gjmzj** [comment]
一般是由于/etc/ansible/hosts配置有问题引起
