### ISSUE TITLE
删除节点报错

### ISSUE THREAD

**Issue by ilanni2460** [easzlab/kubeasz#564]
无论是使用easzctl 命令删除节点，还是使用ansible-playbook命令删除，都会报错。
报错信息如下：
TASK [获取是否运行名为'kubeasz'的容器] **************************************************************************************************************************************************
fatal: [192.168.0.184]: FAILED! => {"msg": "The conditional check 'CONTAINER_RUNTIME == 'docker'' failed. The error was: error while evaluating conditional (CONTAINER_RUNTIME == 'docker'): 'CONTAINER_RUNTIME' is undefined\n\nThe error appears to have been in '/etc/ansible/tools/clean_one_node.yml': line 74, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: 获取是否运行名为'kubeasz'的容器\n          ^ here\n"}

通过把clean_one_node.yml文件中，如下代码注释掉，可以继续执行删除动作：

        #- name: 获取是否运行名为'kubeasz'的容器
        #  shell: 'docker ps|grep kubeasz || echo "NOT FOUND"'
        #  register: install_info

        - name: stop and disable docker service
          service:
            name: docker
            state: stopped
            enabled: no
          ignore_errors: true
          when: "'kubeasz' not in install_info.stdout"

        #- name: unmount docker filesystem-1
        #  mount: path=/var/run/docker/netns/default state=unmounted
        #  when: "'kubeasz' not in install_info.stdout"

        #- name: unmount docker filesystem-2
        #  mount: path=/var/lib/docker/overlay state=unmounted
        #  when: "'kubeasz' not in install_info.stdout"

**Comment by gjmzj** [comment]
嗯，提示`'CONTAINER_RUNTIME' is undefined` ，早上更新了master代码，集成了containerd安装；所以需要在已有ansible hosts中增加变量 CONTAINER_RUNTIME="docker"；
可以参考 example 中的例子

**Comment by ilanni2460** [comment]
问题已经解决了，是因为新版在hosts文件中加入了，对containerd的支持。
如果使用旧的hosts文件模版，需要在hosts文件中加入：
# 集群容器运行时，支持 docker, containerd
CONTAINER_RUNTIME="docker"
