### ISSUE TITLE
allinone的时候分发证书报错

### ISSUE THREAD

**Issue by xiaoweihong** [easzlab/kubeasz#566]
failed: [192.168.2.47] (item=ca.pem) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshpass -d6 /usr/bin/rsync --delay-updates -F --compress --archive '--out-format=<<CHANGED>>%i %n%L' /etc/kubernetes/ssl/ca.pem /etc/kubernetes/ssl/ca.pem", "item": "ca.pem", "msg": "[Errno 32] Broken pipe", "rc": 32}

**Comment by xiaoweihong** [comment]
我用的是ansible 用户名密码方式取执行playbook，换成免密方式后，没有这个错误了，是不是不支持用户名密码方式呀，必须用公私钥方式呢？

**Comment by gjmzj** [comment]
ansible执行是没问题，只是这里 rsync 执行也依赖ssh登陆的
