### ISSUE TITLE
怎么修改alertmanager的报警模版

### ISSUE THREAD

**Issue by zhangiicc** [easzlab/kubeasz#567]
没有找到默认的demo.tmpl文件

**Comment by gjmzj** [comment]
项目中 prometheus 是使用 helm 安装的，要修改告警规则的话，只需更新 `/etc/ansible/manifests/prometheus/prom-alertrules.yaml` 然后按照项目文档 helm upgrade就行

**Comment by zhangiicc** [comment]
我要修改的不是报警规则，是告警样式
![image](https://user-images.githubusercontent.com/30918699/58306657-c1692680-7e2e-11e9-8e60-658eeb74bf00.png)

**Comment by weifan01** [comment]
还有请问下那个labels怎么去掉？感觉告警出来一大堆，只需要看见关键信息就行了

**Comment by crazily-snail** [comment]
这个问题 到现在 有解决办法吗  我在 prom-alertsmanager.yaml 文件中添加了模版文件，
并将其 手动复制到了 pod的指定位置 ，但是看起来还是没有生效
templates:
- /etc/wechat.tmpl
