### ISSUE TITLE
集群启动后再关闭基础认证，kubectl delete -f  basic-auth-rbac.yaml后页面还是弹出密码框

### ISSUE THREAD

**Issue by huanzui** [easzlab/kubeasz#570]
集群启动后再关闭基础认证，kubectl delete -f  basic-auth-rbac.yaml后dashboard页面还是弹出密码框
kubeasz-1.1.0   k8s 1.12.8  
开始BASIC_AUTH_ENABLE == "yes"安装  后 访问dashboard页面弹出密码框，输入后进入token输入框，觉得很麻烦，就关闭基础认证，kubectl delete -f  basic-auth-rbac.yaml后dashboard页面还是弹出密码框，是还需要重启什么服务么？请教请教

**Comment by gjmzj** [comment]
概念有点混淆了，basic-auth-rbac.yaml 这个文件是为用户创建对应 rbac权限；需要关闭基础认证的话：
```
$ easzctl basic-auth -S
```

**Comment by huanzui** [comment]
> 概念有点混淆了，basic-auth-rbac.yaml 这个文件是为用户创建对应 rbac权限；需要关闭基础认证的话：
> 
> ```shell
> $ easzctl help basic-auth
> Usage: easzctl basic-auth <options>
> Option:	 -s enable basic-auth
> 	 -S disable basic-auth
> 	 -u <user> set username
> 	 -p <pass> set password
> # 关闭
> $ easzctl basic-auth -S
> ```
非常感谢，我这里的easzctl在文件夹下 cd /etc/ansible/kubeasz/tools
再执行basic-auth basic-auth -S 报错
grep: roles/kube-master/defaults/main.yml: No such file or directory
看了kubeasz代码，是要在roles/kube-master/defaults/main.yml 这个地址要写绝对地址吧 ，或都引入变量base_dir。

**Comment by huanzui** [comment]
比较悲剧的是不用basic-auth后，https://10.3.87.34:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login，kubernetes-dashboard页面返回
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
