### ISSUE TITLE
通过traefik访问不了kubernetes-dashboard页面

### ISSUE THREAD

**Issue by huanzui** [easzlab/kubeasz#573]
通过traefik访问不了kubernetes-dashboard页面
k8s  1.12.8 
traefik:v1.7.4
服务：
[root@monitor ~]# kubectl get svc -n kube-system
NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                       AGE
heapster                  ClusterIP   10.68.73.67    <none>        80/TCP                        5d20h
kube-dns                  ClusterIP   10.68.0.2      <none>        53/UDP,53/TCP,9153/TCP        22h
kubernetes-dashboard      NodePort    10.68.87.14    <none>        443:25304/TCP                 5d20h
metrics-server            ClusterIP   10.68.89.160   <none>        443/TCP                       5d20h
traefik-ingress-service   NodePort    10.68.19.179   <none>        80:23456/TCP,8080:25900/TCP   5d20h

本机hosts映射：10.3.87.34是master服务器
10.3.87.34 traefik-ui.com
10.3.87.34 dashboard-ui.com

能直接通过nodeport 正常访问kubernetes-dashboard：
https://10.3.87.34:25304

布署了traefik后
加了 traefik-ui.ing.yaml

k8s-dashboard.ing.yaml内容：
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  kubernetes-dashboard
  namespace: kube-system
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: dashboard-ui.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 443

现在能通过http://traefik-ui.com:23456/dashboard/访问traefik-ui页面
![image](https://user-images.githubusercontent.com/7300261/58533185-66627580-821a-11e9-80b1-b6d6363e9c3a.png)

但访问kubernetes-dashboard找不到页面：
http://dashboard-ui.com、https://dashboard-ui.com/#!/login 、http://dashboard-ui.com/#!/login
请问下这个是访问方法错了还是要加端口还是还有什么地方要加认证呢？

**Comment by gjmzj** [comment]
ingress 有没有开启https，安装文档一步步下来应该可以的， https://github.com/easzlab/kubeasz/blob/master/docs/guide/ingress-tls.md#%E9%85%8D%E7%BD%AE-dashboard-ingress

**Comment by huanzui** [comment]
> ingress 有没有开启https，按照文档一步步下来应该可以的（多次测试过）， https://github.com/easzlab/kubeasz/blob/master/docs/guide/ingress-tls.md#%E9%85%8D%E7%BD%AE-dashboard-ingress

感谢回复，我重新按照文档操作 ，先delete traefik-controller.yaml再 apply traefik-controller.yaml：
traefik-controller.yaml部分内容如下，内容没有改过，只是traefik用的是1.7.4的：
  traefik.toml: |
    # 设置insecureSkipVerify = true，可以配置backend为443(比如dashboard)的ingress规则
    insecureSkipVerify = true
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        ### 配置http 强制跳转 https
        #[entryPoints.http.redirect]
        #  entryPoint = "https"
        ### 配置只信任trustedIPs传递过来X-Forwarded-*，默认全部信任；为了防止客户端地址伪造，需开启这个
        #[entryPoints.http.forwardedHeaders]
        #  trustedIPs = ["10.1.0.0/16", "172.20.0.0/16", "192.168.1.3"]
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
            CertFile = "/ssl/tls.crt"
            KeyFile = "/ssl/tls.key"

k8s-dashboard.ing.yaml只改了 - host: dashboard.test.com=》 dashboard-ui.com
但还是访问kubernetes-dashboard找不到页面：
http://dashboard-ui.com、https://dashboard-ui.com/#!/login 、http://dashboard-ui.com/#!/login

而https://dashboard-ui.com:25304可以访问，这个是对的？
25304就nodeport，没装之前就可以访问，那这样访问方式与装不装traefik有什么区别呢？

**Comment by gjmzj** [comment]
你还少了一个步骤； traefik 确实也是需要用nodePort访问的，除非你修改traefik使用 hostPort 443端口，或者用nginx/haproxy转换一下端口；这里有文档
https://github.com/easzlab/kubeasz/blob/master/docs/op/loadballance_ingress_nodeport.md

**Comment by huanzui** [comment]
> 你还少了一个步骤； traefik 确实也是需要用nodePort访问的，除非你修改traefik使用 hostPort 443端口，或者用nginx/haproxy转换一下端口；这里有文档
> https://github.com/easzlab/kubeasz/blob/master/docs/op/loadballance_ingress_nodeport.md

谢谢，上了Haproxy，按照文档配后确实可以用 https://dashboard-ui.com 访问了
