### ISSUE TITLE
kubelet因无法创建/sys/fs/cgroup/pids路径启动失败

### ISSUE THREAD

**Issue by ndaysy** [easzlab/kubeasz#575]
kubelet.service需要创建下述路径，但/sys/fs/cgroup路径是只读的，因此无法启动
[Service]
WorkingDirectory=/var/lib/kubelet
ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/cpuset/system.slice/kubelet.service
ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/hugetlb/system.slice/kubelet.service
ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/memory/system.slice/kubelet.service
ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/pids/system.slice/kubelet.service

启动报错：
systemd[1]: Starting Kubernetes Kubelet...
mkdir[69427]: /bin/mkdir: cannot create directory ‘/sys/fs/cgroup/pids’: Read-only file system
systemd[1]: kubelet.service: control process exited, code=exited status=1
systemd[1]: Failed to start Kubernetes Kubelet.

系统信息：centos7.2 内核3.10

**Comment by ndaysy** [comment]
升级内核可以解决。
不知资源预留最低内核版本要求是多少？

**Comment by gjmzj** [comment]
centos7.2 执行 yum update 升级到 7.6好像也能解决；
当然最新代码中可以在roles/kube-node/defaults/main.yml，禁用设置KUBE_RESERVED_ENABLED: "no"

**Comment by ndaysy** [comment]
yum update好像不能升级内核，这个问题已经明确，关闭
