### ISSUE TITLE
calico什么时候升级到3.6.x 3.7.x呢

### ISSUE THREAD

**Issue by currycan** [easzlab/kubeasz#578]
弱弱的问一句，calico什么时候升级到3.6.x 3.7.x呢？

**Comment by kubeasz** [comment]
3.6/3.7 是否有特别有意思的功能，如果你比较了解的话，可以给大家介绍下，我目前更新策略是根据 k8s 社区支持的calico版本，以确保稳定性；

**Comment by currycan** [comment]
close
