### ISSUE TITLE
多网络插件选择 flannel calico

### ISSUE THREAD

**Issue by gjmzj** [easzlab/kubeasz#58]
近期开始准备 flannel calico网络插件支持
1. flannel 和 calico 将以DaemonSet pod形式运行 (现有calico是以systemd daemon运行的)
2. flannel 直接使用apiserver 存储数据而不是etcd
3. calico 将仍旧使用etcd存储数据
4. 新增分支v1.9，分支v1.8和v1.9将保留目前单calico时的安装模式，新master分支将采用多网络插件方式供选择，如果你只需要calico网络且保留目前安装方式请继续使用v1.9和v1.8模式
5. master分支将始终使用最新版k8s，目前即1.9

**Comment by gjmzj** [comment]
各位如果有什么好的建议请留言

**Comment by EamonZhang** [comment]
建议１　，一个分支对应一个ｋ８ｓ的版本，并把tag对应关系写在　readme 中

新增分支在v1.９中没有看到  ,分支是否与ｋ８ｓ版本对应。　这样可以在安装的时候选择指定版本安装，ｋ8s 的　安装方式每个版本会有差异，或不兼容。

**Comment by evenye** [comment]
请问flannel 和 calico在这套cluster 中各有什么优缺点吗?

**Comment by gjmzj** [comment]
@EamonZhang 一个分支会对应一个k8s大版本，tag会对应某个小版本；待新增的分支v1.9其实就是目前的master，这个是预讨论，还没开始动作
@evenye 不同网络插件优缺点网上有很多分析资料；calico能额外支持networkpolicy，对于生产环境来说很有用，比如保护特定应用的访问，但部署相对复杂一点

**Comment by gjmzj** [comment]
目前已按该`Milestone`更新项目，涉及变更较多，如有问题请反馈；后续还有一些变更文档更新

**Comment by DiamondYuan** [comment]
能否考虑利用docker来启动全部的容器。利用docker来部署。

**Comment by feie22** [comment]
calico2.6支持etcd v2，calico3.0才明确说支持etcd v3，目前这个calico方案是否会有问题

**Comment by gjmzj** [comment]
calico2.6 默认`DATASTORE_TYPE` 就是etcdv2，所以目前这个方案没有问题

**Comment by zwx168238** [comment]
如果可以做成docker 一键部署就厉害了

**Comment by gjmzj** [comment]
@sunchangming 抱歉未能及时回复，提示no ipv4 peers found，是否你是allinone安装，如果是的话，当然没有邻居了；没有calico开头的网卡是否是因为你的集群还未创建pod，相信你创建pod后能够看到，具体的安装指南，请详细阅读本项目文档和calico官网相关文档

**Comment by Zhan-Jie** [comment]
小伙子，在Azure三台虚拟机上安装kubernetes集群，使用calico网络插件，安装后，不同主机间pod无法通信。后来知道是因为微软云会[禁止未知源IP的流量](https://docs.projectcalico.org/v3.1/reference/public-cloud/azure)。
我该有什么好的方法自动检测一下当前网络环境是否支持calico，好在安装之前自动决定安装calico还是flannel？

**Comment by QiQingLin7** [comment]
> 小伙子，在Azure三台虚拟机上安装kubernetes集群，使用calico网络插件，安装后，不同主机间pod无法通信。后来知道是因为微软云会[禁止未知源IP的流量](https://docs.projectcalico.org/v3.1/reference/public-cloud/azure)。
> 我该有什么好的方法自动检测一下当前网络环境是否支持calico，好在安装之前自动决定安装calico还是flannel？

小伙子，来杯红牛压压惊
