### ISSUE TITLE
https://NodeIP:NodePort 方式访问 dashboard 无法访问 

### ISSUE THREAD

**Issue by xinyangbest** [easzlab/kubeasz#582]
https://NodeIP:NodePort 方式访问 dashboard无法访问 多主

**Comment by xinyangbest** [comment]
提示
错误代码： HTTP ERROR -2146697211

**Comment by xinyangbest** [comment]
并且 flannel 内网无法ping通

**Comment by xinyangbest** [comment]
# 服务网段 (Service CIDR），注意不要与内网已有网段冲突
SERVICE_CIDR="10.68.0.0/16"

# POD 网段 (Cluster CIDR），注意不要与内网已有网段冲突
CLUSTER_CIDR="172.20.0.0/16"

172.20 的网段可以 10.68 的不行

**Comment by kubeasz** [comment]
> 
> 
> 提示
> 错误代码： HTTP ERROR -2146697211

是不是提示证书不安全，换个浏览器试试

**Comment by xinyangbest** [comment]
不是整数的问题就是无法访问，端口是在的，而且还有一个问题就是配置的168网段是ping不通的 但是172的那个网段可以

**Comment by xinyangbest** [comment]
按照多主多节点示例的节点配置，准备4台虚机
我见案例上 
192.168.1.1 
192.168.1.2
192.168.1.3
192.168.1.4
正好是4台
但是下面这个192.168.1.10 是出现了第5台吗？
MASTER_IP="192.168.1.10"
KUBE_APISERVER="https://{{ MASTER_IP }}:8443"
我把这个配置的其中一个主的ip 192.168.1.2 是这个影响的dashboard 无法访问 吗？
