### ISSUE TITLE
多主多节点安装 ingress后 直接无法连接上集群

### ISSUE THREAD

**Issue by xinyangbest** [easzlab/kubeasz#590]
kubectl create -f /etc/ansible/manifests/ingress/traefik/traefik-ingress.yaml
![image](https://user-images.githubusercontent.com/26601064/59350048-b6c6f080-8d4d-11e9-9cd6-3323f9376298.png)

**Comment by kubeasz** [comment]
你是多网卡机器吗？部署时使用的kubeasz 代码是哪个版本

**Comment by xinyangbest** [comment]
不是多网卡，vmware虚拟出来的，网络用的net模式共享主机网络，安装了igress后 集群的vip虚拟地址无法访问，但是2主 的apiserver是可以访问的，只有虚拟的vip无法访问

**Comment by xinyangbest** [comment]
kubeasz 是最新clone的
