### ISSUE TITLE
百度网盘链接失效了

### ISSUE THREAD

**Issue by TonyBian** [easzlab/kubeasz#595]
如题

**Comment by AzraelJi** [comment]
同上百度云分享失效了。。。。

**Comment by gjmzj** [comment]
链接:https://pan.baidu.com/s/1zGISPQ_hLvHxhCTfUoRXBA 提取码:qu2c 复制这段内容后打开百度网盘手机App，操作更方便哦
- 1. 之前的分享好像1年到期结束了，百度盘不允许再开无提取码的分享了。
- 2. 百度网盘的二进制文件包不再更新了，因为我们有更方便的下载方式了，详见 tools/easzup 工具脚本

**Comment by TonyBian** [comment]
👍👍👍

**Comment by yoli799480165** [comment]
@gjmzj  easzup 工具有问题，如果是deploy节点复用了master节点的话，easzup工具默认会先安装docker，那么在执行ansible-playbook 03.docker.yml时可能会失败。

**Comment by gjmzj** [comment]
@yoli799480165 理论上两者安装的docker一致，如果怕出错的话，可以在easzup -D 运行成功后，手动停止 docker 服务；后续我看看能不能在 03.docker.yml安装时增加判断是否已经运行docker
