### ISSUE TITLE
EFK过程中，fluent连接不上es

### ISSUE THREAD

**Issue by jiangzhikele** [easzlab/kubeasz#596]
![image](https://user-images.githubusercontent.com/38905258/59828485-bb069580-936d-11e9-93e0-1dec9886f1c2.png)

**Comment by gjmzj** [comment]
是不是 es的 pod 还没有正常 running；
你如果希望别人帮你检查问题，请提供尽量多的信息

**Comment by jiangzhikele** [comment]
部署两个es,集群选举正常
![image](https://user-images.githubusercontent.com/38905258/60006622-692e7a00-96a3-11e9-8025-f282dcff11ab.png)
![image](https://user-images.githubusercontent.com/38905258/60006672-7f3c3a80-96a3-11e9-9784-84cc1d850e69.png)
kibana
![image](https://user-images.githubusercontent.com/38905258/60006717-911ddd80-96a3-11e9-8226-3cf6c954d5f4.png)
但是fluentd一直报错
![image](https://user-images.githubusercontent.com/38905258/60006767-a561da80-96a3-11e9-8447-fbbad4aeb489.png)
![image](https://user-images.githubusercontent.com/38905258/60006783-ae52ac00-96a3-11e9-9805-a3b90efaa53c.png)
![image](https://user-images.githubusercontent.com/38905258/60006796-b3aff680-96a3-11e9-9cfa-a2aeb783ad9d.png)

**Comment by gjmzj** [comment]
我看了错误日志，发现 es应该没有问题，因为kibana提示已经连接上es；
然后我在 kubernetes 项目issues里面搜索 `fluent failed to flush the buffer `;
发现这个跟你类似 https://github.com/kubernetes/kubernetes/issues/72150

**Comment by jiangzhikele** [comment]
现在又出现新的问题
![image](https://user-images.githubusercontent.com/38905258/60162596-7165f100-982c-11e9-9341-7000cfad5a3c.png)
多次刷新后，有添加索引节点，但是出现503
![image](https://user-images.githubusercontent.com/38905258/60162651-8b9fcf00-982c-11e9-9d36-edf13b527813.png)
查看日志
kibana
![image](https://user-images.githubusercontent.com/38905258/60162684-9eb29f00-982c-11e9-84fd-38c3ff5bca93.png)
fluted
![image](https://user-images.githubusercontent.com/38905258/60162711-a7a37080-982c-11e9-9ee6-c2b195d180d5.png)

**Comment by gjmzj** [comment]
efk安装是比较耗资源的，确认你的集群有充足资源，kubectl top node 大致看看

**Comment by jiangzhikele** [comment]
![image](https://user-images.githubusercontent.com/38905258/60226263-06182f80-98bd-11e9-865b-180102568132.png)
es我给的2g
还有这个pod时间的设置怎么统一到一致
