### ISSUE TITLE
最新的安装方式报错

### ISSUE THREAD

**Issue by xiawanyingtest** [easzlab/kubeasz#599]
用容器安装的，非百度云
错误信息：
TASK [kube-master : enable master 服务] ***************************************************************************************************************************************************************************
changed: [192.168.1.121]

TASK [kube-master : 启动 master 服务] *******************************************************************************************************************************************************************************
fatal: [192.168.1.121]: FAILED! => {"changed": true, "cmd": "systemctl daemon-reload && systemctl restart kube-apiserver && systemctl restart kube-controller-manager && systemctl restart kube-scheduler", "delta": "0:00:00.344587", "end": "2019-06-22 03:33:41.154084", "msg": "non-zero return code", "rc": 1, "start": "2019-06-22 03:33:40.809497", "stderr": "Job for kube-apiserver.service failed because the control process exited with error code. See \"systemctl status kube-apiserver.service\" and \"journalctl -xe\" for details.", "stderr_lines": ["Job for kube-apiserver.service failed because the control process exited with error code. See \"systemctl status kube-apiserver.service\" and \"journalctl -xe\" for details."], "stdout": "", "stdout_lines": []}

**Comment by piaobeizu** [comment]
您好，请问是怎么解决的？

**Comment by xkfen** [comment]
我也是遇到了这个问题，反复装了几次，然后也按照了相关issue也没有解决。
刚刚就想看下docker 安装的哪个版本，提示我docker没有启动。
于是我把docker启动了，再次执行：
systemctl daemon-reload && systemctl restart kube-apiserver && systemctl restart kube-controller-manager && systemctl restart kube-scheduler

问题就解决了

**Comment by MichelLiu** [comment]
8080端口被占用也会报次错误，需要修改--insecure-port参数
