### ISSUE TITLE
容器化集群部署

### ISSUE THREAD

**Issue by xiawanyingtest** [easzlab/kubeasz#600]
这个文档好像没有

**Comment by gjmzj** [comment]
看这两个文档就够了，容器化集群部署跟原来没啥差别，只不过原来直接在宿主机上执行 ansible-playbook xxx命令，而容器化时这样执行 docker exec -it kubeasz ansible-playbook xxx
https://github.com/easzlab/kubeasz/blob/master/docs/setup/quickStart.md
https://github.com/easzlab/kubeasz/blob/master/docs/setup/00-planning_and_overall_intro.md
