### ISSUE TITLE
部署失败-基于容器部署方式

### ISSUE THREAD

**Issue by xiawanyingtest** [easzlab/kubeasz#601]
TASK [cluster-addon : 尝试推送离线 heapster镜像（若执行失败，可忽略）] *************************************************************************************************************************************************************
fatal: [192.168.1.135]: FAILED! => {"msg": "The conditional check '\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"' failed. The error was: error while evaluating conditional (\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"): 'heapster_install' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/cluster-addon/tasks/main.yml': line 129, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    - block:\n        - name: 尝试推送离线 heapster镜像（若执行失败，可忽略）\n          ^ here\n"}
...ignoring

TASK [cluster-addon : 获取heapster离线镜像推送情况] ***********************************************************************************************************************************************************************
fatal: [192.168.1.135]: FAILED! => {"msg": "The conditional check '\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"' failed. The error was: error while evaluating conditional (\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"): 'heapster_install' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/cluster-addon/tasks/main.yml': line 133, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: 获取heapster离线镜像推送情况\n          ^ here\n"}
...ignoring

TASK [cluster-addon : 导入 heapster的离线镜像（若执行失败，可忽略）] **************************************************************************************************************************************************************
fatal: [192.168.1.135]: FAILED! => {"msg": "The conditional check '\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"' failed. The error was: error while evaluating conditional (\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"): 'heapster_install' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/cluster-addon/tasks/main.yml': line 137, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: 导入 heapster的离线镜像（若执行失败，可忽略）\n          ^ here\n"}
...ignoring

TASK [cluster-addon : 导入 heapster的离线镜像（若执行失败，可忽略）] **************************************************************************************************************************************************************
fatal: [192.168.1.135]: FAILED! => {"msg": "The conditional check '\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"' failed. The error was: error while evaluating conditional (\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"): 'heapster_install' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/cluster-addon/tasks/main.yml': line 141, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: 导入 heapster的离线镜像（若执行失败，可忽略）\n          ^ here\n"}
...ignoring

TASK [cluster-addon : 创建 heapster部署] ****************************************************************************************************************************************************************************
fatal: [192.168.1.135]: FAILED! => {"msg": "The conditional check '\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"' failed. The error was: error while evaluating conditional (\"heapster\" not in pod_info.stdout and heapster_install == \"yes\"): 'heapster_install' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/cluster-addon/tasks/main.yml': line 145, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: 创建 heapster部署\n      ^ here\n"}

**Comment by xiawanyingtest** [comment]
如果用阿里云安装1.14.2版本，dashboard进不去，按日志显示大概是没有权限，怎么解决

**Comment by gjmzj** [comment]
看项目 dashboard 文档

**Comment by xiawanyingtest** [comment]
> 看项目 dashboard 文档

不是安装完成后就绑定了管理员RBAC了吗？安装后就有超级权限。我记得老版本我把1.6的UI，换个镜像改成1.8的UI安装后就可以直接打开dashboard了，文档看了，还是不明白，我是不是需要卸载重装dashboard

**Comment by xiawanyingtest** [comment]
系统基于centos7.4
