### ISSUE TITLE
v2.0.1自动安装失败

### ISSUE THREAD

**Issue by kelonsen** [easzlab/kubeasz#603]
报错如图：
![image](https://user-images.githubusercontent.com/16333743/59980048-dea63600-9622-11e9-9c51-42ad1adb052c.png)

**Comment by kelonsen** [comment]
容器里面已经挂载了/root/.kube所以不能直接删除.kube，可以删除里面的文件，麻烦修复，谢谢！
/dev/mapper/centos-root                         47.0G      4.5G     42.4G  10% /root/.kube

**Comment by gjmzj** [comment]
可能拉取的kubeasz 2.0.0版本是之前的缓存，新的已经修复这个问题；建议全部清理后，重新拉取镜像

**Comment by gjmzj** [comment]
感谢提醒 @kelonsen 
另外 2.0.1 是昨晚发错的版本，抱歉！正式版本为6/24发布的2.0.0
