### ISSUE TITLE
关于ansible下载时的问题，具体应该怎么操作，请指教

### ISSUE THREAD

**Issue by linux998** [easzlab/kubeasz#604]
[root@m-1 ~]# curl -C- -fLO --retry 3 https://github.com/easzlab/kubeasz/releases/download/${release}/easzup

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (22) The requested URL returned error: 404 Not Found

**Comment by gjmzj** [comment]
2x版本，最新就是2.0.0
curl -C- -fLO --retry 3 https://github.com/easzlab/kubeasz/releases/download/2.0.0/easzup
1x版本，最新就是1.3.0

**Comment by linux998** [comment]
非常感谢， ${release}  只用了1.3 测试，没用1.3.0。这个有说明文档吗？

**Comment by gjmzj** [comment]
最近的release版本，https://github.com/easzlab/kubeasz/releases 这里可以查看
