### ISSUE TITLE
easzup   ERROR] Action failed : download_all

### ISSUE THREAD

**Issue by linux998** [easzlab/kubeasz#605]
![kubeasz](https://user-images.githubusercontent.com/30073234/59989575-5f405300-9672-11e9-826d-981baff2efca.png)

以上是图片内容，
使用2.0.0或者1.3.0均出现以上情况。
以下是文本信息

[root@k8s-1 ~]# ./easzup -D
[INFO] Action begin : download_all
[WARN] docker is already running.
[INFO] downloading kubeasz 1.3.0
Trying to pull repository docker.io/easzlab/kubeasz ... 
1.3.0: Pulling from docker.io/easzlab/kubeasz
Digest: sha256:345aa4030f9dbf5099c088c95f9fe463b54ca0d657f6b6040e87f9cfbf632655
Status: Image is up to date for docker.io/easzlab/kubeasz:1.3.0
[INFO] run a temporary container
c134ccb91161b807636bc620eee5ae6973b33f0774f7e14078ecb66c04d1fd59
mv: 无法获取"/etc/ansible/down/docker-18.09.6.tgz" 的文件状态(stat): 没有那个文件或目录
[ERROR] Action failed : download_all

**Comment by linux998** [comment]
已经解决，将docker 版本换成18.09.6后开始正常工作，不报错。

**Comment by wangzeping722** [comment]
docker 版本为18.09.6也报错。
Docker version 18.09.6, build 481bc77

**Comment by yidaqiang** [comment]
我的解决方案是把本地安装的docker 删除

**Comment by gjmzj** [comment]
已发布 2.0.2 版本，解决了这个问题
