### ISSUE TITLE
node上的 haproxy 容器启动报错

### ISSUE THREAD

**Issue by TonyBian** [easzlab/kubeasz#606]
systemd[1]: Started haproxy.
docker[25435]: [ALERT] 174/081412 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:6] : cannot find user id for 'haproxy' (0:No error information)
docker[25435]: [ALERT] 174/081412 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:7] : cannot find group id for 'haproxy' (0:No error information)
docker[25435]: [ALERT] 174/081412 (1) : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
docker[25435]: [ALERT] 174/081412 (1) : Fatal errors found in configuration.
systemd[1]: haproxy.service: main process exited, code=exited, status=1/FAILURE
docker[25562]: haproxy
systemd[1]: Unit haproxy.service entered failed state.
systemd[1]: haproxy.service failed.

**Comment by gjmzj** [comment]
node上 haproxy是普通系统服务，不是容器化运行的；
不好意思，之前容器化运行haproxy是非正式发布的
