### ISSUE TITLE
2.0版本相关问题

### ISSUE THREAD

**Issue by diandiankou** [easzlab/kubeasz#609]
在使用2.0版本的时候，有以下几个问题：
1、  ./easzup -S启动的容器中无法访问相关节点，无法ping通，所以无法执行ansible任务。当前我是在宿主机安装ansible再执行相关操作的。
2、 ./easzup -D默认会安装和启动docker，如果当前部署节点和k8s想关节点在一起可能会出现问题(比如会重新安装docker)。
3、 现阶段备份好像没有跟1.x版本一样备份hosts文件和证书了，只有一个snapshot.db。
4、 还原的时候报lb组不存在，需要注释24.restore.yml中lb组。
5、 还原TASK [prepare : 分发 kubeconfig配置文件] 步骤报错：Could not find or access '/root/.kube/config'：
task代码如下：
- name: 分发 kubeconfig配置文件
      copy: src=/root/.kube/config dest=/root/.kube/config

6、node节点中haproxy不知道安装在什么地方，宿主机没看到安装，docker里也没看到安装。 (这个可能和我node和master在一起有关？)
暂未测试节点的添加和删除，目前集群已被清空，无法还原。

**Comment by gjmzj** [comment]
1. 需要宿主机上事先配置免密登陆到其他节点，然后 ./easzup -S 启动容器后就能执行 ansible 任务了
2. 如果已经运行 ./easzup -S 运行docker了，其实脚本会判断不会重新安装docker
3. 2x 版本的备份还原脚本目前没有调整过，后续会改造好
6. node节点安装haproxy比较智能：会判断是否有多个master，如果有才启动haproxy，如果只有一个master节点是不需要haproxy的：😀

**Comment by diandiankou** [comment]
1、宿主机上已做ssh互信，我和同事两个人都测试安装过，无法访问remote节点。同事的情况是前一次还可以，后一次把easzup -S的容器停止，重启后又不能访问remote节点了
4、node节点上的haproxy没有看到安装,我有两个两个主节点,但是有一个master节点和node节点共存。

**Comment by longdajiangjun** [comment]
2master+3node
用2.0安装成功
请详细检查安装过程，有没有遗漏或者安装错误。

**Comment by diandiankou** [comment]
已发布新版本
