### ISSUE TITLE
easzup 需要安装docker才能下载？

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#611]
root@Ansible tmp]#./easzup -D
[INFO] Action begin : download_all
[WARN] docker is already running.
[INFO] downloading kubeasz 2.0.0
./easzup: line 97: docker: command not found
[ERROR] Action failed : download_all
现在怎么搞成easzup下载安装包了？原来百度网盘的方式就挺好的了。现在下载流程要怎么走呢？

**Comment by longdajiangjun** [comment]
curl -C- -fLO --retry 3 https://github.com/easzlab/kubeasz/releases/download/2.0.0/easzup

**Comment by lichengx** [comment]
是会安装docker来下载镜像，easzup最好在deploy节点下载 docker镜像，这样和实际的k8s集群服务器的docker不冲突
