### ISSUE TITLE
easzup无法下载安装包建议取消这种方式

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#612]
我个人感觉这个工具真心不好用，不能给新老用户带来任何便利，反而给安装k8s集群带来了很多未知的麻烦，建议还是使用原来的网盘模式下载二进制安装包，简单又方便！没有任何环境依赖。
以下是本人安装了两次还没有下载下来二进制安装包，第一次是提示部署机上没有安装docker，第二次是安装好了docker，结果又提示有问题，如果是新手的话下载二进制岂不是更加麻烦？？？？

[root@Ansible tmp]#./easzup -D
[INFO] Action begin : download_all
[WARN] docker is already running.
[INFO] downloading kubeasz 2.0.0
2.0.0: Pulling from easzlab/kubeasz
e7c96db7181b: Pull complete 
128f1c17c28c: Pull complete 
a69820badab4: Pull complete 
Digest: sha256:6534e21f74a055c1fb3ad3cd7937aa1f2516c75e5f8b4befba748a9eb2e5490a
Status: Downloaded newer image for easzlab/kubeasz:2.0.0
[INFO] run a temporary container
e80ba3a039300f02c45b3260c22404501ea32256406c329cba868852c9371db1
mv: cannot stat ‘/etc/ansible/down/docker-18.09.6.tgz’: No such file or directory

**Comment by sunyifei83** [comment]
同感+1，当指定组件版本时候这个工具会有很多地方需要调整，可以并存但别直接取消网盘这种方式啊

**Comment by gjmzj** [comment]
刚发布了 2.0.1 版本，更新了easzup脚本，现在用起来应该很顺畅；
原有百度盘的二进制还在，不过不更新二进制文件了，链接:https://pan.baidu.com/s/1zGISPQ_hLvHxhCTfUoRXBA 提取码:qu2c

**Comment by Hello-Linux** [comment]
恩恩并存这种方式也不错。既方便了新手也方便了老玩家

**Comment by Hello-Linux** [comment]
@gjmzj  刚测试了一下easzup，效果不是很理想，建议弄一下并存的方式。我从百度网盘下载不要一分钟就完成了，但是使用了easzup整个流程下载要5分钟，网速差的话估计要10多分了，虽然easzup简化了流程但是我还是感觉原来网盘的效果好一点

**Comment by ndaysy** [comment]
离线安装流程不通的。
先在能联网的主机上通过easzup下载好了所有文件打包后，然后进入离线环境的主机，这些主机上是没有安装docker的，因此离线安装第一步“启动 kubeasz 容器”是不具备条件的

**Comment by gjmzj** [comment]
@ndaysy 抱歉忘记了一个步骤，离线机器上也预先执行下就行
```
./easzup -D
```
然后正常安装下去
