### ISSUE TITLE
ssh端口修改后，ansible all -m ping不可达

### ISSUE THREAD

**Issue by jiangzhikele** [easzlab/kubeasz#613]
![image](https://user-images.githubusercontent.com/38905258/60430694-811c7580-9c30-11e9-853b-be710dcbdc17.png)
请问在哪可以修改端口

**Comment by gjmzj** [comment]
在 /etc/ansible/hosts文件，各个主机组下添加非标准端口，比如：
```
[kube-node]
192.168.2.1 ansible_ssh_port=10022
```

**Comment by jiangzhikele** [comment]
我在阿里云3台机器上部署的，准备2个master，其中一个master也做node，还有一个node有deploy角色。
阿里云做了负载
![image](https://user-images.githubusercontent.com/38905258/60476560-a6e85f80-9cae-11e9-9d80-7b47cf3a5d34.png)
hosts文件
![image](https://user-images.githubusercontent.com/38905258/60476369-f5492e80-9cad-11e9-8cd5-6fefbdcd301a.png)
![image](https://user-images.githubusercontent.com/38905258/60476380-009c5a00-9cae-11e9-93f6-4beb69301e20.png)
在执行master文件报错
![image](https://user-images.githubusercontent.com/38905258/60476446-33465280-9cae-11e9-9bc3-039757141a7d.png)
请问这是host文件出错还是负载出错

**Comment by jiangzhikele** [comment]
现在有新的错误
![image](https://user-images.githubusercontent.com/38905258/60490441-1f641600-9cd9-11e9-9d73-3d93f59d2df2.png)
这是etcd的报错
![image](https://user-images.githubusercontent.com/38905258/60490457-23903380-9cd9-11e9-84ee-d1febc2c5dfb.png)
看了master和node的yaml文档，这两个有没有冲突啊，一台主机可以是master也可以是node?
![image](https://user-images.githubusercontent.com/38905258/60490543-51757800-9cd9-11e9-966d-b886525b58da.png)
![image](https://user-images.githubusercontent.com/38905258/60490547-5508ff00-9cd9-11e9-9114-25acbf42bf1f.png)
在hosts文件中
![image](https://user-images.githubusercontent.com/38905258/60490605-7669eb00-9cd9-11e9-938c-ebfe38ce3571.png)
https证书是自动默认使用本地签名？还是需要在阿里云上创建签名

**Comment by gjmzj** [comment]
你的kubeasz代码是什么版本，1.X和2.X版本的 hosts写法不一样；在公有云上建议使用 2.X 版本，不需要配置slb

**Comment by jiangzhikele** [comment]
我用的2.0的，hosts模板没有slb选项，但是在公有云的文档中有，所以是不需要写master-ip地址吗？
![image](https://user-images.githubusercontent.com/38905258/60505456-572d8680-9cf6-11e9-8032-35859cffb661.png)

**Comment by gjmzj** [comment]
用2.0的话，公有云上安装跟自由机房安装一样的，看这个文档就够了
https://github.com/easzlab/kubeasz/blob/master/docs/setup/kubeasz_on_public_cloud.md
