### ISSUE TITLE
尝试验证calico路由反射器模式，在进行bgppeer配置时报错，位置为xxxSelector字段

### ISSUE THREAD

**Issue by Delacroix** [easzlab/kubeasz#614]
![图片](https://user-images.githubusercontent.com/1725134/60533002-2880d180-9d31-11e9-84aa-163e780e560a.png)
以上是报错信息，节点已增加labels：
![图片](https://user-images.githubusercontent.com/1725134/60533078-536b2580-9d31-11e9-9f97-7d87233295a3.png)

calico版本为v3.1.3
-------------
经过查询官方接口文档，该版本无相应字段，脚本是否可以支持升级新版calico？

**Comment by gjmzj** [comment]
如果你的集群calico是v3.1.3版本，那说明你的kubeasz代码已经很老了；不建议升级，当然如果你的集群可以用来折腾的话，可以把最新 kubeasz项目中 roles/calico目录整体替换老的；然后再一个node节点，删除原calico安装 `kubectl delete -f /opt/kube/kube-system/calico`; 然后在管理节点重新安装 `ansible-playbook /etc/ansible/06.network.yml`

**Comment by Delacroix** [comment]
好的 我这边重新搭建了基于release2.0的环境，遇到了新的问题，此问题关闭；
感谢解答。
