### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by jiangzhikele** [easzlab/kubeasz#616]
k8s默认的服务都是UTC时区，阿里云是CST时区，这个有影响吗？比如EFK日志，服务间通信，我想要部署skywalking，会有延迟。请问这和时间有关系吗？

**Comment by gjmzj** [comment]
k8s默认的服务？服务怎么会有时区一说，你说的服务打印的日志吗？
一般来说时区没关系，只是显示，只要时间能够同步就行，当然最后时区设置一样的
