### ISSUE TITLE
release 2.0版本 部署完成后dashboard证书有问题，导致无法打开页面

### ISSUE THREAD

**Issue by Delacroix** [easzlab/kubeasz#617]
查看iptables发现有状态异常
![图片](https://user-images.githubusercontent.com/1725134/60677530-5c383480-9eb4-11e9-8577-d93c1adad474.png)
查看其中一个calico node 发现 out of sync
![图片](https://user-images.githubusercontent.com/1725134/60677583-7e31b700-9eb4-11e9-97d4-4123b7aa7472.png)
重新执行了一次90.setup.yml  node1变成了not ready，calico的问题依旧
![图片](https://user-images.githubusercontent.com/1725134/60677682-c51fac80-9eb4-11e9-9c69-7eb48cd08ec0.png)
-------------
问题已解决，是主机名的问题，确保每台主机名不同就可以

**Comment by Delacroix** [comment]
以上服务器都在同一网段，操作系统为CentOS 7.5，是全新的操作系统环境

**Comment by Delacroix** [comment]
此外，dashboard 的URL通过浏览器打开也报401
![图片](https://user-images.githubusercontent.com/1725134/60677893-598a0f00-9eb5-11e9-8891-b4d86642c985.png)

**Comment by gjmzj** [comment]
浏览器访问dashboard，参考项目dashboard文档看看 
https://github.com/easzlab/kubeasz/blob/master/docs/guide/dashboard.md

**Comment by Delacroix** [comment]
感谢解答，目前已经解决，最后采用Ingress方式访问dashboard
