### ISSUE TITLE
efk中，建议去掉logstash

### ISSUE THREAD

**Issue by longdajiangjun** [easzlab/kubeasz#618]
建议使用filebeat进行收集，使用filebeat的好处是其轻量级。和logstash资源消耗比起来，,filebeat的使用量只有logstash的**1/20.**，filebeat可以将收集起来的数据传输给es进行存储和解析。
logstash太耗资源了，经常占满1G以上内存，近100m cpu。

**kube-system    elasticsearch-logging-0                                 39m          1848Mi          
kube-system    elasticsearch-logging-1                                 23m          1840Mi**          
kube-system    fluentd-es-v2.4.0-6h7k4                                 52m          121Mi           
kube-system    fluentd-es-v2.4.0-74zx9                                 5m           147Mi           
kube-system    fluentd-es-v2.4.0-dg4d6                                 3m           84Mi            
kube-system    fluentd-es-v2.4.0-l2wml                                 8m           121Mi           
kube-system    fluentd-es-v2.4.0-v584s                                 4m           84Mi

**Comment by gjmzj** [comment]
这个你是不是看错了，efk中本来就没有logstash；日志搜集使用的是  fluentd；
你上面两个内存1G以上是 elasticsearch pod；

**Comment by gjmzj** [comment]
https://github.com/easzlab/kubeasz/blob/master/docs/guide/efk.md
项目首页有个efk插件的简单介绍，参考下看看

**Comment by longdajiangjun** [comment]
谢谢大神，是我看错了。
