### ISSUE TITLE
2.0.1安装报/etc/kubernetes/kubelet.kubeconfig does not exist

### ISSUE THREAD

**Issue by diandiankou** [easzlab/kubeasz#620]
![image](https://user-images.githubusercontent.com/35486223/60709560-53db0a80-9f43-11e9-8642-6eed3f4a4b12.png)

通过2.0.1安装时，报如下错误，从node节点上来看 ，执行此步骤时还没有kubelet.kubeconfig文件，master节点上有，所以90.setup.yml只成功安装了master节点。
通过把master上的kubelet.kubeconfig scp到node上 ，再用easzctl add-node可以添加成功

**Comment by gjmzj** [comment]
能否把你的操作过程说明下，如果反馈bug，最好能描述故障重现过程；
是不是进行了集群master节点增加或者减少操作？

**Comment by diandiankou** [comment]
干净的环境，第一次安装

**Comment by diandiankou** [comment]
无法重现
