### ISSUE TITLE
harbor修改安装目录

### ISSUE THREAD

**Issue by jiangzhikele** [easzlab/kubeasz#622]
修改了/etc/ansible/roles/harbor/tasks/main.yml中的data目录。但是还有其他的database和registry在/data目录下。应该在什么地方统一修改目录

**Comment by gjmzj** [comment]
可以修改所有 /etc/ansible/roles/harbor/tasks/main.yml 出现的 /data 相关代码；后续考虑把这个作为变量，方便自定义
