### ISSUE TITLE
按照文档创建了nfs server，但创建动态PV失败

### ISSUE THREAD

**Issue by dazsco** [easzlab/kubeasz#624]
兄弟你好，才开始上手k8s，很多不太熟悉，现在卡在nfs上，这是啥原因导致的，请求帮助。

执行 ansible-playbook /etc/ansible/roles/cluster-storage/cluster-storage.yml ，并没有创建provisioner，返回如下：

[WARNING]: Could not match supplied host pattern, ignoring: deploy

PLAY [deploy] **********************************************************************************
skipping: no hosts matched

PLAY RECAP *************************************************************************************

nfs已启动
# showmount -e 10.10.10.84
Export list for 10.10.10.84:
/data/nfs *

roles/cluster-storage/defaults/main.yml的配置如下

# 动态存储类型, 目前支持自建nfs和aliyun_nas
storage:
  # nfs server 参数
  nfs:
    enabled: "yes"
    server: "10.10.10.84"
    server_path: "/data/nfs"
    storage_class: "class-nfs-01"
    provisioner_name: "nfs-provisioner-01"

  # aliyun_nas 参数
  aliyun_nas:
    enabled: "no"
    server: "xxxxxxxxxxx.cn-hangzhou.nas.aliyuncs.com"
    server_path: "/"
    storage_class: "class-aliyun-nas-01"
    controller_name: "aliyun-nas-controller-01"

**Comment by sanger89** [comment]
你的hosts文件中匹配不到相应的主机信息

**Comment by dazsco** [comment]
@sanger89  谢谢兄弟，是需要把nfs服务器加入到node节点吗？还是需要什么配置，hosts文件里面没有单独nfs配置信息。

**Comment by sanger89** [comment]
## 在hosts文件中加入 
```
[deploy]
XXX.XXX.XXX.XXX  #你的nfs机器的IP
```

**Comment by dazsco** [comment]
@sanger89 nfs服务器是要加入集群吗？

fatal: [10.10.10.84]: FAILED! => {"changed": true, "cmd": "/opt/kube/bin/kubectl apply -f /etc/ansible/manifests/storage/nfs/nfs-provisioner-01.yaml", "delta": "0:00:00.007502", "end": "2019-07-09 15:30:45.864310", "msg": "non-zero return code", "rc": 127, "start": "2019-07-09 15:30:45.856808", "stderr": "/bin/sh: /opt/kube/bin/kubectl: No such file or directory", "stderr_lines": ["/bin/sh: /opt/kube/bin/kubectl: No such file or directory"], "stdout": "", "stdout_lines": []}

**Comment by weifan01** [comment]
@dazsco  nfs不需要加入集群，provisioner是在集群里面的，他会去连nfs，你是在nfs节点上执行的kubectl吗？那样的话当然没有kubectl命令了
建议你先仔细看一遍文档，也了解下存储类

**Comment by dazsco** [comment]
@weifan01  我是按照 https://github.com/gjmzj/kubeasz/blob/master/docs/setup/08-cluster-storage.md 处理了，刚解决，不好意思兄弟。

**Comment by gjmzj** [comment]
@dazsco 抱歉这是一个bug，之前kubeasz 1.x版本有deploy角色，现在 2.x版本取消了 deploy 角色，所以运行不了，最新的master分支已经解决这个问题，详情可以参考这个 e7d2c0bb1cbb8c0119fe340b6b3ab49857e51d5b

**Comment by dazsco** [comment]
@gjmzj 解决了，如果ansible部署单独使用一台服务器，那么部署脚本路径有问题，至少centos是这样的，建立一个链接 ln -s /etc/ansible/bin/kubectl /opt/kube/bin/kubectl  。谢谢兄弟回复
