### ISSUE TITLE
kibana连不上es，es报错

### ISSUE THREAD

**Issue by sanger89** [easzlab/kubeasz#625]
![image](https://user-images.githubusercontent.com/35362585/60867380-441e3780-a25d-11e9-8b20-f7317c56dc9c.png)

![image](https://user-images.githubusercontent.com/35362585/60867159-c78b5900-a25c-11e9-89c0-1ca0e0b68aa1.png)

**Comment by gjmzj** [comment]
es报错信息不是写了：`not enough master nodes...` ，需要2个es master node，你是不是自己改了master副本数目

**Comment by sanger89** [comment]
> es报错信息不是写了：`not enough master nodes...` ，需要2个es master node，你是不是自己改了master副本数目

我确实改了，不过2个的时候也是连不上，这个实验我后面再做做，到时再反馈哦 3Q
