### ISSUE TITLE
为啥取消Node节点kubelet  TLS Bootstrapping Token认证

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#627]
现在kubeasz是取消了kubelet 通过TLS bootstrapping连接apiserver么？看ansible playbook中好像没有这些内容了？

**Comment by Hello-Linux** [comment]
我记得最原始kubeasz采用了Bootstrap Tokens，但是后来为啥取消了？那么现在节点的kubelet动态签署证书流程怎么走的

**Comment by Hello-Linux** [comment]
![000](https://user-images.githubusercontent.com/17851645/61020534-b9f6e000-a3d0-11e9-9a6d-5dbb46729647.png)

**Comment by Hello-Linux** [comment]
你这里少了node节点的kubelet从apiserver动态签署证书，那后期节点多了kubelet的动态签署证书岂不是很麻烦了？
![000](https://user-images.githubusercontent.com/17851645/61020808-85375880-a3d1-11e9-852b-a9a778f5bd16.png)

**Comment by gjmzj** [comment]
node用的kubelet证书使用 ansible 自动创建很方便，且可以自定义证书有效期，即便过期了，也是一条命令重新创建 `ansible-playbook 05.kube-node.yml`

**Comment by gjmzj** [comment]
目前项目默认CA及其他证书有效期：`roles/deploy/defaults/main.yml`
``` bash
# CA 证书相关参数
CA_EXPIRY: "876000h"       -CA 证书有效期
CERT_EXPIRY: "438000h"    -其他证书有效期
```

**Comment by Hello-Linux** [comment]
@gjmzj  恩恩那样也不错
