### ISSUE TITLE
现在kubeasz支持阿里云环境了么？

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#629]
现在kubeasz2.0支持阿里云环境了么？如果支持是如何支持的？

**Comment by gjmzj** [comment]
https://github.com/easzlab/kubeasz/blob/master/docs/setup/kubeasz_on_public_cloud.md

**Comment by Hello-Linux** [comment]
@gjmzj  我之前记得阿里云是不支持VIP模式的，kubeasz现在是怎么走的？使用阿里云自己的SLB？

**Comment by gjmzj** [comment]
单纯高可用集群不需要vip，文档里面都写了，高可用架构修改了

**Comment by Hello-Linux** [comment]
@gjmzj 多master高可用现在k8s自己支持了？

**Comment by gjmzj** [comment]
kubeasz 2.x 架构修改了，集群内部高可用由node节点上的haproxy负载实现
