### ISSUE TITLE
提高某些pod的qos级别

### ISSUE THREAD

**Issue by gj19910723** [easzlab/kubeasz#630]
calico只做了cpu limit，qos为burstable，如果集群中没有besteffort的pod，一旦达到evcition policy设置的条件，可能某些关键的pod，calico或coredns被驱逐然后重建。
某些极端情况下是否可能导致被频繁驱逐？
建议把重要的pod的qos直接设置成guaranteed

**Comment by gjmzj** [comment]
后续抽时间修改，或者您有空帮忙完善下提PR :)
