### ISSUE TITLE
关于从HA1.x升级至HA2.x的疑问

### ISSUE THREAD

**Issue by gj19910723** [easzlab/kubeasz#632]
看了下release note ,HA2.x不支持1.x
但是看了下2.x架构的haproxy使用了不同端口
1, 不升级版本的话，让node先进行架构升级，然后先处理master上haproxy处于backup的master，再升级最后一个master
2, 先处理master，让master上的haproxy同时bind两个端口,支持1.x的那种方式，再升级node的架构

这两个方案是否可行？

**Comment by gjmzj** [comment]
不建议从 1.x 升级到 2.x；
如果原先使用1.x，本身也是很稳定的；
新集群可以使用2.x；2.x其实最大好处还是安装兼容性好，可以在公有云上方便安装
