### ISSUE TITLE
求efk告警插件

### ISSUE THREAD

**Issue by longdajiangjun** [easzlab/kubeasz#633]
群主好，prometheus只能对站点和内存等硬件信息告警；我希望所有的错误能告警到钉钉，求好用的告警插件和教程。

**Comment by gjmzj** [comment]
prometheus的告警规则可以去这个项目学习：https://github.com/coreos/kube-prometheus
项目文档带了一个告警到钉钉的小插件和使用说明 https://github.com/easzlab/kubeasz/blob/master/docs/guide/prometheus.md#%E5%8F%AF%E9%80%89-%E9%85%8D%E7%BD%AE%E9%92%89%E9%92%89%E5%91%8A%E8%AD%A6
