### ISSUE TITLE
kubeasz 1.x 是否能继续支持新版kubernetes?

### ISSUE THREAD

**Issue by farmerluo** [easzlab/kubeasz#636]
kubeasz 1.x 是否能继续支持新版kubernetes? 比如最新的1.15，不知道kubeasz 1.x 后续是暂时开发还是会继续维护？

**Comment by gjmzj** [comment]
kubeasz 1.x 会继续维护，可能个人精力有限不会在1.x加入很多新特性，但是一定会继续支持新版k8s

**Comment by farmerluo** [comment]
> 
> 
> kubeasz 1.x 会继续维护，可能个人精力有限不会在1.x加入很多新特性，但是一定会继续支持新版k8s

那就放心了，感谢！
