### ISSUE TITLE
master节点重启后服务起不来

### ISSUE THREAD

**Issue by jiangzhikele** [easzlab/kubeasz#637]
阿里云部署，两个master，在阿里云做了负载机制。测试关闭一台master服务器，重启后，k8s服务组件需要手动启动，所有组件出现异常
![image](https://user-images.githubusercontent.com/38905258/61386573-1b461400-a8e7-11e9-8e8a-95299d47d6cd.png)
![image](https://user-images.githubusercontent.com/38905258/61386604-24cf7c00-a8e7-11e9-87d5-3e7d8c950730.png)
![image](https://user-images.githubusercontent.com/38905258/61386712-58aaa180-a8e7-11e9-925f-b7745c045844.png)
![image](https://user-images.githubusercontent.com/38905258/61387013-de2e5180-a8e7-11e9-85be-8262d5977961.png)
![image](https://user-images.githubusercontent.com/38905258/61387164-2fd6dc00-a8e8-11e9-8fbd-8da8acdf6588.png)
这是什么原因啊？？谢谢了

**Comment by gjmzj** [comment]
安装使用的基础信息：
kubeasz 哪个版本
k8s 什么版本
etcd 版本
...

**Comment by jiangzhikele** [comment]
用的2.0的版本，k8s是1.14的。
