### ISSUE TITLE
下载地址不存在

### ISSUE THREAD

**Issue by qq971876229** [easzlab/kubeasz#639]
curl -C- -fLO --retry 3 https://github.com/easzlab/kubeasz/releases/download/${release}/easzup

执行不了，这个地址目录上面不存在

**Comment by baosong818** [comment]
${release}是变量
https://github.com/easzlab/kubeasz/releases这里具体查找版本

**Comment by qq971876229** [comment]
好的，谢谢

**Comment by qq971876229** [comment]
> ${release}是变量
> 这里具体查找版本
> https://github.com/easzlab/kubeasz/releases

好的，谢谢
