### ISSUE TITLE
master节点故障引起的相关问题。比如删除master和etcd

### ISSUE THREAD

**Issue by sodwell** [easzlab/kubeasz#642]
情况：
1、线上有3个master，分别装了3个etcd
2、其中一个master出现了故障，无法恢复。
3、执行easzctl del-mater (故障master ip)提示fail，执行easzctl add-master(故障master ip)提示已经添加过了。
解决方法：
故障master关机不再使用，然后执行kubectl del node 故障master ip.
新问题：
执行kubectl get componentstatus，一直显示故障master的etcd是unhealth,也提示连接补上。
执行kubectl del etcd 故障master ip 提示fail。

**Comment by kubeasz** [comment]
请先执行 easzctl add-etcd 新地址；执行成功后可以执行 easzctl del-etcd 旧地址

**Comment by sodwell** [comment]
![image](https://user-images.githubusercontent.com/10768679/61606939-2ac6b380-ac7f-11e9-9d85-d1ec62b6aef0.png)
10.60.8.90是新加进来的etcd，成功不了，如上图。
另外执行kubectl del node (故障master ip) 还有2个问题：
1、在deploy部署机上执行kubectl get nodes 还是会提示故障master无法连接。
2、如果故障master的机器确实无法恢复了，我踢掉他，然后把这个IP地址分配给新申请的服务器，我要把这台机器加进来也是无法成功的，提示这个IP已经加进来了，估计是根据hosts文件来确定的吧，因为host文件的故障IP还在，另外这个host文件还存在故障IP的话，机器灾备，恢复可能也会有问题。

**Comment by sodwell** [comment]
上面红框中，10.8.60.90是新加的master，我准备把它增加etcd的角色，10.8.60.87是故障master。

**Comment by sodwell** [comment]
我个人觉得删除和安装不是一回事，如果安装组件或者添加节点的时候出现问题，应该提示失败，无法继续，当然也可以跳过先安装其他组件。
如果机器和网络一点问题都没有，当然是可以删除的，事实上一般都是出问题才想去删除，如果这台机器删除不了，自然也添加不了。可不可以不管能不能把故障机器的组件都正常删除都提示删除机器成功，机器故障交由运维来解决，能确保新加进来的机器的网络和系统是完好的情况下，都能添加成功即可，比如添加新的node，master（依然使用之前的故障IP），etcd组件等。

**Comment by sodwell** [comment]
故障master无法删除，但是可以增加新的master可以勉强解决问题，至少集群可以正常工作，但是etcd如果无法增加到新增加的master上，这个问题感觉是蛮严重的，比如陆续又挂了个master，以及它上面的etcd挂了......

**Comment by gjmzj** [comment]
我理解你的问题，之前删除节点master/etcd等考虑的情景有遗漏，删除脚本需要再修改下；
1.先手动解决你的问题吧，打开/etc/ansible/hosts 找到 [etcd]组，把你故障的etcd节点移动到[etcd]组最末行；然后再执行新增etcd节点；最后再执行删除etcd节点吧

**Comment by gjmzj** [comment]
@sodwell 关于etcd操作，如果有时间可以读一下官方github文档https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md；
如果有ansible基础可以简单看下 tools/01.addetcd.yml和tools/11.deletcd.yml 中的脚本，现在看来要自动执行你的场景还需要修改，不过可以借鉴看下，手动操作

**Comment by sodwell** [comment]
![image](https://user-images.githubusercontent.com/10768679/61612909-6fa81580-ac92-11e9-9ad0-d7cae118eb87.png)
![image](https://user-images.githubusercontent.com/10768679/61612929-7cc50480-ac92-11e9-8b11-191fb6249e80.png)
谢谢楼上，10.8.60.87是故障master（etcd）节点，手动移动到最后面了，但是还是添加不了，我的方法是否正确，另外可以增加ignore_errors: true后，可以先del etcd再add etcd吗？

**Comment by gjmzj** [comment]
你操作没问题，现在是因为etcd集群不健康所以添加新节点不成功；那么只能增加ignore_errors: true后，先del etcd 坏节点试试

**Comment by sodwell** [comment]
按照您的方法，增加;ignore_errors: true我调整了下顺序，先del etcd，提示成功：
![image](https://user-images.githubusercontent.com/10768679/61613671-894a5c80-ac94-11e9-8905-218bdd701c94.png)
然后add etcd，虽然提示fail：
![image](https://user-images.githubusercontent.com/10768679/61613716-a2530d80-ac94-11e9-93c6-f0ec8cea02a4.png)
但是我看host文件：
![image](https://user-images.githubusercontent.com/10768679/61613731-b139c000-ac94-11e9-94ac-790fb8c8be75.png)
以及
![image](https://user-images.githubusercontent.com/10768679/61613782-cb739e00-ac94-11e9-943a-f532ae7722f6.png)
可以看到add etcd是成功了，在结合上面临时解决master的问题，算是临时解决了这个机器故障的问题，但是这个故障引起的隐患点还是蛮多的，个人能力有限，没法贡献帮忙，还望群主能出个新版本，谢谢！

**Comment by gjmzj** [comment]
好的，这块处理逻辑我是清楚的，就是要转化为ansible的自动脚本还有问题；会继续迭代优化这部分内容。

**Comment by cdx7779** [comment]
TASK [delete a etcd member] ***************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "ETCDCTL_API=3 /opt/kube/bin/etcdctl member remove 79832b2ead2a80fb", "delta": "0:00:05.039170", "end": "2021-09-14 23:09:25.462824", "msg": "non-zero return code", "rc": 1, "start": "2021-09-14 23:09:20.423654", "stderr": "{\"level\":\"warn\",\"ts\":\"2021-09-14T23:09:25.461-0700\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-6af4f652-c5a0-4524-a81c-7497220081da/127.0.0.1:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}\nError: context deadline exceeded", "stderr_lines": ["{\"level\":\"warn\",\"ts\":\"2021-09-14T23:09:25.461-0700\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-6af4f652-c5a0-4524-a81c-7497220081da/127.0.0.1:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}", "Error: context deadline exceeded"], "stdout": "", "stdout_lines": []}

**Comment by cdx7779** [comment]
在 原有 etcd节点  ，对其进行 删除， 也报错啦   再添加也不行

**Comment by cdx7779** [comment]
> 好的，这块处理逻辑我是清楚的，就是要转化为ansible的自动脚本还有问题；会继续迭代优化这部分内容。

大哥  你版本修复了吗

**Comment by cdx7779** [comment]
> 好的，这块处理逻辑我是清楚的，就是要转化为ansible的自动脚本还有问题；会继续迭代优化这部分内容。

大哥 这个版本有修复吗 ，我用的GitVersion:"v1.20.2"   ，这个版本也不行啊

**Comment by cdx7779** [comment]
![Uploading image.png…]() 11
