### ISSUE TITLE
如何访问通过quickstart部署的k8s开发测试环境的dashboard

### ISSUE THREAD

**Issue by AlliotTech** [easzlab/kubeasz#643]
https://github.com/easzlab/kubeasz/blob/master/docs/setup/quickStart.md 这里的dashboard是通过什么访问的呢？
如图应该是部署成功了的：
![image](https://user-images.githubusercontent.com/24980252/61620039-9c642900-aca2-11e9-9106-72ebc33e475b.png)
IP:80   IP:443都无法访问 
![image](https://user-images.githubusercontent.com/24980252/61621188-0087ec80-aca5-11e9-94b6-5de068f0aa73.png)

**Comment by gjmzj** [comment]
项目首页有文档 
![图片](https://user-images.githubusercontent.com/33503702/61678320-16dd8900-ad35-11e9-9b76-c9d6cbad39da.png)

**Comment by gjmzj** [comment]
按你环境应该是 https://IP:20768

**Comment by AlliotTech** [comment]
感谢回复

**Comment by oneslideicywater** [comment]
用谷歌浏览器访问不了的话，[解决Google浏览器不能打开kubernetes dashboard方法](https://www.jianshu.com/p/8021285cc37d)。
