### ISSUE TITLE
ALL IN ONE 部署如何增加节点

### ISSUE THREAD

**Issue by 0x87e5** [easzlab/kubeasz#645]
我看到部署文档上可以将ALL IN ONE 增加节点，通过easzctl工具，但是我没有找到如何初始化easzctl相关介绍？

**Comment by gjmzj** [comment]
增加工作节点 `easzctl add-node 1.1.1.1`
增加主节点`easzctl add-master 1.1.1.1`
增加etcd节点`easzctl add-etcd 1.1.1.1`

**Comment by 0x87e5** [comment]
直接执行似乎不行：
./easzctl add-node 192.168.1.194
[INFO] Action: add a k8s work node : add-node 192.168.1.194
sed: can't read /etc/ansible/hosts: No such file or directory
sed: can't read /etc/ansible/hosts: No such file or directory
./easzctl: line 85: ansible-playbook: command not found
sed: can't read /etc/ansible/hosts: No such file or directory
[ERROR] Action failed : add-node 192.168.1.194

请问这个hosts该如何配置呢？

**Comment by gjmzj** [comment]
allinone基础上增加节点，言外之意是需要先装好allinone啊，`easzctl start-aio`

**Comment by 0x87e5** [comment]
是的，我的意思是我已经按照ALL-IN-ONE的文档部署了一个单机集群，然后我想增加节点，这一步骤的文档我觉得可以稍微明确点

最后我卸载了单机环境，按照多机部署文档完成了我的部署，谢谢
