### ISSUE TITLE
flannel vxlan是否需要增加directrouting的支持？

### ISSUE THREAD

**Issue by weilinqwe** [easzlab/kubeasz#652]
默认vxlan采用隧道技术，支持跨网段，当同网段时效率偏低。 vxlan支持directrouting选项，当节点处于同网段时，通过硬件网卡路由直接转发。
```
"Backend": {
        "Type": "vxlan",
        "Directrouting": true
      }
```
/etc/ansible/roles/flannel/templates/kube-flannel.yaml.j2   

为了脚本适配性，只有backend是vxlan时才选用directrouting选项

@gjmzj

**Comment by gjmzj** [comment]
刚又读了下文档 https://github.com/coreos/flannel/blob/master/Documentation/backends.md；
我觉得可以添加下这个选项，明显公有云上不适用，所以默认关闭；有需要者手动打开即可；
68dd18a03c5cb3380b690175cb2cf128c5e86c43

**Comment by weilinqwe** [comment]
好的。
