### ISSUE TITLE
kubernetes-dashboard无法访问

### ISSUE THREAD

**Issue by GuoCeng** [easzlab/kubeasz#654]
浏览器报错：
192.168.27.130 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 192.168.27.130 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 192.168.27.130，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 192.168.27.130，因为此网站发送了 Google Chrome 无法处理的杂乱凭据。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by gjmzj** [comment]
1.目前可以使用firefox访问
2.按照文档可以配置ingress访问dashboard
3.我试试在安装dashboard时配置自定义ssl证书

**Comment by GuoCeng** [comment]
> 1.目前可以使用firefox访问
> 2.按照文档可以配置ingress访问dashboard
> 3.我试试在安装dashboard时配置自定义ssl证书

好的，谢谢

**Comment by hejiazhen1203** [comment]
按照文档配置了ingress，发现访问http://dashboard.test.com:23456/却是404啊

**Comment by seacnboy** [comment]
2.0.2安装出来chrome访问也是这个问题，但是all in one简易部署出来没有问题，奇怪了

**Comment by batizhao** [comment]
我用这个解决了：https://stackoverflow.com/questions/26388405/chrome-disable-ssl-checking-for-sites

**Comment by xiaoping378** [comment]
尝试下黑魔法，直接在页面盲敲：thisisunsafe
