### ISSUE TITLE
使用AllinOne,显示UNREACHABLE!   可以无密码SSH到本机

### ISSUE THREAD

**Issue by gig05281215** [easzlab/kubeasz#656]
按照安装步骤进行安装，可以从本机无密码ssh 登录到本机，但显示如下错误
![捕获1](https://user-images.githubusercontent.com/1436059/62296763-5f6a1480-b4a2-11e9-813a-19fbdec37dc9.JPG)

下图为ssh 到本机
![捕获2](https://user-images.githubusercontent.com/1436059/62296813-76a90200-b4a2-11e9-94c6-c6e5b48edad9.JPG)

**Comment by gig05281215** [comment]
将/etc/ansible/ansible.cfg 中scp_if_ssh = True进行设置后，仍然报连接不上的错误

**Comment by gig05281215** [comment]
使用ansible测试正确

![捕获3](https://user-images.githubusercontent.com/1436059/62341645-b01b5500-b516-11e9-97cf-945951b95dbc.JPG)

**Comment by gjmzj** [comment]
这个问题看看能不能在ansible项目那边找找，有没有相似的问题。。。

**Comment by gig05281215** [comment]
使用ubuntu 16.04 server 重新安装后，安装成功

**Comment by gjmzj** [comment]
嗯，遇到奇怪的问题有时候可以先避开下，等有能力的时候再去研究，记着有这个坑

**Comment by myndtt** [comment]
现在也遇到这个问题了，之前安装还没有。
