### ISSUE TITLE
calico 和 coredns 异常问题

### ISSUE THREAD

**Issue by TonyBian** [easzlab/kubeasz#657]
kubeasz 版本：1.0.0
kubernetes 版本：v1.13.2
calico版本：v3.4.3
coredns 版本：1.4.0

### 问题和现象：
**1. calico异常问题** 
使用 easzctl add-node 新增节点，等待新的节点 calico 启动之后，新节点上的pod ping不通 coredns pod ip，重启新节点上的 docker 服务后恢复。

从 calico 的配置文件/etc/calico/confd/config/bird.cfg中看到新节点的配置相比其他节点多了一行：
passive on; # Mesh is unidirectional, peer will connect to us.

以下是过滤掉 INFO 后的 calico 日志：
Threshold time for bird readiness check:  30s
2019-08-04 10:08:41.373 [ERROR][8] startup.go 152: Unable to set NetworkUnavailable to False error=nodes "ali-sh-g-pre-k8s-node-02" not found
Threshold time for bird readiness check:  30s
Calico node started successfully
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
bird: Unable to open configuration file /etc/calico/confd/config/bird6.cfg: No such file or directory
Threshold time for bird readiness check:  30s
Threshold time for bird readiness check:  30s
2019-08-04 10:08:42.644 [WARNING][42] ipip_mgr.go 110: Failed to add IPIP tunnel device error=exit status 1
2019-08-04 10:08:42.644 [WARNING][42] ipip_mgr.go 87: Failed configure IPIP tunnel device, retrying... error=exit status 1

**2. coredns 日志中一直存在大量的 error，但不影响使用：**
 [ERROR] plugin/errors: 2 checkpoint-api.weave.works. AAAA: unreachable backend: read udp 172.20.131.180:41516->100.100.2.136:53: i/o timeout
 [ERROR] plugin/errors: 2 200.75.136.117.in-addr.arpa. PTR: unreachable backend: read udp 172.20.131.180:37729->100.100.2.136:53: i/o timeout
 [ERROR] plugin/errors: 2 224.171.49.112.in-addr.arpa. PTR: unreachable backend: read udp 172.20.131.180:49552->100.100.2.136:53: i/o timeout

**Comment by TonyBian** [comment]
第一个问题中的 calico 配置文件内容和日志中的报错，在 kubeasz 2.0.2版本中也有类似的现象，但不需要重启docker

**Comment by gjmzj** [comment]
待重现确认

**Comment by TonyBian** [comment]
每次 add-node 的时候，在准备 calicoctl 配置文件步骤都会超时，但最终 calico-node 可以启动，不知道是否有关系：

TASK [calico : 准备 calicoctl配置文件] *************************************************************************************************************************************************
changed: [172.19.158.34]
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (15 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (14 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (13 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (12 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (11 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (10 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (9 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (8 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (7 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (6 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (5 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (4 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (3 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待calico-node 运行，视下载镜像速度而定 (1 retries left).

TASK [calico : 轮询等待calico-node 运行，视下载镜像速度而定] *************************************************************************************************************************************
fatal: [172.19.158.34 -> 192.168.129.220]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/opt/kube/bin/kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' 172.19.158.34 '|awk '{print $3}'", "delta": "0:00:00.223477", "end": "2019-08-08 10:28:31.507097", "rc": 0, "start": "2019-08-08 10:28:31.283620", "stderr": "", "stderr_lines": [], "stdout": "PodInitializing", "stdout_lines": ["PodInitializing"]}
...ignoring

PLAY RECAP ***********************************************************************************************************************************************************************
172.19.158.34              : ok=76   changed=63   unreachable=0    failed=0

[WARN] Invalid Context
[INFO] Action successed : add-node 172.19.158.34
