### ISSUE TITLE
python-pip 安装失败

### ISSUE THREAD

**Issue by wyuxiao729** [easzlab/kubeasz#659]
00-集群规划和基础参数设定  Centos7 安装 python-pip 失败。需要先安装 epel-release 才行。

yum -y install epel-release

我记得以前的文档中好像有这个命令，后面的取消了哇？

**Comment by gjmzj** [comment]
因为这个命令在prepare阶段安装太费时间了，如果在准备时候安装python-pip需要，那就手动安装下吧
