### ISSUE TITLE
使用新版本的dashboard

### ISSUE THREAD

**Issue by oubeichen** [easzlab/kubeasz#660]
你好，我看到官方终于更新了 dashboard 的版本，目前最新的是 2.0.0 的 beta 版。
https://github.com/kubernetes/dashboard/releases
但是因为改了 namespace 所以光修改原来 `manifests/dashboard/kubernetes-dashboard.yaml` 的版本号会报错。
目前只能用官方提供的办法，
https://github.com/kubernetes/dashboard#getting-started
但是这样就要下载 config 文件并且在本地运行 `kubectl proxy`，而无法直接通过 VIP 节点的 8443 端口访问，比较繁琐。

不知道是否有更新的计划，谢谢！

**Comment by oubeichen** [comment]
另外就是更新集群或者kubeasz之后，好像 deploy、 master 和 node 机器上的 easzctl、easzup、kubectl 等常用工具 binary 都没有更新。也没有看到文档里有对应的内容。
虽说自己手动替换文件也不是很麻烦，但是如果有简单的方案就更好了，谢谢。

**Comment by oubeichen** [comment]
好吧我又发现如果用官方推荐方案装了之后
> kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta3/aio/deploy/recommended.yaml
只需要在原来 url 换个 namespace 就能访问
> https://{master_ip}:8443/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/
囧

**Comment by gjmzj** [comment]
准备在dashboard2.0.0正式版的时候更新

**Comment by autherlj** [comment]
这个版本是不是界面的CPU 和MEM的显示就不依赖于heapter了

**Comment by gjmzj** [comment]
是的
