### ISSUE TITLE
关于 kube-proxy  添加 --cluster-cidr 参数的咨询

### ISSUE THREAD

**Issue by AEGQ** [easzlab/kubeasz#663]
**背景:**

> 1、在验证[Kubernetes Service IP Route Advertisement](https://www.projectcalico.org/kubernetes-service-ip-route-advertisement/)功能时，发现 kube-proxy 在添加 --cluster-cidr 参数后，集群外部节点(安装了bird同步集群reflector路由) 才可以通过service IP 访问服务。

> 2、本地多网卡集群（iptables模式）
主机访问 10.68.0.1 443 端口，时而不通，配置  --cluster-cidr 后正常 （参考了 ：[Kubernetes集群node无法访问service：kube-proxy没有正确设置cluster-cidr](https://www.lijiaocn.com/%E9%97%AE%E9%A2%98/2019/02/28/kubernetes-node-cannot-access-service.html)）
 

**文档查找:**

> 我在[3.0]( https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/#requirements )版本calico文档中找到 _--masquerade-all_ 冲突相关提示(没找到 --cluster-cidr )，而3.1及后续版本没有冲突提示。

**咨询：**

> 看到 部署文档中 有 "bugfix: NetworkPolicy 跨节点失效问题" : https://github.com/easzlab/kubeasz/commit/ec4a07f8ba33e317fe5cd89bb7345a7119d7694b

> 请问 NetworkPolicy 跨节点失效问题 在3.1及后续版本中是否还会因为 --cluster-cidr 参数导致异常【或者异常的简单描述，我本地装了新版本calico，测试一下】

**Comment by gjmzj** [comment]
可能calico3.1版本以后不会造成冲突了，那确实可以把 --cluster-cidr  参数添加起来，我去参考下kubeadm的kube-proxy安装参数，然后再来决定是否恢复添加这个参数

**Comment by gjmzj** [comment]
刚参考了下kubeadm创建集群的相关参数，建议添加以下参数：
```
--cluster-cidr={{ CLUSTER_CIDR }}
--masquerade-all=false
```

**Comment by AEGQ** [comment]
好的，感谢指导 :)
