### ISSUE TITLE
使用2.0.3版本后，在dashboard中看不到CPU、MEM

### ISSUE THREAD

**Issue by linux998** [easzlab/kubeasz#666]
使用2.0.3版本后，在dashboard中看不到CPU、MEM
目前环境如下：  master   1台  192.168.199.231       node 1台  192.168.199.232
centos7.6.1810   两台都是，其它配置根据  2.0.3要求来配置。

已经通过 kubectl apply -f /etc/ansible/manifests/heapster/  部署了heapster。

首先删除 kubectl scale deploy kubernetes-dashboard --replicas=0 -n kube-system
然后新建 kubectl scale deploy kubernetes-dashboard --replicas=1 -n kube-system
也使用过以上两条命令。  现在dashboard 是的容器组里， cpu,mem还是空白的。

heapster  pod  logs 报错内容如下。有多条这样的日志

E0814 13:19:05.010224       1 manager.go:101] Error in scraping containers from kubelet_summary:192.168.199.232:10255: Get http://192.168.199.232:10255/stats/summary/: dial tcp 192.168.199.232:10255: getsockopt: connection refused

kubectl get po,svc --all-namespaces
kube-system   pod/heapster-bcffb65bc-h8qvv         1/1     Running   1         152m
kube-system   pod/kubernetes-dashboard-7d56b85bb8-jgpr6      1/1     Running   1          26h

kube-system   service/heapster      ClusterIP   10.68.7.35      <none>        80/TCP      152m
kube-system   service/kubernetes-dashboard   NodePort   10.68.69.139    <none>        443:27645/TCP                 7d3h

请教

**Comment by gjmzj** [comment]
确实默认是有这个问题，因为根据最佳实践kubelet服务的只读端口10255是关闭的；
1.可以在roles/kube-node/templates/kubelet-config.yaml.j2文件中把 readOnlyPort: 0 改成 readOnlyPort: 10255，然后重新安装 04.kube-master.yml和05.kube-node.yml两步，这样heapseter就能读取数据了
2.等dashboard2.0正式版本发布，我会更新，到时候就可以完全废弃heapster，监控数据会从metrics-server读取，而metrics-server可以从kubelet安全端口读取监控数据

**Comment by linux998** [comment]
非常感谢百忙之中抽空回复。
