### ISSUE TITLE
helm server安装成功后执行无反应

### ISSUE THREAD

**Issue by mymmmumu** [easzlab/kubeasz#668]
部署了几次了，tiller的Pod安装成功后，helm version命令，只能显示client部分的信息，然后就卡住不动了，要想恢复正常，都需要重启主机
`[root@161 ~]# helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
`
请问有其他朋友碰到类似的情况么，如何解决的？

**Comment by coolloves** [comment]
今天刚搞helm,同样的问题

**Comment by coolloves** [comment]
取消tls后可以了

**Comment by mymmmumu** [comment]
> 取消tls后可以了

好的，我也试下,3x

**Comment by weilinqwe** [comment]
我也是，安装好之后helm version显示连不上server，然后用Helm version --debug发现没有tiller服务器地址，用了默认127.0.0.1:随机端口，当然连不上了。需要kubectl get svc -n kube-system获取tiller service的ip和端口配置给菜蔬HELM_HOST

@gjmzj 最好在helm安装文档里注明一下需要配置HELM_HOST

**Comment by weilinqwe** [comment]
好像不是这个问题，helm客户端会根据kubectl config连到K8s找tiller自动连上去。 后来我把HELM_HOST去掉也ok了。 当时连不上不知道什么问题。
