### ISSUE TITLE
阿里云单节点部署(aio)错误

### ISSUE THREAD

**Issue by xiaoxlm** [easzlab/kubeasz#669]
按照快速指南allinone执行到4.2步时，报错
![image](https://user-images.githubusercontent.com/39261724/63089361-33fb2580-bf8a-11e9-8691-5043ea10bbd6.png)

**Comment by gjmzj** [comment]
看提示是因为，机器已经安装了containerd作为运行时，当然不能再安装docker了

**Comment by xiaoxlm** [comment]
> 看提示是因为，机器已经安装了containerd作为运行时，当然不能再安装docker了

所以前提是宿主机上不能有docker。然后按照步骤来执行就可以了？

**Comment by gjmzj** [comment]
阿里云上用一个新建（干净）的ecs去装，肯定没问题

**Comment by anpu2018** [comment]
> 阿里云上用一个新建（干净）的ecs去装，肯定没问题

有个问题麻烦请教下呢，我用华为云的ecs按照您的文档顺利搭建好了环境，但是dashboard指向是的ecs的内网地址而非弹性公网ip，这就导致我的笔记本没办法通过公网ip访问到dashboard，这个请教下怎么解决呢，感谢您在百忙当中回复
