### ISSUE TITLE
两种负载均衡的取舍--ex-lb vs metallb

### ISSUE THREAD

**Issue by neo-feng** [easzlab/kubeasz#674]
最新版的kubeasz支持两种负载均衡 ex-lb和metallb，请问这两个应该怎么取舍？ 如何根据应用场景选择？

**Comment by gjmzj** [comment]
应用场景不太一样：
metallb主要是为了对齐公有云厂商的k8s版本提供的service类型：loadBalance方式；metallb一旦建立起来，那么集群内应用可以方便的使用它来暴露给外部；优点是方便，它是k8s自动实现的；缺点是稳定性差点，项目不是很成熟，可能会有bug；
ex-lb 是用keepalive+haproxy组合成的高可用负载均衡服务，它可以用来负载均衡nodePort类型的服务，或者为外部应用调用k8s apiserver提供负载均衡；优点是技术栈稳定（两个经历检验的老牌linux服务组合），缺点是需要手动去配置haproxy，需要一定使用经验

**Comment by neo-feng** [comment]
多谢回复。我回头先试试看用metallb暴露我的ingress controller
