### ISSUE TITLE
你的k8s RBAC授权中admin怎么没有资源配置文件？

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#675]
我看你的配置中只有read账户进行了角色绑定，但是你的admin账户没有进行角色绑定的相关yaml资源配置文件。你是怎么赋予admin的权限管理呢？
@gjmzj 
![000](https://user-images.githubusercontent.com/17851645/63572270-0aa74e80-c5b5-11e9-8edd-cc3f096a322c.png)

**Comment by weilinqwe** [comment]
文档中有说明的，admin用户证书中的group和 clusterrole cluster-admin有clusterrolebinding， cluster-admin具有cluster管理权限。

```
[root@cloudhost1 kubernetes]# kubectl describe  clusterrolebinding  cluster-admin --all-namespaces
Name:         cluster-admin
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
Role:
  Kind:  ClusterRole
  Name:  cluster-admin
Subjects:
  Kind   Name            Namespace
  ----   ----            ---------
  Group  system:masters  
```

**Comment by gjmzj** [comment]
楼上正解：）

**Comment by Hello-Linux** [comment]
原来如此

**Comment by hanzhaogang** [comment]
> kubectl describe  clusterrolebinding  cluster-admin --all-namespaces
为什么我执行这步的时候，会出错呢：
The connection to the server localhost:8080 was refused - did you specify the right host or port?
