### ISSUE TITLE
EFK日志看不到

### ISSUE THREAD

**Issue by wspd2004** [easzlab/kubeasz#676]
EFK安装在了kube-system这个namespace里面，进入kibana，在条件删选框里只能选到kube-system这个namespace里面的pod，看不到别的namespace，例如default里面的pod日志，请问是什么原因，排查思路在哪里

**Comment by gjmzj** [comment]
fluentd的rbac权限绑定是否有问题，你是按照哪个文档或者yaml配置进行部署的efk

**Comment by wspd2004** [comment]
已经搞定，是因为要先部署efk，再部署app，脑抽了一下，新部署的efk怎么能看到以前的日志呢

**Comment by weilinqwe** [comment]
fluentd配置
默认是tail container log文件
```
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
```
好像官方fluentd没有读文件input plugin的，你要想办法把文件搜集到elasticsearch才能看到，看看有没有第三方plugin或者用filebeat之类的
