### ISSUE TITLE
kubernetes集群停止，重启

### ISSUE THREAD

**Issue by binayabin** [easzlab/kubeasz#677]
在环境维护中少不了服务器的重启，在重启服务器前需要停止k8s集群，保护现场，等服务器断电恢复后，再重新启动k8s集群

**Comment by gjmzj** [comment]
其实你说的概念我理解，但是有没有发现几乎整个社区都不关心这个问题；
- 1.首先对于生产级集群来说，重启任何单一节点（master/etcd/node）等是不会影响应用可用性的，因为本质上k8s是个容器调度，它肯定会完成应用容器从故障节点迁移到正常节点
- 2.对于重启节点，比较好的做法是先执行 kubectl drain 操作，把该节点上的pod主动迁出去，然后再执行该节点重启或者升级操作
- 3.如果确实需要再短时间内重启集群所有节点，那么一般情况下可以直接执行，没什么现场需要保护的；当然如果集群上跑了有状态应用，比如数据库等，那么是该有应用开发人员考虑现场保护问题，一般不是集群层面要考虑的

**Comment by binayabin** [comment]
场景是这样的，我们园区最近施工，晚上10点会停电，我们公司没有备用电源，第二天重启服务器后k8s集群就会出故障，这几次处理都是重新安装，但是这样处理感觉不优雅。

**Comment by TimeBye** [comment]
断电后启动集群出现的是什么故障呢？报什么错呢？

**Comment by binayabin** [comment]
master 节点

**Comment by binayabin** [comment]
master节点：The connection to the server 192.168.0.46:6443 was refused - did you specify the right host or port?
