### ISSUE TITLE
请问 PR 到哪个分支？devX?

### ISSUE THREAD

**Issue by QwertyJack** [easzlab/kubeasz#680]
RT
[文档](https://github.com/easzlab/kubeasz.git)中描述的是使用dev分支提pr，然而目前主仓有
dev{0,1,2}
请问:
1. 这些devX都是干嘛用的？
1. 如果想提pr，那么pr到哪个分支？

谢谢

**Comment by gjmzj** [comment]
新版本都是pr到dev2：）

**Comment by QwertyJack** [comment]
谢谢
