### ISSUE TITLE
Not replacing invalid character(s) "{'-'}" in group name

### ISSUE THREAD

**Issue by pigzhuzhu55** [easzlab/kubeasz#681]
root@iqeq-virtual-machine:/etc/ansible# ansible all -m ping -vvvv
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Not replacing invalid character(s) "{'-'}" in group name (kube-master)
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change, but still 
be user configurable on deprecation. This feature will be removed in version 2.10. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
 [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

Not replacing invalid character(s) "{'-'}" in group name (kube-master)
Not replacing invalid character(s) "{'-'}" in group name (kube-node)
Not replacing invalid character(s) "{'-'}" in group name (kube-node)
Not replacing invalid character(s) "{'-'}" in group name (ex-lb)
Not replacing invalid character(s) "{'-'}" in group name (ex-lb)
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python3.6/dist-packages/ansible/plugins/callback/minimal.py
META: ran handlers

按quickStart 一步一步操作，然后这一步提示很诡异。。后面也出错了

**Comment by gjmzj** [comment]
这个只是一个warning，现阶段应该不受影响，后面出错，可以贴下具体错误提示。
- 后续我抽时间该下group命名，用‘_’替换‘-’
