### ISSUE TITLE
日志收集

### ISSUE THREAD

**Issue by wspd2004** [easzlab/kubeasz#683]
请问一下，我目前是把jar包打成docker image在k8s环境里面运行，那么我的日志文件就会在pod里面，通过怎样的配置能让efk收集到pod内部的日志，然后在kibana中展示呢，是不是首先要把我的日志文件挂在出来，然后该怎么做，或者怎么配置，能提供思路吗

**Comment by weilinqwe** [comment]
默认日志打印到console，efk就会自动搜集的。 日志打印到console，其实会写入var/log/lib/docker下面的docker日志文件，efk就是tail这些文件搜集到es的。如果一个应用要打印几分日志，估计就需要持久化出来，然后给fluentd写单独的搜集配置

**Comment by TonyBian** [comment]
阿里开源的 log-pilot 支持收集指定文件
