### ISSUE TITLE
尝试离线安装，进入kubeasz容器添加节点失败

### ISSUE THREAD

**Issue by cnkidong** [easzlab/kubeasz#684]
离线安装，进入kubeasz容器执行
easzctl add-node 10.170.128.162
但是由于容器无法连接到10.170.128.162导致安装失败
试了容器所在的节点可以连接到10.170.128.162，并设置了无密登录。

**Comment by gjmzj** [comment]
嗯，这个问题之前也偶尔出现，还没有定位到原因，你能不能把错误日志发一下。

**Comment by haiker2011** [comment]
离线安装，进入kubeasz容器执行
`easzctl add-node <ip>`
会出现如下错误，试了很多次都是失败

![image](https://user-images.githubusercontent.com/8073429/65007392-94d69e80-d938-11e9-82e3-883e3ceaed6d.png)

**Comment by weilinqwe** [comment]
用kubectl get node看看是不是10.61.2.162已经添加成功了？  你这个错只是kubectl get node 验证10.61.2.162是不是ready报的错。 和admin server 10.61.2.156:6443连不上，是不是deploy节点的kubectl config配置不对？

**Comment by haiker2011** [comment]
应该是kubectl config不对，我之前使用其他工具安装过，我以为使用这个工具会删掉`~/.kube/`里面东西，好像没有，我手动删除之后，重新部署了一遍就可以了。

**Comment by pkuzhangkai** [comment]
我碰到类似问题，参考这篇文章 https://blog.csdn.net/nklinsirui/article/details/81605389
具体做法如下：
sysctl -w net.ipv4.ip_forward=1
重启docker
目前我的问题已经解决，供你参考。
