### ISSUE TITLE
单节点部署2.0.3版无法登录dashboard

### ISSUE THREAD

**Issue by zhaiyuzhen** [easzlab/kubeasz#685]
根据文档：https://github.com/easzlab/kubeasz/blob/master/docs/setup/quickStart.md
部署2.0.3，部署成功后无法登录dashboard，错误提示如下：

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

**Comment by gjmzj** [comment]
可以看一下首页的dashboard文档。

**Comment by zhaiyuzhen** [comment]
我根据https://github.com/easzlab/kubeasz/blob/master/docs/guide/dashboard.md文档，将token及其内容追加到/root/.kube/config文件的末尾。

**Comment by jinwenming** [comment]
我也是一样，怎么解决的？

**Comment by weilinqwe** [comment]
群主的文档写得很清楚：dashboard有两步认证，第一步是apiserver认证，第二步是dashboard自身认证，后面说的token认证是第二层。你们是第一步认证失败，还没有见到第二步认证界面。第一步无论是nodeport还是用proxy，一种是basic，一种是浏览器嵌入证书。

**Comment by aclk** [comment]
@weilinqwe 记得最开始时`proxy`也是用`basic`认证的，现在怎么改成证书了？知道浏览器需要导入哪个证书吗？

**Comment by weilinqwe** [comment]
文档里不是说了，既可以basic，也可以证书。
basic：如需（用户名/密码）认证，kubeasz 1.0.0以后使用 easzctl basic-auth -s 开启
证书：[与之前1.6.3版本相同](https://github.com/easzlab/kubeasz/blob/master/docs/guide/dashboard.1.6.3.md)   
[3. 证书访问：最安全的方式，配置较复杂](https://github.com/easzlab/kubeasz/blob/master/docs/guide/dashboard.1.6.3.md#3-%E8%AF%81%E4%B9%A6%E8%AE%BF%E9%97%AE%E6%9C%80%E5%AE%89%E5%85%A8%E7%9A%84%E6%96%B9%E5%BC%8F%E9%85%8D%E7%BD%AE%E8%BE%83%E5%A4%8D%E6%9D%82)

**Comment by aclk** [comment]
@weilinqwe 好的，尝试下。

**Comment by zhaiyuzhen** [comment]
有些新用户并非跟着你们的研发团队“一路走来”，而是“半路出家”。
用户是根据文档操作遇到问题来反馈是好事：1、说明有用户愿意和你一起玩；2、说明还有待改进的地方。这是好事。
但是如果以过来人、专家或者老司机训斥小白那样缺乏必要的耐心，至少沟通的氛围就不那么友好。
Whatever,关闭这个ticket吧。我已准备去读官方文档。
