### ISSUE TITLE
需要安装netaddr

### ISSUE THREAD

**Issue by erdongmuxin** [easzlab/kubeasz#686]
在单节点部署的时候提示 FAILED! => {"failed": true, "msg": "The ipaddr filter requires python-netaddr be installed on the ansible controller"}

**Comment by erdongmuxin** [comment]
2.0.3的版本,2.0.2的版本好像没有这个问题

**Comment by zhaiyuzhen** [comment]
你装上python36-netaddr试试？

**Comment by gjmzj** [comment]
是需要安装的。
