### ISSUE TITLE
helm: command not found

### ISSUE THREAD

**Issue by mnuestc** [easzlab/kubeasz#694]
按照kubeasz/docs/guide/helm.md 在线安装 helm，即执行：ansible-playbook /etc/ansible/roles/helm/helm.yml显示成功安装；

在controller节点使用helm安装jenkins，
helm install manifests/jenkins/ --name jenkins
却提示：helm: command not found
请大神指教

**Comment by gjmzj** [comment]
默认是安装在第一个master节点，如果你需要增加安装的节点，可以修改 roles/helm/helm.yml里面的
- hosts：配置

**Comment by autherlj** [comment]
helm 的client 和 tiller 的版本要一致
