### ISSUE TITLE
deploy 机器不能访问集群 提示证书问题

### ISSUE THREAD

**Issue by autherlj** [easzlab/kubeasz#695]
通过2.0.3的版本安全集群，deploy机器(localhosts) 在~/.kube 下面有和master节点一样的config，以及和master 一样的ssl 证书。可是一直提示：Unable to connect to the server: x509: certificate has expired or is not yet valid。 这个deploy机器第一次安装的时候都可以，之后用它安装其他集群就有这个问题了。

**Comment by wt19880712wt** [comment]
你可以试试同步一下host时间

**Comment by autherlj** [comment]
的确是时间同步的问题，现在已经解决@wt19880712wt
