### ISSUE TITLE
阿里云安装harbor，如何公网拉取镜像

### ISSUE THREAD

**Issue by jiangzhikele** [easzlab/kubeasz#697]
Error response from daemon: Get https://47.196.127.208/v2/: x509: certificate is valid for 127.0.0.1, 172.16.49.192, not 47.196.127.208

**Comment by gjmzj** [comment]
1.可以harbor只开启http，然后docker那边启用非安全仓库
2.可以重新生成下harbor证书，把外网地址47.196.127.208也加进去
roles/harbor/templates/harbor-csr.json.j2
btw：阿里云上不是可以使用免费的镜像仓库吗

**Comment by Mikedu1988** [comment]
阿里云申请免费ssl证书，放进去，也可以。
