### ISSUE TITLE
2.0.3版本all in one安装失败，centos-release-7.4（虚拟机）

### ISSUE THREAD

**Issue by cymbalhuang** [easzlab/kubeasz#698]
执行docker exec -it kubeasz easzctl start-aio失败

日志

TASK [kube-node : 轮询等待kubelet启动] ************************************************************************************************************************************************************
FAILED - RETRYING: 轮询等待kubelet启动 (8 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (7 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (6 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (5 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (4 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (3 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (2 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (1 retries left).
fatal: [10.86.2.129]: FAILED! => {"attempts": 8, "changed": true, "cmd": "systemctl status kubelet.service|grep Active", "delta": "0:00:00.012235", "end": "2019-09-18 14:18:17.479973", "rc": 0, "start": "2019-09-18 14:18:17.467738", "stderr": "", "stderr_lines": [], "stdout": "   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-09-18 14:18:14 CST; 2s ago", "stdout_lines": ["   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-09-18 14:18:14 CST; 2s ago"]}

PLAY RECAP **********************************************************************************************************************************************************************************
10.86.2.129                : ok=73   changed=30   unreachable=0    failed=1   
localhost                  : ok=20   changed=12   unreachable=0    failed=0   

[ERROR] Action failed : start-aio

journalctl -xefu kubelet日志：

Sep 18 14:23:30 localhost.localdomain systemd[1]: kubelet.service holdoff time over, scheduling restart.
Sep 18 14:23:30 localhost.localdomain systemd[1]: Starting Kubernetes Kubelet...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has begun starting up.
Sep 18 14:23:30 localhost.localdomain systemd[1]: Started Kubernetes Kubelet.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Sep 18 14:23:30 localhost.localdomain kubelet[122890]: I0918 14:23:30.206860  122890 feature_gate.go:230] feature gates: &{map[]}
Sep 18 14:23:30 localhost.localdomain kubelet[122890]: I0918 14:23:30.208481  122890 feature_gate.go:230] feature gates: &{map[]}
Sep 18 14:23:30 localhost.localdomain kubelet[122890]: I0918 14:23:30.208544  122890 feature_gate.go:230] feature gates: &{map[]}
Sep 18 14:23:30 localhost.localdomain kubelet[122890]: I0918 14:23:30.212305  122890 server.go:408] Version: v1.11.0
Sep 18 14:23:30 localhost.localdomain kubelet[122890]: I0918 14:23:30.212388  122890 feature_gate.go:230] feature gates: &{map[]}
Sep 18 14:23:30 localhost.localdomain kubelet[122890]: I0918 14:23:30.212442  122890 feature_gate.go:230] feature gates: &{map[]}
Sep 18 14:23:30 localhost.localdomain kubelet[122890]: I0918 14:23:30.212560  122890 plugins.go:97] No cloud provider specified.
Sep 18 14:23:30 localhost.localdomain kubelet[122890]: F0918 14:23:30.212604  122890 server.go:262] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Sep 18 14:23:30 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Sep 18 14:23:30 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
Sep 18 14:23:30 localhost.localdomain systemd[1]: kubelet.service failed.

**Comment by gjmzj** [comment]
你的机器环境不干净，应该是之前装过其他k8s工具，使用干净的系统就好了
