### ISSUE TITLE
本人改写了个arm64的，如有冒犯请告知删除

### ISSUE THREAD

**Issue by baosong818** [easzlab/kubeasz#701]
https://github.com/baosong818/kubeasz_to_arm64
这是我改写的，其实只是改写了相应的arm64的包，外加在etcd启动时候多了个判断
{% if (ansible_distribution_release == 'AltArch' and ansible_distribution_major_version == '7' and ansible_distribution == 'CentOS') %}
Environment=ETCD_UNSUPPORTED_ARCH=arm64
{% endif %}

如有冒犯，请告知我会自行删除，谢谢
上传只为留个备份，毕竟也算是arm64的研究成功
再次谢谢大佬写出如此完美的项目

**Comment by gjmzj** [comment]
欢迎～
如果能够在arm64顺利跑通，可以整理出来分享给大家:)

**Comment by baosong818** [comment]
前7步骤已经没问题，tools目录下的增删改查node、master还没测试

**Comment by baosong818** [comment]
请问
[root@etcd1 ansible]# vi roles/flannel/defaults/main.yml 
# 部分flannel配置，参考 docs/setup/network-plugin/flannel.md

# 设置flannel 后端
#FLANNEL_BACKEND: "host-gw"
FLANNEL_BACKEND: "vxlan"
DIRECT_ROUTING: false

#flanneld_image: "quay.io/coreos/flannel:v0.11.0-arm64"
flanneld_image: "lwolf/flannel:v0.11.0-arm64"

# 离线镜像tar包
flannel_offline: "flannel_v0.11.0-arm64.tar"

这里怎么走变量匹配指定arm64或者amd64
先行谢谢指导了

**Comment by gjmzj** [comment]
不是仅修改roles/fannel/defaults/main.yml就可以了；
还需要去修改roles/fannel/templates/kube-flannel.yaml.j2这个配置文件，可能flannel官方有针对arm64的配置模版

**Comment by baosong818** [comment]
我已经全部跑通了，想兼容arm64的前提下还依旧可以在x86_64可用，roles/flannel/defaults/main.yml指向把这个文件也走变量出来arm64或amd64
是不是我需要在hosts里面定义，然后在这里这么调用
hosts
平台="arm64"

flanneld_image: "lwolf/flannel:v0.11.0-{{ 平台 }}"

**Comment by huanyuxiaoxiao** [comment]
@baosong818  兄弟 arm64的怎么样了

**Comment by baosong818** [comment]
@huanyuxiaoxiao https://github.com/baosong818/kubeasz-To-arm64-amd64-mips64 可以试试，我用kubeadm写了个，但全部灵感和成就来自kubeasz，再次感谢
