### ISSUE TITLE
kubectl get node 报错error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by liferight** [easzlab/kubeasz#702]
离线安装 
04.kube-master.yml 
![image](https://user-images.githubusercontent.com/21303400/65569527-8ae41980-df90-11e9-8d25-a44c9adb65f2.png)

报错
error: You must be logged in to the server (Unauthorized)

**Comment by weilinqwe** [comment]
你看看kube config是否正确，默认在/root/.kube/config

**Comment by liferight** [comment]
> 你看看kube config是否正确，替换在/root/.kube/config

删除重建还是报错！
配置双master的话 ，config文件都一样吗？ 
![image](https://user-images.githubusercontent.com/21303400/65581991-15d40c80-dfaf-11e9-94ad-09f2ffaadc95.png)

**Comment by weilinqwe** [comment]
kubeasz版本里，如果是master节点是直接连本节点ip，如果是node接口是通过连haproxy负载到多master节点的
