### ISSUE TITLE
改进文档的建议

### ISSUE THREAD

**Issue by Panlichen** [easzlab/kubeasz#705]
1. 在[安装ansible的说明](https://github.com/easzlab/kubeasz/blob/master/docs/setup/00-planning_and_overall_intro.md#3%E5%9C%A8ansible%E6%8E%A7%E5%88%B6%E7%AB%AF%E5%AE%89%E8%A3%85%E5%8F%8A%E5%87%86%E5%A4%87ansible)那里明确说明所有机器都要配置好root账户的ssh公钥登录才可以保证后续安装脚本可以正常执行，这样对不熟悉ansible的用户会友好些。
2. 说明目前不支持ipv6，并且说明合法的机器别名可以使用的字符范围。
3. [这行指令](https://github.com/easzlab/kubeasz/blob/51c0f61a923203c91973bf2509b90d6d7a832d03/roles/prepare/tasks/main.yml#L57)(`copy: src=/root/.kube/config dest=/root/.kube/config`)事实上要求执行ansible命令的机器也是用root登录，建议修改为`copy: src=~/.kube/config dest=/root/.kube/config`

以上是我在使用过程中遇到过的一些问题，其中第二个问题使得kube-node上的kubelet和kube-proxy反复重启，无法正常使用，根据log猜测是这个原因，对机器的网络重新设置为使用ipv4并且弃用机器别名之后，才可以正常使用。

非常感谢项目的开发者，也希望这几条建议可以被采纳，使这个项目对经验不是很丰富的开发者更加友好。

**Comment by gjmzj** [comment]
非常感谢🙏
我找时间验证后，完善进去～
