### ISSUE TITLE
ansible hosts.multi-node中的[ex-lb]是什么地址

### ISSUE THREAD

**Issue by hurricane1988** [easzlab/kubeasz#713]
#192.168.1.6 LB_ROLE=backup EX_APISERVER_VIP=192.168.1.250 EX_APISERVER_PORT=8443
#192.168.1.7 LB_ROLE=master EX_APISERVER_VIP=192.168.1.250 EX_APISERVER_PORT=8443
你好！以上两条记录是hosts.multi-node中的，这两个地址具体是什么地址，可以被外部访问的地址吗？如果master是单个网卡，那么这个地址是否可以和master的业务地址一致？

**Comment by gjmzj** [comment]
https://github.com/easzlab/kubeasz/blob/master/docs/setup/ex-lb.md
建议阅读下这个文档
