### ISSUE TITLE
Loadbalance配置不生效

### ISSUE THREAD

**Issue by TophillZK** [easzlab/kubeasz#715]
在hosts中Loadbalance处的配置如下：
```
223.***.***.43 LB_ROLE=backup EX_APISERVER_VIP=223.***.***.48 EX_APISERVER_PORT=8443
223.***.***.44 LB_ROLE=master EX_APISERVER_VIP=223.***.***.48 EX_APISERVER_PORT=8443
```
其中43、44是我的两个master节点，48为一个未用IP

操作系统版本：CentOS Linux release 7.7.1908 (Core)
内核版本：5.3.7-1.el7.elrepo.x86_64

在43、44主机上执行lb检查命令：
```
systemctl status haproxy
* haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

systemctl status keepalived
* keepalived.service - LVS and VRRP High Availability Monitor
   Loaded: loaded (/usr/lib/systemd/system/keepalived.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

journalctl -u haproxy
-- No entries --

journalctl -u keepalived
-- No entries --

```
@gjmzj 希望能够帮助解决!!

**Comment by TophillZK** [comment]
还有个问题 EX_APISERVER_PORT 是指定暴露的端口吧？如果我想暴露多个端口，是不是写成以下样式：
`EX_APISERVER_VIP=223.***.***.48 EX_APISERVER_PORT=80 EX_APISERVER_PORT=443`
如果我想暴露所有端口，是不是不写 EX_APISERVER_PORT 这个配置即可？

**Comment by gjmzj** [comment]
> 在hosts中Loadbalance处的配置如下：
> 
> ```
> 223.***.***.43 LB_ROLE=backup EX_APISERVER_VIP=223.***.***.48 EX_APISERVER_PORT=8443
> 223.***.***.44 LB_ROLE=master EX_APISERVER_VIP=223.***.***.48 EX_APISERVER_PORT=8443
> ```
> 
> 其中43、44是我的两个master节点，48为一个未用IP
> 
> 操作系统版本：CentOS Linux release 7.7.1908 (Core)
> 内核版本：5.3.7-1.el7.elrepo.x86_64
> 
> 在43、44主机上执行lb检查命令：
> 
> ```
> systemctl status haproxy
> * haproxy.service - HAProxy Load Balancer
>    Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
>    Active: inactive (dead)
> 
> systemctl status keepalived
> * keepalived.service - LVS and VRRP High Availability Monitor
>    Loaded: loaded (/usr/lib/systemd/system/keepalived.service; disabled; vendor preset: disabled)
>    Active: inactive (dead)
> 
> journalctl -u haproxy
> -- No entries --
> 
> journalctl -u keepalived
> -- No entries --
> ```
> 
> @gjmzj 希望能够帮助解决!!

是否阅读过这个文档
https://github.com/easzlab/kubeasz/blob/master/docs/setup/ex-lb.md

**Comment by gjmzj** [comment]
> 还有个问题 EX_APISERVER_PORT 是指定暴露的端口吧？如果我想暴露多个端口，是不是写成以下样式：
> `EX_APISERVER_VIP=223.***.***.48 EX_APISERVER_PORT=80 EX_APISERVER_PORT=443`
> 如果我想暴露所有端口，是不是不写 EX_APISERVER_PORT 这个配置即可？

不是这样的，目前仅支持暴露后端apiserver 6443；

**Comment by TophillZK** [comment]
> 是否阅读过这个文档
> https://github.com/easzlab/kubeasz/blob/master/docs/setup/ex-lb.md
hi @gjmzj ，很感谢您的回复，您提到的文档我以前阅读过了，不过可能没有阅读的太仔细。今天又仔细研究了一下，同时参考了 [配置负载转发 ingress nodeport](https://github.com/easzlab/kubeasz/blob/master/docs/op/loadballance_ingress_nodeport.md) 这篇文章，发现原来在hosts配置之后，还需要单独运行 ansible-playbook /etc/ansible/roles/ex-lb/ex-lb.yml 命令才能正确启动 haproxy 和 keepalived 。

不过目前这个haproxy和keepalived不能很好实现我的项目需求，我仅仅需要的是向外暴露一个外网VIP，然后后端接一个Nginx的pod（我要在这个Nginx中实现四层和七层的路由）。目前我使用了kube-keepalived-vip的方案来完成（kube-keepalived-vip不能跑在master上）。

另：在使用过程中，从2.0.2升级到2.0.3时，发现externalIPs和ipvs是有冲突的，不知道最新的k8s版本是否解决了这个问题。

最后，再次感谢您的帮助~~
