### ISSUE TITLE
networkpolicy配置不生效

### ISSUE THREAD

**Issue by rice5** [easzlab/kubeasz#722]
Hi，

https://github.com/easzlab/kubeasz/blob/master/docs/guide/networkpolicy.md
我按照指引，配置了default-deny.yaml，但实际测量，在pods内没起到隔离效果，请教一下，这种情况是否能查看networkpolicy的log，进一步排查问题呢？

我安装的是k8s 1.15，flannel v0.11.0-amd64. 麻烦确诊下问题，谢谢！
我查看了有一个已经close的issue，如何最简单实现pods网络隔离 #122 ，没有对应的解决方案。

**Comment by pingod** [comment]
flannel 没有用到iptables,所有没有networkpolicy.
如果用calico就可以配置网络策略

**Comment by rice5** [comment]
好吧，那我先close吧，后面换calico再试试
