### ISSUE TITLE
easzup 执行问题

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#723]
easzup -D 使用docker images 命令查看为啥还下载了一部分镜像呢？不是所有的文件都在/etc/ansible下面么？ 那么我每次离线安装的话除了拷贝/etc/ansible下的所有文件还要在离线机器上重新执行easzup -D？

**Comment by gjmzj** [comment]
easzup -D 会下载常用镜像并保存为离线.tar包，在 /etc/ansible/down/ 目录下面
