### ISSUE TITLE
kubeconfig问题

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#724]
我看ansible生成kubeconfig过程中只指定了一个api-server，如果我这台api-server宕机了，那么我kubectl 如何通过kubeconfig连接api-server呢？
![111](https://user-images.githubusercontent.com/17851645/68085079-c7e8d900-fe77-11e9-8749-6708248cbf71.png)
![222](https://user-images.githubusercontent.com/17851645/68085116-257d2580-fe78-11e9-9ca0-be1c5e80959c.png)

**Comment by gjmzj** [comment]
这个kubeconfig是deploy节点初始生成的；一般deploy节点就是第一个master节点；
当它被复制到其他 master/node节点时，KUBE-APISERVER地址会被替换的；

**Comment by Hello-Linux** [comment]
@gjmzj  那等于是kubectl连接apiserver没有实现高可用吧

**Comment by gjmzj** [comment]
kubectl连接apiserver要实现高可用也很简单，只有安装下项目里面的 [ex-lb]部分，然后把 kubeconfig中的 apiserver地址换成 ex-lb 中的vip地址；
一般情况下也没必要为了kubectl连接apiserver高可用，特意去安装ex-lb
