### ISSUE TITLE
kubeasz2.0 springboot-k8s-example构建失败

### ISSUE THREAD

**Issue by 551685830** [easzlab/kubeasz#725]
## 根据springboot-k8s-example在kubeasz2.0搭建的k8s集群中的Jenkins构建失败。
![image](https://user-images.githubusercontent.com/6261789/68284807-12a56380-00b9-11ea-9b2c-19d730699018.png)
> 我看目前2.0的架构是在各个node节点上安装了haproxy来代理kube-apiserver
> 我排查了各个node节点的haproxy是正常工作的，因为可以在任意node节点来通过本机的6443访问dashboard

![image](https://user-images.githubusercontent.com/6261789/68285101-9d865e00-00b9-11ea-9655-d0735caf30ef.png)

> 我有尝试直接调整/root/.kube/config文件中的server为 真实的kube-apiserver地址，但jenkins都会在最后一步执行失败。请教一个如何处理这个问题？

**Comment by gjmzj** [comment]
不通过jenkins，手动执行能够成功吗？

**Comment by gjmzj** [comment]
你这里背景没介绍清楚，看了群里信息，你的jenkins agent是跑在容器里面的，那当然不行的；
把.kube/config 中的apiserver改成真实master node地址，然后再mount到容器里面应该可以

**Comment by 551685830** [comment]
首先谢谢你的回复！

![image](https://user-images.githubusercontent.com/6261789/68450240-4ac9b500-0225-11ea-83f4-e70b22df6696.png)

我有把各个节点的.kube/config中的host调整为192.168.40.30(master[0])节点的地址，但最后一步还是执行错误，只不过错误信息变了。

![image](https://user-images.githubusercontent.com/6261789/68450344-b449c380-0225-11ea-9a72-80144597419d.png)

Jenkinsfile中已经声明了mount操作，否则也不会因为我调整node节点的apiserver地址，同一样的部署报的错误不一样。

我好奇的事，关于jenkins这一块，kubeasz2.0与1.0并没有什么差别，1.x的没有此问题，2.0的怎么会有问题？难道使用2.x的就我一人遇到这个问题？

**Comment by lusyoe** [comment]
@551685830 这个错误应该跟kubernetes版本有关，可以把`lachlanevenson/k8s-kubectl:v1.10.2`的版本替换为跟集群一致看看。

**Comment by 551685830** [comment]
@lusyoe 感谢你的友情提示。按你提示的我将lachlanevenson/k8s-kubectl升级到了最新版本，就OK了。

```bash
`containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:latest', command: 'cat', ttyEnabled: true)`
```

看来应该是kubeasz中kubectl的版本升级，需要Jenkins中的lachlanevenson/k8s-kubectl也跟着升级，我估计默认使用latest应该就OK。

@gjmzj 希望作者把这个变化更新进kubeasz2.0文档里去，这样其它同学就能少走弯路了。

非常感谢大家！！！
