### ISSUE TITLE
 master主机创建 aggregator-proxy证书和私钥是什么意思

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#726]
在master主机上创建 aggregator-proxy是用来做什么的？文档里面没有说明呢

**Comment by gjmzj** [comment]
metrics-server 用到的，参考https://github.com/easzlab/kubeasz/blob/master/docs/guide/metrics-server.md

**Comment by Hello-Linux** [comment]
@gjmzj  ok我看看
