### ISSUE TITLE
最新版本部署单master多节点的时候的几个问题

### ISSUE THREAD

**Issue by fujinjun** [easzlab/kubeasz#728]
1，hosts文件中的CLUSTER_DNS_DOMAIN最后的.要删除，不然coredns会连接不上集群网络
2，在使用basic auth的时候，kubernetes-dashboard.yaml中的args要添加- --authentication-mode=basic，不然启动集群会dashboard依然会要求使用token
3，没有自动下载python-netaddr包，使用setup的时候会报错

**Comment by gjmzj** [comment]
问题1，我这边安装都没问题，需要再深入看看
问题2，使用basic auth，只是增加验证apiserver的一种方式；它跟登陆dashboard没有耦合关系；当然你这样设置也是登陆dashboard的一种方法；
问题3，在 roles/deploy/tasks/main.yml  最后已经添加了自动安装
