### ISSUE TITLE
最新版本部署helms失败

### ISSUE THREAD

**Issue by huangleilz** [easzlab/kubeasz#729]
2.1.0部署helm在安装tiller时候任务失败，将命令复制到目标机上执行也是失败的，错误内容为$HELM_HOME has been configured at /root/.helm.
Error: error installing: the server could not find the requested resource

**Comment by weilinqwe** [comment]
除了helm客户端程序外，本地有个context目录（/root/.helm）。目前项目好像默认是master第一台能helm客户端（有context目录），其它服务器不行。你要在其它服务器上执行，除了helm客户端程序还要把context目录复制过去

**Comment by huangleilz** [comment]
就是在master的第一台上安装上安装失败的。

**Comment by hurricane1988** [comment]
我也遇到这个问题，是不是部署tiller的ca证书有问题？
 {"changed": true, "cmd": "/opt/kube/bin/helm init --history-max 5 --tiller-tls --tiller-tls-verify --tiller-tls-cert /etc/kubernetes/ssl/tiller001.pem --tiller-tls-key /etc/kubernetes/ssl/tiller001-key.pem --tls-ca-cert /etc/kubernetes/ssl/ca.pem --service-account tiller --tiller-namespace kube-system --tiller-image easzlab/tiller:v2.14.1 --stable-repo-url https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts --upgrade", "delta": "0:00:00.083011", "end": "2019-11-14 15:23:20.040793", "msg": "non-zero return code", "rc": 1, "start": "2019-11-14 15:23:19.957782", "stderr": "Error: error installing: the server could not find the requested resource", "stderr_lines": ["Error: error installing: the server could not find the requested resource"], "stdout": "$HELM_HOME has been configured at /root/.helm.", "stdout_lines": ["$HELM_HOME has been configured at /root/.helm."]}

**Comment by huangleilz** [comment]
是因为k8s升级到16后api发生变化，tiller启动不了。可以看一下helm的官网，升级helm版本后就可以成功安装。

**Comment by mymmmumu** [comment]
安装v3.0的就可以了。。。
不过k8s使用1.16以后，原本的一些yaml参数好像也调整了

**Comment by legolas-zeng** [comment]
是的，1.16不支持helm1.14

**Comment by ZPJeck** [comment]
为

**Comment by ZPJeck** [comment]
执行 helm list  报错 context deadline exceeded ？
按照文档操作的。
