### ISSUE TITLE
安装 flannel网络问题

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#731]
我看技术文档里面说安装flannel网络之后要删除之前创建的CNI默认基础网络配置文件10-default.conf,在这里为什么要删除呢？之前没有用到么？

![000](https://user-images.githubusercontent.com/17851645/68729887-20ea0700-0606-11ea-9f62-a444bdbf5d0f.png)
![111](https://user-images.githubusercontent.com/17851645/68729891-25162480-0606-11ea-836a-d0e98dfbf144.png)

**Comment by AEGQ** [comment]
参考: https://github.com/easzlab/kubeasz/issues/733#issuecomment-554637775
