### ISSUE TITLE
其中一个master的nodeport不能访问

### ISSUE THREAD

**Issue by wangshengjin123** [easzlab/kubeasz#732]
我们其中一套环境是用3台线下自己机房的物理机搭建的2个master和1个node，之前出现过一次这样的问题，后来重装后好了，现在又出现了一次
[root@k8s1 ~]# kubectl get node
NAME         STATUS                     ROLES    AGE   VERSION
172.17.0.7   Ready                      node     27d   v1.13.5
172.17.0.8   Ready                      master   55d   v1.13.5 
172.17.0.9   Ready                      master   51d   v1.13.5
主要表现是其中一个节点master上的pod，通过nodeport访问不了，必须驱逐到其他节点，当时怎么出现的不记得了，折腾不出来就重装这个节点了

今天突然一个master负载爆棚，load好几百了，持续几分钟之后，恢复了，这个master节点又出现了上面的服务用不了的情况
calico网络看不出啥问题，在0.8上ansible kube-master -m shell -a '/opt/kube/bin/calicoctl node status'
172.17.0.8 | CHANGED | rc=0 >>
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+------------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+--------------+-------------------+-------+------------+-------------+
| 172.17.0.9   | node-to-node mesh | up    | 06:09:32   | Established |
| 172.17.0.7   | node-to-node mesh | up    | 2019-10-17 | Established |
+--------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.

172.17.0.9 | CHANGED | rc=0 >>
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.17.0.7   | node-to-node mesh | up    | 06:09:05 | Established |
| 172.17.0.8   | node-to-node mesh | up    | 06:09:05 | Established |
+--------------+-------------------+-------+----------+-------------+

重新执行01的脚本   重启浮动ip也没用，不知道啥情况
对这种情况有啥建议或想法的嘛
route的情况，13是master，2是node
[root@k8s1 ~]#  route -n|grep -v cali
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.0.254    0.0.0.0         UG    100    0        0 enp4s0f0
172.17.0.0      0.0.0.0         255.255.255.0   U     100    0        0 enp4s0f0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.21.110.128  172.17.0.7      255.255.255.192 UG    0      0        0 tunl0
172.21.110.192  172.17.0.7      255.255.255.192 UG    0      0        0 tunl0
172.21.167.0    0.0.0.0         255.255.255.192 U     0      0        0 *
172.21.167.64   0.0.0.0         255.255.255.192 U     0      0        0 *
172.21.219.64   172.17.0.8      255.255.255.192 UG    0      0        0 tunl0
172.21.219.128  172.17.0.8      255.255.255.192 UG    0      0        0 tunl0
172.21.219.192  172.17.0.8      255.255.255.192 UG    0      0        0 tunl0

[root@k8s2 ~]# route -n|grep -v cali
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.0.254    0.0.0.0         UG    100    0        0 enp5s0f0
172.17.0.0      0.0.0.0         255.255.255.0   U     100    0        0 enp5s0f0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.21.110.128  0.0.0.0         255.255.255.192 U     0      0        0 *
172.21.110.192  0.0.0.0         255.255.255.192 U     0      0        0 *
172.21.167.0    172.17.0.9      255.255.255.192 UG    0      0        0 tunl0
172.21.167.64   172.17.0.9      255.255.255.192 UG    0      0        0 tunl0
172.21.219.64   172.17.0.8      255.255.255.192 UG    0      0        0 tunl0
172.21.219.128  172.17.0.8      255.255.255.192 UG    0      0        0 tunl0
172.21.219.192  172.17.0.8      255.255.255.192 UG    0      0        0 tunl0

[root@k8s3 ansible]# route -n|grep -v cali
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.0.254    0.0.0.0         UG    100    0        0 enp2s0f0
172.17.0.0      0.0.0.0         255.255.255.0   U     100    0        0 enp2s0f0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.21.110.128  172.17.0.7      255.255.255.192 UG    0      0        0 tunl0
172.21.110.192  172.17.0.7      255.255.255.192 UG    0      0        0 tunl0
172.21.167.0    172.17.0.9      255.255.255.192 UG    0      0        0 tunl0
172.21.167.64   172.17.0.9      255.255.255.192 UG    0      0        0 tunl0
172.21.219.64   0.0.0.0         255.255.255.192 U     0      0        0 *
172.21.219.128  0.0.0.0         255.255.255.192 U     0      0        0 *
172.21.219.192  0.0.0.0         255.255.255.192 U     0      0        0 *

**Comment by wangshengjin123** [comment]
老规矩，重装解决

**Comment by gjmzj** [comment]
某个节点不能访问nodePort，我之前碰到过的情况是因为节点没开启端口转发；
cat /proc/sys/net/ipv4/ip_forward 检查下看看
