### ISSUE TITLE
CNI plugin是如何给基础容器pause配置网络的呢？

### ISSUE THREAD

**Issue by Hello-Linux** [easzlab/kubeasz#733]
看完你的flannel文档还是有点不理解，你使用flannel daemonset安装，DaemonSet Pod包含两个容器，一个容器运行flannel本身，另一个init容器部署cni 配置文件，init部署的cni配置文件是谁使用的？原来kube-node生成的cni-defalut.conf又是做什么的？最后是怎么实现给基础容器初始化网络的？
![001](https://user-images.githubusercontent.com/17851645/68823816-eb115500-06cf-11ea-817e-c3cfba67dbaa.png)

**Comment by gjmzj** [comment]
原来kube-node生成的cni-defalut.conf是临时用的，因为本项目安装过程启动kubelet的时候真正的网络插件还没有安装，必须默认配置一个，这样kubelet才能启动；
等后面真正网络插件flannel或calico安装时，这个默认cni配置就可以删掉了；
