### ISSUE TITLE
离线安装版本release easzup 中配置的 easzlab/kubeasz-k8s-bin 默认版本v1.15.0已不存在，望修改一下

### ISSUE THREAD

**Issue by CZacker** [easzlab/kubeasz#735]
![image](https://user-images.githubusercontent.com/25023285/68832774-ca0b2d00-06ec-11ea-973a-2ee87273a62e.png)

**Comment by gjmzj** [comment]
可以用参数下载新版的；
```
./easzup -D -k v1.15.5
```
k8s在小版本上尽量保持最新的；能用 v1.15.5 就不用 v1.15.4及之前的；😄
