### ISSUE TITLE
EFK问题：关于kibana版本升级

### ISSUE THREAD

**Issue by DanceKiddle** [easzlab/kubeasz#736]
目前想要支持kibana汉化，所以想升级到6.7或更高版本，但更改镜像版本部署后后发现无法连接elasticsearch。可能是elastic版本过低的问题，
我看到目前elastic镜像用的是2.4.0版，官方也没有更新的版本了，所以想问下，这个gcr.io/fluentd-elasticsearch/elasticsearch和docker官方的elasticsearch有何区别？我能不能直接采用docker官方的fluentd和elasticsearch代替？

**Comment by weilinqwe** [comment]
它就是[官方efk方案](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch)，镜像是在官方镜像基础上做的，执行了一些初始化脚本，有生成镜像的Dockerfile，已经支持到7.3.2了。
