### ISSUE TITLE
【已解决，建议修复】1.16.2版本kube-node创建失败 Unable to update cni config: no valid networks found in /etc/cni/net.d

### ISSUE THREAD

**Issue by Ushijima-yanj** [easzlab/kubeasz#737]
release:2.1.0
创建node节点时读取cni配置文件失败：
![ansible-getnode](https://user-images.githubusercontent.com/45476234/68928086-386eee80-07c4-11ea-9267-4b2a26a760a9.png)
![kubelet](https://user-images.githubusercontent.com/45476234/68928111-43c21a00-07c4-11ea-865c-b00e6160395a.png)
创建的/etc/cni/net.d/10-default.conf文件如下
![image](https://user-images.githubusercontent.com/45476234/68928249-96033b00-07c4-11ea-9f79-af7d834c0b83.png)

参考https://github.com/coreos/flannel/issues/1178#issuecomment-533334103
1.16版本kubernetes需要在配置文件中指定cni版本
![image](https://user-images.githubusercontent.com/45476234/68928523-38bbb980-07c5-11ea-9e25-b81ba6880805.png)
![image](https://user-images.githubusercontent.com/45476234/68928560-4ec97a00-07c5-11ea-82e6-a1082ac0d920.png)

**Comment by gjmzj** [comment]
感谢提醒，不过这个问题在 release 2.1.0 已经修复过了，详见项目文件：
roles/kube-node/templates/cni-default.conf.j2
