### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by 51qzpw** [easzlab/kubeasz#738]
可以出一套视频介绍一下整个项目，以及个性化的参数配置说明，对于初学者来说，其中很多的知识点靠个人的理解不到位，会踩很多坑，曲线度又增加了。

**Comment by gjmzj** [comment]
项目的主线就是 01.prepare.yml 02.etcd.yml ...07.cluster-addon.yml 七个ansible-playbook；
而ansible-playbook的里面的任务，每一个语句基本都是自带注释的，有一点ansible基础的话很容易理解

**Comment by pretendfine** [comment]
免费的大哥，别人没这个义务
