### ISSUE TITLE
当部署dashboard以后 kubectl cluster-info|grep dashboard查看没有内容

### ISSUE THREAD

**Issue by shallone** [easzlab/kubeasz#739]
根据文档正常执行
1.kubectl apply -f /etc/ansible/manifests/dashboard/kubernetes-dashboard.yaml
2.kubectl apply -f /etc/ansible/manifests/dashboard/admin-user-sa-rbac.yaml
3.kubectl apply -f /etc/ansible/manifests/dashboard/read-user-sa-rbac.yaml
提示各项文件创建成功
执行
1.kubectl get pod -n kube-system | grep dashboard
2.kubectl get svc -n kube-system|grep dashboard
3.kubectl logs kubernetes-dashboard-7c74685c48-9qdpn -n kube-system
返回正常
但是执行kubectl cluster-info|grep dashboard返回结果为空，执行kubectl cluster-info会返回Kubernetes master   CoreDNS  Metrics-server的信息，当前安装情况为安装了单机模式后成功扩充了master节点和node节点

还有一个问题是在增加etcd节点的时候每次会在创建/opt/kube/bin/etcdctl文件的时候报错说文件不存在，如果手动在目标主机上创建了这个文件，又会在执行的最后报etcd.ervice 文件不存在的问题，感觉是在etcd的部署模块中没有正常执行相关文件的复制创建工作，我通过ssh命令连接到添加的节点上执行文件添加命令都是没问题的，应该不是权限问题，看了以下yaml文件也没发现具体的详细流程，不知道到底是哪里出的问题，望解答，谢谢🙏

**Comment by 51qzpw** [comment]
kubectl cluster-info|grep dashboard返回结果为空    同有这个问题

**Comment by gjmzj** [comment]
@shallone 
第一个问题：目前版本的dashboard，方便起见可以使用nodePort方式访问dashboard；如果是查看cluster-info ，通过apiserver代理方式访问dashboard，需要首先通过apiserver认证授权，再dashboard认证授权；如果非要使用后者，可以修改下dashboard yaml配置 manifests/dashboard/kubernetes-dashboard.yaml，在Service 里面增加一行：
``` bash
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"  // 增加这行
  name: kubernetes-dashboard
  namespace: kube-system
spec:
...
```

**Comment by gjmzj** [comment]
第二个问题：
创建etcd服务在 roles/etcd/tasks/main.yml
增加/删除 etcd节点，是 tools/01.addetcd.yml  tools/11.deletcd.yml
