### ISSUE TITLE
关于dubbo服务的注册机制，cni插件如何选择？

### ISSUE THREAD

**Issue by currycan** [easzlab/kubeasz#740]
您好！
       请教一下有关dubbo服务的网络插件选型问题，由于dubbo服务注册会将pod ip注册到zk，集群外是无法访问pod ip的，有没有相关建议？谢谢！
       另外，macvlan + multus的模式最近也研究了下，IP段在二层网络上没事问题，三成网络也无法访问了。
       希望有经验的同学能指点一二，再次感谢！

**Comment by gjmzj** [comment]
1. 利用calico/kube-router可以用bgp和外部路由器交换路由
2. 如果节点数不是很大，或者节点变化不频繁，你可以用任意的网络插件创建完集群，然后在你的节点物理网关那边，手动添加每个节点的pod网络指向该节点的IP

**Comment by currycan** [comment]
恩，谢谢您的建议！不过现阶段可能我们用不上
1.采用calico这种方式有考虑过，calico的复杂度有点高，现阶段运维上把控不了。
2. 手动添加路由，的确也考虑过。用flannel-gw的模式，好像也只能支持二层网络。
