### ISSUE TITLE
2.0.2 easzlab/kubeasz-k8s-bin:v1.15.0无法下载

### ISSUE THREAD

**Issue by ruishanservices** [easzlab/kubeasz#742]
[INFO] downloading kubernetes v1.15.0 binaries
Error response from daemon: manifest for easzlab/kubeasz-k8s-bin:v1.15.0 not found: manifest unknown: manifest unknown
[ERROR] Action failed : download_all

**Comment by gjmzj** [comment]
鼓励使用最新的k8s小版本；
可以用参数指定下载版本 `easzup -D -k v1.15.6`
