### ISSUE TITLE
生产环境kubeasz老版本如何将k8s从1.11升级到1.15？

### ISSUE THREAD

**Issue by Candyient** [easzlab/kubeasz#744]
之前生产环境使用老版本kubeasz部署k8s1.11  目前业务需要升级到1.15.但是不能执行clean 再重新部署。想问下如何升级到1.15

**Comment by gjmzj** [comment]
k8s 1.11 升级 k8s 1.15 应该问题不大；
建议先在测试环境演练一把：
- 把生产环境的部署机 /etc/ansible 目录整体复制到测试环境
- 修改测试环境 /etc/ansible/hosts 文件定义，装好测试k8s集群
- 在测试k8s集群里，演练升级 1.11 到 1.12，到1.13，到1.14，到1.15，建议还是逐级升级上来；看看测试集群有没有问题，预计没啥问题；

**Comment by luolizhi** [comment]
使用1.3版本的kueasz，我从1.13升到1.14很顺利，1.14生1.15遇到了问题，主要是kubelet启动不了，需要手动修改roles/kube-node/  目录下面的配置文件

- 增加参数： `kube-node/default/main.yaml` 
```
# 配置为kube组件（kubelet,kube-proxy,dockerd等）预留的资源量
KUBE_RESERVED_ENABLED: "yes"
KUBE_RESERVED: "{'cpu':'200m','memory':'500Mi','ephemeral-storage':'1Gi'}"


# k8s 官方不建议草率开启 system-reserved, 除非你基于长期监控，了解系统的资源占用状况；并且随着系统运行时间，需要适当增加资源预留
SYS_RESERVED_ENABLED: "no"
# 以下系统预留设置基于 4c/8g 虚机，最小化安装系统服务，如果使用高性能物理机请适当增加数值
SYS_RESERVED: "{'cpu':'200m','memory':'500Mi','ephemeral-storage':'1Gi'}"
```
- `kube-node/templates` 目录下增加 `kubelet-config.yaml.j2` 文件,替换 `kubelet.service.j2`, (使用master分支的文件) 
> 如果有没有定义的参数，可以手动添加或者删除。

- 修改 `kube-node/tasks/main.yaml`， 在创建 `kubelet.service` 之前增加步骤
```
- name: 创建kubelet的配置文件
  template: src=kubelet-config.yaml.j2 dest=/var/lib/kubelet/config.yaml
  tags: upgrade_k8s, restart_node
```
 最后在执行

**Comment by Candyient** [comment]
我在https://github.com/kubernetes/kubernetes/blob/v1.15.6/CHANGELOG-1.15.md#downloads-for-v1155下载1.15的包，并把kube-apiserver，kube-controller-manager，kubectl，kubelet，kube-proxy，kube-scheduler这几个文件替换，按照你的方式修改后，还需要在host文件中定义KUBE_VER=1.15
CONTAINER_RUNTIME=docker
这两个参数，测试成功
