### ISSUE TITLE
centos8  install  fail 

### ISSUE THREAD

**Issue by joseanluo** [easzlab/kubeasz#745]
TASK [prepare : 添加Amazon EPEL仓库] **********************************************************************************************************************************************************************************

TASK [prepare : 安装基础软件包] ******************************************************************************************************************************************************************************************
fatal: [192.168.221.131]: FAILED! => {"changed": false, "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}

PLAY RECAP ********************************************************************************************************************************************************************************************************
192.168.221.131            : ok=2    changed=1    unreachable=0    failed=1   
localhost                  : ok=20   changed=12   unreachable=0    failed=0   

[ERROR] Action failed : start-aio
[root@localhost ~]# python --version 
Python 2.7.15
[root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 8.0.1905 (Core) 
[root@localhost ~]# whereis python 
python: /usr/bin/python3.6 /usr/bin/python /usr/bin/python2.7 /usr/bin/python3.6m /usr/lib/python3.6 /usr/lib/python2.7 /usr/lib64/python3.6 /usr/lib64/python2.7 /usr/include/python3.6m /usr/include/python2.7 /usr/share/man/man1/python.1.gz
[root@localhost ~]# whereis python3
python3: /usr/bin/python3.6 /usr/bin/python3 /usr/bin/python3.6m /usr/lib/python3.6 /usr/lib64/python3.6 /usr/include/python3.6m /usr/share/man/man1/python3.1.gz
[root@localhost ~]#

**Comment by gjmzj** [comment]
centos8 还没有完整测试过，你可以尝试根据错误提示修复下；
提示你用 dnf 替换 yum
在文件 roles/prepare/tasks/centos.yml 中
```
- name: 安装基础软件包
  yum:
    name:
      - bash-completion     # bash命令补全工具，需要重新登录服务器生效
      - conntrack-tools     # ipvs 模式需要
      - ipset               # ipvs 模式需要
```

**Comment by MichelLiu** [comment]
用 dnf 替换 yum 报错：Unable to find a match: python3-dnf"

**Comment by todaygood** [comment]
可以把 yum源配置好， 然后clusters/XXX/config.yaml 中设置INSTALL_SOURCE为online即可。 

我在rhel8上跑了一下， 没碰到问题。
