### ISSUE TITLE
使用2.1.0脚本分步安装程序后，在Maste节点上运行kubectl get componentstatus，状态如下显示：

### ISSUE THREAD

**Issue by sunhuaxu** [easzlab/kubeasz#747]
你好：使用2.1.0脚本分步安装程序后，在Maste节点上运行kubectl get componentstatus，状态如下显示，是什么问题？

[root@bogon dashboard]# kubectl get componentstatus
NAME                 AGE
controller-manager   <unknown>
scheduler            <unknown>
etcd-0               <unknown>
etcd-2               <unknown>
etcd-1               <unknown>

[root@bogon dashboard]# kubectl get node
NAME              STATUS                     ROLES    AGE    VERSION
192.168.123.141   Ready,SchedulingDisabled   master   113m   v1.16.2
192.168.123.142   Ready                      node     82m    v1.16.2
192.168.123.143   Ready                      node     82m    v1.16.2

**Comment by sunhuaxu** [comment]
补充显示状态：
[root@bogon ~]# kubectl get componentstatus
NAME                            AGE
scheduler                   unknown
controller-manager   unknown
etcd-1                        unknown
etcd-2                        unknown
etcd-0                        unknown

**Comment by sunhuaxu** [comment]
补充kubectl cluster-info状态为什么地址是Kubernetes master is running at http://localhost:8080？谢谢！
[root@bogon ansible]# kubectl cluster-info
Kubernetes master is running at http://localhost:8080
CoreDNS is running at http://localhost:8080/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at http://localhost:8080/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

**Comment by gjmzj** [comment]
这个是k8s版本v1.16的问题，以后kubectl get cs命令要被弃用了😢
