### ISSUE TITLE
如何选择K8S的版本？安装最新的有一些问题

### ISSUE THREAD

**Issue by huohuanhuan** [easzlab/kubeasz#753]
[root@istio-kube1 ~]# kubectl get cs
NAME                 AGE
controller-manager   \<unknown>
scheduler            \<unknown>
etcd-2               \<unknown>
etcd-1               \<unknown>
etcd-0              \ <unknown>

**Comment by huohuanhuan** [comment]
[root@istio-kube1 ~]# kubectl get cs
NAME                 AGE
controller-manager   <unknown>
scheduler            <unknown>
etcd-2               <unknown>
etcd-1               <unknown>
etcd-0               <unknown>

**Comment by gjmzj** [comment]
这个命令已不被最新k8s版本支持了
