### ISSUE TITLE
flannel启动失败

### ISSUE THREAD

**Issue by shizy123** [easzlab/kubeasz#754]
![image](https://user-images.githubusercontent.com/38031337/70018956-b7389980-15c2-11ea-85ca-0474dd4ba71e.png)

pod报错如下：E1203 03:44:51.632104       1 main.go:241] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-amd64-72lz2': Get https://172.26.68.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-amd64-72lz2: x509: certificate is valid for 127.0.0.1, 10.29.5.157, 10.1.1.1, not 172.26.68.1
k8s版本：1.5.2和1.6.2都发生
网卡是单网卡
集群部署

**Comment by shizy123** [comment]
麻烦指点一下，卡着不能安装了

**Comment by autherlj** [comment]
建议用clean yaml把集群清理了重新安装
