### ISSUE TITLE
CNI_COMMAND env variable missing

### ISSUE THREAD

**Issue by legolas-zeng** [easzlab/kubeasz#762]
node上面的kubelet启动不了，提示`stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory`，然后发现cni也不行，提示`CNI_COMMAND env variable missing`,使用的是centos7.4，k8s1.14.1，求大佬指教。

**Comment by gjmzj** [comment]
应该是你的安装机器没有清理彻底，是不是用过其他安装工具；
如果用 kubeasz 项目的话，建议用全新的虚拟机
