### ISSUE TITLE
离线安装失败

### ISSUE THREAD

**Issue by zeyuanpinghe** [easzlab/kubeasz#763]
3个节点，配置过ssh，确定节点环境没有问题，可以ping通，和ssh。
---------
# 离线安装 docker，检查本地文件等
$ ./easzup -D

# 启动 kubeasz 容器
$ ./easzup -S

# 进入容器
$ docker exec -it kubeasz sh
centos7.3系统
使用的是
# 离线安装 docker，检查本地文件等
$ ./easzup -D

# 启动 kubeasz 容器
$ ./easzup -S

# 进入容器
$ docker exec -it kubeasz sh
------------
这种方式安装的。
执行第一个ansible-playbook 01.prepare.yml

到这个任务“删除centos/redhat默认安装”
显示过node1的信息后，就长时间 没有变化了。
然后停止掉脚本，发现容器内只能访问node1，其他节点都不能访问，Ping的时候提示timeout。

**Comment by gjmzj** [comment]
这个问题确实偶尔有出现，目前没有找到根本原因😢

**Comment by zeyuanpinghe** [comment]
> 这个问题确实偶尔有出现，目前没有找到根本原因
roles/prepare/tasks/cetnos.yml中的任务  
"删除centos/redhat默认安装" 移除掉之后，这个问题就没有了。
但是紧接着出现的是kube-node安装失败，等待node进行ready状态时，失败。查看了下，没有启动6443端口的服务。
然后不启用kube-node的任务，最终可以安装完成，不过是只有master节点。
再使用uncordon命令后，可以进行正常调度。
还有一个问题是ex-lb放开后，没有生成漂移的ip，也就是vip_ip并没有生效，目前没找到原因。

**Comment by zeyuanpinghe** [comment]
> 这个问题确实偶尔有出现，目前没有找到根本原因
@gjmzj 
ex-lb的问题解决了，是我自己没有加那个执行命令
6443端口拒绝连接的那个问题。也查到了，与本机的openssl版本有关，因为是离线环境，没有使用yum update。
但是三个节点，两个master一个node的情况下。centos7系统，完全相同的环境下。
没有执行ex-lb的情况下，安装完成后，
master节点的openssl版本是1.0.2k。
node节点是1.0.1e版本。然后就是node安装失败。
手动升级 Node节点的openssl版本后，再次执行安装命令，安装成功。

**Comment by zeyuanpinghe** [comment]
手动更新了一下Openssl的版本
master节点上的新版本号是因为手动安装ansible时候，它直接更新了openssl。

**Comment by gjmzj** [comment]
之前你提到在容器里面 ，发现容器内只能访问node1，其他节点都不能访问，Ping的时候提示timeout。
这个找到原因了吗？

**Comment by zeyuanpinghe** [comment]
> 之前你提到在容器里面 ，发现容器内只能访问node1，其他节点都不能访问，Ping的时候提示timeout。
> 这个找到原因了吗？

这个原因没找到，我对了网络配置没有改变

**Comment by marksugar** [comment]
```
[WARNING]: Unhandled error in Python interpreter discovery for host 192.168.3.102: Failed to connect to the host via ssh: ssh: connect
to host 192.168.3.102 port 22: Operation timed out
[WARNING]: Unhandled error in Python interpreter discovery for host 192.168.3.101: Failed to connect to the host via ssh: ssh: connect
to host 192.168.3.101 port 22: Operation timed out
fatal: [192.168.3.102]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.3.102\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.3.102 port 22: Operation timed out\r\n", "unreachable": true}
fatal: [192.168.3.101]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.3.101\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.3.101 port 22: Operation timed out\r\n", "unreachable": true}
```

os:  centos 7.9

easzlab/kubeasz:3.0.0

只能够ssh自己
