### ISSUE TITLE
关于k8s  ipvs报错

### ISSUE THREAD

**Issue by rhkjyn** [easzlab/kubeasz#764]
k8s: 1.14.8
OS: centos 7.6 
kernel: 4.4.186
启用ipvs,然后经常会出现主机挂死,大量的报错如下:
IPVS: rr: TCP 100.64.35.249:18080 - no destination available
这时候主机ssh都连不上,需要重启才能临时解决.
请教各位如何解决.
内核参数如附:
cat /etc/sysctl.d/95-k8s-sysctl.conf 

net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-arptables = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_tw_reuse = 0
net.netfilter.nf_conntrack_max=1000000
vm.swappiness = 0
vm.max_map_count=655360
fs.file-max=6553600
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 10
vm.dirty_background_ratio = 5
vm.dirty_ratio = 10

**Comment by gjmzj** [comment]
你们的centos 公司内部定制过吗？
如果是的，这个内核设置不一定会生效 /etc/sysctl.d/95-k8s-sysctl.conf
还是要检查对应 /proc/ 里面实际的值

**Comment by gjmzj** [comment]
cat /proc/sys/net/ipv4/tcp_tw_recycle
cat /proc/sys/net/ipv4/tcp_tw_reuse
看看

**Comment by rhkjyn** [comment]
[root@k8s-node ~]# cat /proc/sys/net/ipv4/tcp_tw_recycle
0
[root@k8s-node ~]# cat /proc/sys/net/ipv4/tcp_tw_reuse
0
看着好像是生效的呢

**Comment by wangshengjin123** [comment]
你最后是怎么处理的啊

**Comment by rhkjyn** [comment]
给k8s各组件预留更多资源



---原始邮件---
发件人: "wangshengjin123"<notifications@github.com&gt;
发送时间: 2020年2月12日(周三) 晚上8:42
收件人: "easzlab/kubeasz"<kubeasz@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"rhkjyn"<28165136@qq.com&gt;;
主题: Re: [easzlab/kubeasz] 关于k8s  ipvs报错 (#764)



你最后是怎么处理的啊

**Comment by wangshengjin123** [comment]
只能给虚拟机加配置？
我是有8G有16G的混合起来的集群，服务也没很多，top显示内存10%到80%的都有
我用的1.13.5的版本，之前用了都没啥问题，年后突然就开始出现了，昨天死机了2次要重启解决

**Comment by rhkjyn** [comment]
预留给k8s组件更多资源



---原始邮件---
发件人: "wangshengjin123"<notifications@github.com&gt;
发送时间: 2020年2月13日(周四) 上午10:21
收件人: "easzlab/kubeasz"<kubeasz@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"rhkjyn"<28165136@qq.com&gt;;
主题: Re: [easzlab/kubeasz] 关于k8s  ipvs报错 (#764)



只能给虚拟机加配置？
 我是有8G有16G的混合起来的集群，服务也没很多，top显示内存10%到80%的都有
 我用的1.13.5的版本，之前用了都没啥问题，年后突然就开始出现了，昨天死机了2次要重启解决

**Comment by xiaodu99** [comment]
![Uploading 4cb3b7f3b580c295ebc82df2fc98535b.png…]()
有大佬吗
