### ISSUE TITLE
关于master、node、etcd的NODE_NAME

### ISSUE THREAD

**Issue by baosong818** [easzlab/kubeasz#766]
此项目中只有etcd调用了NODE_NAME，另外两个有机会希望也匹配，毕竟master1/master2/master3和IP相比更好看些，在prometheus里面取出的值也不是双IP，变成了NODE_NAME+IP更好看，美观而已，取舍看工作量了
谢谢

**Comment by gjmzj** [comment]
因为ip不会重复，取名的话可能会重复，还得增加逻辑去判断，暂时先ip吧 :)
