### ISSUE TITLE
Error response from daemon: manifest for easzlab/kubeasz-k8s-bin:v1.15.0 not found [ERROR] Action failed : download_all

### ISSUE THREAD

**Issue by ChinaArJun** [easzlab/kubeasz#767]
Error response from daemon: manifest for easzlab/kubeasz-k8s-bin:v1.15.0 not found
[ERROR] Action failed : download_all

**Comment by gjmzj** [comment]
推荐用k8s某个大版本里面的最新小版本，比如 easzup -k v1.15.5
比如已经出了 k8s v1.15.1 就不要选择 v1.15.0了，毕竟 v1.15.1 是会包含很多 bugfix的
