### ISSUE TITLE
添加etcd节点报错

### ISSUE THREAD

**Issue by 13567436138** [easzlab/kubeasz#770]
TASK [add a new etcd member] *********************************************************************************************************
fatal: [192.168.198.156 -> ]: FAILED! => {"changed": true, "cmd": "ETCDCTL_API=3 /opt/kube/bin/etcdctl member add etcd3 --peer-urls=https://192.168.198.156:2380", "delta": "0:00:05.016003", "end": "2019-12-13 17:27:05.795804", "msg": "non-zero return code", "rc": 1, "start": "2019-12-13 17:27:00.779801", "stderr": "{\"level\":\"warn\",\"ts\":\"2019-12-13T17:27:05.794+0800\",\"caller\":\"clientv3/retry_interceptor.go:61\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-66827770-89f9-4452-b7d8-2d88af3a8e4c/127.0.0.1:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \\\"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\\\"\"}\nError: context deadline exceeded", "stderr_lines": ["{\"level\":\"warn\",\"ts\":\"2019-12-13T17:27:05.794+0800\",\"caller\":\"clientv3/retry_interceptor.go:61\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-66827770-89f9-4452-b7d8-2d88af3a8e4c/127.0.0.1:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \\\"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\\\"\"}", "Error: context deadline exceeded"], "stdout": "", "stdout_lines": []}

**Comment by gjmzj** [comment]
最新master分支有修复过一次，参考 d0c7938a48f414b 和 d28628d87fab6af89c651e38abb1b9989eb27855
