### ISSUE TITLE
安装calico插件，指定CALICO_IPV4POOL_IPIP=off，还是走IPIP模式？

### ISSUE THREAD

**Issue by lichi6174** [easzlab/kubeasz#774]
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.2.254   0.0.0.0         UG    100    0        0 ens160
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.20.32.128   0.0.0.0         255.255.255.192 U     0      0        0 *
172.20.58.192   192.168.2.248   255.255.255.192 UG    0      0        0 tunl0
172.20.85.192   192.168.2.247   255.255.255.192 UG    0      0        0 tunl0
172.20.122.128  192.168.2.246   255.255.255.192 UG    0      0        0 tunl0
172.20.135.128  192.168.2.249   255.255.255.192 UG    0      0        0 tunl0
192.168.2.0     0.0.0.0         255.255.255.0   U     100    0        0 ens160

###
求解，多谢！

**Comment by xieyanker** [comment]
查看`ippool`是否不为`Never`
```shell
calicoctl get ippool -oyaml | grep ipipMode
```
如果不是，则删除该`ippool`，配置`Never`重建即可。
