### ISSUE TITLE
无法备份

### ISSUE THREAD

**Issue by pansx** [easzlab/kubeasz#781]
2.1.0分步骤安装的,每一步都全ok,集群正常,但是备份失败,提示:
fatal: [localhost -> ]: FAILED! => {"changed": true, "cmd": "mkdir -p /etcd_backup && cd /etcd_backup && ETCDCTL_API=3 /opt/kube/bin/etcdctl snapshot save snapshot.db", "delta": "0:00:00.007606", "end": "2019-12-24 14:43:13.279240", "msg": "non-zero return code", "rc": 127, "start": "2019-12-24 14:43:13.271634", "stderr": "/bin/sh: /opt/kube/bin/etcdctl: No such file or directory", "stderr_lines": ["/bin/sh: /opt/kube/bin/etcdctl: No such file or directory"], "stdout": "", "stdout_lines": []}

看上去是etcdctl的,试了试也确实没有安装etcdctl....难不成分步骤安装不会安装这个吗

**Comment by yoli799480165** [comment]
手工添加etcdctl之后，运行到这一步就卡住了。
TASK [make a backup on etcd node]

不提示错误，也不继续或者退出
