### ISSUE TITLE
关于备份脚本问题

### ISSUE THREAD

**Issue by rhkjyn** [easzlab/kubeasz#782]
etcd Version: 3.3.10
------------------------------
changed: [localhost] => {
    "changed": true, 
    "cmd": "for ip in 10.200.0.42 10.200.0.59 10.200.0.46 ;do ETCDCTL_API=3 /etc/ansible/bin/etcdctl --endpoints=https://\"$ip\":2379 --cacert=/etc/ansible/.cluster/ssl/ca.pem --cert=/etc/ansible/.cluster/ssl/admin.pem --key=/etc/ansible/.cluster/ssl/admin-key.pem endpoint health; done", 
    "delta": "0:00:00.061263", 
    "end": "2019-12-24 17:13:24.484578", 
    "invocation": {
        "module_args": {
            "_raw_params": "for ip in 10.200.0.42 10.200.0.59 10.200.0.46 ;do ETCDCTL_API=3 /etc/ansible/bin/etcdctl --endpoints=https://\"$ip\":2379 --cacert=/etc/ansible/.cluster/ssl/ca.pem --cert=/etc/ansible/.cluster/ssl/admin.pem --key=/etc/ansible/.cluster/ssl/admin-key.pem endpoint health; done", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2019-12-24 17:13:24.423315", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "https://10.200.0.42:2379 is healthy: successfully committed proposal: took = 1.826895ms\nhttps://10.200.0.59:2379 is healthy: successfully committed proposal: took = 1.586054ms\nhttps://10.200.0.46:2379 is healthy: successfully committed proposal: took = 1.513956ms", 
    "stdout_lines": [
        "https://10.200.0.42:2379 is healthy: successfully committed proposal: took = 1.826895ms", 
        "https://10.200.0.59:2379 is healthy: successfully committed proposal: took = 1.586054ms", 
        "https://10.200.0.46:2379 is healthy: successfully committed proposal: took = 1.513956ms"
    ]
}
-------------------------------------------

etcd Version: 3.3.15
-------------------------------------------

changed: [localhost] => {
    "changed": true, 
    "cmd": "for ip in 10.201.109.46 10.201.109.22 10.201.109.48 ;do ETCDCTL_API=3 /etc/ansible/bin/etcdctl --endpoints=https://\"$ip\":2379 --cacert=/etc/ansible/.cluster/ssl/ca.pem --cert=/etc/ansible/.cluster/ssl/admin.pem --key=/etc/ansible/.cluster/ssl/admin-key.pem endpoint health; done", 
    "delta": "0:00:00.055840", 
    "end": "2019-12-24 17:12:10.152518", 
    "invocation": {
        "module_args": {
            "_raw_params": "for ip in 10.201.109.46 10.201.109.22 10.201.109.48 ;do ETCDCTL_API=3 /etc/ansible/bin/etcdctl --endpoints=https://\"$ip\":2379 --cacert=/etc/ansible/.cluster/ssl/ca.pem --cert=/etc/ansible/.cluster/ssl/admin.pem --key=/etc/ansible/.cluster/ssl/admin-key.pem endpoint health; done", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2019-12-24 17:12:10.096678", 
    "stderr": "https://10.201.109.46:2379 is healthy: successfully committed proposal: took = 8.651715ms\nhttps://10.201.109.22:2379 is healthy: successfully committed proposal: took = 6.848758ms\nhttps://10.201.109.48:2379 is healthy: successfully committed proposal: took = 6.960027ms", 
    "stderr_lines": [
        "https://10.201.109.46:2379 is healthy: successfully committed proposal: took = 8.651715ms", 
        "https://10.201.109.22:2379 is healthy: successfully committed proposal: took = 6.848758ms", 
        "https://10.201.109.48:2379 is healthy: successfully committed proposal: took = 6.960027ms"
    ], 
    "stdout": "", 
    "stdout_lines": []
}

-------------------------------------------
kubeasz 2.1.0的etcd版版己更新,采用原来的23.backup.yml 备份出错.注意stderr和stdout,改成如下临时解决.
  - name: get a running ectd node
    shell: 'echo -e "{{ ETCD_CLUSTER_STATUS.stdout }} {{ ETCD_CLUSTER_STATUS.stderr }}"|grep "is healthy"|sed -n "1p"|cut -d: -f2|cut -d/ -f3'
    register: RUNNING_NODE

请作者指导优化.谢谢

**Comment by sealandsigh** [comment]
现在确实存在这个问题，按照楼主说的加上{{ ETCD_CLUSTER_STATUS.stderr }} 可以解决。
