### ISSUE TITLE
文档ansible路径拼写错误

### ISSUE THREAD

**Issue by wolfgang1219** [easzlab/kubeasz#788]
https://github.com/easzlab/kubeasz/blob/master/docs/setup/config_guide.md
源路文档为：1 键安装：ansible-playbook /etc/ansilbe/90.setup.yml
实际路径为： /etc/ansible/90.setup.yml
请把ansilbe改为ansible。
请问是否支持ipv6。
最后为这个项目点赞。

**Comment by gjmzj** [comment]
ipv6应该还没支持，k8s社区也才刚刚开始支持
