### ISSUE TITLE
关于easz 2.X的master高可用疑问

### ISSUE THREAD

**Issue by wangshengjin123** [easzlab/kubeasz#790]
这个版本的我是第一次试用
这个2.x架构，文档说现在master本身是高可用的

我线下环境，我按照文档提供的方案进行安装，凭借经验快速的安装完成了，没有选择ex-lb选项
NAME          STATUS                                  ROLES    AGE     VERSION
172.17.0.68   Ready                                    node     3h22m   v1.15.0
172.17.0.69   Ready,SchedulingDisabled   master   3h23m   v1.15.0
172.17.0.73   Ready,SchedulingDisabled   master   3h23m   v1.15.0

对dashboard：
只有2个master可以访问到dashboard，node不行
对tomcat：
3个ip+nodeport都可以访问

然后我对一个master-172.17.0.69关机操作
此时只有1个master提供dashboard访问了，172.17.0.69并不能访问dashboard，也不能访问tomcat

现在vip也没有了，单master ip访问集群还是存在单点故障

---是我对2.x版本的高可用理解有问题吗

---或者是说，我必须在外部搭建一个ha+keepalive  来代理这2个master？ ex-lb必须安装么；

麻烦大大看到回复下，看到的朋友看到也说说撒。。

**Comment by xin053** [comment]
https://github.com/easzlab/kubeasz/issues/585#issuecomment-502948966
