### ISSUE TITLE
关于dashboard安装并部署、透传代理建议

### ISSUE THREAD

**Issue by baosong818** [easzlab/kubeasz#793]
我已经研究这个项目两个月了，从最开始的适配到现在的深入开发小功能，因为代码改的地方太多太多了，是在无法跟您这个合并了。但也有些建议望采纳
现在说的就是databoard.test.com这个demo，此文件完全可以更改为j2格式，并将host: databoard.test.com变量化，变量在ansible/hosts去定义，我觉得大多数使用者还是部署完会连带部署databoard，但次次都要去手改这个配置文件再继续，有点累赘了，不如来个08.databoard.yml或者其他的配置文件连带部署了

**Comment by gjmzj** [comment]
dashboard 确实是自动安装了的，只不过用ingress方式去暴露dashboard服务“dashboard.test.com”；这个暂时写在文档中 manifests/ingress/traefik/tls/k8s-dashboard.ing.yaml
