### ISSUE TITLE
Containerd already installed!

### ISSUE THREAD

**Issue by huangxuwen** [easzlab/kubeasz#797]
单机部署k8s出现docker已经安装的错误
TASK [docker : fail info1] *********************************************************************************************************************************************************************************
fatal: [192.168.65.169]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}

PLAY RECAP *************************************************************************************************************************************************************************************************
192.168.65.169             : ok=36   changed=11   unreachable=0    failed=1   
localhost                  : ok=20   changed=12   unreachable=0    failed=0   

[ERROR] Action failed : start-aio

**Comment by gjmzj** [comment]
systemctl status containerd 看看，机器是不是装过其他部署工具

**Comment by shadowedge** [comment]
事先安装过docker的机器貌似都不行，必须卸载了安装这个containerd

**Comment by huaihuai0406** [comment]
移除  /lib/systemd/system/containerd.service
systemctl daemon-reload
