### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by getoutout** [easzlab/kubeasz#800]
k8s节点名，使用主机名，然后配置本地hosts解析，不直接使用ip地址，用主机名容易区分一些特殊节点，例如ingress-node,只运行k8s集群负载，es,prometheus等组件，不运行应用pod，实际使用中，ip也不便记忆，用来区分节点。当然这只是个人建议，,源于红帽的openshift，ansible部署。不修改也不是什么大问题。☺
hosts文件
###########################################################################
###########################################################################
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
lb
masters
etcd
nodes

[lb]
master.ocp311.com 

[masters]
# master3.ocp311.com 
# master2.ocp311.com 
master.ocp311.com 

[etcd]
master.ocp311.com 
#master3.ocp311.com 
#master2.ocp311.com

[nodes]
## These are the masters
master.ocp311.com openshift_node_group_name='node-config-master'

## These are infranodes
infranode1.ocp311.com openshift_node_group_name='node-config-infra'

## These are regular nodes
node1.ocp311.com openshift_node_group_name='node-config-compute'
node2.ocp311.com openshift_node_group_name='node-config-compute'

**Comment by gjmzj** [comment]
建议不错；
项目中需要修改的地方有很多，暂时不修改，后续有更强需求的时候再说😄
至于node的不同角色可以用 label 来区分；

**Comment by piano-wow** [comment]
要是可以使用主机名,确实改动挺大的.
听楼主的吧,label

**Comment by imluyuan** [comment]
哈哈哈，强迫症犯了，不用主机名难受。。。

**Comment by piano-wow** [comment]
这是来自QQ邮箱的自动回复邮件。来信已收到！
