### ISSUE TITLE
证书过期求助

### ISSUE THREAD

**Issue by yexingqi** [easzlab/kubeasz#805]
k8s 旧的版本1.8.4. 运行一年后发现所有的node节点变成noready了。 
查了一下logs也是提示证书过期，想请问一下具体应该怎么更新证收呢？ 感谢不尽！！

logs:
authentication.go:64] Unable to authenticate the request due to an error: x509: certificate has expired 

我查到有这样的一些指示：
“一年后集群需要重新删除证书文件和kubelet.config，然后重新进行kubectl certificate approve xxx”
请问具体到哪里删除一个证书呢？ 进行kubectl certificate approve xxx指的又是什么呢？ 谢谢！

**Comment by evenye** [comment]
在node节点上运行以下更新成功了.  但我还不知道master上的三台ETCD是不是也需要更新?
还请指点一下，谢谢！

cd /etc/kubernetes/
mkdir backup
mv kubelet.kubeconfig backup/
cd ssl/
mv kubelet* ../backup/
systemctl restart kubelet.service
kubectl get csr
kubectl certificate approve node-xxxx
kubectl get node

**Comment by gjmzj** [comment]
etcd 只要重新运行下 ansible-playbook 02.etcd.yml

**Comment by evenye** [comment]
> 
> 
> etcd 只要重新运行下 ansible-playbook 02.etcd.yml

谢谢，请问怎么确认这个etcd的证书被更新成功了呢？

**Comment by gjmzj** [comment]
cfssl-certinfo -cert /etc/etcd/ssl/etcd.pem
可以看到证书的生效时间

**Comment by wangshengjin123** [comment]
以前用1.10的时候出现过证书的问题，当时是替换证书ok，后来线上也上了一套，现在不确认是基于那个分支的了，早于还是晚于0.3.1，也不确认会不会出现证书过期问题 @gjmzj 
主版本是v1.13.5，这个版本ok么
