### ISSUE TITLE
kubectl cluster-info 不能获取Prometheus

### ISSUE THREAD

**Issue by zhuozl** [easzlab/kubeasz#806]
已经为 prometheus 的service 设置  kubernetes.io/cluster-service=true。

[root@xxxx    xx]# kubectl cluster-info
Kubernetes master is running at https://192.168.xxx.xxx:6443
Elasticsearch is running at https://192.168.xxx.xxx:6443/api/v1/namespaces/kube-system/services/elasticsearch-logging/proxy
Kibana is running at https://192.168.xxx.xxx:6443/api/v1/namespaces/kube-system/services/kibana-logging/proxy
CoreDNS is running at https://192.168.xxx.xxx:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://192.168.xxx.xxx:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
Metrics-server is running at https://192.168.xxx.xxx:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

**Comment by gjmzj** [comment]
@zhuozl 已经为 prometheus 的service 设置 kubernetes.io/cluster-service=true。
是要在对应 service 里面加

**Comment by zhuozl** [comment]
> prometheus

1. 我是想开放monitor-prometheus-server, 让 kubectl cluster-info 能查询到，直接用proxy 方式可以直接通过k8s api接口进行调用

2. 全文搜索了kubernetes.io/cluster-service=true。未看到prometheus 有相关的设置。查看了prometheus 下面的 server-service.yaml文件也未有 kubernetes.io/cluster-service=true的配置。

3. 修改了monitor-prometheus-server 添加kubernetes.io/cluster-service=true 无效


```
[root@pto-cluster-dev-2 ~]# kubectl get svc monitor-prometheus-server -o yaml -n monitoring
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-14T06:50:04Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: prometheus
    chart: prometheus-9.3.1
    component: server
    heritage: Tiller
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Prometheus
    release: monitor
  name: monitor-prometheus-server
  namespace: monitoring
  resourceVersion: "8648027"
  selfLink: /api/v1/namespaces/monitoring/services/monitor-prometheus-server
  uid: e12192b3-7f63-4810-8374-d57d26aeaad7
spec:
  clusterIP: 10.68.228.0
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: monitor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by zhuozl** [comment]
> @zhuozl 已经为 prometheus 的service 设置 kubernetes.io/cluster-service=true。
> 是要在对应 service 里面加


1. 我是想开放monitor-prometheus-server, 让 kubectl cluster-info 能查询到，直接用proxy 方式可以直接通过k8s api接口进行调用

2. 全文搜索了kubernetes.io/cluster-service=true。未看到prometheus 有相关的设置。查看了prometheus 下面的 server-service.yaml文件也未有 kubernetes.io/cluster-service=true的配置。

3. 修改了monitor-prometheus-server 添加kubernetes.io/cluster-service=true 无效


```
[root@pto-cluster-dev-2 ~]# kubectl get svc monitor-prometheus-server -o yaml -n monitoring
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-14T06:50:04Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: prometheus
    chart: prometheus-9.3.1
    component: server
    heritage: Tiller
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Prometheus
    release: monitor
  name: monitor-prometheus-server
  namespace: monitoring
  resourceVersion: "8648027"
  selfLink: /api/v1/namespaces/monitoring/services/monitor-prometheus-server
  uid: e12192b3-7f63-4810-8374-d57d26aeaad7
spec:
  clusterIP: 10.68.228.0
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: monitor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
