### ISSUE TITLE
traefik 如何处理跨域问题 

### ISSUE THREAD

**Issue by jiangzhikele** [easzlab/kubeasz#808]
之前使用的docker部署nginx做的跨域处理
现在k8s使用了traefik  找不到如何配置跨域
请求帮助

**Comment by gjmzj** [comment]
利用nginx做跨域处理其实不是一个好的方法，因为增加部署复杂度；最好通过程序自己处理；
比如java/go都有成熟的模块/组件处理跨域问题；
所以我认为尽量不要再去研究traefik怎么处理跨域；
参考下这个 https://www.cnblogs.com/heioray/p/9403246.html
