### ISSUE TITLE
想请教现在如何批量增加节点？

### ISSUE THREAD

**Issue by farmerluo** [easzlab/kubeasz#813]
在以前是很快的多节点可以同时增加（通过addnode.yml），现在好像只能通过easzctl一台一台的增加节点了。

**Comment by gjmzj** [comment]
确实是，
暂时只能手动搞一下
1. 手动修改下 /etc/ansible/hosts ，新建一个组叫做[new-node]，然后一次性把要加的节点都加进[kube-node]组和[new-node]组
2. 修改下 tools/02.addnode.yml 开头，
```
- hosts:
  - new-node
  roles:
  - { role: chrony, when: "groups['chrony']|length > 0" }
  - prepare
```
3. 执行`/etc/ansible/tools/02.addnode.yml` 即可

**Comment by edenlong2006** [comment]
1. 手动修改下 /etc/ansible/hosts ，新建一个组叫做[new-node]，然后一次性把要加的节点都加进[kube-node]组和[new-node]组
2. 修改/etc/ansible/tools/easzctl 文件中add-node 函数
`function add-node() {

    groupname=$1
    ips=$(ansible $groupname --list-hosts | sed '1d')

    for ip in $ips
    do
        # check new node's address regexp
        [[ $ip =~ ^(2(5[0-5]{1}|[0-4][0-9]{1})|[0-1]?[0-9]{1,2})(\.(2(5[0-5]{1}|[0-4][0-9]{1})|[0-1]?[0-9]{1,2})){3}$ ]] || { echo "[ERROR] Invalid ip address!"; return 1; }
        # check if the new node already exsited
        sed -n '/^\[kube-master/,/^\[harbor/p' $BASEPATH/hosts|grep "^${ip}[^0-9]*$" && { echo "[ERROR] node $ip already existed!"; return 2; }
    done

    # add a node into 'kube-node' group
    for ip in $ips
    do
        sed -i "/\[kube-node/a $ip NEW_NODE=yes ${@:2}" $BASEPATH/hosts
    done

    # check if playbook runs successfully
    ansible-playbook $BASEPATH/tools/02.addnode.yml -e NODE_TO_ADD=$groupname || { for ip in $ips; do sed -i "/$ip NEW_NODE=yes/d" $BASEPATH/hosts; done; return 2; }

    # save current cluster context if needed
    [ -f "$BASEPATH/.cluster/current_cluster" ] && save_context
    return 0
}`
3、通过以下命令批量添加节点
tools/easzctl add-node new-node
