### ISSUE TITLE
关于cgroup 泄露问题

### ISSUE THREAD

**Issue by autherlj** [easzlab/kubeasz#815]
k8s version： 1.15.0
centos 7.3 内核3.10.0-514.10.1.el7.x86_64
产生的问题:
![Inked微信图片_20200306111427_LI](https://user-images.githubusercontent.com/30717333/76047148-eb926c00-5f9c-11ea-9e03-1166a7ffb624.jpg)

问题原因可能是kmem accounting 对3.x的内核支持不够好，然又是默认开启的。参考：https://www.bookstack.cn/read/kubernetes-practice-guide/troubleshooting-summary-cgroup-leaking.md

建议：我们是直接用的bin下的k8s二进制包，能否有更好的方式关闭kmem accounting？

**Comment by gjmzj** [comment]
看了这个问题详情，感觉最方便就是升级内核啊，4.15 以上😄
二进制包，按照描述需要重新编译，如果你自己已经编译了，那么替换bin目录下就行了

**Comment by kenwoodjw** [comment]
kmem accouting 升级内核才能解决，试过centos7.5自己编译kubelet关闭kmem accouting ，有的容器生效有的不生效。runc的话docker 版本18.09以上已经默认关闭了kmem accouting。
