### ISSUE TITLE
安装harbor 1.9.4，出现这种错误Destination /etc/cloud/templates/hosts.redhat.tmpl does not exist !

### ISSUE THREAD

**Issue by ZPJeck** [easzlab/kubeasz#820]
我是用的是centos7的镜像，安装harbor 1.9.4出现错误：
Destination /etc/cloud/templates/hosts.redhat.tmpl does not exist !
大佬们。有没有遇到这种错误的，请求讲解下。谢谢

**Comment by NIUYULEE** [comment]
同样在1.10.2版本也出现了同样的问题，同样希望有解决方法

**Comment by uuwang** [comment]
这是一个可选的步骤，错误并不会带安装造成影响，原因是针对启动 cloud-init 的虚拟机hosts文件的修改，本来可以忽略的。解决方法：
1）不用理会，（无功能影响）
2）删除 11.harbor.yml 81行后面的代码
后续我会提交一个新pr做一下自动检测
