### ISSUE TITLE
项目中Prometheus的deployment和daemonset文件修改

### ISSUE THREAD

**Issue by zhaohui-1986** [easzlab/kubeasz#825]
helm安装Prometheus，需要修改manifests/prometheus/prometheus/templates中的deployment和daemonset文件，添加selector.matchLabels内容，需要和template.labels对应。

**Comment by gjmzj** [comment]
prometheus 确实有段时间没更新了，可以参考这个 https://github.com/coreos/kube-prometheus

**Comment by godsend1024** [comment]
> 
> 
> helm安装Prometheus，需要修改manifests/prometheus/prometheus/templates中的deployment和daemonset文件，添加selector.matchLabels内容，需要和template.labels对应。

补充一下：manifests/prometheus/prometheus/templates中所有的deployment和daemonset文件中，添加spec.selector.matchLabels内容,需要和当前文件下方的spec.template.metadate.labels内容一致。

**Comment by DanceKiddle** [comment]
添加selector后，按目前文档安装，显示所有pod正常运行，仍然无法通过http://$NodeIP:39000访问，有谁遇到过吗？
