### ISSUE TITLE
centos7 AllinOne部署，ssh UNREACHABLE

### ISSUE THREAD

**Issue by zzq392342084** [easzlab/kubeasz#826]
已配置ssh免登陆：
`[root@cup-xtbgcsdb ~]# ssh 192.168.197.21`
`Last login: Wed Apr  8 13:51:39 2020 from 192.168.197.21`
`[root@cup-xtbgcsdb ~]# exit`
`logout`
`Connection to 192.168.197.21 closed.`

`TASK [Gathering Facts] *****************************************************************************
fatal: [192.168.197.21]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"192.168.197.21\". Make sure this host can be reached over ssh", "unreachable": true}

PLAY RECAP *****************************************************************************************
192.168.197.21             : ok=0    changed=0    unreachable=1    failed=0 `

**Comment by LibraDuck** [comment]
今天也遇到同样的问题，正在查找解决方法。

**Comment by zzq392342084** [comment]
找到办法后，分享下，谢谢~~

**Comment by xiaopohou** [comment]
我也遇到这个问题了，问题解决了吗？哥们
