### ISSUE TITLE
多MASTER集群安装完后，不正常

### ISSUE THREAD

**Issue by yananshiwo** [easzlab/kubeasz#829]
kubeasz 2.0.3安装多节点：配置文件如下
# master node(s)
[kube-master]
10.1.200.185
10.1.200.186
10.1.200.187

# work node(s)
[kube-node]
10.1.200.188

# [optional] harbor server, a private docker registry
# 'NEW_INSTALL': 'yes' to install a harbor server; 'no' to integrate with existed one
[harbor]
#192.168.1.8 HARBOR_DOMAIN="harbor.yourdomain.com" NEW_INSTALL=no

# [optional] loadbalance for accessing k8s from outside
[ex-lb]
10.1.200.185 LB_ROLE=master EX_APISERVER_VIP=10.1.200.183 EX_APISERVER_PORT=8443
10.1.200.186 LB_ROLE=backup EX_APISERVER_VIP=10.1.200.183 EX_APISERVER_PORT=8443
10.1.200.187 LB_ROLE=backup EX_APISERVER_VIP=10.1.200.183 EX_APISERVER_PORT=8443

安装完了，查看集群信息
kubectl cluster-info
Kubernetes master is running at https://10.1.200.185:6443
CoreDNS is running at https://10.1.200.185:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://10.1.200.185:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
Metrics-server is running at https://10.1.200.185:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

显示的不是VIP地址，这个是什么问题啊

**Comment by gjmzj** [comment]
EX_APISERVER_VIP=10.1.200.183 是给集群外部负载均衡用的，集群内部master高可用不是依赖这个；详见https://github.com/easzlab/kubeasz/blob/master/docs/setup/00-planning_and_overall_intro.md#ha-architecture
