### ISSUE TITLE
kubeconfig未起作用

### ISSUE THREAD

**Issue by asdlif** [easzlab/kubeasz#830]
您好：
部署环境：AllinOne部署
版本：
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

问题：
发现删除了.kube/config，重启了机器，仍然能正常使用kubectl获得各种权限，这个本机器认证是没经过kubeconfig吗？

**Comment by gjmzj** [comment]
`netstat -antlp|grep 8080`
看下，老版本k8s默认在本机监听非认证端口；
kubectl 默认也是连接 127.0.0.1:8080 端口

**Comment by asdlif** [comment]
您好：
[root@mykube ~]# netstat -antlp|grep 8080|grep LISTEN
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      6713/kube-apiserver 
的确是有这个端口监听，如果修改呢？
