### ISSUE TITLE
按照教程安装efk报错

### ISSUE THREAD

**Issue by linorwang** [easzlab/kubeasz#831]
kubeasz版本2.2.0，按照教程安装efk报错，其中elasticsearch一直在PodInitializing，kibana一直在ContainerCreating，详情请看图片，提示镜像拉起中。请教下如何解决呢？
![TIM截图20200419222828](https://user-images.githubusercontent.com/23013733/79690634-ef98f580-828d-11ea-8234-de46158203b2.png)
![TIM截图20200419222841](https://user-images.githubusercontent.com/23013733/79690636-f32c7c80-828d-11ea-96af-1596d51faea1.png)
![TIM截图20200419223133](https://user-images.githubusercontent.com/23013733/79690637-f4f64000-828d-11ea-8d0c-94e2e6b23fae.png)

**Comment by gjmzj** [comment]
这个日志看不出啥问题，只是显示还在拉取镜像；es本身镜像体积较大，目前注意修改下docker镜像加速配置，azure中国的加速不能用了

**Comment by gjmzj** [comment]
如果镜像拉取完了，还是显示错误，那用 kubectl describe / kubectl logs 看看具体的信息
