### ISSUE TITLE
安装子节点后出现网络问题

### ISSUE THREAD

**Issue by wmabcde** [easzlab/kubeasz#836]
1，通过all-in-one方式安装单机版（172.20.32.234）
2，运用kubeasz的 easzctl add-node 172.20.32.196安装子节点
操作系统类型和版本:CentOS Linux release 7.6.1810 (Core) 4.4.220-1.el7.elrepo.x86_64

3.1，kubectl top node命令无法查看子节点数据
[root@goodrain ~]# kubectl top node
NAME            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
172.20.32.234   1026m        6%     23960Mi         60%
172.20.32.196   unknown     unknown      unknown     unknown
3.2，metrics-server日志如下：
E0506 10:01:05.801199 1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:01:35.814806 1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:02:05.801373 1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:02:35.801090 1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:03:05.846686 1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:03:35.801106 1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:04:02.437850 1 reststorage.go:135] unable to fetch node metrics for node "172.20.32.196": no metrics known for node
E0506 10:04:03.493452 1 reststorage.go:135] unable to fetch node metrics for node "172.20.32.196": no metrics known for node

**Comment by weilinqwe** [comment]
是不是单机版的缘故？

**Comment by wmabcde** [comment]
> 是不是单机版的缘故？

不知道啊。难道需要一次性安装成功吗？

**Comment by weilinqwe** [comment]
https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true    直接访问试试看，是不是网不通？

**Comment by wmabcde** [comment]
> https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true 直接访问试试看，是不是网不通？
> telnet 172.20.32.196 10250试试看 ，这个应该是kubelet开的端口

主节点下是通的：
[root@goodrain ~]# telnet 172.20.32.196 10250
Trying 172.20.32.196...
Connected to 172.20.32.196.
Escape character is '^]'.

主节点的容器内部是不通的：

[root@goodrain ~]# kubectl exec -it rbd-api-75c6d89bb8-4g2dg /bin/bash -n rbd-system
bash-4.3# telnet 172.20.32.196 10250

**Comment by weilinqwe** [comment]
那可以排查一下K8s网络组件，flannel/calico之类的

**Comment by wmabcde** [comment]
> 那可以排查一下K8s网络组件，flannel/calico之类的

能帮忙看一下吗？
主节点：
[root@goodrain ~]# ip route
default via 172.20.32.254 dev ens160 proto static metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
172.20.0.0/24 dev cni0 proto kernel scope link src 172.20.0.1
172.20.3.0/24 via 172.20.3.0 dev flannel.1 onlink
172.20.32.0/24 dev ens160 proto kernel scope link src 172.20.32.234 metric 100

子节点：
[root@localhost ~]# ip route
default via 172.20.32.254 dev ens192 proto static metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.20.0.0/24 via 172.20.0.0 dev flannel.1 onlink
172.20.1.0/24 dev cni0 proto kernel scope link src 172.20.1.1 linkdown
172.20.32.0/24 dev ens192 proto kernel scope link src 172.20.32.196 metric 100

**Comment by weilinqwe** [comment]
我觉得是不是可能pod网段和node网段都是172.20.0.0的子网段有关，不知道对不对
既然node ip是172.20.的子网段，cluster CIDR需要换一下，比如172.30.0.0/16
# Cluster CIDR (Pod CIDR), not overlap with node(host) networking
CLUSTER_CIDR="172.20.0.0/16"

另外iptables有没有限制

**Comment by wmabcde** [comment]
> 我觉得是不是可能pod网段和node网段都是172.20.0.0的子网段有关，不知道对不对
> 既然node ip是172.20.的子网段，cluster CIDR需要换一下，比如172.30.0.0/16
> 
> ```
> # Cluster CIDR (Pod CIDR), not overlap with node(host) networking
> CLUSTER_CIDR="172.20.0.0/16"
> ```
> 
> 另外iptables有没有限制

你说得对，后来我把这个cluster cidr网段避开了就好了。感谢！
