### ISSUE TITLE
how to add etcd monitoring in prometheus

### ISSUE THREAD

**Issue by MaPing01** [easzlab/kubeasz#838]

**Comment by ndaysy** [comment]
`apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: etcd

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-metrics
    port: 2379
    protocol: TCP
    targetPort: 2379

---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: kube-system
subsets:
- addresses:
  - ip: 132.0.0.1
  - ip: 132.0.0.2
  - ip: 132.0.0.3
  ports:
  - name: https-metrics
    port: 2379
    protocol: TCP
`

**Comment by ndaysy** [comment]
[http://www.ksky.net/archives/107](url)
