### ISSUE TITLE
扩增公网节点到内网集群中

### ISSUE THREAD

**Issue by zhbitzwz** [easzlab/kubeasz#843]
假如内网私有网段里已经搭建好k8s集群，有没有什么方法可以把公网节点添加到集群里，内网机器有公网ip可以作端口映射，请问有什么方案吗？

**Comment by zhiyue** [comment]
先自己组个内网吧。。tinc 或者 nebula

**Comment by zhbitzwz** [comment]
> 先自己组个内网吧。。tinc 或者 nebula

请问用了tinc，双网卡怎么作路由配置呢？
