### ISSUE TITLE
kubelet无法启动

### ISSUE THREAD

**Issue by BlueSky15171** [easzlab/kubeasz#847]
ansible-playbook 04.kube-master.yml 

[root@master01 ~]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 六 2020-05-23 00:53:53 CST; 2s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 37653 ExecStart=/opt/kube/bin/kubelet --config=/var/lib/kubelet/config.yaml --cni-bin-dir=/opt/kube/bin --cni-conf-dir=/etc/cni/net.d --hostname-override=172.16.57.150 --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --network-plugin=cni --pod-infra-container-image=easzlab/pause-amd64:3.2 --root-dir=/var/lib/kubelet --v=2 (code=exited, status=1/FAILURE)
  Process: 37651 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/pids/system.slice/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 37648 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/memory/system.slice/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 37644 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/hugetlb/system.slice/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 37643 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/cpuset/system.slice/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 37637 ExecStartPre=/bin/mount -o remount,rw /sys/fs/cgroup (code=exited, status=0/SUCCESS)
 Main PID: 37653 (code=exited, status=1/FAILURE)

5月 23 00:53:53 master01 kubelet[37653]: --proxy-port-range port-range                  Range of host ports (...osen.
5月 23 00:53:53 master01 kubelet[37653]: --show-hidden-metrics-for-version string       The previous version for w...
5月 23 00:53:53 master01 kubelet[37653]: --skip-headers                                 If true, avoid header...sages
5月 23 00:53:53 master01 kubelet[37653]: --skip-log-headers                             If true, avoid header...files
5月 23 00:53:53 master01 kubelet[37653]: --stderrthreshold severity                     logs at or above this...lt 2)
5月 23 00:53:53 master01 kubelet[37653]: --udp-timeout duration                         How long an idle UDP ...50ms)
5月 23 00:53:53 master01 kubelet[37653]: -v, --v Level                                      number for the lo...osity
5月 23 00:53:53 master01 kubelet[37653]: --version version[=true]                       Print version informa... quit
5月 23 00:53:53 master01 kubelet[37653]: --vmodule moduleSpec                           comma-separated list ...gging
5月 23 00:53:53 master01 kubelet[37653]: --write-config-to string                       If set, write the def...exit.
Hint: Some lines were ellipsized, use -l to show in full.

请问怎么排查？

**Comment by gjmzj** [comment]
日志打得详细些，修改/etc/systemd/system/kubelet.service 文件里面--v=2 改成 --v=4；然后 
```
systemctl daemon-reload
systemctl restart kubelet
```
用 journalctl -u kubelet -f 查看日志
