### ISSUE TITLE
异常：转换docker版本信息为浮点数

### ISSUE THREAD

**Issue by Edisonboy** [easzlab/kubeasz#851]
![image](https://user-images.githubusercontent.com/19949495/83322996-3ff07380-a28e-11ea-9fe5-28a133fed09e.png)

**Comment by gxjluck** [comment]
我也是遇到同样的问题。求解！

**Comment by gjmzj** [comment]
能不能写下复现的步骤，我来看看

**Comment by gxjluck** [comment]
环境配置参照：https://github.com/easzlab/kubeasz/blob/master/docs/setup/00-planning_and_overall_intro.md

# 这里我用的是最新的2.2.1的release
export release=2.2.1
curl -C- -fLO --retry 3 https://github.com/easzlab/kubeasz/releases/download/${release}/easzup
chmod +x ./easzup

# 使用工具脚本下载
./easzup -D

//以上步骤执行正常，所有文件和镜像都下载成功。
执行 ansible-playbook 90.setup.yml 就出现下面问题。
![image](https://user-images.githubusercontent.com/4863433/83323809-bd6ab280-a293-11ea-8434-716c73ef4acf.png)

**Comment by Edisonboy** [comment]
按照 [单机快速体验k8s集群的测试环境--AllinOne部署](https://github.com/easzlab/kubeasz/blob/master/docs/setup/quickStart.md)

执行 docker exec -it kubeasz easzctl start-aio

后会报这个错误

docker版本是：Docker version 19.03.6, build 369ce74a3c

**Comment by gjmzj** [comment]
在 roles/docker/tasks/main.yml 中插入如下调试信息，然后再执行看看
```
# 18.09.x 版本二进制名字有变化，需要做判断
- name: 获取docker版本信息
  shell: "{{ base_dir }}/bin/dockerd --version|cut -d' ' -f3"
  register: docker_ver
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: debug info
  debug: var="docker_ver"
  tags: upgrade_docker, download_docker
```

**Comment by Edisonboy** [comment]
你是指这个吗
![image](https://user-images.githubusercontent.com/19949495/83324140-b644a400-a295-11ea-9a43-d8ae5b45543f.png)

**Comment by gjmzj** [comment]
在上面也再多加一个debug

**Comment by Mikedu1988** [comment]
同样的问题。。。非常痛苦

**Comment by Edisonboy** [comment]
@gjmzj 加上debug日志后打印这个
![image](https://user-images.githubusercontent.com/19949495/83324743-fad23e80-a299-11ea-8b6c-52a31d10a73a.png)

**Comment by gjmzj** [comment]
是不是两位的机器上本身已经安装过docker，不是使用easzup安装的

**Comment by Edisonboy** [comment]
@gjmzj 嗯是的，机器已经安装过docker

**Comment by gjmzj** [comment]
问题很清楚是 /etc/ansible/bin目录下没有 dockerd 二进制；重新执行一遍 `easzup -D` 就好了

**Comment by Mikedu1988** [comment]
全新机器安装，之前也没有装过docker，但是跑起来还是有问题。
跑之前，检查dockerd版本，正常：
![image](https://user-images.githubusercontent.com/24424690/83473279-c4740980-a4bb-11ea-84a5-1084979cdc0f.png)
后来去检查了一下目录，bin目录确实被清空了，重新跑了-D是解决了。但是可能需要检查一下为什么这个目录被清空了。

**Comment by Mikedu1988** [comment]
版本2.0.X似乎没有这个问题。

**Comment by gjmzj** [comment]
> 全新机器安装，之前也没有装过docker，但是跑起来还是有问题。
> 跑之前，检查dockerd版本，正常：
> ![image](https://user-images.githubusercontent.com/24424690/83473279-c4740980-a4bb-11ea-84a5-1084979cdc0f.png)
> 后来去检查了一下目录，bin目录确实被清空了，重新跑了-D是解决了。但是可能需要检查一下为什么这个目录被清空了。

已经找到原因，是easzup启动脚本有点小问题，master分支已经修复
