### ISSUE TITLE
[ kubectl: command not found ] 

### ISSUE THREAD

**Issue by Zhang-BigSmart** [easzlab/kubeasz#852]
按照单机部署方式 [单机快速体验k8s集群的测试环境--AllinOne部署](url)

在第4步验证安装 执行 **kubectl version** 后提示 **kubectl: command not found**

**Comment by gjmzj** [comment]
可能环境变量没有生效，执行 `source /root/.bashrc`

**Comment by jinwandalaohu** [comment]
同样的问题
/root/.kube 为空。
/root/.bashrc 没有关于kubectl的配置。
环境为 centos7.7  VMware的虚拟机，使用root用户。

**Comment by MapleMart** [comment]
执行 source /root/.bashrc
也是不行

**Comment by MapleMart** [comment]
@gjmzj 
执行 source /root/.bashrc 后还是不行

**Comment by andrew2558** [comment]
我的也是，我是按照 https://github.com/easzlab/kubeasz/blob/master/docs/setup/quickStart.md
这个文档操作完成，最后使用`kubectl version`显示 `kubectl: command not found`

**Comment by andrew2558** [comment]
我使用`sudo -s`，切换成root用户后，再执行`source /etc/bash.bashrc`后，就可以使用`kubectl version`命令了。但是退出后，使用普通用户还是不行
