### ISSUE TITLE
集群中有pod pending的情况下 easzctl add-node 导致 mynet0和cni0同时存在

### ISSUE THREAD

**Issue by sunnoy** [easzlab/kubeasz#853]
1、 使用 easzctl add-node 在原有的集群上添加node的时候会在新的node上添加 mynet0 网卡
2、该网卡会添加pod网段路由
3、导致从原来的node上去连接新的node上的pod不通，问题出在新加node上的mynet创建的路由

**Comment by gjmzj** [comment]
- 添加 mynet0 网卡是在kubelet启动时候做 `roles/kube-node/tasks/main.yml`
- 当开始安装真正网络插件flannel/calico 时候会删除这个配置，详见`roles/flannel/tasks/main.yml`

是不是添加node时没有跑完网络插件相关任务

**Comment by sunnoy** [comment]
具体的触发场景是这样的：

1、集群中有pending状态的pod
2、此时进行了添加node操作
3、task中的
https://github.com/easzlab/kubeasz/blob/4110515bb6b0c1e3c2a47d8f2fab7fdef175c715/roles/kube-node/tasks/main.yml#L34
会指定mynet0网卡
4、kubelet启动的时候会检查cni的配置文件，因为配置了3中配置了这个文件，因此kubelet会启动完成，状态为 ready
5、一旦node为ready了，pod就会调度到该新加的node上
6、随着新加node上的容器启动 mynet0 自动创建了（**新加的node上面没有pod的话是不会创建网桥的**）
7、接着是flannel的安装，以及删除原来的cni配置文件
https://github.com/easzlab/kubeasz/blob/4110515bb6b0c1e3c2a47d8f2fab7fdef175c715/roles/flannel/tasks/main.yml#L64
8、等到flannel安装完成后，后面来的pod就会跟着创建cni0的虚拟网卡
9、此时新加的node上存在两个网卡 mynet0和cni0

----------------------

如何解决？

1、在node安装的时候不去复制cni的配置文件
2、下面这个task删掉
https://github.com/easzlab/kubeasz/blob/4110515bb6b0c1e3c2a47d8f2fab7fdef175c715/roles/kube-node/tasks/main.yml#L34
3、因为没有cni的配置文件，kubelet会报错启动失败，此时node 状态为notready，pod不会调度过来
```bash
kubelet[6674]: E0602 16:20:47.143960    6674 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
4、随着安装的进行，原来的flannel的daemonsets资源会在还没有ready的node上进行创建pod，接着flannel就会创建cni配置文件在 /etc/cni/net.d 里面
5、一旦cni配置文件在 /etc/cni/net.d创建文件，kubelet就会启动成功
6、正在pending的pod就会过来，然后创建cni0
7、由于需要等待flannel启动因此下面的等待时间需要延长
https://github.com/easzlab/kubeasz/blob/4110515bb6b0c1e3c2a47d8f2fab7fdef175c715/roles/kube-node/tasks/main.yml#L92
经测试，在线安装的情况下需要接近一分钟的时间。

----------
这中场景正常情况下的缺不一定遇到。。。

**Comment by gjmzj** [comment]
写得很详细，这种情况下能否手工介入处理下
1. 首先删除错误使用mynet0网络的pod，自动重建后应该会使用cni0网络
2. 然后手工删除 `ip link del mynet0`

**Comment by sunnoy** [comment]
pending的情况下，批量集群扩容的时候手动介入不是很好，会导致很多服务的重启
