### ISSUE TITLE
卸载问题

### ISSUE THREAD

**Issue by DanceKiddle** [easzlab/kubeasz#857]
使用同一个deploy节点安装了两个不同环境的集群，配置分别保存ansible1和ansible2中。
先安装的ansible1后安装的ansible2，两个集群各节点ip都不同。
结果在cd到ansible1中使用ansible-playbook 99.clean.yml时，发现卸载的是ansible2安装的集群。
就是说不管在哪个目录下执行clean，总是会卸载最新安装的集群。

不知道该怎么让ansible卸载第一次安装的集群？

**Comment by DanceKiddle** [comment]
ansible-playbook默认读取/etc/ansible/文件夹下的hosts，改下目录就好了

**Comment by longshilei** [comment]
每天都收到好多这种邮件， 怎么取消接收邮件啊？
大佬们有知道的嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"西流"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 下午4:23
收件人:&nbsp;"easzlab/kubeasz"<kubeasz@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [easzlab/kubeasz] 卸载问题 (#857)





 
ansible-playbook默认读取/etc/ansible/文件夹下的hosts，改下目录就好了

**Comment by DanceKiddle** [comment]
> 每天都收到好多这种邮件， 怎么取消接收邮件啊？ 大佬们有知道的嘛？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"西流"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月8日(星期一) 下午4:23 收件人:&nbsp;"easzlab/kubeasz"<kubeasz@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [easzlab/kubeasz] 卸载问题 (#857) ansible-playbook默认读取/etc/ansible/文件夹下的hosts，改下目录就好了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

自己查下github取消订阅设置下就好了

**Comment by weilinqwe** [comment]
Unwatch就可以
