### ISSUE TITLE
是否考虑过支持Harbor 2.0

### ISSUE THREAD

**Issue by baosong818** [easzlab/kubeasz#858]
主要私人需求，我在大佬代码基础上改写了兼容arm64（飞腾银河、中标麒麟）之前告知过
需求来了，镜像仓库支持多架构镜像的功能，查到2.0可以支持，可否推进下，万分感谢

**Comment by gjmzj** [comment]
安装harbor 2.0 可以参考官网吧，这块应该不复杂，至于要不要集成到kubeasz中自动安装，主要现在精力投入不太够😄

**Comment by baosong818** [comment]
谢谢了，已经搭建完成了
docker buildx build --platform linux/amd64,linux/arm64 -t harbor.bochtec.com/test/tiller --push . 但这个命令失败了，哎
