### ISSUE TITLE
FLANNEL_SUBNET 被重写

### ISSUE THREAD

**Issue by lizhongyi2008** [easzlab/kubeasz#859]
![image](https://user-images.githubusercontent.com/15866669/84125229-d4b55700-aa6e-11ea-8ee6-8c28a0a42dd4.png)
![image](https://user-images.githubusercontent.com/15866669/84125285-ebf44480-aa6e-11ea-8c8f-c6c3ab5d306b.png)
[root@fy8-238 etcd]#  /opt/etcd/etcdctl get /coreos.com/network/config
{"Network": "172.7.0.0/16", "Backend": {"Type": "host-gw"}}
哪位大佬指教下，我原来设置是Subnets 172.7.238.1/24,但是被reusing成172.7.99.1/24

**Comment by gjmzj** [comment]
没法单节点指定flannel subnets的吧，这块是整体设置一个大的网段，比如 172.17.0.0/16；然后在安装集群时每个节点会动态生成一个子网段
