### ISSUE TITLE
SSH Error: data could not be sent to remote host

### ISSUE THREAD

**Issue by lookbackagain** [easzlab/kubeasz#864]
docker exec -it kubeasz easzctl start-aio
[INFO] Action: start an AllInOne cluster : start-aio
[WARN] aio is already the current context

[INFO] setup cluster with context: aio
[INFO] setup begin in 5s, press any key to abort
:

PLAY [kube-master,kube-node,etcd,ex-lb,chrony] *************************************************************************

TASK [Gathering Facts] *************************************************************************************************
fatal: [172.16.0.14]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"172.16.0.14\". Make sure this host can be reached over ssh", "unreachable": true}

PLAY RECAP *************************************************************************************************************
172.16.0.14                : ok=0    changed=0    unreachable=1    failed=0

[ERROR] Action failed : start-aio

已配置ssh免登陆：ssh root@123.207.XXX.XX

CentOS Linux release 7.7.1908 (Core)

**Comment by gjmzj** [comment]
ssh root@172.16.0.14  可以免密码登陆吗？
