### ISSUE TITLE
CentOS 7安装K8s遇到SSH Error: data could not be sent to remote host 错误

### ISSUE THREAD

**Issue by zgjlxy** [easzlab/kubeasz#866]
之前用过ubuntu安装过k8s, 但这次因为某些原因要在内核为CentOS7的某国产系统搭建k8s
在docker exec -it kubeasz easzctl start-aio 这步遇到了
···
{"changed": false, "msg": "SSH Error: data could not be sent to remote host \"192.168.163.139\". Make sure this host can be reached over ssh", "unreachable": true}
···

在 /etc/ssh/sshd_config 中将PermitRootLogin 设置为yes
systemctl stop firewalld.service 关闭了防火墙
export ANSIBLE_SCP_IF_SSH=y 设置环境变量
/etc/ansible/ansible.cfg 将scp_if_ssh = True
ssh-keygen 的root用户免密登入也设置好了

在容器内部使用SSH命令可以免密登入到对应地址
目前一直卡在这一步
求助

**Comment by dhdh-lulu** [comment]
我也是，可以看看~/.ssh/authorized_keys里边的主机名是否正确，有可能是默认的localhost

**Comment by stone4774** [comment]
同样遇到该问题，centos7.7，执行ansible xxxx -m ping失败，调试发现ssh容器ip时直接被refused； @dhdh-lulu 容器内部没有~/.ssh/authorized_keys文件，容器宿主机中该文件里面是宿主机的hostname

**Comment by stone4774** [comment]
换成一个干净的centos7之后没出现该问题；之前的机器安装过openshift，将openshift干掉后直接使用easzup安装k8s会出现上述问题
