### ISSUE TITLE
默认配置的问题疑问？

### ISSUE THREAD

**Issue by han13579** [easzlab/kubeasz#867]
我有一次用helm更新一个应用的时候后，发现大量pod处于ContainerCreating状态。原因是我刚才更新服务的时候，kubelet一直在拉取镜像，这个镜像下载很慢，然后其他镜像拉取一直处于等待状态。kubelet有一个参数--serialize-image-pulls，默认是true。有没有考虑将这个参数默认改成false呢？

**Comment by gjmzj** [comment]
--serialize-image-pulls
--
  | Pull images one at a time. We recommend *not* changing the default value on nodes that run docker daemon with version < 1.9 or an Aufs storage backend. Issue #10959 has more details. (default true)

**Comment by han13579** [comment]
这个我有看到，你的这个工具支持的最低k8s版本是1.15的版本，docker支持的版本高于1.9。aufs的存储的问题的话，在工具支持的系统版本中，基本已经默认使用overlay2了。应该不用太考虑这个支持的问题。

**Comment by gjmzj** [comment]
> 这个我有看到，你的这个工具支持的最低k8s版本是1.15的版本，docker支持的版本高于1.9。aufs的存储的问题的话，在工具支持的系统版本中，基本已经默认使用overlay2了。应该不用太考虑这个支持的问题。

嗯，下一版本我把它优化进去
