### ISSUE TITLE
The connection to the server localhost:8080 was refused

### ISSUE THREAD

**Issue by oneslideicywater** [easzlab/kubeasz#868]
The connection to the server localhost:8080 was refused - did you specify the right host or port?

单机版应该是`/etc/kubernetes/admin.conf`缺失，我找不到这个文件，没办法复制到我的用户目录`.kube`,请问这个怎么解决？

**Comment by gjmzj** [comment]
集群安装完都自动复制的，不需要手动；

**Comment by GaiserChen** [comment]
我也出现这个问题，有解决方案吗

**Comment by LuoShiXi** [comment]
同问

**Comment by XinePan** [comment]
同问

**Comment by drepig** [comment]
注意切换到root下

**Comment by drepig** [comment]
> 
linux下的配置文件在/root/.kube/config下

**Comment by angusjch** [comment]
看看是不是以前安装过，环境变量没有清除
