### ISSUE TITLE
大哥你的华为云镜像仓库是不是挂了？

### ISSUE THREAD

**Issue by johntsu** [easzlab/kubeasz#871]
执行  docker exec -it kubeasz easzctl start-aio 这条命令后，最后报错如下
fatal: [192.168.200.120]: FAILED! => {"changed": false, "msg": "http://mirrors.huaweicloud.com/centos/7.6.1810/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found\nTrying other mirror.\nTo address this issue please refer to the below knowledge base article \n\nhttps://access.redhat.com/articles/1320623\n\n
……

大哥你的华为云镜像仓库是不是挂了？

**Comment by medzeus2** [comment]
版本升级了，你用最新的centos。
