### ISSUE TITLE
helm install jenkins error

### ISSUE THREAD

**Issue by luanweijie** [easzlab/kubeasz#874]
文中建议用helm3，但是安装Jenkins的文档还是helm2，报一下错误
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
[root@bogon jenkins]#  unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by sivasubramanian95** [comment]
I guess the `**apiVersion** `for deployment mismatch. Did you give a try with ``**apps/v1**``

Cheers!!
