### ISSUE TITLE
deploy : 生成 CA 证书和私钥 cfssl: cannot execute binary file

### ISSUE THREAD

**Issue by wangzy0327** [easzlab/kubeasz#880]
"cmd": "cd /etc/kubernetes/ssl && /opt/kube/bin/cfssl gencert -initca ca-csr.json | /opt/kube/bin/cfssljson -bare ca", "delta": "0:00:00.1
21045", "end": "2020-07-20 08:37:59.503470", "msg": "non-zero return code", "rc": 126, "start": "2020-07-20 08:37:59.382425", "stderr": "/bin/sh: /opt/kube/bin/cfssl: cannot execute binary file\n/bin/sh: /opt/kube/bin/cfssljson: cannot execute binary file"

**Comment by Cole-GG** [comment]
我也报这个错误好像是在bin下面没有cfssl执行文件
