### ISSUE TITLE
执行docker exec -it kubeasz easzctl start-aio 出现错误

### ISSUE THREAD

**Issue by huowolf** [easzlab/kubeasz#882]
TASK [prepare : 分发证书工具 CFSSL] ***************************************************************************************
failed: [10.0.3.15] (item=cfssl) => {"changed": false, "checksum": "889d87f6814fbe8d6985713aca35e3be4c632afd", "expected_checksum": "93c040caed4a4d89eb9935ce8a0f6efb876c9b52", "item": "cfssl", "msg": "Copied file does not match the expected checksum. Transfer failed."}
ok: [10.0.3.15] => (item=cfssl-certinfo)
failed: [10.0.3.15] (item=cfssljson) => {"changed": false, "checksum": "d852c18c7fcebad1e21706cde7e3a9ef335448cc", "expected_checksum": "a9766e7eef71a39a5d2ca94061c8a6004fcdd524", "item": "cfssljson", "msg": "Copied file does not match the expected checksum. Transfer failed."}

PLAY RECAP **********************************************************************************************************
10.0.3.15                  : ok=21   changed=5    unreachable=0    failed=1   
localhost                  : ok=32   changed=22   unreachable=0    failed=0   

[ERROR] Action failed : start-aio
thanks~~~

**Comment by zhangyuming** [comment]
我也碰到同样的问题， 发现是 同一个文件 的sha1 值两次获取的不一样导致的， 但是为什么同一个文件两次sha1 值不一样，到现在我也不知道， 求解
