### ISSUE TITLE
安装 mster 和node报错An unhandled exception occurred while templating '{{ SERVICE_CIDR | ipaddr('net') | ipaddr(2) | ipaddr('address') 

### ISSUE THREAD

**Issue by xmtao0805** [easzlab/kubeasz#886]
fatal: [192.168.100.200]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ SERVICE_CIDR | ipaddr('net') | ipaddr(2) | ipaddr('address') }}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: The ipaddr filter requires python's netaddr be installed on the ansible controller"}

后来在hosts中添加 这两个参数就好了，
CLUSTER_DNS_SVC_IP=
CLUSTER_KUBERNETES_SVC_IP

这个是什么问题呢？ netaddr 我也装了啊

**Comment by pretendfine** [comment]
参考 废弃ansible hosts中变量CLUSTER_DNS_SVC_IP等
https://github.com/easzlab/kubeasz/commit/813db54a2f95db81b401ca8f76e4ce877cb06318
我是照着这个改的

**Comment by pretendfine** [comment]
装插件的时候又报这个错了，用楼主的方法搞定了
