### ISSUE TITLE
GPU node 配置

### ISSUE THREAD

**Issue by lsy643** [easzlab/kubeasz#89]
我做了基于device plugin 配置GPU node 的实验， 可以提交一个PR 吗？
涉及到以下几个方面：
1. 在[kube-proxy.service.j2](https://github.com/gjmzj/kubeasz/blob/master/roles/kube-node/templates/kube-proxy.service.j2)中，添加`--feature-gates="DevicePlugins=true"`

1. 需要安装nvidia driver

1. 比较麻烦的一点是，nvidia-docker 安装过程中对docker的版本要求比较奇怪，必须是各个版本的最新稳定版。在使用您提供的离线安装包之后，必须要手动更新docker才能完成nvidia-docker的安装。

**Comment by peterpijing** [comment]
@lsy643 @gjmzj  强烈推荐gpu的部署

**Comment by gjmzj** [comment]
欢迎提交PR，对于docker版本，我可以单独出离线安装包更新

**Comment by peterpijing** [comment]
如果是gpu node.只需要执行 ansible-playbook 21.gpunode.yml 就好了么？@lsy643 @gjmzj

**Comment by peterpijing** [comment]
只支持ubuntu?

- name: 下载nvidia driver安装包
  copy: src={{ base_dir }}/bin/nvidia-diag-driver-local-repo.deb dest=/tmp/nvidia-diag-driver-local-repo.deb
  when: ansible_distribution == "Ubuntu"

- name: 安装nvidia dirver驱动
  apt:
    deb: /tmp/nvidia-diag-driver-local-repo.deb
  when: ansible_distribution == "Ubuntu"

- name: Add the package repositories 1
  shell: curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -
  when: ansible_distribution == "Ubuntu"

- name: Add the package repositories 2
  shell: curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list
  when: ansible_distribution == "Ubuntu"

**Comment by lsy643** [comment]
@peterpijing 
在配置好hosts的前提下，执行`ansible-playbook 21.gpunode.yml `就可以了。

目前只支持ubuntu，但如果有其他操作系统的需要，稍作修改就可以了，这部分主要是安装驱动和nvidia docker2.0

**Comment by gjmzj** [comment]
@lsy643 我想稍微改动下你的提交，尽量避免对不使用`gpu node`用户的影响

**Comment by lsy643** [comment]
@gjmzj 
好的哈，没有问题

**Comment by xiongraorao** [comment]
请问下NVIDIA-docker的部署文件现在更新过来了吗

**Comment by patterson163** [comment]
@lsy643 麻烦问下gpu的yaml文件我找不到,请问在哪里可以找到呢?多谢多谢
