### ISSUE TITLE
离线部署

### ISSUE THREAD

**Issue by jinyaoqun** [easzlab/kubeasz#894]
在离线部署的时候运行 ./easzup -S
ssh文件生成好像失败
[INFO] generate ssh key pair
getaddrinfo lo:: Name or service not known

后面再安装集群时也会失败
*
fatal: [192.168.1.1]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"192.168.1.1\". Make sure this host can be reached over ssh", "unreachable": true}

**Comment by kenwoodjw** [comment]
容器有启动吗？

**Comment by jinyaoqun** [comment]
有启动的
