### ISSUE TITLE
etcd endpoint health check默认输出到stderr而不是stdout中，导致backup失败

### ISSUE THREAD

**Issue by plantegg** [easzlab/kubeasz#899]
原因： etcd issue： https://github.com/etcd-io/etcd/pull/11322/files/e48ad568b9e0ad9d3fbcecb82bf77998b19f6499

错误现象：   ansible-playbook /etc/ansible/23.backup.yml -v

TASK [get etcd cluster status] *****************************************************************
changed: [localhost] => {"changed": true, "cmd": "for ip in 192.168.0.97 192.168.0.98 192.168.0.99 ;do ETCDCTL_API=3 /etc/ansible/bin/etcdctl --endpoints=https://\"$ip\":2379 --cacert=/etc/ansible/.cluster/ssl/ca.pem --cert=/etc/ansible/.cluster/ssl/admin.pem --key=/etc/ansible/.cluster/ssl/admin-key.pem endpoint health; done", "delta": "0:00:00.628634", "end": "2020-09-04 03:14:05.382175", "rc": 0, "start": "2020-09-04 03:14:04.753541", "stderr": "https://192.168.0.97:2379 is healthy: successfully committed proposal: took = 7.63227ms\nhttps://192.168.0.98:2379 is healthy: successfully committed proposal: took = 7.258602ms\nhttps://192.168.0.99:2379 is healthy: successfully committed proposal: took = 7.682486ms", "stderr_lines": ["https://192.168.0.97:2379 is healthy: successfully committed proposal: took = 7.63227ms", "https://192.168.0.98:2379 is healthy: successfully committed proposal: took = 7.258602ms", "https://192.168.0.99:2379 is healthy: successfully committed proposal: took = 7.682486ms"], "stdout": "", "stdout_lines": []}

TASK [debug] ***********************************************************************************
ok: [localhost] => {
    "ETCD_CLUSTER_STATUS.stdout": ""
}

TASK [get a running ectd node] *****************************************************************
changed: [localhost] => {"changed": true, "cmd": "echo -e \"\"|grep \"is healthy\"|sed -n \"1p\"|cut -d: -f2|cut -d/ -f3", "delta": "0:00:00.572500", "end": "2020-09-04 03:14:06.174758", "rc": 0, "start": "2020-09-04 03:14:05.602258", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [debug] ***********************************************************************************
ok: [localhost] => {
    "RUNNING_NODE.stdout": ""
}

TASK [make a backup on etcd node] **************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"127.0.0.1\". Make sure this host can be reached over ssh", "unreachable": true}

PLAY RECAP *************************************************************************************
localhost                  : ok=6    changed=2    unreachable=1    failed=0

**Comment by gjmzj** [comment]
已修复
