### ISSUE TITLE
运行04.kube-master.yml 出现问题

### ISSUE THREAD

**Issue by jeffzhao99** [easzlab/kubeasz#910]
使用host_allinone 部署单机版，版本2.2.1， 前面步骤都还正常，但是运行 04.kube-master.yml ,出现下面错误：
TASK [kube-master : 替换 kubeconfig 的 apiserver 地址] ***********************************************************************************************************************
ok: [192.168.6.221] => (item=/root/.kube/config)
failed: [192.168.6.221] (item=/etc/kubernetes/kube-controller-manager.kubeconfig) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/kubernetes/kube-controller-manager.kubeconfig", "msg": "Destination /etc/kubernetes/kube-controller-manager.kubeconfig does not exist !", "rc": 257}
failed: [192.168.6.221] (item=/etc/kubernetes/kube-scheduler.kubeconfig) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/kubernetes/kube-scheduler.kubeconfig", "msg": "Destination /etc/kubernetes/kube-scheduler.kubeconfig does not exist !", "rc": 257}

host 使用的example目录的host_allinone文件，请问什么原因？

**Comment by playsoysauce** [comment]
"msg": "Destination /etc/kubernetes/kube-scheduler.kubeconfig does not exist !"
/etc/kubernetes/kube-scheduler.kubeconfig这个文件不存在

**Comment by Huweicai** [comment]
> host 使用的example目录的host_allinone文件，请问什么原因？

请问后面解决了吗，我也遇到了同样的问题

**Comment by Huweicai** [comment]
@jeffzhao99
