### ISSUE TITLE
kubernetes-dashboard提示Unauthorized

### ISSUE THREAD

**Issue by evenye** [easzlab/kubeasz#913]
kubeasz版本2.2.1 ，全新安装。 没有错误logs，能查到pods运行状态和token，但是直接访问kubectl cluster-info的地址不能打开。 

kubernetes-dashboard is running at https://10.10.10.161:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

直接提示下述错误：
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

请问我还需要额外修改什么配置吗？ 谢谢！

**Comment by evenye** [comment]
直接用node + 端口是可以访问的。 问题是为啥用cluster VIP的IP不能访问呢？ 怎么修复这个问题呀？

**Comment by evenye** [comment]
close 
kubeasz 1.0.0以后使用 easzctl basic-auth -s 开启

**Comment by evenye** [comment]
kubeasz 1.0.0以后使用 easzctl basic-auth -s 开启

**Comment by godsend1024** [comment]
> kubeasz 1.0.0以后使用easzctl basic-auth -s开启

无效呢，使用命令开启后还是401
