### ISSUE TITLE
Helm安装报错

### ISSUE THREAD

**Issue by evenye** [easzlab/kubeasz#914]
ansible-playbook /etc/ansible/roles/helm/helm.yml

请问以下问题怎么检查处理呢？ 谢谢！！

TASK [helm : 安装tiller] **************************************************************************************************************************************************
fatal: [10.10.10.161]: FAILED! => {"changed": true, "cmd": "/opt/kube/bin/helm init --history-max 5 --tiller-tls --tiller-tls-verify --tiller-tls-cert /etc/kubernetes/ssl/tiller001.pem --tiller-tls-key /etc/kubernetes/ssl/tiller001-key.pem --tls-ca-cert /etc/kubernetes/ssl/ca.pem --service-account tiller --tiller-namespace kube-system --tiller-image easzlab/tiller:v2.14.1 --stable-repo-url https://kubernetes-charts.storage.googleapis.com --upgrade", "delta": "0:00:00.091347", "end": "2020-09-24 11:34:05.016252", "msg": "non-zero return code", "rc": 1, "start": "2020-09-24 11:34:04.924905", "stderr": "Error: unknown command \"init\" for \"helm\"\n\nDid you mean this?\n\tlint\n\nRun 'helm --help' for usage.", "stderr_lines": ["Error: unknown command \"init\" for \"helm\"", "", "Did you mean this?", "\tlint", "", "Run 'helm --help' for usage."], "stdout": "", "stdout_lines": []}
...ignoring

TASK [helm : 配置helm客户端] *************************************************************************************************************************************************
fatal: [10.10.10.161]: FAILED! => {"changed": true, "cmd": "cp -f /etc/kubernetes/ssl/ca.pem ~/.helm/ca.pem && cp -f /etc/kubernetes/ssl/helm001.pem ~/.helm/cert.pem && cp -f /etc/kubernetes/ssl/helm001-key.pem ~/.helm/key.pem", "delta": "0:00:00.006310", "end": "2020-09-24 11:34:05.512444", "msg": "non-zero return code", "rc": 1, "start": "2020-09-24 11:34:05.506134", "stderr": "cp: cannot create regular file '/root/.helm/ca.pem': No such file or directory", "stderr_lines": ["cp: cannot create regular file '/root/.helm/ca.pem': No such file or directory"], "stdout": "", "stdout_lines": []}
...ignoring

**Comment by evenye** [comment]
cat /etc/ansible/roles/helm/helm.yml             
- hosts: "{{ groups['kube-master'][0] }}"
  roles:
  - helm

cat /etc/ansible/roles/helm/defaults/main.yml
helm_namespace: kube-system 
helm_cert_cn: helm001
tiller_sa: tiller
tiller_cert_cn: tiller001
tiller_image: easzlab/tiller:v2.14.1
repo_url: https://kubernetes-charts.storage.googleapis.com
history_max: 5
# 如果默认官方repo 网络访问不稳定可以使用如下的阿里云镜像repo
#repo_url: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts

**Comment by gjmzj** [comment]
helm 安装的role，需要修改了，现在不建议使用 helm v2版本，安装helm v3版本更加简单了
