### ISSUE TITLE
dashboard访问报401

### ISSUE THREAD

**Issue by ZQHcode** [easzlab/kubeasz#920]
按照安装步骤操作，通过浏览器访问服务器的地址，出现401
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

**Comment by godsend1024** [comment]
Kibana也是如此，只要是经过api代理的路径全部都是401。我的集群版本是v1.20.1

**Comment by jacky-neo** [comment]
新版kubeasz 通过NodePort访问dashboard. 而不是用kubectl cluster-info里看到的连接来访问了。可通过如下命令来查看nodePort
```
# 查看dashboard service
kubectl get svc -n kube-system|grep dashboard
kubernetes-dashboard   NodePort    10.68.219.38   <none>        443:24108/TCP                   53s
```
 然后在浏览器输入https://[node-ip]:24108即可
