### ISSUE TITLE
efk日志时区问题

### ISSUE THREAD

**Issue by zjcnew** [easzlab/kubeasz#921]
存储在es中的每天被分割成一个index，容器默认使用utc时区，第二天了发现还是只有前一天的索引，怎么解决？
![企业微信截图_20200930113747](https://user-images.githubusercontent.com/22335594/94640461-62180200-0311-11eb-8dae-b535cb5bebf7.png)

**Comment by easoncon** [comment]
我也是按照教程安装的，没有这个index的错误，但是我的EFK运行一段时间之后会没有日志输出了，找了很多文章也没发现问题，请问你的EFK会出现这个问题吗？我的解决方法是重启fluentd，然后就有新的日志了

**Comment by zjcnew** [comment]
> 我也是按照教程安装的，没有这个index的错误，但是我的EFK运行一段时间之后会没有日志输出了，找了很多文章也没发现问题，请问你的EFK会出现这个问题吗？我的解决方法是重启fluentd，然后就有新的日志了

我没有你这种问题，我是直接没有日志。重建了很多次问题依旧
