### ISSUE TITLE
 ansible-playbook 04.kube-master.yml  时报错

### ISSUE THREAD

**Issue by itswl** [easzlab/kubeasz#923]
TASK [kube-node : 开启kube-proxy 服务] ******************************************************************************************************************************
changed: [192.168.43.101]
FAILED - RETRYING: 轮询等待kubelet启动 (8 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (7 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (6 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (5 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (4 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (3 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (2 retries left).
FAILED - RETRYING: 轮询等待kubelet启动 (1 retries left).

TASK [kube-node : 轮询等待kubelet启动] ********************************************************************************************************************************
fatal: [192.168.43.101]: FAILED! => {"attempts": 8, "changed": true, "cmd": "systemctl status kubelet.service|grep Active", "delta": "0:00:00.015436", "end": "2020-10-09 21:14:35.571584", "rc": 0, "start": "2020-10-09 21:14:35.556148", "stderr": "", "stderr_lines": [], "stdout": "   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-10-09 21:14:33 CST; 2s ago", "stdout_lines": ["   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-10-09 21:14:33 CST; 2s ago"]}

PLAY RECAP ******************************************************************************************************************************************************
192.168.43.101             : ok=32   changed=16   unreachable=0    failed=1    skipped=27   rescued=0    ignored=0

**Comment by easoncon** [comment]
这是我的解决方法
kubelet启动失败，报错：

10月 11 20:05:18 server03 kubelet[15984]: error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"
10月 11 20:05:18 server03 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
10月 11 20:05:18 server03 systemd[1]: Unit kubelet.service entered failed state.
10月 11 20:05:18 server03 systemd[1]: kubelet.service failed.
解决方法如下：https://blog.csdn.net/qijian2003122/article/details/83021091

如果启动脚本中没有指定Cgroup，请修改daemon.json

可以看下主机上kubelet的报错，然后在一步步解决
