### ISSUE TITLE
在OpenStack的虚拟机装k8s集群，无法Harbor上传镜像文件，怀疑是MTU参数引起的问题

### ISSUE THREAD

**Issue by pkvov** [easzlab/kubeasz#927]
在OpenStack的虚拟机装k8s集群，无法上传镜像文件到Harbor，文件上传不报错，但是在Harbor Web UI 中，看到镜像大小为0，
怀疑是MTU参数引起的, 如何修改集群的MTU参数，比如docker0 的mtu参数

**Comment by pkvov** [comment]
kubeasz/roles/docker/files/docker
这里面有 --mtu的参数，但是不知道如何修改成具体的值

**Comment by yotoobo** [comment]
修改 roles/docker/templates/daemon.json.j2 , 新增配置, 值的话根据实际环境自定义. 
![image](https://user-images.githubusercontent.com/5196242/102630421-7e487400-4187-11eb-9875-b7053caf39dd.png)
