### ISSUE TITLE
dashboard的pod都是在running状态，但是确无法访问到dashboard页面

### ISSUE THREAD

**Issue by wushuaiping** [easzlab/kubeasz#931]
状态正常：
![image](https://user-images.githubusercontent.com/26813459/97276145-c9be6000-1871-11eb-9aab-11e93af2db25.png)
本地访问：
![image](https://user-images.githubusercontent.com/26813459/97276210-dba00300-1871-11eb-8a26-e2d530b09f5d.png)

**Comment by alinuxsa** [comment]
确认一下svc是否是NodePort,然后通过NodePort访问

**Comment by lwnmengjing** [comment]
我也遇到这个问题，是指标监控访问不了，流量进不来，部署有问题
