### ISSUE TITLE
The ipaddr filter requires python-netaddr be installed on the ansible controller

### ISSUE THREAD

**Issue by H121** [easzlab/kubeasz#938]
![image](https://user-images.githubusercontent.com/58348609/98951476-40778080-2535-11eb-8267-0024c42f7fc1.png)
请问有人遇到这个问题吗

**Comment by pretendfine** [comment]
fatal: [192.168.1.100]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: {{ SERVICE_CIDR | ipaddr('net') | ipaddr(1) | ipaddr('address') }}: The ipaddr filter requires python-netaddr be installed on the ansible controller"}

需要安装 python-netaddr，安装命令pip install netaddr

安装pip

 

  wget https://bootstrap.pypa.io/get-pip.py

    python get-pip.py

**Comment by H121** [comment]
> fatal: [192.168.1.100]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: {{ SERVICE_CIDR | ipaddr('net') | ipaddr(1) | ipaddr('address') }}: The ipaddr filter requires python-netaddr be installed on the ansible controller"}
> 
> 需要安装 python-netaddr，安装命令pip install netaddr
> 
> 安装pip
> 
> wget https://bootstrap.pypa.io/get-pip.py
> 
> ```
> python get-pip.py 
> ```

No，I installed it. This is what I am confused about

**Comment by david0718** [comment]
我也遇到了，郁闷。

**Comment by the-elder** [comment]
> > fatal: [192.168.1.100]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: {{ SERVICE_CIDR | ipaddr('net') | ipaddr(1) | ipaddr('address') }}: The ipaddr filter requires python-netaddr be installed on the ansible controller"}
> > 需要安装 python-netaddr，安装命令pip install netaddr
> > 安装pip
> > wget https://bootstrap.pypa.io/get-pip.py
> > ```
> > python get-pip.py 
> > ```
> 
> No，I installed it. This is what I am confused about

check your python(pip)  version，ansible may use the wrong Python interpreter
