### ISSUE TITLE
2.2.1 easzup离线下载脚本存在问题

### ISSUE THREAD

**Issue by jr19825** [easzlab/kubeasz#940]
readhat7操作系统下, 
使用2.2.1easzup -D 下载文件提示错误. 
Unit docker.service could not be found.
[INFO] generate docker service file
[INFO] generate docker config file
[INFO] prepare register mirror for CN
[INFO] turn off selinux in CentOS/Redhat
Disabled
[INFO] enable and start docker
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /etc/systemd/system/docker.service.
[WARN] kubeasz already existed
[INFO] downloading kubernetes v1.18.3 binaries
v1.18.3: Pulling from easzlab/kubeasz-k8s-bin
31603596830f: Pull complete 
92d77e68b815: Pull complete 
Digest: sha256:fc6b09bfa6ddc47c99de504fba19b5ae0f77b45e528e978309b117bdb402a3ee
Status: Downloaded newer image for easzlab/kubeasz-k8s-bin:v1.18.3
docker.io/easzlab/kubeasz-k8s-bin:v1.18.3
[INFO] run a temporary container
3263602c39150eb2814b9e4762fb703f7213ff1713bcec8933891016916c4d3b
[INFO] cp k8s binaries
[INFO] stop&remove temporary container
temp_k8s_bin
[INFO] downloading extral binaries kubeasz-ext-bin:0.5.2
0.5.2: Pulling from easzlab/kubeasz-ext-bin
31603596830f: Already exists 
7df813a7df18: Pull complete 
Digest: sha256:57a2f8d8a085cbb1510c5325579fd1d42bf1608130c81581adddc6fa567cf770
Status: Downloaded newer image for easzlab/kubeasz-ext-bin:0.5.2
docker.io/easzlab/kubeasz-ext-bin:0.5.2
[INFO] run a temporary container
8269609f77ce8338282d271e318119390dfee7cf2609f76f5c00e6a6868ddede
[INFO] cp extral binaries
[INFO] stop&remove temporary container
temp_ext_bin
[INFO] downloading Containerd binaries 1.2.6
[INFO] downloading containerd binaries 1.2.6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53.6M  100 53.6M    0     0  6413k      0  0:00:08  0:00:08 --:--:-- 9072k
/bin/cp: cannot stat ‘/etc/ansible/down/containerd/usr/local/bin/containerd-shim-runc-v2’: No such file or directory
[ERROR] Action failed : download_all
vi 了该文件确认代码写的就是 /etc/ansible/down/containerd/usr/local/bin/containerd-shim-runc-v2 这个是不是少了空格之类的,

**Comment by gjmzj** [comment]
默认下载的containerd包中没有 containerd-shim-runc-v2  这个文件，已更新；

不建议使用master分支代码，使用release的版本
