### ISSUE TITLE
2.2.2版本异常

### ISSUE THREAD

**Issue by taoshanghu** [easzlab/kubeasz#943]
安装docker时，查看下载的docker压缩包，解压后得到如下文件：
-rwxr-xr-x 1 yguser yguser 36781096 9月  17 01:05 containerd
-rwxr-xr-x 1 yguser yguser  7172096 9月  17 01:05 containerd-shim
-rwxr-xr-x 1 yguser yguser 19152872 9月  17 01:05 ctr
-rwxr-xr-x 1 yguser yguser 61125298 9月  17 01:05 docker
-rwxr-xr-x 1 yguser yguser 68887544 9月  17 01:05 dockerd
-rwxr-xr-x 1 yguser yguser   708616 9月  17 01:05 docker-init
-rwxr-xr-x 1 yguser yguser  2928566 9月  17 01:05 docker-proxy
-rwxr-xr-x 1 yguser yguser  9600824 9月  17 01:05 runc

但是脚本会检查以下文件到检查失败
 with_items:
      - docker-containerd
      - docker-containerd-shim
      - docker-init
      - docker-runc
      - docker
      - docker-containerd-ctr
      - dockerd
      - docker-proxy

**Comment by gjmzj** [comment]
你的docker 版本选了哪个？

**Comment by gjmzj** [comment]
- name: 下载 docker 二进制文件
      copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
      - docker-containerd
      - docker-containerd-shim
      - docker-init
      - docker-runc
      - docker
      - docker-containerd-ctr
      - dockerd
      - docker-proxy
      tags: upgrade_docker, download_docker
      when: "DOCKER_VER|float < 18.09"

    - name: 下载 docker 二进制文件(>= 18.09.x)
      copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
      - containerd
      - containerd-shim
      - docker-init
      - runc
      - docker
      - ctr
      - dockerd
      - docker-proxy
      tags: upgrade_docker, download_docker
      when: "DOCKER_VER|float >= 18.09"
