### ISSUE TITLE
kubeasz-2.2.2 单机版安装后报错

### ISSUE THREAD

**Issue by piano-wow** [easzlab/kubeasz#944]
采用的是单机离线安装k8s
安装完成后检查：
1. k8s服务正常
2. 可以部署简单的服务
3. docker 和 kube-apiserver 有报错，报错如下

问题：
这两个组件的这个问题，会影响生产环境的稳定吗？如果没影响，我就忽略了。
再次感谢楼主坚持更新，造福运维。

![image](https://user-images.githubusercontent.com/35907674/100607932-a130f680-3346-11eb-9555-6fba6f8dab84.png)

journalctl -f -u docker.service
-- Logs begin at 一 2020-11-30 14:49:38 CST. --
11月 30 14:53:14 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
11月 30 14:53:14 localhost.localdomain dockerd[1364]: time="2020-11-30T14:53:14.317388280+08:00" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
11月 30 14:53:14 localhost.localdomain dockerd[1364]: time="2020-11-30T14:53:14.371783495+08:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
11月 30 14:53:14 localhost.localdomain dockerd[1364]: time="2020-11-30T14:53:14.376461982+08:00" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
11月 30 14:53:14 localhost.localdomain systemd[1]: Started Docker Application Container Engine.

journalctl -f -u kube-apiserver.service
11月 30 20:00:16 localhost.localdomain kube-apiserver[1440]: I1130 20:00:16.451968    1440 client.go:360] parsed scheme: "passthrough"
11月 30 20:00:16 localhost.localdomain kube-apiserver[1440]: I1130 20:00:16.452036    1440 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://192.168.123.20:2379  <nil> 0 <nil>}] <nil> <nil>}
11月 30 20:00:16 localhost.localdomain kube-apiserver[1440]: I1130 20:00:16.452056    1440 clientconn.go:948] ClientConn switching balancer to "pick_first"
11月 30 20:00:16 localhost.localdomain kube-apiserver[1440]: I1130 20:00:16.452207    1440 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00f811de0, {CONNECTING <nil>}
11月 30 20:00:16 localhost.localdomain kube-apiserver[1440]: I1130 20:00:16.461681    1440 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00f811de0, {READY <nil>}
11月 30 20:00:16 localhost.localdomain kube-apiserver[1440]: I1130 20:00:16.462677    1440 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"

[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
[root@localhost ~]# kubectl get componentstatuses
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE             ERROR
scheduler            Healthy   ok
controller-manager   Healthy   ok
etcd-0               Healthy   {"health":"true"}

**Comment by piano-wow** [comment]
尝试安装三节点的集群版本，依旧是上面的报错；
尝试升级etcd为3.4.13，依旧是上面的报错；

**Comment by gjmzj** [comment]
这两个日志报错可以忽略；
apiserver 的报错可以看这个issue：https://github.com/kubernetes/kubernetes/issues/83938
