### ISSUE TITLE
希望增加对CentOS 8的支持

### ISSUE THREAD

**Issue by piano-wow** [easzlab/kubeasz#946]
1. K8s已经声明：“Kubernetes 1.20 版本开始将弃用 Docker，是时候拥抱 Containerd 和 Podman 了！”；
2. 国内主流云服务厂商的云服务器也已经支持“CentOS 8“了。

在2021年，kubeasz有希望支持CentOS 8吗？
如果需要测试样本，可以在微信群内发公测帖，我们也能尽一份微薄之力。
![image](https://user-images.githubusercontent.com/35907674/101112738-f73cbd00-3618-11eb-886e-cd1cc181f088.png)

**Comment by gjmzj** [comment]
2021应该会去做支持，我也需要比较成熟的方案，然后才能去做自动化

**Comment by piano-wow** [comment]
> 2021应该会去做支持，我也需要比较成熟的方案，然后才能去做自动化

2021个👍
