### ISSUE TITLE
k8s节点NAME显示问题,ip显示过于混乱

### ISSUE THREAD

**Issue by 21ki** [easzlab/kubeasz#948]
修改如下两个配置文件
roles/kube-node/templates/kube-proxy.service.j2    roles/kube-node/templates/kubelet.service.j2
修改内容为
--hostname-override={{ ansible_hostname }}
![image](https://user-images.githubusercontent.com/24515576/101426514-13519e80-3938-11eb-98ad-bcad3b82a1f0.png)
报错了

**Comment by 740355215** [comment]
是的，单纯修改这个还是不够，我也遇到同样问题。

**Comment by gjmzj** [comment]
我觉得ip显示好看😄😂

**Comment by 740355215** [comment]
> 我觉得ip显示好看😄😂

大佬是否有方案更新Node Name?
或者 有什么版本兼容的计划吗
