### ISSUE TITLE
交流提问技巧与礼仪

### ISSUE THREAD

**Issue by gjmzj** [easzlab/kubeasz#95]
### 描述问题
如果你能描述清楚一个问题，那80%概率你已经能够解决了，或者能够轻易找到答案了；大部分人碰到的问题都已经有人先你一步碰到过了且很可能已经解决了。google搜索或者去k8s官方项目提交issue，当然如果使用本项目脚本优先在这里提交issue。
### 提供线索
遇到实在无法描述的问题，那就请尽量提供可能有帮助的信息：错误提示，相关日志，相关检查步骤，或者自己排查的思路都可以交流下；提问者本身也是最可能的潜在问题解决者，自助者天助也。
### 提问礼仪
请持续关注自己提交的issue，有任何新的进展或者补充请及时更新；切勿抛下一个问题，没有任何后续反馈，对解决问题没有任何帮助，对后来者也是无用的信息；提`issue`区别于QQ或者微信群最大益处是可以方便为后来者提供检索帮助，开源项目优势所在；
### 一般排查思路
1.检查集群主要组件健康状况和错误日志 `master/node/etcd`
2.检查 pod运行日志
3.检查pod所在node节点kubelet运行日志
4.检查网络组件 flannel或calico状况和iptables filter表forward链是否有默认允许规则

**Comment by luokeychen** [comment]
理解！
这是一种文化也是该有的素质。

**Comment by huapox** [comment]
good!
