### ISSUE TITLE
离线部署文档内容命令错误

### ISSUE THREAD

**Issue by junly917** [easzlab/kubeasz#952]
![image](https://user-images.githubusercontent.com/16676780/102203477-9ad47a00-3f03-11eb-9661-c3559945d4fe.png)

https://github.com/easzlab/kubeasz/blob/master/docs/setup/offline_install.md
这些md的命令是不是写错了，kubectl 应该改成docker吧。

**Comment by gjmzj** [comment]
是的，写错了笔误😄
