### ISSUE TITLE
debian 10 安装多master后, coredns和metrics-server连接不上api-apiserver的问题

### ISSUE THREAD

**Issue by huqiangjz** [easzlab/kubeasz#953]
分步安装全程正常（除了可以ignoring的），kubectl get node 也全是ready
安装完后coredns,kubernetes-dashboard和metrics-server 三个pod不能正常启动
查看coredns日志发现 "https://172.30.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 172.30.0.1:443: connect: connection refused

运行 kubectl describe svc kubernetes ， 发现apiserver监听的是宿主机的端口。而宿主机的6443端口确实是打开的。貌似一切正常
Name:              kubernetes
Type:              ClusterIP
IP:                172.30.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         10.169.6.1:6443,10.169.6.2:6443
---------------
最后发现问题在于每个pod只能ping通自己pod的ip和所在宿主机的ip，其他的pod（集群ip）和其他的宿主机的ip不能访问。所以在node上的pod不能访问到apiserver。
敢请问楼主，这个怎么解决。
我发现只要执行了第一步01.prepare.yml ， 我在node的机器上自己建立普通docker的容器，容器内部也不能在访问外部ip。

**Comment by lushenle** [comment]
各个组件的版本信息帖一下？包括 iptables version
