### ISSUE TITLE
[WIP] about gpu, nvidia-container-runtime support

### ISSUE THREAD

**Issue by lushenle** [easzlab/kubeasz#956]
:joy: 看到过有类似的 GPU node 相关的 issue #879 

目前好像还没有相关的 role :trollface: 

:grimacing:  是否有计划做吗？目前我自己本地维护的一个包含部署 NVIDIA-driver, nvidia-container-runtime, nvidia-device-plugin 的分支，不过我们生产测试环境都是使用 Debian 10，目前只有 Debian 10 的支持。

container runtime 使用 containerd, 不安装 nvidia-docker 等类似的 command line tool, 只安装 nvidia-container-runtime

:handshake:  如果有这个计划的话，可以完善一下， pr 一波 :handshake: 
:joy:

**Comment by lushenle** [comment]
nvidia-driver 目前使用 runfile 方式安装

**Comment by gjmzj** [comment]
欢迎提交PR，我本人没有接触到gpu相关内容，所以你要持续维护更新这块内容，可以单独创建一个role，另外建议也封装一个命令行，类似 easzctl add-gpu-node xx.xx.xx.xx

**Comment by lushenle** [comment]
:ok_hand:

**Comment by lushenle** [comment]
> 欢迎提交PR，我本人没有接触到gpu相关内容，所以你要持续维护更新这块内容，可以单独创建一个role，另外建议也封装一个命令行，类似 easzctl add-gpu-node xx.xx.xx.xx

:ok_hand:

**Comment by kenwoodjw** [comment]
这个需求我有实现，看下怎么贡献给kubeasz
