### ISSUE TITLE
阿里云ecs单机安装k8s报错"/etc/ansible/bin"不是目录

### ISSUE THREAD

**Issue by HalcyonDaysssss** [easzlab/kubeasz#957]
[root@iZwz9apu1bn3mar7lzve5jZ ~]# export release=2.2.3
[root@iZwz9apu1bn3mar7lzve5jZ ~]# curl -C- -fLO --retry 3 https://github.com/easzlab/kubeasz/releases/download/${release}/easzup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   632  100   632    0     0    206      0  0:00:03  0:00:03 --:--:--   206
100 13167  100 13167    0     0   2162      0  0:00:06  0:00:06 --:--:--  4998
[root@iZwz9apu1bn3mar7lzve5jZ ~]# chmod +x ./easzup
[root@iZwz9apu1bn3mar7lzve5jZ ~]# ./easzup -D -d 19.03.14 -k v1.20.1
[INFO] Action begin : download_all
[INFO] downloading docker binaries 19.03.14
[INFO] downloading docker binaries 19.03.14
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 59.5M  100 59.5M    0     0  4196k      0  0:00:14  0:00:14 --:--:-- 1538k
Unit docker.service could not be found.
[INFO] generate docker service file
[INFO] generate docker config file
[INFO] prepare register mirror for CN
[INFO] turn off selinux in CentOS/Redhat
Disabled
[INFO] enable and start docker
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /etc/systemd/system/docker.service.
[INFO] downloading kubeasz 2.2.3
[INFO] run a temporary container
Unable to find image 'easzlab/kubeasz:2.2.3' locally
        2.2.3: Pulling from easzlab/kubeasz
31603596830f: Pull complete 
edea76eb5c98: Pull complete 
Digest: sha256:bb1306fc964880e49c5df7cedf76128d520a6ae2dc4b049928fdb8ddb5c7d826
Status: Downloaded newer image for easzlab/kubeasz:2.2.3
5a94a1717b9441b00d03a5d4b4804b134b286bca9cf0999a478ac6026b66e785
[INFO] cp kubeasz code from the temporary container
[INFO] stop&remove temporary container
temp_easz
/bin/mv: 目标"/etc/ansible/bin" 不是目录
[INFO] downloading kubernetes v1.20.1 binaries
v1.20.1: Pulling from easzlab/kubeasz-k8s-bin
31603596830f: Already exists 
f646c987b553: Pull complete 
Digest: sha256:19662b456c90eeb35721224edf6394e5ad0dc72d5ad692be64f38b92ecf869bb
Status: Downloaded newer image for easzlab/kubeasz-k8s-bin:v1.20.1
docker.io/easzlab/kubeasz-k8s-bin:v1.20.1
[INFO] run a temporary container
bb4e3c7ca960db7326891cae1b0b0aae839251ee4d77ef6d885396fd0aab7a8e
[INFO] cp k8s binaries
/bin/mv: 目标"/etc/ansible/bin" 不是目录
[ERROR] Action failed : download_all

**Comment by gjmzj** [comment]
先手动创建下目录， mkdir -p /etc/ansible/bin
具体问题我再看看脚本内容。。。
