### ISSUE TITLE
nodes name为IP地址

### ISSUE THREAD

**Issue by wxh512** [easzlab/kubeasz#961]
node name和hostname现在没有关联，labels属性不是很完整，升级prometheus 2.22.0 node-exporter v1.0.1 grafana 7.2 后集群监控就不完整，中文的dasboard 得不到相对应的数据，基本都需要全部自己重新写一遍

**Comment by gjmzj** [comment]
需要找时间测试下，你有更多信息可以提供帮助🙏

**Comment by wxh512** [comment]
主要是现在版本问题导致数据错误，还有就是dashborad相对版本内的参数导致的，一些prometheus新版本的返回key值不一样，例如对cpu，memory现在都在一个key内需要过滤才能得到
