### ISSUE TITLE
建议kubeasz申请加入CNCF云原生社区

### ISSUE THREAD

**Issue by ilanni2460** [easzlab/kubeasz#962]
现在kubeasz已经非常稳定，而且使用人数非常多。
建议kubeasz申请加入CNCF云原生社区，强烈建议!!!-

**Comment by gjmzj** [comment]
这个要花点时间，我找时间试试

**Comment by ilanni2460** [comment]
@gjmzj 哈哈 这个非常可以有呢，期待啊！！！
