### ISSUE TITLE
二进制文件bridge的arm版本

### ISSUE THREAD

**Issue by yexingqi** [easzlab/kubeasz#969]
请教一下，我正在尝试把arm版本的节点centos8.0 加入到K8S的节点上去。 
我的做法是将所有的x86的二进制文件替换成arm的二进制文件。 放到节点的 /opt/kube/bin下面。 并且ansible的复制选项加入不要覆盖已有的文件。 （这样就不会把X86的二进制文件再复制到节点上来）

**Comment by evenye** [comment]
现在就报这个错误： 可能是这个bridge 的文件仍然是X86的二进制，所以在arm上不能正常运行？ 



TASK [kube-node : 轮询等待node达到Ready状态] *****************************************************************************************************************************************************
FAILED - RETRYING: 轮询等待node达到Ready状态 (8 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (7 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (6 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (5 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (4 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (3 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (2 retries left).
FAILED - RETRYING: 轮询等待node达到Ready状态 (1 retries left).
fatal: [10.10.172.80]: FAILED! => {"attempts": 8, "changed": true, "cmd": "/opt/kube/bin/kubectl get node 10.233.130.80|awk 'NR>1{print $2}'", "delta": "0:00:00.254849", "end": "2021-01-14 18:57:32.856053", "rc": 0, "start": "2021-01-14 18:57:32.601204", "stderr": "The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}

PLAY RECAP *******************************************************************************************************************************************************************************
10.233.130.80              : ok=73   changed=32   unreachable=0    failed=1
