### ISSUE TITLE
Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-240.10.1.el8_3.x86_64

### ISSUE THREAD

**Issue by forTWOS** [easzlab/kubeasz#974]
centos8 升级内核4.18.0-193.el8.x86_64 -> 4.18.0-240.10.1.el8_3.x86_64，报这个错。

- modprobe nf_conntrack [ok]
- modprobe nf_conntrack_ipv4 [error]

**Comment by gjmzj** [comment]
这个具体有哪个参考文档，我在网上找到都是说内核大于等于4.19 采用 nf_conntrack
