### ISSUE TITLE
外部如何调用 k8s api 的https接口

### ISSUE THREAD

**Issue by DanceKiddle** [easzlab/kubeasz#977]
正常 https 应该这样:
`
curl https://1.2.3.1:443/api/v1/nodes \
    --cacert /etc/kubernetes/ssl/ca.crt \
    --cert /etc/kubernetes/ssl/apiserver-kubelet-client.crt \
    --key /etc/kubernetes/ssl/apiserver-kubelet-client.key
`
但使用 ansible 安装之后 找不到各个证书文件的位置，有哪位大神指教一下，感激不尽

**Comment by gjmzj** [comment]
2.x 版本在 /etc/kubernetes/ssl 目录
3.x 版本在 /etc/kubeasz/clusters/ssl 目录
