### ISSUE TITLE
example Cluster DNS Domain  不规范

### ISSUE THREAD

**Issue by lswzw** [easzlab/kubeasz#978]
# Cluster DNS Domain
CLUSTER_DNS_DOMAIN="cluster.local."

这里应该改为 
# Cluster DNS Domain
CLUSTER_DNS_DOMAIN="cluster.local"

最后多一个 .    会导致dns匹配时最后也要加上  .    跟官方的默认值不一样。

**Comment by gjmzj** [comment]
收到，已修改 🙏
