### ISSUE TITLE
安装完集群后，无法添加nodee节点，报错如图一，客户端kubelet无法启动，提示如图二

### ISSUE THREAD

**Issue by StrongPudge** [easzlab/kubeasz#980]
图一：
![image](https://user-images.githubusercontent.com/31201013/107148904-b3579280-6990-11eb-9d51-8b67ff8ad049.png)

图二，客户端kubelete报错
![image](https://user-images.githubusercontent.com/31201013/107148939-e69a2180-6990-11eb-9900-bd30594aed0d.png)

**Comment by gjmzj** [comment]
是不是已经解决，解决了请自行填写错误原因，并close

**Comment by gjmzj** [comment]
机器有旧配置遗留，之前大概装过其他的k8s

**Comment by StrongPudge** [comment]
已解决，之前的node节点装过其他的k8s版本
