### ISSUE TITLE
模板中各组件启动参数的依据出处是？

### ISSUE THREAD

**Issue by matribots** [easzlab/kubeasz#986]
有一个疑问想请教一下，就是想了解一下最初编写各组件配置模板中的启动参数的依据是（是根据自身的最佳实践，还是根据官网上的推荐，还是说这是一个比较通用的配置）？

**Comment by gjmzj** [comment]
都有吧，有官网的推荐，也有同类项目的借鉴，还有一些自身的实践

**Comment by caolijun1166** [comment]
> 都有吧，有官网的推荐，也有同类项目的借鉴，还有一些自身的实践

好哩，谢谢~
