### ISSUE TITLE
增加etdc节点报错!~

### ISSUE THREAD

**Issue by LBC100** [easzlab/kubeasz#987]
集群是AllinOne部署的.
1. 免密
![](https://i.loli.net/2021/02/20/24XAYWmDCyH3ENL.png)

2. 查看当前集群:
查看集群: docker exec -it kubeasz ezctl list
2021-02-20 08:57:31 INFO list of managed clusters:
==> cluster 1:  default (current)
3.添加etdc节点: docker exec -it kubeasz ezctl add-etcd default  172.16.0.13
增加etdc的文档是这样的
![image](https://user-images.githubusercontent.com/38514123/108591029-8b5d2b80-73a1-11eb-8730-124a76ffec19.png)
5.报错信息
[root@VM-0-11-centos ~]# sudo docker exec -it  kubeasz  ezctl add-etcd default  172.16.0.10
2021-02-20 09:25:49 INFO add 172.16.0.10 into 'etcd' group
2021-02-20 09:25:49 INFO start to add a etcd node:172.16.0.10 into cluster:default
/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature

PLAY [172.16.0.10] **************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************
ok: [172.16.0.10]

TASK [set NODE_IPS of the etcd cluster] *****************************************************************************************
ok: [172.16.0.10]

TASK [get etcd cluster status] **************************************************************************************************
changed: [172.16.0.10]

TASK [debug] ********************************************************************************************************************
ok: [172.16.0.10] => {
    "ETCD_CLUSTER_STATUS": {
        "changed": true, 
        "cmd": "for ip in 172.16.0.10 172.16.0.13 172.16.0.17 172.16.0.11 ;do ETCDCTL_API=3 /etc/kubeasz/bin/etcdctl --endpoints=https://\"$ip\":2379 --cacert=/etc/kubeasz/clusters/default/ssl/ca.pem --cert=/etc/kubeasz/clusters/default/ssl/etcd.pem --key=/etc/kubeasz/clusters/default/ssl/etcd-key.pem endpoint health; done", 
        "delta": "0:00:15.262908", 
        "end": "2021-02-20 09:26:12.519673", 
        "failed": false, 
        "rc": 0, 
        "start": "2021-02-20 09:25:57.256765", 
        "stderr": "{\"level\":\"warn\",\"ts\":\"2021-02-20T09:26:02.481Z\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-6f62725f-7f71-4c64-a809-f720c4f217e9/172.16.0.10:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}\nhttps://172.16.0.10:2379 is unhealthy: failed to commit proposal: context deadline exceeded\nError: unhealthy cluster\n{\"level\":\"warn\",\"ts\":\"2021-02-20T09:26:07.488Z\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-7c0e222b-1f76-463e-8061-df514b5e5193/172.16.0.13:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}\nhttps://172.16.0.13:2379 is unhealthy: failed to commit proposal: context deadline exceeded\nError: unhealthy cluster\n{\"level\":\"warn\",\"ts\":\"2021-02-20T09:26:12.495Z\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-0454b6ed-edf6-408b-a9d9-e1e106a138e0/172.16.0.17:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}\nhttps://172.16.0.17:2379 is unhealthy: failed to commit proposal: context deadline exceeded\nError: unhealthy cluster\nhttps://172.16.0.11:2379 is healthy: successfully committed proposal: took = 16.359327ms", 
        "stderr_lines": [
            "{\"level\":\"warn\",\"ts\":\"2021-02-20T09:26:02.481Z\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-6f62725f-7f71-4c64-a809-f720c4f217e9/172.16.0.10:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}", 
            "https://172.16.0.10:2379 is unhealthy: failed to commit proposal: context deadline exceeded", 
            "Error: unhealthy cluster", 
            "{\"level\":\"warn\",\"ts\":\"2021-02-20T09:26:07.488Z\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-7c0e222b-1f76-463e-8061-df514b5e5193/172.16.0.13:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}", 
            "https://172.16.0.13:2379 is unhealthy: failed to commit proposal: context deadline exceeded", 
            "Error: unhealthy cluster", 
            "{\"level\":\"warn\",\"ts\":\"2021-02-20T09:26:12.495Z\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-0454b6ed-edf6-408b-a9d9-e1e106a138e0/172.16.0.17:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}", 
            "https://172.16.0.17:2379 is unhealthy: failed to commit proposal: context deadline exceeded", 
            "Error: unhealthy cluster", 
            "https://172.16.0.11:2379 is healthy: successfully committed proposal: took = 16.359327ms"
        ], 
        "stdout": "", 
        "stdout_lines": []
    }
}

TASK [get a running ectd node] **************************************************************************************************
changed: [172.16.0.10]

TASK [debug] ********************************************************************************************************************
ok: [172.16.0.10] => {
    "RUNNING_NODE.stdout": "172.16.0.11"
}
[WARNING]: Unhandled error in Python interpreter discovery for host 172.16.0.10: Failed to connect to the host via ssh:
root@172.16.0.11: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

TASK [add a new etcd member] ****************************************************************************************************
fatal: [172.16.0.10]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"172.16.0.11\". Make sure this host can be reached over ssh: root@172.16.0.11: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}

PLAY RECAP **********************************************************************************************************************
172.16.0.10                : ok=6    changed=2    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
![image](https://user-images.githubusercontent.com/38514123/108591091-c6f7f580-73a1-11eb-8fc4-ba3f87c1d4ab.png)

6.主机是腾讯云的竞价主机, 开了几个都试了, 后来不行就删了, 只剩下172.16.0.10
备注: 172.16.0.11 是AllinOne部署的. 准备添加172.16.0.10 为etdc节点. 然后再把172.16.0.10也添加为node节点. 也就是说想把172.16.0.10当etdc和node节点来用
![image](https://user-images.githubusercontent.com/38514123/108591113-edb62c00-73a1-11eb-850e-094231cbee40.png)

**Comment by marksugar** [comment]
is unhealthy: failed to commit proposal: context deadline exceeded

同样错误
