### ISSUE TITLE
kubeasz 3.0.0 NFS动态存储问题

### ISSUE THREAD

**Issue by mrjooz** [easzlab/kubeasz#989]
**问题**
1. 执行`kubectl apply -f manifests/storage/test.yaml`后，查看pod,一直_Pending_。
2. 使用`kubectl describe`查看，提示_waiting for a volume to be created, either by external provisioner..._，检查了role配置没问题。
3. 执行`kubectl logs nfs-provisioner-01-7fdc6486fb-drgxm -n kube-system`查看日志，提示：
_Unexpected error getting claim reference to claim "default/test-claim": selfLink was empty, can't make reference_。
4. 查询资料，得到k8s 1.20+需要在kube-apiserver启动的时候加上`--feature-gates=RemoveSelfLink=false`。

**解决方法**
1. 在master节点`vim /etc/systemd/system/kube-apiserver.service`，加上`--feature-gates=RemoveSelfLink=false \`
2. 重启kube-apiserver服务`systemctl daemon-reload && systemctl restart kube-apiserver`

问题解决~

**Comment by gjmzj** [comment]
👌好的，后面我更新下

**Comment by zerols** [comment]
> **问题**
> 
> 1. 执行`kubectl apply -f manifests/storage/test.yaml`后，查看pod,一直_Pending_。
> 2. 使用`kubectl describe`查看，提示_waiting for a volume to be created, either by external provisioner..._，检查了role配置没问题。
> 3. 执行`kubectl logs nfs-provisioner-01-7fdc6486fb-drgxm -n kube-system`查看日志，提示：
>    _Unexpected error getting claim reference to claim "default/test-claim": selfLink was empty, can't make reference_。
> 4. 查询资料，得到k8s 1.20+需要在kube-apiserver启动的时候加上`--feature-gates=RemoveSelfLink=false`。
> 
> **解决方法**
> 
> 1. 在master节点`vim /etc/systemd/system/kube-apiserver.service`，加上`--feature-gates=RemoveSelfLink=false \`
> 2. 重启kube-apiserver服务`systemctl daemon-reload && systemctl restart kube-apiserver`
> 
> 问题解决~

现在1.20加这一行解决不了了吧

**Comment by gjmzj** [comment]
不建议使用--feature-gates=RemoveSelfLink=false ； 而是使用新的镜像，已更新

**Comment by yf1147** [comment]
> 不建议使用--feature-gates=RemoveSelfLink=false ； 而是使用新的镜像，已更新

是的，更新下镜像就行了 
registry.cn-beijing.aliyuncs.com/mydlq/nfs-subdir-external-provisioner:v4.0.0
