### ISSUE TITLE
kubeasz3.0 安装harbor过程中安装失败？

### ISSUE THREAD

**Issue by wangzy0327** [easzlab/kubeasz#995]
在运行11.harbor.yaml过程中报错
fatal: [10.255.1.14]: FAILED! => {"msg": "The conditional check 'NEW_INSTALL == 'yes' and groups['chrony']|length > 0' failed. The error was: error while evaluating conditional (NEW_INSTALL == 'yes' and groups['chrony']|length > 0): 'NEW_INSTALL' is undefined\n\nThe error appears to have been in '/etc/kubeasz/roles/chrony/tasks/main.yml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: 安装 chrony\n  ^ here\n"}

**Comment by gjmzj** [comment]
3.0.1 安装harbor已更新
